### ISSUE TITLE
create a dependencies XML format: group/artifact/version/xml/dependences which is conceptually like xml/features but based on java/main class loader

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1231]
we need an equivalent XML file to Karaf Features files like this:
https://github.com/fabric8io/fabric8/blob/master/fabric/fabric8-karaf/src/main/resources/fabric-features.xml#L19

but which is completely based on a maven <dependency> style model; suitable for flat class loaders, java container, WARs or JBoss Modules; without using the OSGi import/export graph class loader model; namely using the 'only 1 version of a jar is visible' kinda rule.

Folks could create these by hand and then compile them via a maven build process #1232; or code generate them from an existing xml/features file #1233 (and just do an automatic translation with maybe custom rules to exclude stuff from the xml/features file and include new stuff etc).

### Source of dependencies XML
The source might look something like this - so kinda similar other than the "xml/dependencies" type/classifiers:
```
<features name="fabric-${project.version}"
          xmlns="http://fabric8.io/xmlns/dependencies/v1.0.0">

  <repository>mvn:org.apache.cxf.karaf/apache-cxf/${cxf-version}/xml/dependencies</repository>
  ...
  <repository>mvn:org.apache.camel.karaf/apache-camel/${camel-version}/xml/dependencies</repository>
  <repository>mvn:org.apache.activemq/activemq-karaf/${activemq-version}/xml/dependencies-core</repository>
  <repository>mvn:org.apache.jclouds.karaf/jclouds-karaf/${jclouds-karaf-version}/xml/dependencies</repository>
  <repository>mvn:io.hawt/hawtio-karaf/${hawtio-version}/xml/dependencies</repository>
  <repository>mvn:org.apache.karaf.assemblies.features/standard/${karaf-version}/xml/dependencies</repository>
  <repository>mvn:org.apache.karaf.assemblies.features/spring/${karaf-version}/xml/dependencies</repository>
  <repository>mvn:org.apache.karaf.assemblies.features/enterprise/${karaf-version}/xml/dependencies</repository>

  <feature name="karaf" version="${karaf-version}" resolver="(obr)">
    <feature>cheese</feature>
    <dependency mvn="org.apache.felix/org.apache.felix.configadmin/${felix-configadmin-version}"/>
    <dependency mvn="org.ops4j.pax.url/pax-url-mvn/${pax.url.version}"/>
    ...
  </feature>
  ...
</features>
```
One of the main differences in the source is we use <dependency mvn="..."> so that we can also use includes/excludes to explicitly include optional dependencies (which by default should be excluded) and to exclude things too. (When compiling the source, we should respect maven's <exclusions> metadata in pom.xml files).
e.g.
```
<dependency mvn="group/artefact/version">
   <include>groupWildcard:artefactWildcard</include>
   <include>groupWildcard:artefactWildcard</include>
   <exclude>groupWildcard:artefactWildcard</exclude>
   <exclude>groupWildcard:artefactWildcard</exclude>
</dependency>
```

### Compiled/runtime dependencies XML

Whether its compiled from source or generated from an xml/features file, we should resolve the dependencies explicitly; so that runtime is nice and fast (no need to keep resolving individual pom files for each dependency etc). This basically means to translate the <dependency> elements into their artefact trees. The compiled dependencies XML files should look kinda like the output of "mvn dependency:tree" so that if folks are wondering where a jar comes from in their classpath its easy to diagnose where it comes from (and so easy to add an exclusion either in the project's pom.xml or in the source XML or translation XML).

```
<artefact mvn="group/artefact/version">
  <artefact mvn="group/artefact/version">
    <artefact mvn="group/artefact/version">
  </artefact>
  <artefact mvn="group/artefact/version"/>
</artefact>
```

### Using dependencies/features

We can then use the xml/dependencies files just like xml/features; just without the OSGI class loader model; so we can have 1-1 mappings of all the features in OSGi land (e.g. "camel-twitter, camel-spring" can be a list of features which works using xml/features in OSGi or with xml/dependences when using a flat class loader.

We can then reuse the nice features UIs and tooling in hawtio/fabric8 - we just use different XML files (repositories) to load the features based on whether we are using OSGi or whether using a flat class loader / jboss modules

**Comment by davsclaus** [comment]
This is not needed for v2
