### ISSUE TITLE
tomcat should the idea of a shared bundle/jar and a global bundle/jar so we can avoid polluting the global classpath

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1268]
I think the default behviour in Tomcat should be to not put stuff on the global classpath unless we really really have to. 

e.g. we want to deploy/undeploy WARs; and it'd be nice to be able to add new features into the Fabric WAR (to add/remove fabric features).

In both of these I think we should default to not using the global class loader for Tomcat.

Only if a bundle/feature is marked as global should we put it on the global classpath (which should be carefully considered really).

So I think we should add to fabric8/gravia the idea of 'shared' and 'global' (or something like that) so that stuff can be shared (within the fabric8 WAR or with a custom classloader in the fabric8 WAR) and then, if specified, some stuff may be chosen to also go on the global classpath.

Folks may want to share some jars across wars (e.g. camel); though if in doubt we should err on the side of caution and keep the WARs separate - and keep shared jars for fabric to use - local to fabric

**Comment by davsclaus** [comment]
process manager in v1 is no longer maintained
