### ISSUE TITLE
add a nice JMX API to the create project command so we can build a nice hawtio plugin for it too

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1335]
once we have created #1091 we should add a little JMX API so we can build a nice hawtio console. 

Basically let folks query all the available known archetypes (say id, label, description etc) then when one is chosen, we get the json schema of the values required to be completed; when the form is completed, we have an execute JMX method so we can create the archetype. 

So a JMX API something along these lines...

```
public class ArchetypeSummaryDTO {
   private String id;
   private String name;
   private String description;
   private String[] tags;
  ...
}

public interface ArchetypeGenerateMXBean {
   public List<ArchetypeSummaryDTO> getArchetypes();

   public String getJsonSchema(String archetypeId);

   /** generates the artefact; with the output folder being an attribute passed. Returns the response */
   public String createArchetype(Map<String,String> attributes);
}
```

**Comment by davsclaus** [comment]
the forge commands wil be reuseable from web so we can use them from hawtio as well
