### ISSUE TITLE
expose profile configuration files to a local folder available via a system property / env var

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1452]
it might be nice for folks in any container (or Java Container) to have access to the current profile(s) configuration files in a canonical way. 

e.g.
```
new File(System.getProperty("fabric8.profile.dir"), "foo.properties")
```
and the contents of the "fabric.profile.dir" would contain the combined profile configuration files and properties files etc (after any property replacement are done etc).

Then folks have a simple, no Java client required, way to access to configuration files

**Comment by davsclaus** [comment]
process manager in v1 is no longer maintained
