### ISSUE TITLE
expose the managed broker group / broker discovery ActiveMQConnectionFactory into JNDI for tomcat/jetty/wildfly

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1477]
rather than using the osgi registry or DS injection; we should auto-expose the ActiveMQConnectionFactory into JNDI so WARs in tomcat/wildfly can easily use JMS while reusing the broker group or broker discovery mechanism. see https://github.com/fabric8io/fabric8/issues/1386

**Comment by davsclaus** [comment]
process manager in v1 is no longer maintained
