### ISSUE TITLE
create a JRebel and/or spring loaded profile so folks can get even faster reloading of bytecode in a stand alone Java container (micro service)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1495]
it'd be nice to have a profile to enable JRebel so folks don't have to actually restart the JVM on a change to the classpath/bytecode; but instead we could use JRebel's fast bytecode reloading agent thingy.

Another option could be to try spring-loaded as a Java Agent:
https://github.com/spring-projects/spring-loaded

**Comment by davsclaus** [comment]
process manager in v1 is no longer maintained
