### ISSUE TITLE
Auto-detect base package of deployed Spring Boot app

### ISSUE THREAD

**Issue by hekonsek** [fabric8io/fabric8#1558]
Now we need to specify the package or base class of the deployed Spring Boot application. For example:

    profile-edit --pid=io.fabric8.container.java/jvmArguments=-Dspring.main.sources=io.fabric8.process.spring.boot.itests.service.invoicing invoicing

I don't like it, because this is error-prone part of the application setup (typo in package name, etc). It will be nice if Fabric8 could try to autodetect base package of the installed jar. This is do-able with some basic jar file scanning.

For example:

    com
      example
         project
           MyClass1.class
           MyClass2.class

Should return `com.example.project`.

**Comment by davsclaus** [comment]
Non karaf stuff in v1 is no longer maintained
