### ISSUE TITLE
expose the Debug port for karaf containers (with a debug profile?)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1628]
we support the debug port in the Java and Tomcat containers now (see #1604 and #1603).

Mostly its a case of passing in the JVM arguments with a dynamic port (in the case of child containers)- like this:
https://github.com/jstrachan/fabric8/blob/81fa6d2b85e87b5dd36fe3cf277f3938ea87a2d3/fabric/fabric8-karaf/src/main/resources/distro/fabric/import/fabric/profiles/containers/java.debug.profile/io.fabric8.environment.properties#L18

and then exposing the port value into ZK:
https://github.com/jstrachan/fabric8/blob/4a685a753487922bf68e4125e977a242dac579a0/fabric/fabric8-karaf/src/main/resources/distro/fabric/import/fabric/profiles/containers/java.debug.profile/io.fabric8.zookeeper.publish-debug.properties#L17

We should do the same for Karaf containers too!

**Comment by akhettar** [comment]
Hi 

I am using fabric 1.1.0.CR5, I have added container-debug profile to karaf child container still not able to remove debug the container. The last statement of James "We should do the same for Karaf containers too" is this still the case?

Thanks

Ayache
