### ISSUE TITLE
dozer quickstart should do some transformations in camel

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#1700]
then folks can see how to combine camel and dozer with transforms etc.

the ReadMe.md should maybe describe how we can use the autotest profile to make it easy to re-run a set of sample messages whenever dozer/camel is changed; to get rapid feedback on how the changes affect the route behaviour and outputs

**Comment by davsclaus** [comment]
We dont ship that quickstart in v2, and its not maintained in v1 for fuse 6.2. So closing ticket.
