### ISSUE TITLE
cannot delete a failed ssh container

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2014]

**Comment by rafachies** [comment]
Any workaround on this? I'm running in JBoss Fuse 6.1.0 and also can't delete a container that failed when it was created through ssh. How can I remove this container from zookeper?

**Comment by davsclaus** [comment]
Have you checked the RH customer portal - it has a knowledge base, I think there may be some articles there about this.

There was also this blog post about this or related to this
https://pgaemers.wordpress.com/2014/09/20/stopping-a-fabric-container-after-container-has-not-been-created-by-fabric-error-message/

**Comment by rafachies** [comment]
Thanks Claus. I've already searched in CP, but nothing that helped. The steps of the blog is a path, not good, but a path. Thanks!
