### ISSUE TITLE
add a 'template' concept; kinda like the current requirements but which can be added/removed individually

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2017]
right now we've got the [requirements and the autoscaler](http://fabric8.io/gitbook/requirements.html) that given global requirements can spin up the right amount of stuff.

however it'd be nice to have templates in the wiki which we can start/stop as kinda 'groups'. so a template could be 'loan broker demo' (which adds a broker and then 4 containers for each service); then folks can see it starting and then stop it and all the services stop.

So rather than working at the individual profile -> container level; if the auto-scaler is added, we could start/stop groups of things in one go. 

So adding a 'template' (not sure the best name for it), we'd have a list of templates running and be able to see how each of them are provisioned and so forth. Then folks can just stop a named template and its resources then stop.

One thing that'd be nice is to specify some things are shared. e.g. if folks were using the loan broker demo template and the camel-activemq template (that both needed mq-default) that they could define that profile as being shared; so that if both templates need 1 mq-default profile; it'd only actually spin up one. Then starting the 2 templates and stopping 1 would leave 1 mq-profile container running the whole time; until the last template is stopped.

So we'd need a JMX / REST API to view all the templates started; to add new ones and stop them etc.

**Comment by davsclaus** [comment]
auto scaler is no longer maintained in 1.x
