### ISSUE TITLE
autoscaler to automatically register new ZK ensemble servers when we autoscale from 1 to 3 (or 3 to 5) ZK servers

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2019]
it'd be nice to be able to specify how many ZK ensemble nodes are required and the autoscaler just did it for you
http://fabric8.io/gitbook/requirements.html

I'm guessing when there's 1 container and we've stared another 2 then the autoscaler could (if enabled) automatically register the 3 of them in the ensemble? Maybe failing to accept an even number of ensemble servers?

**Comment by davsclaus** [comment]
auto scaler is no longer maintained in 1.x
