### ISSUE TITLE
provide an autoscaler capability to automatically spin up compute nodes we can then use via ssh to create containers

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2071]
it'd be great if we could autoscale compute nodes as well as containers; to give us a pool of compute nodes we can then use to provision containers on. e.g. once created, they could be added to the ssh configuration on the FabricRequirements so the autoscaler could use them to create containers

**Comment by davsclaus** [comment]
auto scaler is no longer maintained in 1.x
