### ISSUE TITLE
have a transaction CLI command so folks could group a bunch of profile-create/edit commands into a single git commit

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2248]
it'd be nice to be able to start a transaction; run a bunch of CLI commands (like profile create / delete / edit commands) and then commit in a single atomic change

**Comment by PhilHardwick** [comment]
This would be a really useful feature to have especially when deploying a lot of properties to profiles. Why was it closed?

**Comment by davsclaus** [comment]
fabric8 v1 issues is tracked in jboss fuse project.
