### ISSUE TITLE
camel plugin for JBoss Forge to list current camel components used on a project and to allow new components to be added

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2729]
given any maven build using camel it'd be awesome to be able to type the following in [forge](http://forge.jboss.org/):
```
camel-list-component
```
to get a list of the current components. then
```
camel-new-component --named f<tab>
```
and get tab completion on all the available known camel components that are not yet in the current project.

Picking a new camel component (e.g. activemq) would then update the pom.xml to add the necessary dependencies and then generate some _component configuration code_ using spring annotations / XML or CDI Java or blueprint.

The component configuration code would basically be a @Produces function in Java (or bean configuration thingy in spring) to create a named bean for the component to be added; with code generated default configuration. The user can then customise this configuration in their IDE. Ideally we'd recommend folks use Java configuration for this - so things are all typesafe.

Also it'd be nice to default to transactional mode for things like JMS / databases; so it'd @Inject the necessary transaction manager and whatnot.

To implement this we'll need a list of all camel components and how the names map to the camel component class. We can discover whats there already using the same camel discovery service in camel right now; then to show what could be added thats not on the classpath we'll need to generate (e.g. in the fabric8 build) a properties file or something of all the components in the camel feature files.

**Comment by davsclaus** [comment]
There is a `project-camel-info` command that list details

**Comment by jstrachan** [comment]
I wonder if we can close this one now? I moved the CDI code generation to this separate issue: https://github.com/fabric8io/fabric8/issues/3437

**Comment by davsclaus** [comment]
Yep
