### ISSUE TITLE
Forge plugin for camel-new-endpoint

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2730]
similar to #2729 but for Endpoints rather than Components.

```
camel-new-endpoint --named cheese --component activemq --path foo<tab>
```
with smart completion of the component names; then the path could support tab completion using Camel's [EndpointCompleter](http://camel.apache.org/endpointcompleter.html) plugin if its supported on the component to smart complete queue/topic names, folders in a file system, tables in a database, entity bean classes in a JPA / hibernate component etc.

In addition we could maybe allow users to specify key/value pair values using the endpoint annotations and UriEndpointComponent (if supported) to allow folks to customise the URI parameters that are available (letting folks tab complete a parameter name, then add its value (some components have lots of optional parameters like jms/file).

Adding the endpoint to a project depends on the kind of project it is. If its Java DSL and there's one or more RouteBuilder classes we maybe need to let the user prompt the class to add the endpoint to. It could then update the Java code to something like:

```
public class MyRouteBuilder {
    protected void configure() {
        /// start of generated new code
        Endpoint myNewEndpoint = endpoint("activemq:myPath?param1=value1");
        /// end of generated new code

       ...
    }
}
```

Or it could use fields maybe? Folks might want to have a base route builder where stuff is injected as a protected level fields - maybe annotating it as the place that new endpoints get added?

If the project is using camel XML (spring / blueprint) then we can add these as named endpoints inside the camelContext via...
```
<camelContext xmlns="....">
        <endpoint id="myNewEndpoint" uri="activemq:myPath?param1=value1/>
         ....
</camelContext>
```

**Comment by davsclaus** [comment]
We got one now for route builder + xml files. It need Camel 2.15.1 to generate the url - but all the other logic should be there.
