### ISSUE TITLE
add forge camel-new-json-format command for generating a new Camel DataFormat for a json schema / example json file along with auto-generating DTOs for it

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2731]
it'd be nice if folks could add json schema files or example json files to a project via this command; which would internally use the maven plugin from [jsonschema2pojo](http://www.jsonschema2pojo.org/) to auto generate DTOs which can then be used directly in the project - plus generate a DataFormat for it for use in camel (via Spring Java code, CDI Java code, blueprint XML or Spring XML).

To make it easier to grok what data formats have been created having a generated properties file / JSON file / XML file with all the data formats and how they map to the source files and generated package names might be nice; though we can maybe try parsing the jsonschema2pojo XML in the pom?

I'd say good defaults to use would be using Jackson 2.x style annotations along with adding JSR 303 annotations and hashCode / equals / toString implementations by default. (those could always be configured later via command line arguments)

**Comment by davsclaus** [comment]
I wonder if there is some overlap with the data mapper project?

**Comment by davsclaus** [comment]
Lets close this ticket here, and let people use the data mapper tooling from Eclipse.
