### ISSUE TITLE
add forge camel-new-xsd-format command to generate DTOs and a new Camel DataFormat

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2732]
```
camel-new-xsd-format --url http://foo.acme.com/blah.xsd --name blah
```
We could default the package name from a common base package plus a name for each format maybe; or let the user customise it. 

When an XSD is referred to that is not already in the project source we could either copy it into the project or just refer to it via URL inside the pom.xml.

This would then generate the necessary pom.xml changes to use the JAXB XJC tooling - e.g. via the [jaxb2:xjc goal](http://mojo.codehaus.org/jaxb2-maven-plugin/xjc-mojo.html) so that java classes are generated based on the given XSD passing in a good default set of flags and packageName etc. 

In addition we should autogenerate a Camel DataFormat instance; either using Spring Java configs, XML configs, CDI or blueprint so that the data format can be referred to from the tooling (e.g. in the Java DSL / XML DSL)

**Comment by davsclaus** [comment]
I wonder if there is some overlap with the data mapper project?

**Comment by jstrachan** [comment]
agreed- we should maybe try unify the 2 maven projects so the camel forge commands are all in one place?

**Comment by davsclaus** [comment]
Lets close this ticket here, and let people use the data mapper tooling from Eclipse.
