### ISSUE TITLE
forge command to add camel support to a project

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2735]
not sure the correct forge naming convention; something like

```
camel-enable
```
which based on the current project it'd check if the user is using spring, CDI or blueprint and add camel-spring, camel-cdi, camel-blueprint to the pom.xml.

In addition it'd be nice to add the camel:run maven plugin; and the [hawtio:camel](http://hawt.io/maven/) plugin too so folks can easily run camel or camel in hawtio

**Comment by davsclaus** [comment]
It seems that forge uses the naming `setup` for enabling stuff. So I am going to name it `camel-setup`

**Comment by davsclaus** [comment]
Adding the custom plugins for camel / hawtio does not work with jboss forge. I can't get it working

**Comment by davsclaus** [comment]
Okay got the maven plugin working. 

For the hawtio version we dont know the latest version, so I guess either the user needs to type a version or we somehow hardcoded / or try to lookup latest from maven central?

**Comment by davsclaus** [comment]
We define the hawtio version in the pom.xml so we use the version of hawtio that fabric8 supports
