### ISSUE TITLE
forge camel-add-route-builder

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2736]
```
camel-add-route-builder --name FooBuilder
```
generates a Java class for a new route builder with the given name (could default the package based on previous java code it finds?) If none found prompt the user for a good default (e.g. find base package and add camel or something?) remember previous package we created a route inside and use it next time?

**Comment by davsclaus** [comment]
We got a nice little one now as a start. It has tab completion for the package names. I decided to split it up into 2 args, --targetPackage to use same naming as OOTB forge commands
