### ISSUE TITLE
forge camel-add-context

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2737]
creates a new camel context XML using spring / blueprint; if no file is specified it just generates a new one or modifies a given spring.xml to ensure the XSD changes are made and a default camel context is created etc

**Comment by davsclaus** [comment]
I guess the name of the command should be something about xml?

Maybe camel-add-xml-context

And then you can choose spring or blueprint. But it attempts to auto discover if you already are spring or osgi buy.

**Comment by davsclaus** [comment]
We have commands for creating spring or blueprint xml now
