### ISSUE TITLE
add a maven-add-docker command to automatically add a "mvn docker:build" and "mvn docker:push" goals so folks can build docker images from a maven project

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2750]
e.g. for a WAR project we may want to do something like this https://github.com/jstrachan/fabric8/blob/2.0/quickstarts/war/camel-servlet/pom.xml#L173-173

e.g. adding this to pom.xml

```
      <plugin>
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.9.9</version>
        <configuration>
          <image>fabric8/tomcat-8.0</image>
          <mergeData>true</mergeData>
          <assemblyDescriptorRef>artifact</assemblyDescriptorRef>
        </configuration>
      </plugin>```

It'd be awesome if the plugin also looked at the application and guessed the best base image and assemblyDescriptorRef...
https://hub.docker.com/u/fabric8/

maybe remembering the users preferred web app image etc?

**Comment by jstrachan** [comment]
I guess the other approach is to do all the docker stuff in an STI build so users don't have to touch their projects (which would be nice)

**Comment by davsclaus** [comment]
Yeah the plugin can adhere to our quickstarts, and try to guess the image.

I am messing a bit with the forge configuration api to build the xml structure - it seems at first try it leaves out empty middle tags :(

**Comment by davsclaus** [comment]
We have a setup-docker command now, that detects if its bundle / war or jar project. For jar it does not yet support a main class, which you need to add manually or something for it to know how to bootstrap it.

**Comment by davsclaus** [comment]
There is a fabric-setup command - it can add docker or jube or both.

@jstrachan do we want a vanilla docker setup command that does not know about fabric8?

**Comment by jstrachan** [comment]
I don't think we need to worry about the non-fabric8 / non-kubernetes use of docker for now? Or rather its very low priority; creating endpoints is way more useful ;)

**Comment by davsclaus** [comment]
Yeah just got a few things left on the fabric setup command. And then I will look at helping with the endpoint command
