### ISSUE TITLE
have an App for logging all docker / kubernetes logs into ElasticSearch

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2869]
it'd be awesome if we had an out of the box App so that all journald / syslogd / docker / kube logs went to ElasticSearch. 

I guess its just a matter of configuring logstash to find all the journald/syslogd stuff that docker/kubernetes/openshift outputs and using the existing ElasticSearch App?

**Comment by jimmidyson** [comment]
This is all working now
