### ISSUE TITLE
create a command to update the replica count on a replication controller

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3026]
something like:

```
kubernetes-size --replica=someID --count=bar
```

I guess we should check the latest kube to align naming conventions etc

**Comment by davsclaus** [comment]
Is the kubernetes command a priority? Or do we more rely on hawtio and the os3, kubecfg command scripts?

**Comment by jstrachan** [comment]
yeah, lets not worry too much about this TBH; as the kube command line is pretty good these days (as is hawtio)
