### ISSUE TITLE
figure out how the docker get started script can work well on docker 1.3.1 or later with TLS enabled

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3092]
it seems the kube apply scripts hung for me when I tried it when TLS was enabled.

I'm not 100% sure if the "mvn docker:build docker:push" works either with TLS enabled on the quickstarts.

It would be good to figure this out and get things working on any docker install!

**Comment by jimmidyson** [comment]
Closing as this works now tested on centos 7 with docker 1.3
