### ISSUE TITLE
getting the below error in [Core] Operation apply failed due to: javax.ws.rs.ForbiddenException : HTTP 403 Forbidden in http://127.0.0.1:8585/hawtio/wiki/branch/master/view/java-simple-mainclass

### ISSUE THREAD

**Issue by bobquest33** [fabric8io/fabric8#3135]
Error in hawtio console    

Stack trace:

    Error: e is null

    a.KubernetesJsonDirective

    n/n.success/<@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:12785

    fc/h/g.promise.then/i@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:2371

    fc/h/g.promise.then/i@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:2371

    fc/i/<.then/<@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:2932

    ic/this.$get

    ic/this.$get

    ic/this.$get

    f@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:13209

    r@http://127.0.0.1:8585/hawtio/app/app.js?463fe92ac4c60bed:17:14920

    sc/
    [Core] Operation apply failed due to: javax.ws.rs.ForbiddenException : HTTP 403 Forbidden
    [Core] Operation apply failed due to: javax.ws.rs.ForbiddenException : HTTP 403 Forbidden

**Comment by davsclaus** [comment]
Closing as no response. Feel free to reopen if hitting something like this with latest release
