### ISSUE TITLE
cannot build fabric8 - missing dependency

### ISSUE THREAD

**Issue by abedwardsw** [fabric8io/fabric8#3150]
could someone tell me which repository http://repository.jboss.org/nexus/content/groups/ea/org/apache/karaf/features/org.apache.karaf.features.core/2.4.0.redhat-620038/ artifact is stored in.  
The location above is blank and I cannot build the 1.x branch of fabric8.   Is there another repo or is the dependency truly missing? 

I see some of the newer versions exist in that repo.  for example: http://repository.jboss.org/nexus/content/groups/ea/org/apache/karaf/features/org.apache.karaf.features.core/2.4.0.redhat-620045/

**Comment by nelsongraca** [comment]
I know I may be ressurecting something old and outdated but knowing the reason why this was closed would be nice.

**Comment by jstrachan** [comment]
the 1.x code is maintained here now btw: https://github.com/jboss-fuse/fabric8
