### ISSUE TITLE
Kibana not displaying logs

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#3213]
I've just updated all the docker images, running the start script with -ukf, when I look at the logs in Kibana the search doesn't return any results, even after removing search criteria (although it does have them from earlier on in the day when I was testing)

I can see that there's results increase in ES when running..
curl 'http://172.121.17.6:9200/_search?pretty'

It may well be something local to me as I had to recreate my boot2docker vm again today but I thought I'd raise it incase others experience it whilst I investigate on my setup.

**Comment by jimmidyson** [comment]
This is fixed now
