### ISSUE TITLE
validate the IDs used for services / replication controllers / pods / containers better

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3249]
right now its way too easy to have clashes or invalid values for IDs in the various parts of the service/controller/pod/container/image model and for errors to only appear when you try to run the kubernetes json.

It'd be nice to enumerate the validation rules (e.g. camelCase versus lowercase-with-dashes and to ensure IDs are unique etc) - so that we can be more sure apps will just work

**Comment by davsclaus** [comment]
What is the status today?

**Comment by jimmidyson** [comment]
Done thanks to @iocanel's fluent builders & JSR-303 validation
