### ISSUE TITLE
Docs on environment variables too Windows/Mac specific?

### ISSUE THREAD

**Issue by nmcl** [fabric8io/fabric8#3295]
http://fabric8.io/v2/openShiftDocker.html#environment-variables

talks about environment variables that need to be set. In some areas of the doc it suggests you only need to set these variables if you're running on a Mac or Windows, which then makes sense of the requirement for boot2docker in DOCKER_IP, for instance. However, the quickstart example (http://fabric8.io/v2/example.html) uses DOCKER_REGISTRY irrespective of OS type. Of course if you're following the quickstart and have started OpenShift you get the docker registry info when it runs, so maybe all that's needed is a reference to that in the docs?

**Comment by davsclaus** [comment]
The docs has been updated recently.
