### ISSUE TITLE
Maven build for quickstart error message typo

### ISSUE THREAD

**Issue by nmcl** [fabric8io/fabric8#3297]
mvn clean install docker:build

[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.10.4:build (default-cli) on project quickstart-war-camel-servlet: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.10.4:build failed: No url given and now DOCKER_HOST environment variable set -> [Help 1]

Should probably be "and no DOCKER_HOST".

**Comment by davsclaus** [comment]
There is a new 0.10.5 and 0.11.0 release

**Comment by davsclaus** [comment]
Ah darn 0.10.5 now requires a higher maven version

[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.10.5:build (default-cli) on project quickstart-java-camel-cdi: The plugin org.jolokia:docker-maven-plugin:0.10.5 requires Maven version 3.2.1 -> [Help 1]

**Comment by davsclaus** [comment]
Same for 0.11.0

**Comment by davsclaus** [comment]
Setting mvn 3.2.1 as pre req in our pom.xml and upgrading to newer docker maven plugin

**Comment by davsclaus** [comment]
Ah 0.11.0 requires a new option

[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.0:build (default-cli) on project quickstart-java-camel-cdi: Unable to parse configuration of mojo org.jolokia:docker-maven-plugin:0.11.0:build for parameter assemblyDescriptorRef: Cannot find 'assemblyDescriptorRef' in class org.jolokia.docker.maven.config.BuildImageConfiguration -> [Help 1]

Upgrading to 0.10.5 for starters

**Comment by davsclaus** [comment]
Wonder if its due we have a placeholder in the quickstart pom.xml
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/java/camel-cdi/pom.xml#L178

**Comment by davsclaus** [comment]
The typo is still there in 0.10.5 release

**Comment by davsclaus** [comment]
Upgraded to 0.11.0
