### ISSUE TITLE
getting started guide seems broken.

### ISSUE THREAD

**Issue by sateeshkv** [fabric8io/fabric8#3305]
Hi,

  I tried to follow the getting started with openshift + docker (on Linux mint), but the documentation seems to be broken.

  An example, it says "docker pull fabric8/hawtio" followed by an instruction to run "./bin/start" 

  I navigated to:

  http://fabric8.io/v2/getStarted.html
    then to:
  http://fabric8.io/v2/openShiftInstall.html
    then at the bottom of this page to:
  http://fabric8.io/v2/runFabric.html

**Comment by rawlingsj** [comment]
Yeah I think we ought to review the getting started guides as there are a couple of similar issues and we have improved some of the workflows for devs on different operating systems.

**Comment by umeetiusbaar** [comment]
Yes, please do that! I am having a very hard time trying to figure out the best way to migrate from V1 to V2 and how to change our builds for V2 and the current documentation does not help in that very much.

**Comment by rawlingsj** [comment]
WIP but here's a start.  Feedback most welcome https://github.com/rawlingsj/fabric8/blob/docs/docs/openShiftDocker.md

**Comment by davsclaus** [comment]
The documentation has been improved, is there more work?

**Comment by jimmidyson** [comment]
The getting started guide has had a full overhaul & flows much better now.

Migration guide is covered by a different issue.
