### ISSUE TITLE
Unable to create pods using API

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#3308]
I've been trying to create pods using the API but they don't seem to start correctly.  The issue I'm seeing can be recreated using the Example below and passing KUBERNETES_MASTER as an argument, e.g. `http://192.168.203.136:8080`.  Once the Example runs the pods are stuck in 'Waiting' status and never start.

https://github.com/fabric8io/fabric8/blob/master/components/kubernetes-api/src/test/java/io/fabric8/kubernetes/api/Example.java

**Comment by rawlingsj** [comment]
I'm not sure if this is an issue with my setup or with Openshift / Kube.  Using the JSON from the Example above to create a pod using kubecfg works, 

Success...
`kubecfg -c testCreatePod.json create pods`

but using the JSON with the Rest API produces the same error as using `kubernetes.createPod(pod);`

Fails...
```
curl -H "Content-Type: application/json" -d '{"desiredState":{"manifest":{"containers":[{"command":[],"env":[],"image":"fabric8/fabric8","name":"cheese","ports":[],"volumeMounts":[]}],"version":"v1beta1","volumes":[]}},"id":"cheese","labels":{"fabric8":"true","container":"cheese"}}' http://192.168.203.137:8080/api/v1beta1/pods
```

**Comment by jstrachan** [comment]
I've just added a fix to the Example.java - its working fine now -turns out that the apiVersion is mandatory on the Pod. Am looking to see if we can auto-generate the Pod to have that value populated by default...
