### ISSUE TITLE
[v2] - port apm module to v2

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#3343]
re-invigorating the apm module in fabric8 (currently in the sandbox) ?

**Comment by jimmidyson** [comment]
I'd like to use this APM strategy to get deeper stats for Camel/CXF/ActiveMQ for Insight v2. I'd also like to add an option to push metrics out from the APM rather than just exposing it via JMX.

**Comment by davsclaus** [comment]
Okay got a start of the port, the test app now runs and I can see some data from hawtio.

**Comment by davsclaus** [comment]
@jimmidyson good ideas, do you mind creating new tickets for those, eg such as what kind of push technology you are looking for?

Mind that codehale metrics has a servlet that can output the metrics in its standard json format. We use that in camel-metrics.
