### ISSUE TITLE
Break kubernetes-api project in order to provide the Kubernetes API alone

### ISSUE THREAD

**Issue by pires** [fabric8io/fabric8#3348]
I'm using ```kubernetes-api``` in all my projects that need to talk to Kubernetes API server. Thing is, while hacking support for Kubernetes on Karaf Cellar (```cellar-kubernetes```) I end up seeing a lot of the following (two messages each three seconds) when installing the bundle:
```
2015-01-14 19:49:11,005 | WARN  | Timer-2          | AppView | 142 - io.fabric8.kubernetes-api - 2.0.19 | No MBean is available for: io.fabric8:type=Kubernetes
2015-01-14 19:49:11,005 | WARN  | Timer-2          | AppView | 142 - io.fabric8.kubernetes-api - 2.0.19 | No MBean is available for: io.fabric8:type=Kubernetes
```

So, it would be really nice to split current ```kubernetes-api``` project in two (or more if you see fit). One that provides the actual API and nothing more, and another one for the hawt-io stuff.

**Comment by rawlingsj** [comment]
I think this is a good idea.  I've been doing a bit of work around automating the generation of that API for fabric8.  This approach would help there too as we could version the API each time it changes.  Maybe we could confirm with others and if ok I'm happy to do the work as I'm in that area.

**Comment by jimmidyson** [comment]
+1
