### ISSUE TITLE
Camel-servlet example dockerhost URL wrong

### ISSUE THREAD

**Issue by nmcl** [fabric8io/fabric8#3369]
http://fabric8.io/v2/example.html refers to http://dockerhost:9901/war-camel-servlet-2.0-SNAPSHOT/ in order to check that the example was deployed. What IP address should be used, because neither FABRIC8_CONSOLE IP or DOCKER_IP work.

Note, running Fedora 20 and OpenShift3 via docker. Successfully deployed and running instances.

**Comment by davsclaus** [comment]
The web console shows the address as shown in the red circle.
![screen shot 2015-03-10 at 6 41 14 am](https://cloud.githubusercontent.com/assets/477100/6569778/5f7edd10-c6f0-11e4-82f2-d9c4c3b49939.png)
