### ISSUE TITLE
maven fabric8:zip fails if no <distributionManagement/> in pom.xml

### ISSUE THREAD

**Issue by maschmid** [fabric8io/fabric8#3387]
Running mvn fabric8:zip on a project with no <distributionManagement/> in pom.xml fails with the following error

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.0.19:zip (default-cli) on project karaf-camel-amq: The parameters 'deploymentRepository' for goal io.fabric8:fabric8-maven-plugin:2.0.19:zip are missing or invalid -> [Help 1]

**Comment by davsclaus** [comment]
That is needed to know which url to use for  the deploy phase
http://maven.apache.org/plugins/maven-deploy-plugin/

What do you want to do? Just to install/deploy to your local m2 repo? If so we could skip the deploy phase so the zip is just created and installed in your local m2.

**Comment by davsclaus** [comment]
This should not be optional, and only required if you run the deploy phase, such as when building a release etc.
