### ISSUE TITLE
Unable to get fabric8 installed and ran 

### ISSUE THREAD

**Issue by rhui** [fabric8io/fabric8#3389]
I use fedora 20 and has docker installed 
I ran bash <(curl -sSL https://bit.ly/get-fabric8) based on http://fabric8.io/v2/openShiftDocker.html
but it seems stopped at building the console. 

Error for openshift

[root@rwhui-pc ~]# bash <(curl -sSL https://bit.ly/get-fabric8) 
Validating your environment...

Validating firewall rules

2015/01/21 20:29:36 Error response from daemon: Conflict, The name openshift is already assigned to e6aa0793c08e. You have to delete (or rename) that container to be able to assign openshift to a container again.
E0121 12:29:37.222999       1 apply.go:69] Config.item[0].create: invalid value '<*>(0xc208206030)Post http://localhost:8080/api/v1beta1/services?namespace=default: dial tcp 127.0.0.1:8080: connection refused': unable to create: {"kind":"Service","id":"fabric8-console-service","creationTimestamp":null,"apiVersion":"v1beta1","port":8080,"selector":{"component":"fabric8Console"},"containerPort":8080}
E0121 12:29:37.223258       1 apply.go:69] Config.item[1].create: invalid value '<*>(0xc2081b7620)Post http://localhost:8080/api/v1beta1/replicationControllers?namespace=default: dial tcp 127.0.0.1:8080: connection refused': unable to create: {"kind":"ReplicationController","id":"fabric8ConsoleController","creationTimestamp":null,"apiVersion":"v1beta1","desiredState":{"replicas":1,"replicaSelector":{"component":"fabric8Console"},"podTemplate":{"desiredState":{"manifest":{"version":"v1beta2","id":"","volumes":null,"containers":[{"name":"fabric8-console-container","image":"fabric8/hawtio:latest","ports":[{"containerPort":8080,"protocol":"TCP"}],"env":[{"name":"DOCKER_REGISTRY","key":"DOCKER_REGISTRY","value":"$REGISTRY_SERVICE_HOST:$REGISTRY_SERVICE_PORT"}],"imagePullPolicy":"PullIfNotPresent"}],"restartPolicy":{}}},"labels":{"component":"fabric8Console"}}},"currentState":{"replicas":0,"podTemplate":{"desiredState":{"manifest":{"version":"","id":"","volumes":null,"containers":null,"restartPolicy":{}}}}},"labels":{"component":"fabric8ConsoleController"}}
E0121 12:29:37.226499       1 apply.go:69] Config.item[2].create: invalid value '<*>(0xc20826d290)Post http://localhost:8080/osapi/v1beta1/routes?namespace=default: dial tcp 127.0.0.1:8080: connection refused': unable to create: {"kind":"Route","apiVersion":"v1beta1","metadata":{"creationTimestamp":null},"host":"fabric8.local","serviceName":"fabric8-console"}
E0121 12:29:40.633394       1 apply.go:69] Config.item[0].create: invalid value '<*>(0xc2081880f0)Post http://localhost:8080/api/v1beta1/services?namespace=default: dial tcp 127.0.0.1:8080: connection refused': unable to create: {"kind":"Service","id":"registry-service","creationTimestamp":null,"apiVersion":"v1beta1","port":5000,"selector":{"name":"registry-pod"},"containerPort":5000}
E0121 12:29:40.633536       1 apply.go:69] Config.item[1].create: invalid value '<*>(0xc2081d1fb0)Post http://localhost:8080/api/v1beta1/replicationControllers?namespace=default: dial tcp 127.0.0.1:8080: connection refused': unable to create: {"kind":"ReplicationController","id":"registry-controller","creationTimestamp":null,"apiVersion":"v1beta1","desiredState":{"replicas":1,"replicaSelector":{"name":"registry-pod"},"podTemplate":{"desiredState":{"manifest":{"version":"v1beta2","id":"","volumes":[{"name":"registry-persistent-storage","source":{"hostDir":{"path":"/volumes/registry/data"},"emptyDir":null,"persistentDisk":null,"gitRepo":null}}],"containers":[{"name":"registry-container","image":"registry","ports":[{"containerPort":5000,"protocol":"TCP"}],"env":[{"name":"STORAGE_PATH","key":"STORAGE_PATH","value":"/registry"}],"volumeMounts":[{"name":"registry-persistent-storage","mountPath":"/registry","path":"/registry"}],"imagePullPolicy":"PullIfNotPresent"}],"restartPolicy":{}}},"labels":{"name":"registry-pod"}}},"currentState":{"replicas":0,"podTemplate":{"desiredState":{"manifest":{"version":"","id":"","volumes":null,"containers":null,"restartPolicy":{}}}}},"labels":{"name":"registry-controller"}}
F0121 12:29:43.964563       1 get.go:151] Get http://localhost:8080/api/v1beta1/services?namespace=default: dial tcp 127.0.0.1:8080: connection refused

Waiting for services to fully come up - shouldn't be too long for you to wait

Waiting for Fabric8 console

**Comment by rhui** [comment]
So, I rm the docker containers and rerun it
[root@rwhui-pc ~]# docker ps -a
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS                      PORTS               NAMES
0c5abe6d2e24        google/cadvisor:0.8.0     "/usr/bin/cadvisor"    13 hours ago        Exited (0) 12 hours ago                         cadvisor            
e6aa0793c08e        openshift/origin:latest   "/usr/bin/openshift    13 hours ago        Exited (255) 13 hours ago                       openshift           
[root@rwhui-pc ~]# docker rm cadvisor openshift 
cadvisor
openshift
[root@rwhui-pc ~]# docker start cadvisor openshift
Error response from daemon: No such container: cadvisor
Error response from daemon: No such container: openshift
2015/01/22 09:21:31 Error: failed to start one or more containers
[root@rwhui-pc ~]# bash <(curl -sSL https://bit.ly/get-fabric8) 
Validating your environment...

Validating firewall rules

W0122 01:22:04.064603       1 start.go:92] Unable to lookup hostname, using "localhost": Couldn't determine hostname: exit status 1
I0122 01:22:04.128158       1 apply.go:65] Creation succeeded for Service with name fabric8-console-service
I0122 01:22:04.128172       1 apply.go:65] Creation succeeded for ReplicationController with name fabric8ConsoleController
I0122 01:22:04.128175       1 apply.go:65] Creation succeeded for Route with name 
W0122 01:22:07.931048       1 start.go:92] Unable to lookup hostname, using "localhost": Couldn't determine hostname: exit status 1
I0122 01:22:07.982845       1 restclient.go:146] Waiting for completion of operation 6
I0122 01:22:09.984635       1 apply.go:65] Creation succeeded for Service with name registry-service
I0122 01:22:09.984649       1 apply.go:65] Creation succeeded for ReplicationController with name registry-controller
W0122 01:22:13.573023       1 start.go:92] Unable to lookup hostname, using "localhost": Couldn't determine hostname: exit status 1

Waiting for services to fully come up - shouldn't be too long for you to wait

Waiting for Fabric8 console

>> Still seems to stuck in fabric8..

**Comment by rhui** [comment]
So, using step 2 to rm the containers and a little more patience to waiting for the fabric8 console to come up. 
It works now. 
Waiting for Fabric8 console

You're all up & running! Here are the available services:

Service              | URL                                                         
-------              | ---                                                         
Fabric8 console      | http://172.30.17.143:8080/hawtio/                           
Docker Registry      | http://172.30.17.4:5000

**Comment by jimmidyson** [comment]
Yeah a bit of patience the first time is needed. Should be quicker on
subsequent runs though hopefully, depending on hardware obviously.

**Comment by jstrachan** [comment]
BTW if you ever see things like
```
2015/01/21 20:29:36 Error response from daemon: Conflict, The name openshift is already assigned to 
```
then pass in the -f option to the script; this will force the old docker containers to be removed first. 

FWIW when naming a docker container (e.g. 'openshift') if the container is running or dead; you can't create other container with the same name until you remove the old containers. By default the bash script doesn't do that unless you pass in -f.

@jimmidyson BTW I wonder if we should default to -f behaviour and tone down the warning a little if no old containers exist to be deleted?

**Comment by jimmidyson** [comment]
@jstrachan - agreed. Need to add a check to see if containers exist first &
ask user if they want to delete existing containers if they do, even if
running without -f.

**Comment by rhui** [comment]
@jstrachan I think it would be nice to check with the user and do a -f ... 
Also, one question and suggestion: the question is where is a good place to ask newbie questions on this? For example, I can't figure out what's my $DOCKER_HOST should be and I think it is my default systemd didn't set it when I start ( -H <empty>). This leads to a suggestion is that the instruction seems to cover boot2docker instructions for mac os users and windows users. I currently am using fedora 20 and some of the instructions are hard to find.
