### ISSUE TITLE
ElasticSearch River plugin for LevelDB files?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#341]
I spotted this
https://github.com/domdorn/elasticsearch-river-activemq/

and it got me thinking; it'd be handy if folks could search over all messages sent (even after they have been consumed), so folks can do analysis and so forth.

It might be nice to have an ElasticSearch plugin (River) for ActiveMQ which is LevelDB aware; so that as a file is created; its then indexed in one bulk operation (which is much more efficient in ES), then folks could query the data in ES

**Comment by davsclaus** [comment]
no
