### ISSUE TITLE
Not existent vagrant-restart-openshift.sh mentioned in docs

### ISSUE THREAD

**Issue by ppalaga** [fabric8io/fabric8#3469]
`vagrant-restart-openshift.sh` does not exist anymore but the docs in https://github.com/fabric8io/fabric8/blob/master/docs/openShiftVagrant.md#recreating-openshift mentions `vagrant-restart-openshift.sh` three times. The docs should be fixed to describe some supported way of resetting of OpenShift.

**Comment by davsclaus** [comment]
I wonder if the docs at
http://fabric8.io/v2/openShiftDocker.html

is better. They talk about vagrant, and how to reset it from a snapshot.

@rawlingsj wonder if you have any thoughts?

**Comment by ppalaga** [comment]
https://github.com/fabric8io/fabric8/pull/3575 replaces the mentions of the non-existent `vagrant-restart-openshift.sh` with steps that I use to reset the vagrant VMs.

**Comment by ppalaga** [comment]
Fixed by merging https://github.com/fabric8io/fabric8/pull/3575
