### ISSUE TITLE
create an app for gogs

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3503]

**Comment by jimmidyson** [comment]
Done

**Comment by jstrachan** [comment]
coolio. It'd be awesome to auto-configure it in the docker image/CLI so that it starts up configured to use the embedded database and so its got a login/pwd. Not a biggie right now though...

**Comment by jimmidyson** [comment]
Yeah I had a look & couldn't figure out how to do it in a reasonable amount
of time (minutes ;)). Might come back to this some time in future but it's
enough for now I think.
