### ISSUE TITLE
Add app json templateing

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8#3505]
When building apps that require passwords or other secrets, fabric8 plugin should generate template kind instead of config kind with specified generated parameters. When running an app that has a template kind rather than a config kind, fabric8 should run this through the processor, capture & display those generated parameters.

**Comment by jstrachan** [comment]
@iocanel fancy having a go at this one now we've the lovely new builder stuff; should be easier to generate an OpenShift Template for all apps; then have a way to specify parameters via maven properties etc?

**Comment by jstrachan** [comment]
this issue relates to this one too https://github.com/openshift/origin/issues/1629 in that it'd be nice if we could generate OpenShift Templates which have icons + documentation inside them too (so they become kinda like App Zips)

**Comment by jstrachan** [comment]
Think this is all fixed now - define template parameters via a properties file, maven properties or the DSL
