### ISSUE TITLE
we should limit pod restarts on RCs in the arquillian test

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3506]
if there's no restart policy on pods / RCs we should set some upper limit of say 3 times that the RC should try and restart a pod - to avoid failing pods doing continuous restarts for a long time

**Comment by iocanel** [comment]
Last time I checked there was no obvious way to set the maxim restarts counts or something like this.

Are you suggesting that we should poll or something?

**Comment by jstrachan** [comment]
Gonna close this - I think this issue is fixed by this now: #5326. My motivation for this issue was to avoid the case where a pod starts up; but then barfs and restarts again and again. Just testing a pod stays ready for a period of time is a better assertion
