### ISSUE TITLE
better link for services

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/fabric8#3512]
If I'm on the kibana services view there is a column with the addresses providing links to the service views (this is what i guessed). Instead a new tab with some json opens as the link points to a url like http://172.30.17.181/kubernetes/api/v1beta2/proxy/services/app-library/?namespace=default

**Comment by davidatkins** [comment]
I think clicking that link is meant to go to the service via the proxy, but the proxy was  broken in fabric8 last week which led to you seeing json instead. I was getting the same thing. It now seems to be working in the latest code base.

I think it's counter-intuitive that a link should state one address but take you to another. I propose:

* Still provide the actual service address, but either remove the link or make it link to the actual service
* Add a link/button next to the service address that links to the proxied endpoint. Text could be 'via proxy'?

**Comment by jstrachan** [comment]
I think this is now fixed - links use the Route host name for services - or their portalIP if not
