### ISSUE TITLE
DOCKER_REGISTRY value created by start script doesn't behave with Docker Maven Plugin

### ISSUE THREAD

**Issue by davidatkins** [fabric8io/fabric8#3530]
Hello,

The quickstarts use the DOCKER_REGISTRY environment variable to configure the Docker Maven Plugin:

      <docker.registryPrefix>${env.DOCKER_REGISTRY}/</docker.registryPrefix>
      <docker.image>${docker.registryPrefix}fabric8/${project.artifactId}:${project.version}</docker.image>

The value for DOCKER_REGISTRY output by the start script includes an http prefix:

      export DOCKER_REGISTRY=http://172.30.17.229:5000

But this upsets the docker maven plugin:

      [INFO] --- docker-maven-plugin:0.11.0:build (default-cli) @ example-camel ---
      [INFO] Copying files to /Users/david/Documents/Work/projects/openshift/blueprint-openshift/blueprints/examples/camel-cdi/target/docker/build/maven
      [INFO] Building tar: /Users/david/Documents/Work/projects/openshift/blueprint-openshift/blueprints/examples/camel-cdi/target/docker/tmp/docker-build.tar
      [INFO] DOCKER> Creating image [http://172.30.17.229:5000/fabric8/example-camel:1.0-SNAPSHOT]
      [WARNING] DOCKER> Couldn't parse answer chunk 'Invalid repository name (ex: "registry.domain.tld/myrepos")
      ': org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

Two fixes come to mind:

1. Remove the http:// prefix from the start script output - does anything rely on it having that prefix?
2. Somehow strip the http:// before passing the docker maven plugin (I can't think of any easy way to do that in Maven?)

**Comment by davidatkins** [comment]
We could create a new property using the Maven Build Plugin using a Regex to strip the http:// from the DOCKER_REGISTRY environment variable, but it's pretty clunky - http://stackoverflow.com/questions/12002033/in-maven-how-can-i-dynamically-build-a-property-value-at-runtime

**Comment by jimmidyson** [comment]
Think we should just drop the http from the registry URL - there was a fix in a separate PR for this, but it included other stuff. Will see if I can cherry-pick it.

**Comment by davidatkins** [comment]
Sounds good to me!
