### ISSUE TITLE
create a Continuous Delivery pipeline on OpenShift

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3541]
lots of fabric8 users really want a nice CD pipeline setup between environments. In many ways we consider releasing of binary artefacts or images as being either the existing builds in OpenShift (e.g. STI) or done outside of OpenShift via CI tools like Jenkins.

Once a new image is created though; we want to setup build pipelines that run integration/load/soak/regression tests in different environments which also have human approval which if the builds + approvals are met, then another environment/namespace gets triggered to perform a deployment (e.g. via the build updating a tag on a docker image so that we can reuse [OpenShift's DeploymentConfig option](https://github.com/openshift/origin/blob/master/docs/deployments.md#strategies)).

[OpenShift has pretty flexible builds](https://github.com/openshift/origin/blob/master/docs/builds.md) right now but unfortunately [they cannot easily be composed into loosely coupled pipelines](https://github.com/openshift/origin/issues/1228).

So I guess for now - until OpenShift can handle pipelines or post-build-notifications/triggers - we need to use Jenkins for all those build steps.

We could maybe start with an OpenShift build that fires off a Jenkins build when a new docker image is available; then that jenkins build can do the usual jenkins workflow/pipeline stuff - and invoke OpenShift's webhooks when it wants to fire off any OpenShift builds?

Maybe we leave OpenShift just do to image change triggers (which seem supported pretty well on BuildConfigs and DeploymentConfigs) - and do everything else via scripting Jenkins?

**Comment by rawlingsj** [comment]
Yeah I think this is an easier place to start as the tools are more familiar and we can work out any larger problems that could hit us.  Then when more examples and a clearer way of using the openshift parts are available then we can offer those as pluggable parts.

Having said that, it's not the nicest but we could use many generic hook triggers and at the end of each build stage if successful use curl to trigger the next one.  This seems a bit rubbish as there's overhead of how you chain them all together and managing the correct env vars values that are used by curl to trigger the correct next stage.

Given the two I think the Jenkins option will be easier to get going with.

**Comment by rawlingsj** [comment]
Just thinking about that some more... I wonder if we could have Jenkins running in the build container, the builder.sh script does a git clone of all the config jenkins needs for that particular pipline.  Once thats on the filesystem Jenkins picks it all up (may need a jenkins restart I guess) that way Jenkins will dynamically create all the jobs and we can make the build generic.  We'd then just need to know when the pipeline has finished to trigger the openshift deployment.

Equally we could do this for GoCD as well.

**Comment by jstrachan** [comment]
I love the idea of just hacking build configs in git so we don't have to muck about pushing stuff to REST APIs in Jenkins etc.

Maybe we mount a volume for the jenkins / GoCD configurations? Then we have a separate container does the 'git clone' thingy - then we could use different mechanisms to create the configuration (e.g. templating on the fly?)

**Comment by jstrachan** [comment]
I guess the only complexity is gonna be ensuring the config works with the docker image of jenkins (e.g. its got the right plugins installed)? But then we'd have the same issue if the wizard is configured with template build configs etc too

**Comment by rawlingsj** [comment]
I reckon we can list the plugins needed in a properties file of some sort and store it in git with the config, then in the builder script loop round each and download it to the jenkins plugin folder.  It might work :)

wget http://updates.jenkins-ci.org/latest/$PLUGIN  $JENKINS_HOME/plugins/

**Comment by rawlingsj** [comment]
Yeah I thought about mounting the volume to start with in a pod that could be shared between two containers, one the cloning and the second jenkins this would be perfect https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md#emptydir

Only the openshift 'builder' is a docker image and not a pod but I still think the idea of splitting them is good.

**Comment by jstrachan** [comment]
Ah yeah, good point ;)

Maybe for now we hack a docker image that is capable of cloning a git repo and using that for its config? Then its nice and simple and a single image?

**Comment by jstrachan** [comment]
I've been looking at the [jenkins workflow plugin](https://github.com/jenkinsci/workflow-plugin) which looks pretty cool stuff: https://www.youtube.com/watch?v=gpaV6x9QwDo another video here: https://www.youtube.com/watch?v=rswdksvwvJY
here's [an example flow](https://github.com/jenkinsci/workflow-plugin-pipeline-demo/blob/master/flow.groovy).

The things I like about this:
* its very flexible and can easily do anything
* avoids having zillions of jenkins plugins for everything; one script can define a whole pipeline
* it can handle restarts of jenkins
* its easy to use a programming language to pass state between builds (e.g. version numbers, image tags, namespace names etc)

Things I'm less keen on
* I prefer the simplicity of just declaratively chaining builds together; then builds can be more like black boxes and easy to draggy droppy together. i.e. pushing complexity into a CustomBuild docker image -  rather than doing it all in a script
* its harder to tool; its trivial to tool all the BuildConfigs / DeploymentConfigs in OpenShift
* its more low level; a few lines of the script tends to be replaced by an STI or Docker build for example
* its harder to visualise whats going on (whereas build triggers are easy)

I guess folks can use a combination of either; as a CustomBuild in OpenShift could just trigger a jenkins workflow - so we can let folks figure out which approach suits them the most. It'd be nice to be able to choose when to use one or the other. 

It definitely would be nice to at least have the option to do everything with pure OpenShift; then folks can decide when using the jenkins workflow plugin makes sense

**Comment by davidatkins** [comment]
+1 for the workflow plugin. I noticed that it has inbuilt git support - see 'Loading script text from version control' @ https://github.com/jenkinsci/workflow-plugin/blob/master/TUTORIAL.md. What's nice about using this there would be a mechanism in the Jenkins GUI to update the job definition (rather than a custom fabric8/OpenShift script to get Jenkins to see the change, which may involve a restart?).

It does mean that the setup will have two seperate git pulls - one to get the base jenkins setup, install plugins and create the workflow config, and then the workflow plugin itself to pull in the workflow definition.

another possible +1 for the workflow plugin is I suspect it would be easy to create OpenShift specific functions as shared POJO/POGO code in a JAR without having to worry about writing full Jenkins Plugins?

**Comment by jstrachan** [comment]
@davidatkins agreed! Keeping the workflow scripts in a git repo sounds a great idea - then we can just have a single App (docker image) which has the workflow plugin installed. Then for each pipeline we have a jenkins job which knows to pull its workflow definition from the git repo. Simples!

I love the idea of a POJO/POGO library we could install in the Jenkins image by default that has simple functions for triggering OpenShift builds - or for things like adding a docker image tag. (e.g. after an integration test works on an image, move the "production" tag to the docker image so that the OpenShift DeploymentConfig kicks in on the production namespace)

**Comment by davidatkins** [comment]
Following James' awesome demo I wanted to capture a few 'nice to haves' that come to mind for this:

* Centralised archive of build history  e.g. who progressed the pipeline into production, junit results, timings etc. I could see this data being available in various source (E.g. Gerrit for human interaction, Sonar for test info, Kibana for build logs, OpenShift Builds for image build history, Maven Repo if we decide to publish build artifacts to one, ), but it would be good to have a centralised view on this historical data.
* Human interaction - we discussed gerrit as a mechanism for this. the pipeline plugin above supports huamn steps
* Replay functionality - this could be tricky. I think it's possible that we may want to manually retry a step if it fails first time. This is more likely to be an issue for functional tests like selenium etc. that tend to be a little more fragile. A simple answer is to just the start the pipeline from scratch :)

**Comment by jstrachan** [comment]
starting a prototype using jBPM to see how that hangs together: https://github.com/fabric8io/fabric8/issues/3671

**Comment by jstrachan** [comment]
gonna mark this as closed as the CI / CD pipeline is rocking thanks to loads of hard work by @rawlingsj
