### ISSUE TITLE
[v2] - Docker private registry should allow insecure access

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#3565]
I have created a local fabric8 using the get fabric script from
http://fabric8.io/v2/openShiftDocker.html#run-the-start-script

And then following the example guide at
http://fabric8.io/v2/example.html

And then after building the example from maven I run the docker push
```
davsclaus:~/workspace/quickstarts/quickstarts/war/camel-servlet (master)/$ docker push $DOCKER_REGISTRY/fabric8/quickstart-war-camel-servlet:2.2-SNAPSHOT
FATA[0002] Error: Invalid registry endpoint https://172.30.17.21:5000/v1/: Get https://172.30.17.21:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.30.17.21:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.30.17.21:5000/ca.crt
```

**Comment by davsclaus** [comment]
My boot2docker had the --insecure pointing to a different IP - but restaring boot2docker will kill all the containers, but it could be something in the script and when using osx with boot2docer that this deamon must be configured in its config.

**Comment by jimmidyson** [comment]
In docs we specify "--insecure-registry 172.0.0.0/8". This covers all pod IPs so no need to change it if you do need to rebuild everything.

**Comment by jimmidyson** [comment]
Closing as docs cover this
