### ISSUE TITLE
allow @Service to inject the URL of the service using OpenShift Routes if outside of kubernetes

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3582]
if java is running outside of kubernetes (e.g. in your IDE, in JUnit) we use $KUBERNETES_MASTER to connect to the remote cluster. In those cases we usually cant' see the portal IP address of the service. 

If the kubernetes environment is openshift, there may be OpenShift Routes defined to map to global host names for the service (and maybe has DNS support too).

So we may wanna use the routes first rather than the portal IP addresses.

**Comment by iocanel** [comment]
Fixed by da3b9e47a93efdeae128cd2bc2ac50684033146c
