### ISSUE TITLE
the defaulted apiVersion for OpenShift stuff should use v1beta1 right now for osapi

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3594]

**Comment by davsclaus** [comment]
Ah beta1 vs beta2 vs beta3 - I hope we get to v1final one day.

**Comment by jstrachan** [comment]
yeah, we're working on it ;) Hope to get to v1beta3 really soon; then v1 is very similar to that and should arrive upstream soon...

**Comment by jstrachan** [comment]
now on v1beta3!
