### ISSUE TITLE
create an @Service equivalent for Spring from fabric8-cdi

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3646]
Using @Service rocks; but we should let spring / spring boot folks benefit from this awesome too

**Comment by iocanel** [comment]
So how about moving all the annotations to a different module, say fabric8-annotations or something and then have fabric-cdi, fabric-spring and what not?

**Comment by jstrachan** [comment]
sounds good to me. Not sure we need a spring version of @Configuration and stuff; as Spring's kinda got something similar baked in - but definitely for @Service

**Comment by jstrachan** [comment]
Think this is fixed now @iocanel isn't it?

**Comment by iocanel** [comment]
yeap
