### ISSUE TITLE
Understanding "upload" attribute of maven plugin in fabric8

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [fabric8io/fabric8#3651]
Hi

I am working on a maven based proprietary project for my company.
I am using fabric8 maven plugin, within which I have set "upload" element of configuration to true

On http://fabric8.io/gitbook/mavenPlugin.html page, I see below content for "upload" element

upload - Whether or not the deploy goal should upload the local builds to the fabric maven repository. You could disable this step if you have configured your fabric maven repository to reuse your local maven repository. Defaults to true. 

Based on above description, when I set upload to true, would the built maven project be uploaded to external repository on the web or it would be uploaded to locally set up fabric8/data/maven.... location?
If it's uploaded to external repository on the web, it's not something intended as the project is proprietary.  Pls advice.

Thanks in advance,
Ramesh

**Comment by davsclaus** [comment]
It uploads to the fabric server you have defined here
http://fabric8.io/gitbook/mavenPlugin.html#configuring-the-plugin

**Comment by davsclaus** [comment]
i.e. in other words it does not upload to the public internet such as maven central. It uploads to the fabric server you have configured. The fabric v1 server comes out of  the box with an embedded maven repo, that repo is where its being uploaded.
