### ISSUE TITLE
create system dump operation

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#367]
it'd be great to have a JMX operation and CLI to generate a dump of thread dumps, logs and the git repo for a fabric.

Maybe we create a tarball with a directory for each container; with a dump of threads, metrics, log files etc - then  the git config; then make a big tarball - maybe even auto-uploading it to RH portal?

**Comment by davsclaus** [comment]
Fuse 6.2 has some RH support assistance or something related to this
