### ISSUE TITLE
forge-rest - web form should indicate fields as required

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#3687]
For example adding a new camel endpoint then it has some options which is required. They should be shown in bold or with * or something to indicate they are required.

**Comment by davsclaus** [comment]
![screen shot 2015-03-31 at 2 22 18 pm](https://cloud.githubusercontent.com/assets/477100/6919200/46de86ae-d7b5-11e4-8367-924d33802218.png)

**Comment by davsclaus** [comment]
For example that screenshot above, then host is required. (port is not as Camel can default to 21 etc)

**Comment by jstrachan** [comment]
we should show the list of required fields at the bottom of the page now
