### ISSUE TITLE
kubernetes-api should default to using KUBERNETES_SERVICE_HOST if available...

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3694]
see https://github.com/openshift/origin/issues/196#issuecomment-64098502 also if no env vars we could default to openshift.default.local as well?

**Comment by jimmidyson** [comment]
It already should be defaulting to KUBERNETES_SERVICE_HOST for writable operations & KUBERNETES_RO_SERVICE_HOST read-only ops. Is that not working?

**Comment by jstrachan** [comment]
ah yeah :) just raised the issue to double check it was all set in terms of the latest upstream. 

Gonna close - sorry for the noise. (haven't had a coffee yet - lemme fix that... ;-)
