### ISSUE TITLE
Issues with autoscale, deployment

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [fabric8io/fabric8#3700]
Hi 

I am facing below issues

1) Below error occurs while creating and starting new container for deployed osb
		a) java.lang.RuntimeException: Creating container c2d. java.io.IOException: Error resolving artifact org.jolokia:jolokia-jvm:jar:agent:1.2.2: Could not transfer artifact org.jolokia:jolokia-jvm:jar:agent:1.2.2 from/to central (http://repo1.maven.org/maven2/): Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.2.2/jolokia-jvm-1.2.2-agent.jar
			Caused by: java.net.UnknownHostException: repo1.maven.org 
			"Here java 1.8 was being used"
			
		b) Error transferring file: Server returned HTTP response code: 407 for URL: http://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.2.2/jolokia-jvm-1.2.2-agent.jar from http://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.2.2/jolokia-jvm-1.2.2-agent.jar with proxyInfo ProxyInfo{host='appproxy.bankofamerica.com', userName='null', port=8080, type='http', nonProxyHosts='null'}
			"Here java 1.7 was being used"

			There is bug posted on https://issues.apache.org/jira/browse/KARAF-3342 related to "Version 3.0.2 ignores maven settings, proxy and mirrors in particular".  Is my problem at b) above due to this bug?
			
2) autoscale feature
		a) when we try to include autoscale to root container by setting like below before starting container, autoscale is not getting included to root container;
			export FABRIC8_PROFILES=autoscale
		"We have to manually add autoscale profile to root container to make autoscale work.  Am I missing something?"

3) on a fresh install of fabric8, enabling autoscale with 3 min below error occurred
2015-04-01 05:06:32,222 | WARN  | ontainer-monitor | JolokiaAgentHelper               | 190 - io.fabric8.fabric-process-container - 1.2.0.Beta4 | Failed to query: http://admin:admin@1.1.1.1:9006/jolokia/list/?maxDepth=1. java.io.IOException: Server returned HTTP response code: 503 for URL: http://admin:admin@1.1.1.1:9006/jolokia/list/?maxDepth=1
java.io.IOException: Server returned HTTP response code: 503 for URL: http://admin:admin@1.1.1.1:9006/jolokia/list/?maxDepth=1
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)[:1.7.0_51]

Thanks in advance

**Comment by davsclaus** [comment]
auto scaler is no longer maintained in 1.x
