### ISSUE TITLE
kubernetes client should support client auth file

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8#3711]
As detailed at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/clientauth/clientauth.go.

Basically parse a json file to get paths to ca certificate & client certificate details.

**Comment by jstrachan** [comment]
@jimmidyson is this one done now? We parse the config for the token at least - we might need to add some code to read the certs too maybe?

**Comment by jimmidyson** [comment]
I added the parsing for certs, etc this morning. This should now work
properly. Tested using the maven plugin, oc login, no env vars set like
KUBERNETES_MASTER etc & all works great.

**Comment by jstrachan** [comment]
awesome! Lets close this one then
