### ISSUE TITLE
mvn fabric8:create-env should default to using external service hosts (routes rather than portalIPs) by default

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3754]
the default use case for the excellent command:
```
mvn fabric8:create-env
```
is gonna be when you're remote, on your laptop running some stuff thats connecting to remote services on kubernetes. So the default should be to use external (routes / DNS names) rather than service portalIPs. 

I guess we could have a parameter to use internal names; but I'd have thought external is a better default and the most useful.

**Comment by iocanel** [comment]
If a route of the service exists it will be preferred over the service. If not it will still fallback to the portal ip.
