### ISSUE TITLE
k8s Controller.java convertYamlToJson(String) treats json string as file name

### ISSUE THREAD

**Issue by jbweeks** [fabric8io/fabric8#3760]
kubernetes-api/src/main/java/io/fabric8/kubernetes/api/Controller.java
...looks like it has a copy & paste error, treating a json string argument as a file name:

   private String convertYamlToJson(String yamlString) throws FileNotFoundException {
        Yaml yaml = new Yaml();
        FileInputStream fstream = new FileInputStream(yamlString);

        Map<String, Object> map = (Map<String, Object>) yaml.load(fstream);
        JSONObject jsonObject = new JSONObject(map);

        return jsonObject.toString();
    }

**Comment by davsclaus** [comment]
Yes indeed there is a method that takes a java.io.File which has the same code.

**Comment by davsclaus** [comment]
Thanks for reporting. It should be fixed now.

Btw you are welcome to work on patches as PRs - we love contributions.
