### ISSUE TITLE
Jube run with Quickstart fails to deploy

### ISSUE THREAD

**Issue by EvilJohn** [fabric8io/fabric8#3762]
Following the instructions here: http://fabric8.io/guide/jubeRunQuickstart.html
Executing the final command in the sequence

mvn clean install fabric8:json fabric8:run

Produces this error:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.0.43:run (default-cli) on project quickstart-java-camel-spring: Unexpected character (',' (code 44)): was expecting double-quote to start field name
[ERROR] at [Source: java.io.ByteArrayInputStream@1cc708a7; line: 29, column: 20]

I tested this on both OS X and Linux Mint.

**Comment by davsclaus** [comment]
Ah yeah there is a build problem on latest code in the mq controller. You can build from the 2.0.43 tag which was released and should work. Or you can `cd quickstarts` to only build the quickstarts and try the ones without mq.

**Comment by davsclaus** [comment]
I assume its the mvn plugin that generates the json that has a flaw
```
            "containers": [
                {
                  "name": "fabric8-mq-controller-container",
                  "image": "${env.DOCKER_REGISTRY}/fabric8/fabric8-mq-controller:2.2-SNAPSHOT",
                  "imagePullPolicy": "PullAlways",
                  ,
                  "ports": [
                    {
                      "containerPort": 6162,
                      "name": "amq"
    
                    }, 
                    {
                      "containerPort": 8778,
                      "name": "jolokia"
    
                    }
                  ]
                }
              ]
```

Notice the empty value that results in a double space.

@jimmidyson, @rawlingsj  didnt the fabric8 mvn plugin recently get some code changes that may cause this?

**Comment by davsclaus** [comment]
@EvilJohn  so to only build the camel-spring quickstart and try it on jube you can do
```
git clone https://github.com/fabric8io/quickstarts.git
cd quickstarts
cd quickstarts/java/camel-spring
mvn install
mvn clean install fabric8:json fabric8:run
```

**Comment by davsclaus** [comment]
Ah this always seems to generate invalid json, also for the camel-spring quickstart
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.0.43:run (default-cli) on project quickstart-java-camel-spring: Unexpected character (',' (code 44)): was expecting double-quote to start field name
[ERROR] at [Source: java.io.ByteArrayInputStream@245522e1; line: 29, column: 20]
```

**Comment by davsclaus** [comment]
If you use 2.0.42 version of the plugin it works
```
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>2.0.42</version>
```

**Comment by jimmidyson** [comment]
Probably a change I made recently. I'll fix today. Sorry about that.

**Comment by jimmidyson** [comment]
A misplaced comma in the mvel... I'd like to try to move away from mvel & just use jackson to do the marshalling of the manifests - much easier to maintain & more flexible.
