### ISSUE TITLE
Kubernetes API model is broken

### ISSUE THREAD

**Issue by pires** [fabric8io/fabric8#3817]
For instance, `Memory` is an `int` which will blow up if there's more than 2GB used. See https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/9

**Comment by davsclaus** [comment]
@jimmidyson did you fix this?

**Comment by pires** [comment]
@davsclaus https://github.com/fabric8io/origin-schema-generator/issues/25 still open.

**Comment by jimmidyson** [comment]
Yeah not fixed yet, looking now. Hope for a quick fix.

**Comment by jimmidyson** [comment]
This should be fixes now in kube model - ready for next release.

**Comment by pires** [comment]
When will we have next release? I believe this issue is worth cutting a new release, no?

**Comment by davsclaus** [comment]
I think @jstrachan talked about a new release the week we come into now.
