### ISSUE TITLE
create a CD process for the fabric8 / jube / fabric8io/quickstarts projects

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3821]
we really need a responsive CD process for building, testing and promoting releases of fabric8 / jube / quickstarts / archetypes along with java/maven artefacts and docker images. Right now its very manual, very error prone and we can end up releasing stuff before we find out things don't quite work ;).

Ideally each commit would result in a new canary release internally that would then be used to run a bunch of integration tests and be auto-deployed in running OpenShift environments to help give rapid feedback to developers. Then when all the tests are run and the team are happy we can promote a canary build to the public maven central, public docker registry and update the website.

## Overview

inspired by posts like [this](http://hardmockcafe.blogspot.de/2015/03/job-dsl-part-i.html) and [this](http://axelfontaine.com/blog/final-nail.html) we're taking the following approach:
* all infrastructure runs on kubernetes using fabric8 apps (jenkins, nexus, gogs etc)
* use Jenkins to setup multiple pipelines using the [Job DSL plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin)
* store the job DSL in [a git repository](https://github.com/fabric8io/jenkins-pipeline-dsl) so we can easily hack it and version it and anyone can run their own version of the CD system
* canary releases go to a local nexus running on kubernetes (which also acts as a mvn proxy to stuff downloaded from the internet).
* we trigger releases and integration test builds on each commit to any of the projects (fabric8, jube, quickstarts)
* when the CD process completes successfully (possibly with human approval) we promote to maven central and docker.io and push the scm tags up to github.com

## Pending issues

* need to promote / sync to maven central all the promoted canary build artifacts
* do we tag/branch in a local gogs repo until promotion; then push the tag for that release up to github.com on promotion?
* need a script to push all images with a specific tag in a local docker registry

**Comment by jstrachan** [comment]
wonder if the git server plugin might help for tagging canary releases in git until we are ready to promote: https://wiki.jenkins-ci.org/display/JENKINS/Git+Server+Plugin

**Comment by jstrachan** [comment]
One thing I'm not sure about is the docker registry host/port in docker image names.

Part of me would prefer to use generic <code>user/repo</code> names in all the generated kubernetes.json files. Then they'd work just fine with global images.

When using a local docker registry (rather than the global docker hub) folks often prefix the registry:port on the docker name. e.g. <code>myrepo.com:5000/user/repo</code>.

For doing a canary release; we'll need to use a local docker registry to store the images until they get released and pushed.

I wonder if there's a way to get kubernetes to search a list of repositories. so for an image called <code>user/repo</code> it'd look in <code>myrepo.com/5000</code> as well as the global docker registry? Then we don't have to mess around changing all the kubernetes.json files for each kubernetes environment?

I guess it should be possible to configure the list of docker registries to look for; I wonder if this has to be done at the docker daemon level before installing OpenShift; or we can configure it inside OpenShift?

**Comment by gashcrumb** [comment]
You can set up docker to use a local docker registry mirror pretty easily, I wound up doing this myself actually just so it was easy to push stuff and get it picked up.  You just add :

`--registry-mirror=http://localhost:5000` 

to your docker launch command after starting your docker registry.  MIght be nice to leave off the host/port from images if possible so that it's easy to use a local registry or not maybe?

**Comment by jstrachan** [comment]
getting close now! :) we managed to deploy stuff into the itest namespace in a CD job. though docker died... ;)
