### ISSUE TITLE
fabric8 console does not display objects not in default namespace

### ISSUE THREAD

**Issue by rcernich** [fabric8io/fabric8#3830]
Steps to reproduce:
1. Create a new project in OpenShift (openshift cli new-project foo)
2. Create an application in the project (openshift cli create -n foo -f some.json)
3. Open the fabric8 console and try to view specifics of one of the objects in the foo project.  Notice a blank screen with a spinning cursor.

**Comment by jstrachan** [comment]
I think this is fixed now; I've been using multiple namespaces lately.

Run this on your openshift box:
```
docker pull fabric8/fabric8-console
```
then delete the current fabric8 console pod(s); the RC will then recreate them. Then hit reload in your browser ;)
