### ISSUE TITLE
fabric8 v2 installation support

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [fabric8io/fabric8#3888]
Hi

We are trying to install fabric8 v2, and we found that jube and openshift are 2 ways to get started with fabric8 v2 as per http://fabric8.io/guide/getStarted.html
We would like to if openshift is mandatory to have fabric8 v2 running or docker/kubernetes installation would do to consider fabric8 v2?

Any article that mentions step by step instructions to install fabric8 v2 without openshift?
Also, it would be helpful to know that if we want to call fabric8 v2 so, what are components that we need to have installed?  And what relationship that fabric8 v2 has with docker/ kubernetes?

Thanks in advance
Ramesh

**Comment by jstrachan** [comment]
Hi @ramesh-mohan-reddy 

Sorry things are so confusing on our website right now! We're working hard at the moment migrating to the latest greatest kubernetes / openshift releases; and to create a single json file for different deployment options of fabric8:

* base
* management (base + centralised logging/metrics)
* continuous deployment environment (nexus / jenkins / sonaqube / gogs and integrated chat etc)
* iPaaS 
* kitchen sink (all of the above)

when that release is out; hopefully in a week or so - then given a kubernetes installation; whether thats done by hand using Kubernetes itself or its RHEL Atomic or OpenShift V3 or Google cloud; then it'll be a single command line command to install and run it all.

e.g. using the ['osc' command line tool](https://github.com/openshift/origin/blob/master/docs/cli.md) in OpenShift it would be something like
```
osc process -f thefabric8file.json | osc create -f -
```
and thats it!

In general fabric8 v2 now sits on top of the kubernetes model and REST API. So you need some kubernetes installation of some kind; either 
* [kubernetes itself](http://kubernetes.io/)
* RHEL Atomic / [Project Atomic](http://www.projectatomic.io/)
* [OpenShift V3](http://www.openshift.org/)
* [Google Container Engine (GKE)](http://www.openshift.org//)

There's also [Jube](http://fabric8.io/jube/index.html) which is a pure Java version of kubernetes. Its much [simpler than kubernetes](http://fabric8.io/jube/differences.html) and intended really for running Java stuff only really; it can't run docker containers or do any of the nice docker container stuff (isolation, CPU/IO/Memory limiting etc) or the kubernetes networking stuff (IP address per pod and service etc) but is there really for folks who can't run Linux and want to provision java processes in a kubernetes-like way.

If you possibly can run docker and linux then we highly recommend the real kubernetes to Jube; its way more powerful and can run any docker container etc. Jube is more for folks who are on legacy operating systems or can't yet use Docker

**Comment by ramesh-mohan-reddy** [comment]
Thanks James for a detailed explanation
No worries, I understand how best we have been trying to contribute to community.

Now, I understand that fabric8 v2 needs kubernetes and docker running, so I would like to know where I can get fabric8 v2 as an installable?

**Comment by jstrachan** [comment]
everything in fabric8 v2 is available as a docker container, kubernetes json and jube image zips. 

Here's now to install it currently:
http://fabric8.io/guide/openShiftDocker.html

we should have a one liner you can run on top of any kubernetes / openshift environment next week when we get 2.1.0 out...

**Comment by jstrachan** [comment]
I've added some better install instructions which we'll merge into the website once 2.1.0 is out...
https://github.com/jstrachan/fabric8/blob/docs-2.1.x/docs/fabric8OnOpenShift.md

**Comment by jstrachan** [comment]
FWIW 2.1.1 is out with the updated installation instructions:
http://fabric8.io/guide/getStarted.html

in particular http://fabric8.io/guide/fabric8OnOpenShift.html

**Comment by jstrachan** [comment]
I think we can close this one now - let us know if not; we can always reopen again
