### ISSUE TITLE
"Get started" for OpenShift V3 doesn't work for me

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8#3900]
I had quite some hard times with the "Getting started" guide in the docs when trying to use fabric8 with OpenShift:

* Using the Docker approach doesn't really work for me because the docker provisioning of Vagrant installs and starts the Docker daemon without TCP socket (but only with Unix socket). 
* Using the Vagrant approach I hit this [bug](https://github.com/openshift/origin/issues/2153) when using `$OPENSHIFT_DEV_CLUSTER=1`)

For the Docker approach I tend to recommend to avoid using the Vagrant docker provisioning but provide an own box with Docker preinstalled. That way we can be sure about the state of the docker installation and don't dependent on any upstream changes in the Vagrant docker provisioning.

**Comment by rhuss** [comment]
The Vagrant issue with he missing issue has been fixed in the meantime. 

Now I'm struggling with the smoke test check using curl since the location of the certs has been moved (and my initial guess to use the one call admin in `openshift.local.config/master/` fails with 'Can't load certificate and private key' error)

**Comment by rhuss** [comment]
Tried to use

````bash
$ curl --cert openshift.local.config/master/admin.crt \
         --key openshift.local.config/master/admin.key  \
         --cacert openshift.local.config/master/ca.crt  \
         https://10.245.2.2:8443/api/v1beta1/pods
````

and got 

````
curl: (58) SSL: Can't load the certificate "openshift.local.config/master/admin.crt" and its private key: OSStatus -25299
`````

**Comment by jimmidyson** [comment]
Are you running command as root? Those files are owned by root, 0600, so vagrant user won't be able to read them.

**Comment by rhuss** [comment]
I run it locally from OS X:

````
-rw-r--r-- 1 roland staff  1115 May 11 08:55 admin.crt
-rw------- 1 roland staff  1679 May 11 08:55 admin.key
-rw------- 1 roland staff  7150 May 11 09:14 admin.kubeconfig
-rw-r--r-- 1 roland staff  1066 May 11 08:55 ca.crt
-rw------- 1 roland staff  1675 May 11 08:55 ca.key
````

Isn't the smoke test mentioned in http://fabric8.io/guide/openShiftVagrant.html supposed to be run from outside the VMs ?

Running it as root doesn't help, BTW.

**Comment by jstrachan** [comment]
can we close this now we've the new instructions?
http://fabric8.io/guide/getStarted.html

**Comment by rhuss** [comment]
yes, sure.
