### ISSUE TITLE
Finding if GAed version of fabric8 v1 is available

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [fabric8io/fabric8#3905]
Hi

We are exploring the usage of fabric8 and it would take sometime to switch to fabric8 v2.
Until then, we want to find if general availability version of fabric v1 is available?

Currently, I see fabric v1 beta version is available

Thanks
Ramesh

**Comment by davsclaus** [comment]
The GA version of fabric8 v1 will be the JBoss Fuse 6.2 release which has an ETA for summer 2015.

There is no going to be more community releases of fabric8 v1, the community has moved on to pursue with fabric8 v2.

**Comment by davsclaus** [comment]
btw for fabric8 v2 then 2.1.1 has just been released.

JBoss Fuse 6.2 is in the final stages of latest QE and are still aimed at being GA for summer 2015.
