### ISSUE TITLE
Docs incorrect on openShiftDocker; clean-up-scripts anchor incorrect

### ISSUE THREAD

**Issue by garethahealy** [fabric8io/fabric8#3912]
Clean up scripts anchor is incorrect. Goes to '#clean-up-scripts' but should be '#clean-up-script'

* no 's' on the end.

[1] http://fabric8.io/guide/openShiftDocker.html#prerequisites

**Comment by davsclaus** [comment]
Thanks @garethahealy for reporting and the PR
