### ISSUE TITLE
Docs incorrect on openShiftDocker; running hawtio

### ISSUE THREAD

**Issue by garethahealy** [fabric8io/fabric8#3913]
Think the docs need to be made a bit clearer for 'running hawtio'. It seems to suggest you need to create hawtio container even after the 'kitchen-sink' script has been run, which is incorrect.

Maybe a slight change to clarify this.

[1] http://fabric8.io/guide/openShiftDocker.html#running-a-hawtio-console

**Comment by garethahealy** [comment]
i.e.:

If you have installed Fabric8 on OpenShift via the 'kitchen-sink' URL, hawt.io is already installed and can be accessed via http://{SERVER_IP}/

Else If you are developing and working ...

**Comment by davsclaus** [comment]
@garethahealy you are welcome to do a PR with the docs update.

I assume you already know the docs are in the source at
https://github.com/fabric8io/fabric8/tree/master/docs

**Comment by davsclaus** [comment]
thanks for the PR
