### ISSUE TITLE
Reuse openshift oauth tokens in Jolokia agent

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8#3982]
Currently because we proxy requests to jolokia through the API server & the API server requires auth via a bearer token, we cannot use jolokia through the console as jolokia is currently configured to require auth too.

A couple of options:

1. Short term disable jolokia auth so only proxy auth is required (bad, but quick win until 2 is implemented.
2. Implement oauth2 auth provided for jolokia & provide openshift oauth implementation to authorize against API server. This would mean that the token would be reused for proxying as well as for authing against jolokia.

**Comment by davsclaus** [comment]
Yeah good idea with 1 first and then 2 is ready later.

**Comment by davsclaus** [comment]
Jolokia auth is disabled by default in our java and tomcat based docker images. Its as I can see only in karaf docker images it uses JAAS. And thus admin/admin etc as login.

**Comment by jimmidyson** [comment]
OK cool. So I guess we just need to take a look at hawtio-kubernetes how we can propagate the bearer token somehow.

**Comment by jstrachan** [comment]
this might need a change in the Jolokia JS client; as it wraps up the HTTP access to jolokia

**Comment by gashcrumb** [comment]
So I just pushed a tweak to hawtio-jmx actually to look for a 'token' parameter in the URL and save it with the connection details, was mostly done for openshift-jvm.  But we could probably use this for our own stuff too.  Basically hawtio-jmx now supports a few query params to set up a jolokia connection, for example we can do something like:

```
        var targetURI = new URI()
                                 .query({
                                   jolokiaUrl: jolokiaUrl,
                                   title: title,
                                   returnTo: returnTo,
                                   token: token
                                 });
        window.location.href = targetURI.toString();
```
the `title` and `returnTo` params are optional, but basically this will make hawtio-jvm save the token with the connection details, then use that token for all jolokia requests, thanks to `$.ajaxSetup`.  So we can probably just change the connect links in hawtio-kubernetes to do something like the above and it'll just work.  Note it's important to use `window.location.href` here to force a reload, using `$location` or a normal anchor tag won't work.

**Comment by rhuss** [comment]
If I understand the discussion right, then the thing missing piece is the authentication step on Jolokia's side, i.e. contacting an OAuth2 authentication server for verifying a provided auth token. For the JVM agent this shouldn't be a big deal as soon as I know, how the protocol looks like for the verification. (issue [#197](https://github.com/rhuss/jolokia/issues/197)).

AFAIK there is no 'official' standard yet for how this verification should be done and it is vendor specific. There is some [standard](https://tools.ietf.org/html/draft-ietf-oauth-introspection-04) under way but up to then everybody does it on its [own](http://stackoverflow.com/questions/12296017/how-to-validate-a-oauth2-0-access-token-for-a-resource-server). 

So I wonder how OpenShift OAuthProvide does the verification and how I can implement this is generic way without sticking to OpenShift. That would be the optimal solution so that I can put it into upstream agent.

**Comment by rhuss** [comment]
I also wonder, whether for real security shouldn't SSL be used everywhere ? Otherwise passing a token around serves not much more than a fig-leaf  ....

**Comment by jimmidyson** [comment]
Well yes, but in different environments, e.g. private cloud, quite often people will not use SSL inside the cluster as it introduces problems around key management, etc. I'd be happier supporting this for TLS & non-TLS. but documenting the risk of non-TLS comms, especially in a mixed/shared env?

**Comment by rhuss** [comment]
Ok for me if also the admin browsers are running within the cloud wit all those fancy HTML 5 consoles talking directly with backend (i.e. jolokia). A central "Jolokia" proxy (with SSL on the front) alone for this reason might be worth considering.

**Comment by jimmidyson** [comment]
Interesting. So we'd have a jolokia central server that all jolokia traffic would route through? Using the openshift API server proxy we kind of already have that as it requires auth already to be able to proxy. It also wouldn't prevent direct traffic bypassing the central proxy, going direct to jolokia endpoint ports would it?

**Comment by rhuss** [comment]
You can prepare the Jolokia Agent that way that it only allows access from a given IP address (or IP range). This can be done by simply repackaging it. So when you allow only access via the proxy then you should be save. Also, one could think about enhancing Jolokia that this IP might be picked up from the environment so you could specify the proxy IP as env when starting up a container.

Another thing is, how routing would be done through the proxy. One possibility would to evaluate extra HTTP headers (which would have the least impact on clients like hawt.io wich would have to be adapted).

**Comment by jimmidyson** [comment]
This works now!
