### ISSUE TITLE
provide an option to process templates locally in Java so that OpenShift templates can be installed on any Kubernetes environment

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3989]

**Comment by christian-posta** [comment]
Does this allow you to process the OpenShift templates (locally) and generate the kubernetes.json with all of the parameters plugged in? ie.. would be nice to basically have a "oc process -f " with our maven plugins?

**Comment by jstrachan** [comment]
Yeah. It's the equivalent of running that locally. It means you can apply OpenShift templates on any Kubernetes environment

**Comment by christian-posta** [comment]
that's what i thought, but it seems to actually apply the json as well. was hoping something would just spit it out and I can apply it manually or examine it

**Comment by jstrachan** [comment]
Ah. We should add another goal / flag to just process and not apply it

On Friday, June 19, 2015, Christian Posta <notifications@github.com> wrote:

> that's what i thought, but it seems to actually apply the json as well.
> was hoping something would just spit it out and I can apply it manually or
> examine it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/3989#issuecomment-113595610>.
>


-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: jstracha@redhat.com
Blog: http://macstrac.blogspot.com/

hawtio: http:/ <http://fusesource.com/>/hawt.io/
fabric8: http:/ <http://fusesource.com/>/fabric8.io/

Open Source Integration

**Comment by christian-posta** [comment]
Okay opened an issue https://github.com/fabric8io/fabric8/issues/4261 for that. will be diving into and helping with some of these types of issues when demo is over :)
