### ISSUE TITLE
Duplicated oAuthClients in demo startup json files

### ISSUE THREAD

**Issue by marvec** [fabric8io/fabric8#3998]
Following the instructions at http://fabric8.io/guide/fabric8OnOpenShift.html I ended up with an error message that oAuthClient/fabric8 already exists. It is the case of almost all the json files linked in the docs but the base one. After creating a local copy and removing the duplicate entries in http://central.maven.org/maven2/io/fabric8/apps/kitchen-sink/2.1.1/kitchen-sink-2.1.1-kubernetes.json for fabric8 and googs names, it worked well.

**Comment by iocanel** [comment]
I think that this issue has been addressed in the last release of the model and the current master has been updated and aligned with it. We'll need a new release of the apps so that they include fix.

**Comment by davsclaus** [comment]
Thanks @iocanel.

Closing this one.
