### ISSUE TITLE
Doc about multiple ports for service is not correct

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4005]
The documentation specifies that to create a kubernetes service with several ports, the syntax to be used is : 

| Syntax | Description |
| --------- | ----------------| 
| fabric8.service.`<portName>`.port | The service port to generate (if a kubernetes service is required with multiple ports) |
| fabric8.service.`<portName>`.containerPort | The container port to target to generate (if a kubernetes service is required with multiple ports) |
| fabric8.service.`<portName>`.protocol | The protocol of this service port to generate (if a kubernetes service is required with multiple ports) |

The doc is not correct as the syntax to be used is : 

| Syntax | Description |
| --------- | ----------------| 
| fabric8.service.port.`<portName>` | The service port to generate (if a kubernetes service is required with multiple ports) |
| fabric8.service.containerPort`<portName>` | The container port to target to generate (if a kubernetes service is required with multiple ports) |

Remark : 
- The portname is to be placed at the end

**Comment by jimmidyson** [comment]
Good catch. PR welcome.
