### ISSUE TITLE
How can we generate route when we have multiple ports for a service

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4006]
The gerrit docker container exposes 2 ports (http : 8080 & ssh : 29418) but this is not supported by the maven fabric8:create-routes plugin. Is there a workaround ?

```
[INFO] Not generating route for service gerrit-service as only single port services are supported. Has ports: [80, 29418]

```

Config 

```
<!-- Service -->
<fabric8.service.name>${project.artifactId}-service</fabric8.service.name>
<!-- HTTP Protocol -->
<fabric8.service.port.http>80</fabric8.service.port.http>
<fabric8.service.containerPort.http>8080</fabric8.service.containerPort.http>
<!-- SSH Protocol-->
<fabric8.service.port.ssh>29418</fabric8.service.port.ssh>
<fabric8.service.containerPort.ssh>29418</fabric8.service.containerPort.ssh>
```

**Comment by cmoulliard** [comment]
Link to openshift 2092 issue reported by James

**Comment by jstrachan** [comment]
Until OpenShift can support routes for services with 2 ports (especially http & https) I'd recommend creating 2 separate services

**Comment by cmoulliard** [comment]
This is what I have done : https://github.com/christian-posta/ceposta-devops-ose/blob/master/gerrit-docker/src/main/java/io/fabric8/app/gerrit/GerritModelProcessor.java#L10-L43

**Comment by jstrachan** [comment]
I'm gonna close tie for now. You can create multiple ports on a service - via maven properties or the DSL - though until OpenShift Routes support it they are not recommended anyway
