### ISSUE TITLE
fabric8:json to support multiple docker.image names?

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4029]
As we can have multiple containers in pods should we support multiple docker.image maven properties?

As an example the hubot-letschat app requires a redis image with no configuration, i.e.

```json
          {
            "image":"redis",
            "name":"hubot-redis-container"
          }
```

Although I'm wondering if in this example a separate redis service should be used.

**Comment by jstrachan** [comment]
I think the annotation processors are the cleanest way to add a new container via the typesafe DSL
http://fabric8.io/guide/annotationProcessors.html
