### ISSUE TITLE
[proposition] New gerrit Docker container

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4030]
The existing Docker containers for Gerrit (https://github.com/larrycai/docker-gerrit/, ) don't support to backup the setup (database, etc config files, ...) and by consequence, the user account, setup must be reconfigured every time a new docker container is recreated or when we stop it while it is managed by kube & openshift

I propose to move the code of this new Gerrit container (https://github.com/christian-posta/ceposta-devops-ose/tree/master/gerrit-docker/src/main/docker/gerrit) to Fabric 8 in order to benefit of these new features and to update too the apps/gerrit of Fabric8 quickstart to use it :
 
- Volume can be mounted with the gerrit-site to "restore" previous configs (https://github.com/christian-posta/ceposta-devops-ose/blob/master/gerrit-docker/src/main/docker/gerrit/Dockerfile#L6-6, https://github.com/christian-posta/ceposta-devops-ose/blob/master/gerrit-docker/src/main/docker/gerrit/bin/conf-and-run-gerrit.sh#L54, https://github.com/christian-posta/ceposta-devops-ose/blob/master/gerrit-docker/pom.xml#L49-L50)
- Auth_type can be passed as env var or defined as kube env
- Git Server (hostname, port), user, pwd & project root can be defined for the replication with gogs or gitlab (https://github.com/christian-posta/ceposta-devops-ose/blob/master/gerrit-docker/src/main/fabric8/env.properties#L4-L8)

Remark : There is an issue with the current gerrit.sh script as it generates this error at the line 429 ("https://groups.google.com/forum/#!topic/repo-discuss/vp38wGaIK1k") when launched without supervisor within the container. This is why currently the java jar cmd is used.

**Comment by jstrachan** [comment]
sounds good; maybe lets just fork the current docker-gerrit and apply the necessary changes?

**Comment by jstrachan** [comment]
for folks watching on github; the github repo for the new gerrit docker image is here: https://github.com/fabric8io/docker-gerrit

**Comment by christian-posta** [comment]
Seems we should be able to closet this, @cmoulliard?

**Comment by cmoulliard** [comment]
As we are using the Fabric8 docker-gerrit container now implementing the features described, we can close this ticket
