### ISSUE TITLE
mvn fabric8:create-env should output the docker command line to run the docker image

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4056]
it'd be nice to output a line something like:
```
docker run -dP -e FOO=bar -e X=Y fabric8/myimagename
```
so folks can just copy/paste the line to a console on any machine with docker to try out the image as if its on kubernetes

**Comment by davsclaus** [comment]
+1 this is a great idea

**Comment by jstrachan** [comment]
maybe even generating a file `target/dockerRun.sh` that runs the image in docker might be slick?

**Comment by oscerd** [comment]
Are the docker run flags always equals to -dP?

**Comment by oscerd** [comment]
I'd like to work on this

**Comment by jstrachan** [comment]
yeah - its probably safest to use -dP then for each env var -e - and if you wanna get really clever, add any volume mounts (though those are harder ;)

**Comment by oscerd** [comment]
Insider the CreateEnvMojo we don't have information about Volumes, or I'm losing something? :-/

**Comment by jstrachan** [comment]
the create-env can parse the generated List or Template and look in the DTO to find the ReplicationController, then inside there for each pod template you should see everything in the kubernetes JSON model.

e.g. from the jenkins kubernetes JSON here's the replication controller's volume stuff
https://gist.github.com/jstrachan/34c6da86149c4ee8effd#file-jenkins-kubernetes-json-L69
https://gist.github.com/jstrachan/34c6da86149c4ee8effd#file-jenkins-kubernetes-json-L86

**Comment by oscerd** [comment]
Now I see, I didn't see the loadKubernetesJson method invocation in the execute.

Thank you very much :-) I'll work on this :-)
