### ISSUE TITLE
mvn fabric8:create-env should detect template parameters and replace them in any environment variable expressions

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4057]
allowing them to be specified on the CLI as system properties like the `mvn fabric8:apply`

see: http://fabric8.io/guide/mavenFabric8Apply.html#templates

**Comment by oscerd** [comment]
Do you mean something like:

```
mvn fabric8:create-env -Dfabric8.create.env.FOO=bar
```

and suppose I have a property like

```
varbar = ${FOO}
```

I'll have varbar=bar inside my envinroment variables map?

**Comment by oscerd** [comment]
It's similar to https://github.com/fabric8io/fabric8/blob/07807aed847e1d0589c094461544e54a2677cbf5/fabric8-maven-plugin/src/main/java/io/fabric8/maven/ApplyMojo.java#L242

**Comment by oscerd** [comment]
I'll work on this.

**Comment by oscerd** [comment]
I'll work on this.

**Comment by jstrachan** [comment]
yes - thanks!
