### ISSUE TITLE
jenkins job DSL should add gogs webhook when it creates jenkins jobs for a gogs repo

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4063]
to avoid polling frequently, we should be able to register a webhook to each gogs repo that has a jenkins build

**Comment by christian-posta** [comment]
For documentation purposes, here's the link you posted to me in IRC... can take a look at this when I get #4045 working 


https://github.com/jstrachan/fabric8/blob/cdelivery/forge/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/main/GitCommandCompletePostProcessor.java#L446-446

**Comment by jstrachan** [comment]
I wonder if its gonna be easiest to do this via a maven plugin; so we can do it at the same time as we add the BuildConfig:
https://github.com/fabric8io/default-jenkins-dsl/blob/master/seedBuilds.groovy#L31

**Comment by jstrachan** [comment]
adding a maven goal to add a webhook to gogs...

**Comment by jstrachan** [comment]
this is now fixed; the `mvn fabric8:create-build-config` now generates the webhook if its given a jenkins job to link to
