### ISSUE TITLE
migrate the karaf quickstarts to use the karaf maven plugin to create an immutable karaf distribution with everything required

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4075]
here's an example pom.xml thats using mvn dependencies on features/bundles and creates an immutable karaf distro:
https://github.com/apache/karaf/blob/master/assemblies/apache-karaf-minimal/pom.xml#L97

this one is similar but using profiles too:
https://github.com/apache/karaf/blob/master/demos/profiles/static/pom.xml#L106

it'd be great if we used this maven plugin to create a local distro of karaf; then reused the docker java container and had a standard docker maven plugin assembly that'd put the karaf distro in the right place on the docker image.

Then we'd be able to remove the kar building and simplify the requirements of what needs to be added to users pom.xml files for them to migrate easily any OSGi / Karaf / Fuse project to Fabric8 V2 / Kubernetes

**Comment by davsclaus** [comment]
Without the kar then I think end users would need to write a features.xml file to define what their own app(s) should include of bundles.

**Comment by jstrachan** [comment]
see those example pom.xml files; a mvn dependency on features and/or bundles is all thats required. No feature.xml file is required by the user

**Comment by jstrachan** [comment]
the karaf plugin can take transitive `<dependency>` elements or features and figure out the flat list of all actual bundles that need to be included. Folks can still create a feature.xml if they really want - but there's no need to if all folks want is a karaf distro with the required features etc.

BTW we might wanna create a base dependency feature to include common stuff (e.g. a base karaf set of features) to minimise what needs to go into a pom.xml

**Comment by christian-posta** [comment]
So ideally, we'd like *all* of the feature/bundles loaded in the startup phase and have no installation phase. See this pom.xml for an example, but still working through some OSGI hatred: 

https://gist.github.com/christian-posta/a60b08dcfd88cc1d2364
https://gist.github.com/christian-posta/4f71e83c71ab0aac70df

Getting close though...

**Comment by christian-posta** [comment]
Have it working here: https://github.com/christian-posta/fabric8-karaf-camel-demo
Will merge these changes into the fabric8-quickstarts once I'm happy with it. Still a couple issues to work through:

* use the static framework doesn't work yet (see [this branch](https://github.com/christian-posta/fabric8-karaf-camel-demo/tree/static-framework) if you can help out .. getting a [silly osgi dependency error](http://pastebin.com/z1kEpMQz) that i haven't got time at the moment to resolve

* when using these 4.0.0-SNAPSHOTS of karaf, if you boot up the assembly from the karat-assembly module, everything seems to work (i.e., jolokia installed, the correct app installed, etc) but cannot do "feature:list" ... get a NPE for some reason

**Comment by cmoulliard** [comment]
As the image is created from Apache Karaf 2.4, I would suggest to generate the features (durng assembly) using also the same version and not 4.0.0-SNAPSHOT which corresponds to a different version of Karaf & where the commands have been refactored, ....

**Comment by jimmidyson** [comment]
It looks like you're using a karaf 2.4 base image but adding 4.0.0-SNAPSHOT features? Doesn't the maven plugin work with karaf 2.4 features properly?

**Comment by davsclaus** [comment]
Please leave this as is working with karaf 2.4 this week as we have an event in London, and would like to keep it working. Myself and Roland just got the examples working end of last week again.

**Comment by davsclaus** [comment]
And I agree with @jimmidyson  we cannot use 4.0-SNAPSHOT of karaf. 

Maybe create a new karaf quickstart that is for 4.0-SNAPSHOT and only enable that quickstart using a maven profile etc.

**Comment by christian-posta** [comment]
Yah, agreed with everyone to use 2.4 features etc. 
Wanted to use the latest stuff to make sure it works, since anything upstream in karaf would be tested against 4.0-SNAPSHOT first... I plan to get this working with 2.4.

@davsclaus which examples did you get working? the quick starts?

**Comment by davsclaus** [comment]
Yes the karaf quickstarts out of the box works for me now.

**Comment by davsclaus** [comment]
Well if karaf 4 in the longer run would be required as the best option for running as docker containers then imho its fine to migrate and only support that. But as karaf 4 is no GA yet we would need to wait until that happens. And anyone know what the timeframe for that is?

**Comment by davsclaus** [comment]
the karaf quickstarts builds images with all included.
