### ISSUE TITLE
inconsistencies with the archetype generation

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4092]
so the archetypes are automatically generated using the [archetype-builder](https://github.com/fabric8io/fabric8/tree/master/tooling/archetype-builder) from the [quickstarts](https://github.com/fabric8io/quickstarts/tree/master/quickstarts) which are all real projects. 

When the archetypes actually get generated on a build, some inconsistencies happen:

for the java-camel-cdi-archetype, if you look inside src/test/java you'll see the AppKubernetesTest is at the wrong java package (i.e., if i specified org.foo when creating the archetype, the AppKubernetesTest.java file is at io.fabric8.tests.integration.org.foo .. which is wrong. everything in the src/main/java looks right) Additionally, the package declaration in the java file is wrong (says io.fabric8.tests.integration). Ideally the packages would be org.foo.tests.integration and the correct package would be reflected in the java source file. If you look at AppKubernetesTest.java that gets processed after trying to build the archetype, it does not have the ${package} placeholders in it.

Also, for the java-camel-spring-archetype, the test/src is missing altogether. 

There may be others, but these are the ones I noticed.

From the source code, the relevant area seems to be https://github.com/fabric8io/fabric8/blob/master/tooling/archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/ArchetypeBuilder.java#L300

**Comment by christian-posta** [comment]
Also, these versions are missing from the pom.xml that get generated (because in the quick starts, it's being pulled in from the parent.. but it should be made explicit for the quick start)

    <jube.version>2.1.5</jube.version>
    <docker.maven.plugin.version>0.11.5</docker.maven.plugin.version>

**Comment by davsclaus** [comment]
@christian-posta - I cannot find the problem with not having jube and docker versions explicit in the generated pom.xml. 

Also about the src/test then I have committed a fix for that.

**Comment by davsclaus** [comment]
> Also, these versions are missing from the pom.xml that get generated (because in the quick starts, it's being pulled in from the parent.. but it should be made explicit for the quick start)
> <jube.version>2.1.5</jube.version>
> <docker.maven.plugin.version>0.11.5</docker.maven.plugin.version>

@christian-posta I think some of the versions are imported from the bom such as
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/java/cxf-cdi/pom.xml#L76

I think those versions defined above are required for the maven plugins, as those cannot be imported from bom. The idea is that otherwise those versions are using the same versions from the fabric8 bom.

**Comment by christian-posta** [comment]
@davsclaus okay thx for tackling these. i'll check the latest code. Is the idea to have the archetypes inherit from a BOM once they've been created? Or are they 100% standalone projects?

**Comment by davsclaus** [comment]
they import the bom, they do not have any parent project. So they are 100% standalone.

eg importing a bom is also how people is recommended to work with spring-boot etc.

**Comment by davsclaus** [comment]
the archetypes are better now. Lets close this and open new tickets for new issues.
