### ISSUE TITLE
Figure out a way to automate hubot-letschat

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4143]
Currently there are a few manual steps required to get hubot-letschat to run.  We need to setup the fabric8 user and generate an auth token in lets chat, this is then set as a template value when running hubot.

**Comment by jstrachan** [comment]
so close now! Looks like we can't generate a token outside and pass it in; so we might have to try use the user/pwd to find the token in hubot-letschat?

**Comment by rawlingsj** [comment]
Yay!
