### ISSUE TITLE
fabric8 forge doesn't populate the list of archetypes first time

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4151]
second time its fine ;)

**Comment by davsclaus** [comment]
Is it from the archetype-catalog (which we include fabric8 / camel out of the box) or is it the general one? Frankly I have not seen any problems recently with using forge to create new projects.

**Comment by jstrachan** [comment]
Yeah, it's the archetype catalog; the list of archetypes is empty first time you use it - then it loads them second time you try the form.

To reproduce the bug; try deleting the fabric8-forge pod and try create a project? Seems to fail to populate the list most of the time for me
