### ISSUE TITLE
lets add the fabric8 console (and a route) to the fabric8 vagrant image by default

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4154]
then folks can just open the web console (when its up).

Also I wonder if we should install a few of the common OpenShift templates (e.g. management / logging / metrics / cdelivery-core / cdelivery / iPaaS / kitchen sink)?

**Comment by davsclaus** [comment]
I think those other bits should be optional.

I would like to have a bare installation with a low footprint, that people can kick the tires first. Some people may just want to get a simple quickstart deployed first and see it working + sorta like a local installation.

**Comment by rawlingsj** [comment]
It would be nice if the vagrant box / boxes could be tied into the CD process so that when a new release is cut a vagrant up would check and pull down the latest http://docs.vagrantup.com/v2/boxes/versioning.html

**Comment by jstrachan** [comment]
@davsclaus BTW by installing the templates I meant, just adding the templates as OpenShift Template objects so that they appear in the Run... page - not installing the resources from the templates. (Sorry - its confusing - you can install templates without applying them).

**Comment by jstrachan** [comment]
@rawlingsj ah nice idea. I'd like a way to pull all the required images too (as we don't always list the image version tag in the releases - which we should fix anyways really ;) so its currently too hard to know if your vagrant image has the latest.

I'd also love an easier reset command (to avoid losing the cache of all those docker image layers)
https://github.com/fabric8io/fabric8/issues/4148
