### ISSUE TITLE
mvn fabric8:create-env should sort the env.properties file so they are easier to grok/edit

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4158]

**Comment by jstrachan** [comment]
I added sorting to the env.sh but we should do it for the .properties too

**Comment by davsclaus** [comment]
@oscerd this is a good beginner if you fancy.

Its this mvn goal
https://github.com/fabric8io/fabric8/blob/master/fabric8-maven-plugin/src/main/java/io/fabric8/maven/CreateEnvMojo.java

I wonder if properties has a way of sorting or something.
https://github.com/fabric8io/fabric8/blob/master/fabric8-maven-plugin/src/main/java/io/fabric8/maven/CreateEnvMojo.java#L237

**Comment by davsclaus** [comment]
Though its a bit tricky to test as you would need a running kubernetes. Or write some kind of unit test that can run a test standalone, which we frankly kinda need. As the mvn plugins gets bigger and bigger.

**Comment by oscerd** [comment]
Thank you Claus :-)

I will work on this.
