### ISSUE TITLE
Add the forge camel addon to the forge website

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4186]
See
http://forge.jboss.org/document/share-your-addon-on-the-forge-website

**Comment by oscerd** [comment]
Just to prepare our PR:

---
id: io.fabric8.forge:camel
name: Camel
description: Apache Camel and Forge togheter!
author: Fabric8 Team
email: ?
website: http://fabric8.io/guide/forge.html
repo: ?
ref: master
tags: Camel
logo: ?
---

Maybe we need to create a separate repository for the project to submit the PR.

What do you think?

**Comment by rawlingsj** [comment]
Looks good.  A couple of things, there's a typo in the description "togheter"

Email - you could use the fabric8 google groups email address `fabric8@googlegroups.com`
Repo - Presumably the repo needs to be https://github.com/fabric8io/fabric8
Logo - The fabric8 logs can be found http://design.jboss.org/fabric8/

The repo is forked here https://github.com/fabric8io/website-data

Does this give you all you need?

**Comment by oscerd** [comment]
Hi, James.

Yes, you're right, I'll change that ugly "togheter" :-)

I think I have everything I need. Thank you :-)

**Comment by rawlingsj** [comment]
Excellent.  Nice work BTW!

**Comment by oscerd** [comment]
I think we are ready :-)

https://github.com/fabric8io/website-data/pull/1

**Comment by oscerd** [comment]
I've pushed on the fabric8 fork just to make you review :-)

**Comment by oscerd** [comment]
I think we can close this :-)

**Comment by jimmidyson** [comment]
Yay! Thanks again

**Comment by oscerd** [comment]
I've just submitted a little update to Fabric8 Team avatar url:

https://github.com/forge/website-data/pull/15
