### ISSUE TITLE
add a Chaos Monkey RC which ideally could be configured via a hawtio UI

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4226]
some kind of [Chaos Monkey](https://github.com/Netflix/SimianArmy/wiki/Chaos-Monkey) or (angry honey badger?) folks could enable/disable via scaling from 0 to 1 containers; be nice to allow a little UI to configure things like which kinds of pod should not be harmed and the frequency of killing things.

Ideally each kill should be animated on the chat window ;)

**Comment by rawlingsj** [comment]
+1

**Comment by rawlingsj** [comment]
This would help enforce good development practices.  i.e. design and develop containers that can be killed / deleted at anytime.  I think this is a great idea and offers a way to help people adapt to developing a container based architecture.

We can also generate metrics of the number of times a pods is recreated, a service uptime and other stats to generate a leaderboard of services that run on the platform.

**Comment by christian-posta** [comment]
awesome!!
