### ISSUE TITLE
Still a number of references to 'osc' command in the docs

### ISSUE THREAD

**Issue by garethjevans** [fabric8io/fabric8#4254]
The latest docs still refer to the 'osc' command rather than 'oc', will submit a pull request now.

**Comment by davsclaus** [comment]
Thanks do you mind checking the docs and source about the config file location change. See the RC2 release notes at
https://github.com/openshift/origin/releases

eg its at `~/.kube/config` now.

**Comment by davsclaus** [comment]
Fixed those references
