### ISSUE TITLE
fabric8-installer - The install guide should mention docker 1.6.2 is required

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4272]
I upgraded to 1.7.0 with latest boot2docker, and followed the install guide, and noticed the pods was not ready - they were in `pending` state.

And `docker ps` reported version miss-match as my client was 1.7.0. So I did a `vagrant suspend` and installed boot2docker 1.6.2, and then `vagrant up` and the pods are in ready state now

```
davsclaus:~/workspace/fabric8-installer/vagrant/openshift-latest (master)/$ oc get pods
NAME                      READY     REASON    RESTARTS   AGE
docker-registry-1-h11xn   1/1       Running   0          2m
fabric8-i39yz             1/1       Running   0          7m
router-1-fnh9f            1/1       Running   0          2m
```

I wonder if the install guide should mention something about if having docker installed locally as well, then 1.7.0 is not supported.

**Comment by jimmidyson** [comment]
It doesn't support docker 1.7? Oh man

**Comment by davsclaus** [comment]
To be fair I didnt try again from scratch with docker 1.7.0. But though it could be a problem when i typed `docker ps` and noticed the miss match.

I can try again as the ipaas apps has trouble downloading and running some of the docker images - which i have logged elsewhere.

**Comment by jimmidyson** [comment]
Interesting. The client version shouldn't have any effect on the pods so might just have been pulling images? Were you impatient? ;)
