### ISSUE TITLE
Apps - description for the apps is the same

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4273]
Followed the guide and noticed on the apps page that the different app groups have more or less the same summary

![screen shot 2015-06-20 at 11 38 47 am](https://cloud.githubusercontent.com/assets/477100/8266759/3252a2a4-1740-11e5-8a06-ed1770045b63.png)

**Comment by davsclaus** [comment]
Also wonder if we should not have a `MQ` app group or would people know its the iPaaS ?

**Comment by davsclaus** [comment]
whoa ipaas has a lot, its like the kitchen-sink more or less ;)

**Comment by jstrachan** [comment]
agreed, we need an MQ app too!

right now the icon / descriptions are a bit random. We need the fabric8:json goal to override the icon/description when apps are aggregated into a Template with a concrete description etc.

I noticed `oc get templates` shows the description too so we probably want to have a plain text version for the description metadata in the template

**Comment by jstrachan** [comment]
I've raised a separate issue for the MQ app: https://github.com/fabric8io/fabric8/issues/4298
