### ISSUE TITLE
Error pulling image - error mounting image

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4275]
I am installing the ipaas app on latest release and did a `oc get pods --watch` and noticed it printed

api-registry-bwhtn   0/1       Error pulling image (2.2.1) from docker.io/fabric8/api-registry, Error mounting '/dev/mapper/docker-253:0-67168046-df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c' on '/var/lib/docker/devicemapper/mnt/df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c': invalid argument   0         5m
fabric8-forge-736ve   0/1       Error pulling image (2.2.1) from docker.io/fabric8/fabric8-forge, Error mounting '/dev/mapper/docker-253:0-67168046-df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c' on '/var/lib/docker/devicemapper/mnt/df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c': invalid argument   0         5m
gerrit-kscp2   1/1       Running   4         5m
hubot-notifier-yb9xh   0/1       Error pulling image (2.2.1) from docker.io/fabric8/hubot-notifier, Error mounting '/dev/mapper/docker-253:0-67168046-df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c' on '/var/lib/docker/devicemapper/mnt/df2a0347c9d081fa05ecb83669dcae5830c67b0676a6d6358218e55d8a45969c': invalid argument   0         5m

**Comment by jimmidyson** [comment]
This is an intermittent error with docker & devicemapper. Not much we can do about it sadly

**Comment by jstrachan** [comment]
The only workaround I've found is to delete the relevant k8s resources, delete the failed docker images and pull them via the command line, then try again

**Comment by davsclaus** [comment]
Also sometimes doing a vagrant destroy and vagrant up can fix this. Just had this problem today.
And Roland says to reboot the laptop may fix a glitch with virtual box.
