### ISSUE TITLE
2.3-SNAPSHOTs are missing Service objects in kube.json 

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4278]
for services that try to declare multiple services (i.e., gogs, and gogs-ssh, or gerrit and gerrit-ssh)

https://oss.sonatype.org/content/repositories/public/io/fabric8/jube/images/fabric8/gogs/2.3-SNAPSHOT/gogs-2.3-20150617.154900-1-kubernetes.json

Is this because of the way the build job runs? Or maybe something changed in the plugin?

**Comment by jimmidyson** [comment]
Very odd - local build with master produces correct kubernetes.json with multiple services as expected. Not sure why that's different on the build server. Interestingly that is the same for 2.2-SNAPSHOT but correct in releases... Does it work correctly for you locally?

**Comment by christian-posta** [comment]
Yah, locally it seems to work fine. But on a couple apps, I'm using SNAPSHOT, and when there's a new build remotely, it likes to download that, and that's how I discovered this oddity.

**Comment by jstrachan** [comment]
Wonder if it's related to maven lifecycle; the annotation processor might not be kicking in? You doing 'mvn install' or just 'mvn fabric8:json'?

**Comment by cmoulliard** [comment]
The workaround for local build is to run this command `mvn clean fabric8:json compile` or `mvn clean fabric8:json install`

**Comment by christian-posta** [comment]
Locally things seem to build just fine -- no issue there -- something on
the build machine is different for snapshots though.

On Sun, Jun 21, 2015 at 8:12 AM, Charles Moulliard <notifications@github.com
> wrote:

> The workaround for local build is to run this command mvn clean
> fabric8:json compile or mvn clean fabric8:json install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4278#issuecomment-113912549>.
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by christian-posta** [comment]
This seems to be resolved in latest 2.3-SNAPSHOTs
eg:
https://oss.sonatype.org/content/repositories/public/io/fabric8/jube/images/fabric8/fabric8-forge/2.3-SNAPSHOT/fabric8-forge-2.3-20150706.105140-106-kubernetes.json

**Comment by christian-posta** [comment]
we should reopen this. i'm finding the maven plugin to not generate the service object in the kube json when building locally. anyone else? even tried @cmoulliard workaround (which should invoke that ModelProcessor thingy right? https://github.com/fabric8io/quickstarts/blob/master/apps/gerrit/src/main/java/io/fabric8/app/gerrit/GerritModelProcessor.java

**Comment by jimmidyson** [comment]
@christian-posta I added prometheus yesterday & service is generated properly for me... wonder if it's something specific to the gerrit app? I'll take a look.

**Comment by jimmidyson** [comment]
@christian-posta It's to do with the change in model packages - i'll fix that now.

**Comment by jimmidyson** [comment]
@christian-posta Updated quickstarts, seems ok. Can you try now please?

**Comment by christian-posta** [comment]
@jimmidyson yah, building locally it looks like services are back! thanks!!
