### ISSUE TITLE
create an apiman template for running everything required to get started with apiman

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4296]
in the vagrant image we install the main templates now:
http://fabric8.io/guide/getStartedVagrant.html

so lets install one for apiman by default. I wonder what kube apps we'd need to run by default - would it be
* apiman
* fabric8-http-gateway

anything else required?

**Comment by KurtStam** [comment]
Yes elasticsearch for storage.

**Comment by jstrachan** [comment]
cool thanks - adding it now...

**Comment by KurtStam** [comment]
On 6/22/15 9:12 AM, James Strachan wrote:
>
> cool thanks - adding it now...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fabric8io/fabric8/issues/4296#issuecomment-114097909>.
>
Cool - I'm hoping to work on adding keycloak in the mix this week so I 
can properly specify the roles. Will ping you if I succeed, so we can 
add that too.

**Comment by jstrachan** [comment]
ah great!
