### ISSUE TITLE
fix up the MQ docs to describe the current capabilities:

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4311]
we've now a nice 1 click install of the Messaging app in the vagrant image; we could use better docs on whats there now - particularly after this awesome blog post
https://medium.com/fabric8-io/fabric8-mq-not-just-a-message-broker-18ca5af1e0f

it'd be good to describe the relationship between the `fabric8mq` app (the service folks talk to) and the `amqbroker` RC to avoid confusion

**Comment by davsclaus** [comment]
mq is being removed

**Comment by rajdavies** [comment]
its going back :)

**Comment by jimmidyson** [comment]
Yay!

**Comment by davsclaus** [comment]
@rajdavies yay did you win a strong-arm content to get it back ;)
