### ISSUE TITLE
Using the log tab is not useable out of the box

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4312]
Using latest vagrant.

I installed the quickstarts which is a little client server app that talks to each out and logs to system out etc.

I then installed the logging app and ES and kibana installed nicely. When I click the Logs tab in the hawtio UI then kibana opens.

But it ask me about some index which seems to be not configured out of the box, and I assume the end users would not know what to do or get this working.

![screen shot 2015-06-23 at 12 42 57 pm](https://cloud.githubusercontent.com/assets/477100/8304274/cd170404-19a4-11e5-8ed7-b759d9699ac6.png)

**Comment by davsclaus** [comment]
@jimmidyson didnt you try to work on this or was I mistaken? IMHO would be awesome to get this working out of the box with installing just from the apps page

**Comment by jimmidyson** [comment]
I just need to add the fluentd container to the vagrant image by default.

**Comment by jimmidyson** [comment]
As the fluentd pod has to be run per node this isn't something you can create as part of an app - involves configuration on the node unfortunately.

**Comment by jstrachan** [comment]
aha!

**Comment by jimmidyson** [comment]
Working as expected
