### ISSUE TITLE
Getting started vagrant docs - need that 

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4328]
Need to include that new plugin required

davsclaus:~/workspace/fabric8-installer/vagrant/openshift-latest (master)/$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.5.0)'!
davsclaus:~/workspace/fabric8-installer/vagrant/openshift-latest (master)/$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/davsclaus/workspace/fabric8-installer/vagrant/openshift-latest/Vagrantfile
Message: Please type this command then try again: vagrant plugin install landrush
davsclaus:~/workspace/fabric8-installer/vagrant/openshift-latest (master)/$ vagrant plugin install landrush
Installing the 'landrush' plugin. This can take a few minutes...
Installed the plugin 'landrush (0.18.0)'!
davsclaus:~/workspace/fabric8-installer/vagrant/openshift-latest (master)/$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'jimmidyson/centos-7.1' is up to date...

**Comment by davsclaus** [comment]
And the vagrant script outputs those no longer needed ENV variables

==> default:    export KUBERNETES_MASTER=https://172.28.128.4:8443
==> default:    export KUBERNETES_DOMAIN=vagrant.f8
==> default:    export KUBERNETES_TRUST_CERT=true

Though maybe domain is still needed? @jstrachan

**Comment by jimmidyson** [comment]
I had removed those env vars from the Vagrantfile - seems they've been reintroduced.

KUBERNETES_DOMAIN is still needed, others not.

**Comment by rhuss** [comment]
My fault. I will remove everything except KUBERNETES_DOMAIN. 

Should I make the message more OS agnostic (e.g. with a Windows example with 'set') ?

**Comment by jimmidyson** [comment]
Yeah! Can potentially detect OS & spit out what's required?

**Comment by rhuss** [comment]
Script is running in the VM. Maybe I can inject the host OS as an env var during provisioning ?

**Comment by rhuss** [comment]
Added hint to startup message.
