### ISSUE TITLE
Log tab - Missing default dashboard

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4332]
I just got the new vagrant image and the log tab works. Though a few observations

1)
Could not locate that dashboard (id: Fabric8)
is shown in the top bar as a kinda warning.

2)
Under settings the timestamp field is red, but when I click it it suggests `@timestamp` and the Create button then works.

![screen shot 2015-06-24 at 4 13 07 pm](https://cloud.githubusercontent.com/assets/477100/8331927/3d77587a-1a8b-11e5-8eb6-bd43d9e32ea4.png)

**Comment by jimmidyson** [comment]
Working now
