### ISSUE TITLE
create a Jenkins Kubernetes Workflow - like a combination of Jenkins Docker Workflow + Kubernetes Jenkins plugin

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4340]
Jenkins Workflow rocks; as does the [Jenkins Docker Workflow](http://developer-blog.cloudbees.com/2015/06/orchestrating-workflows-with-jenkins.html?m=1).
It would also be nice to use something like the [Kubernetes Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin
https://github.com/jenkinsci/kubernetes-plugin) to auto-scale builds on kubernetes (so there's basically no build queue; stuff just builds immediately)

Getting these 2 ideas to work together is non trivial though. Reusing them both together as is; the kubernetes jenkins plugin creates a pod per slave; which then runs the build. For builds which run inside the slave container thats fine - but using docker workflow we need to create new docker containers per step in the DSL - which rocks - but which is harder to do inside a kubernetes slave pod; since [a pod can't just make new docker containers on the fly right now](https://github.com/GoogleCloudPlatform/kubernetes/issues/4212) and making a new pods for each docker container in the docker workflow could end up being on any host - which would then require shared distributed disk which is harder.

So reusing those 2 components as is would require either:

* the slave pod reusing the same docker daemon as kubernetes and using that to create new child docker containers (which runs the risk of kubernetes garbage collecting containers/images it doesn't know anything about); then sharing a host disk volume that can be mounted in the docker containers. The slave pod then needs to orchestrate docker containers (kinda what k8s does) which could leave stray containers running if the pod terminates abruptly.
* the slave pod uses docker in docker; having a docker daemon inside the slave pod; this avoids the orchestration problem; but introduces another level of docker registry and caching (and it can be hard to ensure the docker registries/mirrors are setup the same)

Neither of those appear simple and awesome; but both are possible for sure.

Here's an idea for pure Kubernetes solution to both of the above in a clean Kubernetes-way...

### Jenkins Kubernetes Workflow idea

The idea is we split the DSL into 2 stages; the `compile` stage and the `run` stage. 

At the `compile` stage we run the Docker Workflow flow.groovy script to find out all the `docker.image` blocks in the DSL and to find the image names required. e.g. for each block of code like this in the DSL:
```
docker.image("maven") {
   .... commands run inside the maven docker image here 
}
```
we create a list of the docker container images we need to create.

Then we generate a Kubernetes Pod so that it has: 

* one `DSL container` which runs the DSL and evaluates variables, expressions, fires commands, gets the results, manages state. i.e. this container implements the `run` phase of the workflow
* a `build container` for each docker image block found: `docker.image(name) {}` which uses the docker image `name` and they run commands they are given from the `DSL container`

This then means that in the `compile` stage a Docker Workflow can be turned into 1 concrete Kubernetes Pod that kubernetes can provision atomically. On startup all the containers start. The idea is that the `build containers` start and then wait for commands (from the `DSL container` to execute. 

The `DSL container` then starts evaluating the DSL. Each time it needs to evaluate a command within a `docker.image` block it just sends the command to the respective local docker container inside the pod and gets the results back.

### Why this helps

Doing things this way means a Docker Workflow flow.groovy becomes (in the Kubernetes Workflow) just a single Kubernetes Pod which never changes its kubernetes definition and is provisioned atomically by Kubernetes all on the same host; which makes it really easy to share local volumes between build containers.

The `DSL container` then just focusses on implementing the flow and sending commands to the `build containers` - which keep running for the duration of the pod.

We then delegate to Kubernetes for all the orchestration and tooling of containers. We can also then annotate the Pod so any kubernetes tooling can see all the pods running (1 pod per Kubernetes Workflow build) and can look inside each container in each pod (and view the individual logs or use `oc exec` to run a bash shell inside any of them too).

i.e. we'd be working with Kubernetes in the right way FTW

### How commands are exchanged

The part I'm not 100% clear on is; how does the `DSL container` invoke commands on the `build containers`. We want to try keep the `build containers` to be clean and pure. e.g. just a docker image of maven or nodejs or gradle or whatever.

We could add an sshd into each one; but that means folks making custom images to work with the `DSL container`.

So maybe we use `docker exec` (or kubernetes / openshift `osc exec`) in the DSL container to execute commands in the build containers? Then the docker command for each build container is basically a sleep loop or waiting for input from the keyboard or something.

The other option is each build build container is configured to start up in interactive mode, waiting for interactive shell input? Then the `DSL container` figures out how to mimick the `docker run -it foo` command line to interactively connect to the docker container's terminal and pipe commands in and receive output? So the `DSL container` acts kinda like an interactive shell really. This would mean that any docker image could be a `build container`

**Comment by jstrachan** [comment]
I raised an issue against the docker workflow plugin in case anyone in the jenkins community is looking at this kinda thing too https://issues.jenkins-ci.org/browse/JENKINS-29342

**Comment by elibixby** [comment]
Not sure if this helps but I've been working on a [Kubernetes Workflow Steps Plugin](https://github.com/GoogleCloudPlatform/jenkernetes) that allows you to provision pods on the fly with workflow steps. Combined with the docker build step plugin this could get you something like what you want.

**Comment by jstrachan** [comment]
thanks @elibixby jenkernetes has been on my lists of things to check out; looks like I'll be noodling it quite soon! :) 

Yeah, I'd seen the Kubernetes workflow steps plugin which is cool. My aim was to be able to take any docker workflow plugin groovy file and run it as is on kubernetes / jenkernetes without having to change the script. So keeping the docker workflow semantics really; just making it work nicely on Kubernetes.

The main worry was if a pod was used for each `docker.image("maven")  { ... }` block then we'd require a highly available disk volume since each pod in the docker workflow could be provisioned on any host; which isn't too hard on GKE but its harder to run on other k8s environments that way - so was musing about trying to ensure that all docker containers for a single docker workflow build are on the same host for now. (e.g. turning all the docker containers for a single docker workflow script into a single pod). 

We could try create a docker workflow implementation that creates a pod per docker container and tries to use [pod placement](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/node-selection) to try remove the GKE shared volume dependency

**Comment by elibixby** [comment]
@jstrachan Sorry I think I'm missing something. Why do you need a disk for your slaves?

**Comment by jstrachan** [comment]
@elibixby so the docker workflow in jenkins lets you run parts of your build in different docker containers. e.g. a docker container for maven, one for nodejs, one for golang etc. Its a docker based replacement for the 'tools installation' stuff in jenkins.

e.g. here's an example that runs a couple of docker images:
https://github.com/jenkinsci/docker-workflow-plugin/blob/master/demo/repo/flow.groovy#L23

it works well the workflow runs on a single slave machine, creates a local a workspace volume and shares it then with each docker image that is started in the `flow.groovy` file .

However if using kubernetes things are little more complex; since each pod generally could run anywhere and configuring globally shared volumes is generally non-portable. 

We could make `docker.image("maven").inside { ... }` in the [docker workflow plugin](https://github.com/jenkinsci/docker-workflow-plugin) effectively create a new pod for that image; but volume sharing of the workspace could be harder

**Comment by elibixby** [comment]
@jstrachan I see. This is potentially another use case for [volume containers in k8s](https://github.com/GoogleCloudPlatform/kubernetes/issues/831) which would be the ideal solution. Store the workspace for a job on a volume container, when a new slave is cut push the volume, and pull it down on the pod. 

However, there is a large amount of communication given by the fact that they are running in the same workflow script. What do you imagine doing that doesn't work with that? 

P.S. I don't think it would be that hard to duplicate the syntax of the docker workflow plugin with the kubernetes workflow steps plugin. I'll take a look at implementing that

**Comment by jstrachan** [comment]
@elibixby thanks for the heads up on volume containers. Yes that sounds like a great idea!

Oh and supporting docker workflow DSL inside jenkernetes would be awesome :)

**Comment by jstrachan** [comment]
It looks like turning a workflow into a Pod isn't gonna fly: https://issues.jenkins-ci.org/browse/JENKINS-29342 so its looking more like using Jenkernetes with DIND and swarm slaves is looking like the happy path going forward so we can reuse Jenkins Docker Workflow - plus use jenkernetes - see [background here](http://iocanel.blogspot.gr/2015/09/jenkins-setups-for-kubernetes-and.html)
