### ISSUE TITLE
API: ServiceAccounts missing from Kubernetes object

### ISSUE THREAD

**Issue by mwringe** [fabric8io/fabric8#4350]
ServiceAccounts are missing from the Kubernetes object in the API.

This causes tests to fail when using the Fabric8 arquillian plugins when the kubernetes.json file creates a service account.

It also means that users of the API have no way to access or manage service accounts.

**Comment by jimmidyson** [comment]
ServiceAccounts are included in recent releases - try 2.2.3?

**Comment by jimmidyson** [comment]
Ah I misunderstood! Thanks!

**Comment by mwringe** [comment]
I am running on master. Its not exposed and causes tests to not run when using the arquillian plugin since it doesn't understand what a service account it.

I created a PR which allows the tests to pass and access service account details: https://github.com/fabric8io/fabric8/pull/4351

**Comment by davsclaus** [comment]
Thanks a lot @mwringe. The PR has been merged. Is there more to this ticket or can it be closed?

**Comment by mwringe** [comment]
I believe that is it for this ticket, so it can be closed.

Is that something you expect the ticket creator to do? Or something the person who did the merging to do?

**Comment by davsclaus** [comment]
Thanks. The ticket can be auto closed if the commit message has `fixes #nnn` in the message.

But anyone with the permission to close should fell free to close if a ticket is resolved / no more work.
