### ISSUE TITLE
Option to pull all the images in a template

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4360]
It would be great if we could have an option to pull all the images in a template before running it.  Once all have been pulled a notification could be sent and also have a way in the console to identify that a template is ready.

If we did this then I wonder if we could have a status / output of the docker pulls as currently I don’t think there’s a way to get this info.  You would then be able to see what images are being downloaded and which are queued.

**Comment by davsclaus** [comment]
There is this gofabric8 pull command that helps at least. But yeah would be great with some feedback in the ui about image downloads and whatnot.

**Comment by rawlingsj** [comment]
yeah I think this can be closed as we now use the `gofabric8 pull` command.  I'm also not sure how easy it would be to figure out if images have been pulled as we could be in a clustered env where some nodes have images and some dont.  

I'll close this issue until a clearer requirement comes about the visualising the image pulls.
