### ISSUE TITLE
Add label to fluentd pod

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4365]
On a clean vagrant up, then this pod is the only one without a label.
Also wonder if we could strip out the ip adr of its pod name?

![screen shot 2015-06-29 at 12 18 16 pm](https://cloud.githubusercontent.com/assets/477100/8405902/36f87dc8-1e58-11e5-88e8-321be41e0941.png)

**Comment by jimmidyson** [comment]
This is a special kind of pod called a static (or mirror) pod. The reason the IP address is in the pod name is because this runs on every node - adding the IP address is done by Kubernetes/OpenShift & is not configurable.

I can add labels but that is all.

**Comment by davsclaus** [comment]
Did you add a label?

**Comment by jimmidyson** [comment]
Not yet.

**Comment by jimmidyson** [comment]
Want to move fluentd to a daemon controller pod which will be labeled etc just like any other pod.

**Comment by jimmidyson** [comment]
Done.
