### ISSUE TITLE
mvn fabric8:create-env should output volumes, ports the same way we do with env variables

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#4375]
I think it can be useful if fabric8:create-env phase prints informations about Volumes, ports and so on, in the same way as we already do with the environment variables? What do you think about?

**Comment by davsclaus** [comment]
yeah good idea. And maybe make it stand out so the user wont easily mix up the new information as ENV variables.

**Comment by oscerd** [comment]
Ok, I'll work on this :-)
