### ISSUE TITLE
merge the christian-posta fork of default-jenkins-dsl to the master branch

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4376]
these changes should get merged:
https://github.com/christian-posta/default-jenkins-dsl

which might help fix
https://github.com/fabric8io/default-jenkins-dsl/issues/2

maybe we make the Gerrit approval step conditional based on an env var for now? Until we can do it via the fabric8.yml file

**Comment by christian-posta** [comment]
Thx for the heads up; i'll get a PR going for this

**Comment by christian-posta** [comment]
This should be closed with https://github.com/fabric8io/default-jenkins-dsl/commit/377c18036f70baf8a35aa91309680978784477bd

**Comment by jstrachan** [comment]
thanks @christian-posta
