### ISSUE TITLE
Mac - docker versions incompatable

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#4392]
Just tried the latest fabric8 vagrant image and get:

Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

I have just upgraded to the latest version of boot2docker on my mac: Boot2Docker-cli version: v1.7.0

Any workaround?

**Comment by davsclaus** [comment]
Yeah I think the vagrant openshift + docker is on 1.6.2 still. Hopefully we can upgrade to 1.7.1 when it comes out sometime soonish.

**Comment by davsclaus** [comment]
And btw its  docker thing, apparently they want the client and server to must use same version branch.

**Comment by stevef1uk** [comment]
I discovered that the original docker was saved in my ~/.boot2docker directory so I can use that version

**Comment by stevef1uk** [comment]
Also, on the +'ve side I am not seeing those device mapper errors anymore. I have tried to run the iPaaS set of applications and my CPU is running red hot, but after a while I get communication errors and the console is no longer responsive. What is the recommended hardware footprint to run fabric8 these days? I may need to switch to AWS.

**Comment by davsclaus** [comment]
You can edit the vagrant file as its set to low spec with 2 cpus and 4gb memory. If you have a more powerful computer then you can inc those values.
