### ISSUE TITLE
Upgrade to docker maven plugin 0.13.0

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4400]

**Comment by oscerd** [comment]
I'll take care of this.

**Comment by davsclaus** [comment]
Thanks we also have this plugin version in the quickstarts
https://github.com/fabric8io/quickstarts

**Comment by oscerd** [comment]
Yes. I'll open a ticket on quickstart project also and I'll take care of it
:-)
Il 06/lug/2015 17:44, "Claus Ibsen" <notifications@github.com> ha scritto:
