### ISSUE TITLE
Using OSE v1 getting a 403 when the console attempts to watch the kubernetes and oapi 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4401]
This seems to only happen using OSE and a manual install (i.e. not using the vagrant image).  Looking at the request headers in the Network tab of chrome there is no token passed during the request..

```
Request URL:wss://fabric8.cd.fabric8.io:8443/api/v1/namespaces/default/pods?watch=true
Request Method:GET
Status Code:403 Forbidden
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, If-Modified-Since
Access-Control-Allow-Methods:POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin:http://fabric8.cd.fabric8.io
Cache-Control:no-store
Content-Length:224
Content-Type:application/json
Date:Mon, 06 Jul 2015 08:03:14 GMT
Request Headers
view source
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:Upgrade
Cookie:OPENSHIFT_default-fabric8_SERVERID=10.1.0.8:9090; csrf=1190c609-23b5-11e5-b272-fa163e069618; ssn=MTQzNjE2OTcyMnxMZWxBZjJmZHRCQTd3azZVbDZnMzhjaTFtR2lzZGlQS3lWa3BzSko5MFJjX3VucUlDcXIzaWVjcU5PQUhlUVlzWU5tOTd3MHRxU2ZpeDZmNVlCTmtwUmFxTEhsS253YkplS05UeUxTVVJpMTVEdkpjdnVqNEoyWDk4djN5SDhEWVZ3PT187gPbNI0UfA51_Vdz_t1HhqeGBQoZj_jMYnbVpF8zitE=
Host:fabric8.cd.fabric8.io:8443
Origin:http://fabric8.cd.fabric8.io
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:qPBy2dP9dh5Z6O2iJXCETg==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
Query String Parameters
view source
view URL encoded
watch:true
```

After adding some logging I can see that the userDetails object is empty https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/watcher.ts#L74

**Comment by rawlingsj** [comment]
In the resources tab under local storage I can see the bearer token that gets stored after logging in.

**Comment by jimmidyson** [comment]
Do you think this could be related to the basic auth changes @jstrachan introduced last week? Wonder if it's worth reverting those & adding those in a separate branch until they work properly?

**Comment by rawlingsj** [comment]
I can try but I think they were isolated changes.  I could try an older version of the console to rule it out though.

Initially I was thinking it might somehow be related to OSE as all the other installs we have are using Origin.  I'll try testing with origin and also an older version of the console to be sure.

**Comment by gashcrumb** [comment]
Should actually work fine on OSE AFAIK, the little embedded java console
(openshift-jvm) that's in the openshift console uses the same approach,
also pretty sure I ran hawtio-kubernetes when doing a little OSE testing a
couple weeks ago to manage some stuff and it was alright.  But yeah, worth
maybe testing with an older version of the console just to see if it's an
issue that's been introduced or if it's been broken all along :-)

**Comment by rawlingsj** [comment]
Ah yeah just tested with fabric8/fabric8-console:v1.0.8 and the auth token does get passed so I think it might be a bug our side.  I noticed when I added a bit of logging just before the [URI query](https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/watcher.ts#L72) the UserDetails object whilst was empty it had a reference to GoogleOAuthConfig even though earlier in the logs it confirms that OpenShift OAuth is being used.

This is a screenshot of the javascript console from v1.0.9
![screen shot 2015-07-06 at 10 44 08](https://cloud.githubusercontent.com/assets/1457180/8530134/065ef556-2417-11e5-892e-f7fce4b8251e.png)


Incidentally I still do get a 403 but only on the first namespace request, subsequent websocket requests for pods etc are 200 ok.

This is a screenshot of the javascript console from v1.0.8
![screen shot 2015-07-06 at 19 41 08](https://cloud.githubusercontent.com/assets/1457180/8530146/17017258-2417-11e5-8177-2ccd24ee3582.png)

**Comment by gashcrumb** [comment]
It'd be interesting to see the Authorization header value for those two other calls to /api/v1/namespaces right above there, think one of them should be a normal GET rather than an upgrade request.  We try from the watcher to fetch the namespaces up front in a pre-bootstrap task so they're available to help make the selected namespace a bit more deterministic.

**Comment by rawlingsj** [comment]
Ah ok, yeah here are the other two /api/v1/namespaces.  BTW its accessible via our VPN if that also helps http://fabric8.cd.fabric8.io/.

![screen shot 2015-07-06 at 20 44 49](https://cloud.githubusercontent.com/assets/1457180/8531532/fa6968fe-241f-11e5-813e-630ef0fbce0e.png)

![screen shot 2015-07-06 at 20 45 03](https://cloud.githubusercontent.com/assets/1457180/8531533/fa6c2256-241f-11e5-83cb-5b9f053f6c8a.png)

**Comment by gashcrumb** [comment]
Hmm, in my case it's failing due to:

```OPTIONS https://fabric8.cd.fabric8.io:8443/oapi/v1/users/~ net::ERR_INSECURE_RESPONSE```

which then takes me back to the login page.  Do you have the ```ca.crt``` handy?

In any case, this is probably just noise.  We do want to make sure that the google oauth plugin doesn't activate itself at all if there's no config, and definitely need to make sure it doesn't clear out any existing token in the userDetails object.  Think I've spotted a bug in that plugin, let me check it out and maybe push a fix.

**Comment by rawlingsj** [comment]
Ah that would be awesome if you're on to something there!

I'm not sure about the cert.  I've checked my browser certificates and there's nothing obvious to say which one it is.  I'm not entirely sure what I'm looking for I'm afraid.

**Comment by gashcrumb** [comment]
K, worked over the google oauth plugin a bit, think it should reliably disable itself now.  I also changed the google oauth plugin to store all of the token details including the expiry, rather than just the token itself, hopefully caught all the spots where we grab the token from local storage :-).

**Comment by rawlingsj** [comment]
This in now working with the latest code from master.

**Comment by rawlingsj** [comment]
Thanks for this @gashcrumb @jstrachan

**Comment by rawlingsj** [comment]
Reopened - seems this might be a timing issue.  It might be that there's no token available when the initial namespace request is made.

**Comment by rawlingsj** [comment]
Tested with 2.2.9.1 and all working.
