### ISSUE TITLE
Gerrit should use secrets and not manual installation of keys

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4412]
Gerrit has some plugins enabled by default for creating the Jenkins and Admin users and it requires certificates/keys to do this. We should be using kube secrets/serviceAccounts to access those keys, not the manual steps required now as described here: https://github.com/fabric8io/docker-gerrit/blob/master/scripts/copy-keys-vagrant.sh

**Comment by jstrachan** [comment]
passing in user/pwd via environment variables would be even easier for users to get started with gerrit - if its possible to do things that way.

**Comment by cmoulliard** [comment]
This is already the case : https://github.com/fabric8io/quickstarts/blob/master/apps/gerrit/src/main/fabric8/env.properties#L12-L19

**Comment by jstrachan** [comment]
so we can close this issue then - there's no need for secrets?

**Comment by cmoulliard** [comment]
No as we should improve what exist to avoid to copy/paste the keys to the Vagrant host VM as reported by Christian Posta.

**Comment by jstrachan** [comment]
When I said user/pwd I meant instead of having to use ssh keys & secrets BTW; then installation is nice and easy. If ssh keys are mandatory then we've no option but to go with secrets though. Its just it requires lots of CLI messing around for customers not using our vagrant images

**Comment by christian-posta** [comment]
@jstrachan yah, secrets removes the dependency of manually configuring the host (which i wanted to get rid of), but then it's on the user to set up the secrets correctly (or whatever automation scripts they use) which is kinda sucky. I've already start to move this to secrets, but wondering if @cmoulliard can recall what options we had? can we just move to username/password like James asked? i.e., for the admin user, is it possible to create it w/out having to have ssh keys? or is SSH the only API that gerrit allows for configuring additional options+new users? I cannot remember...

if we have to stick with the SSH key, @jstrachan is there a way we should document using secrets with this app? ie... do we have other apps that use keys, etc?

**Comment by christian-posta** [comment]
or we make a flag to "enable" the gerrit replication stuff and admin user stuff... though it becomes quite a bit less useful in the platform if it's just a stock gerrit app that isn't connected in.

**Comment by cmoulliard** [comment]
There is one SSH key which is mandatory until now (= gerrit admin user) as this ssh is used when we will create the gerrit git project from the java plugin used by the maven gerrit create project plugin.

Maybe it will be also required that we have a SSH key if we would like to use the gerrit jenkins plugin. But we should discuss that in another issue ticket

**Comment by jstrachan** [comment]
the next release which should be here in a few hours should be all setup to create secrets etc. 

@cmoulliard @christian-posta it'd be good to give the new gerrit app a try and see if it works for you

**Comment by jstrachan** [comment]
I think this is all sorted now with the secrets annotations and gofabric8 installer https://github.com/fabric8io/fabric8/blob/master/docs/secretAnnotations.md

**Comment by cmoulliard** [comment]
No. We can't use the public keys generated by gofabric8. @rawlingsj is aware of the problem and will update gofabric8. This is why for the moment, we have to use these instructions (see steps from 1 to 4) --> https://github.com/cmoulliard/emea-partners-2015/blob/master/slideshow/installations-cd.adoc#installation
