### ISSUE TITLE
Openshift login loop

### ISSUE THREAD

**Issue by mmaier2** [fabric8io/fabric8#4422]
Hi, 

I can't use the hawtio console. I'm stuck in an endless login loop on the openshift login web page before.

I've installed Openshift origin via ansible and deployed the router and registry. Then I've created the necessary config changes for Openshift (scc, service user, secret etc.)  and deployed the pod and configurations for the fabric8 console by processing the template in base-2.2.5.json.
The pod(s) are running and the maven plugin creates the routes.
If I access the fabric8 route with firefox I could see the hawtio console a couple of seconds then the openshift login screen appears. I'm logging in with admin (), the hawtio console appears again for 1-2 seconds and I'm redirected (302 found) back the openshift login.

What did I do wrong or what can I do to get more insight into this problem? Do you have any clue?

oc version:
oc v1.0.0-1-g6ffebda
kubernetes v0.17.1-804-g496be63

**Comment by gashcrumb** [comment]
Any errors on the javascript console?

**Comment by mmaier2** [comment]
Thanks for the tip. There're indeed some messages in the js console:

Sry. This is a german output. But as it seems, first it complains about CORS, and that a header 'Access-Control-Allow-Origin' is missing and therefore it blocks /api/v1/namespaces:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://fabric8...:8443/api/v1/namespaces. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).1 <unbekannt>

Then it says that 

 "[api-manager] apiman reports that it is not running."1 libs-e02573de.js:10:25942
consoleLogger() libs-e02573de.js:10
Ok, I've just processed the base json, that's just the console. So maybe I should also run the apiman-2.2.5.json.

I'm using firefox 38.0.1.

**Comment by jimmidyson** [comment]
When you start OpenShift you have to start it with the
"--cors-allowed-origins=.*" flag. That allows the fabric8 console to talk
to the openshift API server which otherwise checks the origin of requests &
rejects unknown sources.

Thanks,
Jimmi

**Comment by mmaier2** [comment]
Wow... thanks a lot! I never would have figured that out!

**Comment by jstrachan** [comment]
We should make this command line option in kinda bold on the docs page ;)

On 7 July 2015 at 16:37, mmaier2 <notifications@github.com> wrote:

> Wow... thanks a lot! I never would have figured that out!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4422#issuecomment-119241504>.
>



-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration

**Comment by gashcrumb** [comment]
Yeah, and a FAQ entry too right at the top if we don't have one already :-)

**Comment by davsclaus** [comment]
The command is listed today at
http://fabric8.io/guide/getStarted/openshift.html

But we had 2 or more people recently hit this issue. Maybe we could add some INFO box or something to highlight its important to set that cors option.

**Comment by jimmidyson** [comment]
This is working now.

**Comment by glennodickson** [comment]
Hi

Using a Windows setup, I started minishift last night and used the following command :
> `gofabric deploy`

This deploys Fabric8 and seem to work as expected. You may want to try that, its a quite good.
