### ISSUE TITLE
Kubernetes client library dependency graph is messy

### ISSUE THREAD

**Issue by paulbakker** [fabric8io/fabric8#4430]
The list of dependencies required to use the Kubernetes client is quite long. This is mostly caused by transitive dependencies, but that doesn't change the practical issue. Specially running in a bare bone OSGi environment this is painful.

Make the client library more self-contained would make the library more usable in different environments.

I'm the author of another OSGi focussed Kubernetes client, which I started after failing to work with the Fabric8 one. @jimmidyson suggested on a blogpost to open a issue here (http://paulbakker.io/amdatu/amdatu-kubernetes-api/).

**Comment by christian-posta** [comment]
Yah, good point.

Is this similar to issue #4428?

On Wed, Jul 8, 2015 at 8:37 AM, Paul Bakker <notifications@github.com>
wrote:

> The list of dependencies required to use the Kubernetes client is quite
> long. This is mostly caused by transitive dependencies, but that doesn't
> change the practical issue. Specially running in a bare bone OSGi
> environment this is painful.
>
> Make the client library more self-contained would make the library more
> usable in different environments.
>
> I'm the author of another OSGi focussed Kubernetes client, which I started
> after failing to work with the Fabric8 one. @jimmidyson
> <https://github.com/jimmidyson> suggested on a blogpost to open a issue
> here (http://paulbakker.io/amdatu/amdatu-kubernetes-api/).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4430>.
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by jimmidyson** [comment]
@christian-posta It was @paulbakker's blog post that kicked @davsclaus into life on #4428 ;) I still think there is more that we can do though as @paulbakker has proven with his Kubernetes client lib.

**Comment by davsclaus** [comment]
This is much better now. closing this ticket.
