### ISSUE TITLE
Kubernetes Node.getStatus().getCapacity().get("memory").getAmount() incorrectly serialized

### ISSUE THREAD

**Issue by paulbakker** [fabric8io/fabric8#4440]
The "amount" property on the capacity specification of a Kubernetes node is serialized as number. This is strange since "getAmount" returns a String. It is also incorrect, because Kubernetes returns values like "3528176Ki" for memory.

**Comment by jimmidyson** [comment]
@paulbakker Pushed a fix to the kube model project - would you be able to try the SNAPSHOT version to see if it fixes the problem? Project repo is https://github.com/fabric8io/origin-schema-generator. Simple `mvn clean install` should do it.

**Comment by paulbakker** [comment]
The fix works, thanks for responding so quickly!

**Comment by jimmidyson** [comment]
We aim to please ;) We'll get a release out of the model out now too - we need a few fixes in it.
