### ISSUE TITLE
Images with a prefix of docker.io prevent nodes using the local registry 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4462]
If a pod references docker image names with a prefix of docker.io this means all nodes will pull directly from dockerhub rather than using a local registry.  This isn't great especially if running in a cloud environment where you are charged for download traffic.

**Comment by jimmidyson** [comment]
@rhuss Why do we need this prefix again? I assume we could just override `fabric8.dockerPrefix` property when building to use the openshift cluster's registry?

**Comment by rhuss** [comment]
The problem is with Docker on Fedora/CentOS: https://bugzilla.redhat.com/show_bug.cgi?id=1241950

Therefore we introduced in the Quickstart a ${docker.registryPrefix} in the image name which by default is empty (so shouldn't be an issue) and for a release we set it in Jenkins to 'docker.io/'.

**Comment by rhuss** [comment]
@jimmidyson : Yes, you can set it simply to the cluster's registry prefix or leave it empty if the Docker host is configured to use OS's registry as default.

**Comment by jimmidyson** [comment]
Are there any docs that need updating for users to know about this & how to
use it properly with a local registry or is this done already?

**Comment by rawlingsj** [comment]
this has been resolved - all repo prefixes have been removed and all pull now go via the cluster registry
