### ISSUE TITLE
Run button only appears in the default namespace

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4463]
As the Run button only appears in the default namespace you are not able to run a template that doesn't require and template values, to be scheduled in a namespace other than default.

For example the mq producer and consumer apps can only be run in the the default namespace from the console.

**Comment by gashcrumb** [comment]
You can,  however flip over to the default namespace and select a different
namespace to actually run a template in.

**Comment by rawlingsj** [comment]
Ah yeah sorry, I missed it there, I thought the target namespace option was only available if you were overriding template values.  Thanks @gashcrumb.

**Comment by davsclaus** [comment]
can this be closed or is there something to be worked on?

**Comment by rawlingsj** [comment]
just tested and the run button appears in all namespaces now.
