### ISSUE TITLE
Camel forge - Add command to add/update kubernetes services in pom.xml

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4477]
For example to define a service in kubernets.json, you can specify this in the pom.xml using 3 properties.

See this example
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/war/camel-servlet/pom.xml#L55

```
    <fabric8.service.name>quickstart-camelservlet</fabric8.service.name>
    <fabric8.service.port>9101</fabric8.service.port>
    <fabric8.service.containerPort>8080</fabric8.service.containerPort>
```

So the command should take in 3 options

- service name
- service port
- container port

In the example above container port is the internal port the the contiainer uses eg default Apache Tomcat 8080. Then 9101 is the port that clients need to use when talking to it.

**Comment by davsclaus** [comment]
Maybe this command is a bit similar to camel-setup
https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/CamelSetupCommand.java

It can be used as inspiration / starting point. 

And to update properties in the pom.xml to add/edit those 3, then see this how it can be done
https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/FabricStepCommand.java#L196

**Comment by oscerd** [comment]
I'd really to work on this if possible :-)
