### ISSUE TITLE
Camel-Forge: Remove Component Command

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#4484]
Hi,

I've noticed we have an add-component command in Camel-forge and no remove-component command.

Do we need a remove-component command?

Andrea

**Comment by davsclaus** [comment]
I am not so sure it adds so much value. The benefit of the add is that its a wizard that can help discover the component you are looking for - eg I want to add a NoSQL component, and then there is a wizard to show the components that can do that etc.

Removing a component complicates matter as you would likely need to detect if the component is in use, and if so warn the user etc.

**Comment by oscerd** [comment]
You're right.

**Comment by oscerd** [comment]
However, we can think of some new commands to add to available set.
