### ISSUE TITLE
Some apps depend on openshift-secrets which causes issues when running on vanilla Kubernetes

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4488]
As a work around to getting the messaging app to run I created an empty secret called openshift-secrets. 

```
cat <<EOF | kc create -f -
---
  apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "openshift-cert-secrets"
EOF
```

**Comment by jimmidyson** [comment]
If that actually worked with empty secrets then the secret isn't required at all... worth removing from the app.

**Comment by jstrachan** [comment]
this should be fixed now - all the use of 'openshift-cert-secrets' have gone from the quickstarts.

The installer should help too: https://github.com/fabric8io/fabric8/issues/4545
