### ISSUE TITLE
Kubernetes API cannot handle secrets in kubernetes.json file

### ISSUE THREAD

**Issue by mwringe** [fabric8io/fabric8#4513]
io.fabric8.kubernetes.api.Controller.java currently does not handle secrets in ApplyEntity and they are ignored if present in a kubernetes.json file. This means tests cannot be performed if a secret is required.

**Comment by mwringe** [comment]
PR: https://github.com/fabric8io/fabric8/pull/4514

**Comment by jstrachan** [comment]
FWIW ServiceAccounts are preferable to Secrets; we try use them where possible in kubernetes.json files

**Comment by jimmidyson** [comment]
They serve different purposes.

Service accounts are used to provide generated token mounted in the pods that can be used to auth to api server.

Secrets should be used for other kind of secret info: certificates, ssh keys, shared keys, etc rather than any kind of auth token to the api server.

**Comment by mwringe** [comment]
Is there any issue with the PR or anything else that needs to be discussed before it can be pulled? I would rather get in pulled in sooner than later so that I doesn't get out of sync with the code base.

**Comment by jimmidyson** [comment]
Merging. What's your use case for secrets btw?

**Comment by mwringe** [comment]
For passing the token to access the secured kubernetes api endpoint. 

Note: that is a joke :) I know how to use service account.

I am using secrets to setup certificates and keys between containers so that they can securely talk to each other.

**Comment by jstrachan** [comment]
closing as the PR got merged
