### ISSUE TITLE
Camel-Forge: Show endpoint options command

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#4534]
I think it can be useful to have a command like this.

What do you think about?

**Comment by davsclaus** [comment]
Do you mean to list all the endpoints, or to show information about one specific endpoint?

**Comment by oscerd** [comment]
I mean one specific endpoint.
Il 23/lug/2015 12:49, "Claus Ibsen" <notifications@github.com> ha scritto:

**Comment by davsclaus** [comment]
What do you want to show? Maybe kinda like what the karaf/jolokia command can do for explain-endpoint? Where it can list all the options and their docs etc. Those commands only work on a existing running Camel app. Not like these forge addons that can work on the source code.

**Comment by oscerd** [comment]
I was thinking to something that show the options on a specific endpoint starting from an XML camel configuration.

Similar to camel-add-endpoint-xml, but showing the options in an ordered way.

**Comment by davsclaus** [comment]
yeah sure that would be nice

**Comment by oscerd** [comment]
Perfect :-)
