### ISSUE TITLE
Create a golang based installer binary for fabric8 on openshift or kubernetes

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4545]
there are a few steps to installing fabric8 on openshift & kubernetes given a Linux and docker installation. Mostly it's secrets & some roles and a few templates to get the base going - from there the console or CLIs can take over.

It's still a little clunky for folks getting started though! The installer could run more checks too to ensure things are all setup properly.

Also we have some bash magic in our vagrant files that's hard to reuse and can't be used for folks on a vanilla openshift or kubernetes environment.

It'd be nice if we put all the logic to install things into a single binary - folks can then just download & run it - then the vagrant files can all reuse it too. It'd help everyone then - vagrant or not - to install fabric8 given an openshift or kubernetes installation. We'd also be able to share code more easily between openshift & vagrant versions too.

The installer could then also ask the user what apps they want to install and if need be pre-download all the images etc

Who knows one day the installer could get clever enough to do what our vagrantfiles do right now - download and install kubernetes or openshift and run it too if it's not already installed?

**Comment by jstrachan** [comment]
I guess for now the installer could just be a bash script - maybe we just refactor the script out of the vagrant files - so folks can use it inside or outside of vagrant?

**Comment by pulse00** [comment]
+1

**Comment by jimmidyson** [comment]
Started on the validation side of this to begin with - it will be needed after install anyway to pick up on successful deployment. Work on this can be tracked & run locally with `go install github.com/fabric8io/gofabric8` - when a release is done this will use github releases to download a binary but for now go is needed locally to build it.

You can then run it with `gofabric8 validate`. All the normal `kubectl` flags are allowed as it basically inherits from there & will use your `~/.kube/config` file by default - like I said all options are overrideable in the same way `kubectl` works.

Couple of questions:

* Are the secrets actually required any more? With recent versions of kubernetes & openshift the CA cert (which was the main thing we used IIRC) is now provided as part of the mounted service account token.
* Does fabric8 need to be a cluster admin on an openshift installation? Don't think there's anything special that needs to be set up on Kubernetes similar to this?
* Do we create a `fabric8` namespace or do we deploy to `default` atm? Should we deploy core components to `fabric8` namespace?

**Comment by jstrachan** [comment]
Oooh - maybe we don't need lots of the secrets! Would be nice to let fabric8 just be a kubernetes.json that works OOTB! 

Which version of OpenShift are the CA certs mounted & where are they? We should try port as many services away from using secrets as possible.

I can't remember why the need for the cluster admin role TBH - and yeah there's no kubernetes equivalent. Lets try remove as many of these pre-requisites in our CI / CD system and see if things still work ;)

Right now we deploy to wherever the user wants to ;) Which defaults to 'default'. But yeah we could pick a fabric8 namespace. I guess the user could maybe pick the namespace?

**Comment by jstrachan** [comment]
BTW I did wonder about putting all the templates inside the installer binary; but then figured; they're all in a canonical place in maven central so maybe the installer could be version agnostic and let folks specify the version on the command line or it'd default to the latest?

**Comment by jimmidyson** [comment]
According to the trusty release notes, CA cert is mounted in OpenShift >= 1.0.2. The client (old & new iirc) uses the CA cert if available so no need to do anything I don't think - but fyi it's mounted at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.

As we're extending `kubectl` base functionality (basically replacing all subcommands with our own ones, e.g. `validate`) the namespace can be specified by `--namespace=...` & will default to whatever's the current namespace from the user's `~/.kube/config` (or kubeconfig file specified with `--kubeconfig` or `KUBECONFIG` env var).

Remind me what the mvn GAV is for the base templates? Can we deploy these in the same way to OpenShift & Kubernetes?

**Comment by jimmidyson** [comment]
Oh & btw it's got colour & everything ;)

**Comment by jstrachan** [comment]
Awesome! :) 

We've currently got 2 areas in maven where there kubernetes.json files get released:

* individual apps go here http://central.maven.org/maven2/io/fabric8/jube/images/fabric8/ - mostly for historic jube reasons :( might be nice to switch to a nicer group id TBH
* the consolidated 'group apps' are here: http://repo1.maven.org/maven2/io/fabric8/apps/

I wonder if we need to release some kind of index file per release that lists all the kube jsons available? Then it'll be easier for the installer; given a release number to be able to enumerate all the mvn coords/links for all the possible apps?

All the kubernetes.json files are OpenShift Templates usually; though if we process the template parameter ${FOO} expressions locally - we should be able to apply them to both OpenShift and Kubernetes. We do the same in `mvn fabric8:apply`; if on kubernetes we default to locally processing templates (as does hawtio)

**Comment by jstrachan** [comment]
We've also got a 'distro' now which includes the common stuff (though not everything) as a tarball
http://repo1.maven.org/maven2/io/fabric8/apps/distro/

maybe the installer should just use that and over time we can fix the distro to try include everything?

**Comment by jimmidyson** [comment]
:+1: to distro. Can list available versions of distro via the Maven metadata hopefully, default to latest release.

**Comment by jstrachan** [comment]
Yeah - lets just use that distro! :) much easier!

**Comment by jimmidyson** [comment]
I was thinking of just deploying the templates & only running those that the user asks for - by default just fabric8 console & perhaps template microservice on kubernetes (although not sure which app that is!)? Then deploy templates to env, run those that the user specifies (if any)? Are there any more defaults that should always be deployed for a minimum fabric8 experience?

**Comment by jstrachan** [comment]
yeah sounds good!

**Comment by jstrachan** [comment]
Here's a single kubernetes json for running the console + the templates service on kubernetes:
ttp://central.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.16/console-kubernetes-2.2.16-kubernetes.json

Yeah thats a good point - just run the console on openshift (and install the templates) or the console-kubernetes.json and we should be good. The latter populates the templates right now from this git repo: https://github.com/fabric8io/templates/tree/master/default/template. Though it might be nice to be consistent and deploy the same templates to both environments in the same way?

**Comment by jstrachan** [comment]
BTW here's the hack I used to make the templates be pre-populated by default when using the console on kubernetes / GKE:
https://github.com/jstrachan/quickstarts/blob/changes/apps/templates/pom.xml#L67-67

it might be nice for the installer to remove that volume from the templates json; then just install the same templates for OpenShift and Kubernetes from the same distro. Though we can always get the CI / CD pipeline to ensure that the git repo we use  in the templates service is populated with the same stuff as the OpenShift installer creates.

**Comment by davsclaus** [comment]
dont we have this now or is there more work?

**Comment by jimmidyson** [comment]
No this is done.
