### ISSUE TITLE
Camel-Forge: Add/Show/Edit endpoint XML commands doesn't work correctly with endpoint with & 

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#4548]
The following commands:

- Edit endpoint XML
- Show endpoint options XML also

don't work correctly when the endpoint inside XML configuration file contains and "&amp;" token.

In particular they don't work when  the endpoint is passed as argument to the command. If we don't pass the argument and follow the wizard then everything seems ok (even though the edit endpoint command doesn't save the edited endpoint inside the XML file).

The problem seems to be related to setValueChoices of Forge.

**Comment by oscerd** [comment]
I did an in-depth analysis and the problem is inside Forge. I'll raise a JIRA to Forge Team.

**Comment by davsclaus** [comment]
@oscerd did you raise an issue to forge?

**Comment by oscerd** [comment]
@davsclaus Yes, I've re-opened this one:

https://issues.jboss.org/browse/FORGE-552

**Comment by oscerd** [comment]
The issue is closed now. The edit endpoint xml command doesn't save in the camel configuration file the edited endpoint.

I'll do an analysis to see if it is a Forge problem again or maybe is our fault.

**Comment by davsclaus** [comment]
I think this works better now - we can edit/add endpoints in both java and xml now.

**Comment by davsclaus** [comment]
@oscerd do you remember which kind of uris that would fail?

The latest code on master seems to work fine for me - i can both add/edit endpoints in both java and xml projects.

**Comment by oscerd** [comment]
@davsclaus In my tests I add an endpoint xml and then I try to edit it.

**Comment by oscerd** [comment]
I'll do a test on my own too :-)

**Comment by davsclaus** [comment]
Seems to be working now with all the latest bits of forge and camel
