### ISSUE TITLE
cannot create oauthclients at the cluster scope

### ISSUE THREAD

**Issue by huembi** [fabric8io/fabric8#4556]
I try to install the fabric8-base package on Openshift v3, but I do not have enough rights to install it:
 
	oc process -v DOMAIN=$KUBERNETES_DOMAIN -f base-2.2.16.json | oc create -f -
		replicationcontrollers/fabric8
		Error from server: User "rene.huber@axa-tech.com" cannot create oauthclients at the cluster scope

Is the registration of the OAuthClient required to run fabric8?
Is there a way to get around this constraint?
Or do you know whether I can have distinct rights on OpenShift v3 to add a OAuthClient withouth being a Administrator?

**Comment by jstrachan** [comment]
OAuthClient is required for the fabric8 console; its required to allow OAuth login.

I guess to enable the OAuthClient you need to be a cluster-admin? We usually add cluster-admin role to the fabric8 service account in our vagrantfile:
https://github.com/fabric8io/fabric8-installer/blob/master/vagrant/openshift/latest/Vagrantfile#L150

**Comment by huembi** [comment]
Thanks for your support. They gave me now some more rights to install it.

**Comment by hodrigohamalho** [comment]
As a system:admin user

do:
```
oadm policy add-cluster-role-to-user cluster-admin ramalho
```

Just to make it easy  :)
