### ISSUE TITLE
lets remove the Gerrit app from the cdelivery app until it works OOTB

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4571]

**Comment by cmoulliard** [comment]
What is the issue ?

**Comment by jstrachan** [comment]
It doesn't start ;)

**Comment by cmoulliard** [comment]
I will have a look this week after reviewing changes done by Christian.

**Comment by davsclaus** [comment]
does it work now?

**Comment by jstrachan** [comment]
yeah, pretty much there now - gonna close this issue

**Comment by cmoulliard** [comment]
Gerrit kube app is working excepted that we don't sync gogs & gerrit repo ('https://github.com/fabric8io/fabric8-devops/issues/44''). So, please, don't remove gerrit from cd-pipeline
