### ISSUE TITLE
rename some main apps

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4572]
e.g. here's some suggestions

```
base -> console
cdelivery-core -> ci-cd
cdelivery -> devops
```

**Comment by davsclaus** [comment]
@jstrachan @rawlingsj have you guys not done some restructure in the apps / quickstarts and whatnot. Anyting more to rename?

**Comment by jstrachan** [comment]
yeah - renamed lots of things to be cleaner; plus ipaas and devops separated - so gonna close this one now
