### ISSUE TITLE
fabric8:create-env with DOMAIN env var set doesnt replace string in env.properties

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4586]
running 
```
mvn fabric8:create-env -Dfabric8.create-env.DOMAIN=vagrant.f8 -Dfabric8.create-env.GOGS_SERVER_DOMAIN=test
```
in https://github.com/fabric8io/quickstarts/tree/master/apps/gogs updates the `GOGS_SERVER_DOMAIN` string but not the `DOMAIN` in the generated target/env.properties

**Comment by oscerd** [comment]
I will take a look. Maybe there's something wrong in the create-env phase :-)

**Comment by rawlingsj** [comment]
ah ok, many thanks!

**Comment by oscerd** [comment]
The PR should resolve the issue.

I think I need to work a little more on the environment variables expansion, cause actually if we have more than one enviroment variable in our property, than the expansion doesn't work well. I'll improve this feature.
