### ISSUE TITLE
Quickstarts repo needs to be split up

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4632]
We need to split up the quickstarts repo, here's a suggested split but there a few questions so a bit of feedback is needed...

4 questions numbered below.

Looking at the current quickstarts directory structure..

__quickstarts__
To remain..
```
app-groups <-- [Q1] split out into own repo?
apps <-- contents to be moved into separate devops, management apps as detailed below and this folder deleted
archetype-itests <-- keep
archetypes-catalog <-- keep
archetypes <-- keep
distro <-- keep
quickstarts <-- keep
```

__management-apps__
```
apiman
cadvisor
elasticsearch
fabric8
grafana2
heapster
keycloak
kibana
prometheus
templates
```
__devops-apps__
```
artifactory
brackets
cdelivery
chaos-monkey
fabric8-forge
gerrit
gogs
hubot-irc
hubot-letschat
hubot-notifier
hubot-slack
image-linker
jenkins
kiwi-irc
letschat
nexus
orion
sonarqube
taiga
```

__ipaas-apps__
Not sure about these.  [Q2] Should the ipaas apps be the two we have in the quickstarts/app-groups today and we need to add more?  
```
move and rename https://github.com/fabric8io/quickstarts/tree/master/app-groups/quickstarts-http ->  ipaas-http
move and rename https://github.com/fabric8io/quickstarts/tree/master/app-groups/quickstarts-rest ->  ipaas-rest
```

__To be deleted?__ see https://github.com/fabric8io/fabric8/issues/4600#issuecomment-131027037
[Q3] Do the mq apps have to be removed now or can they stay until the MaaS solution is available?
```
amqbroker
fabric8-http-gateway
fabric8mq-autoscaler
fabric8mq-consumer
fabric8mq-controller
fabric8mq-producer
fabric8mq
```

[Q4] Should these apps still be maintained or have they been replaced by different apps or approaches?
```
api-registry
app-library
grafana
influxdb
infinispan-server
jadvisor
jbpm-designer
registry
zookeeper
```

**Comment by davsclaus** [comment]
@rawlingsj are there more work on this ?

**Comment by rawlingsj** [comment]
@davsclaus no I think we can close this and raise issues if there is anything found to be outstanding.
