### ISSUE TITLE
allow any maven project to be created via the hawtio/forge wizard and automatically enable fabric8/docker maven plugins and optional jenkins workflow

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4652]

**Comment by oscerd** [comment]
I'm sorry about the forge upgrade. I didn't know there was a bug on 2.18.0.Final

**Comment by jstrachan** [comment]
No worries! I didn't know either! Its our bad for not having got really
good automated system tests on the generated docker images inside
kubernetes/openshift. Am gonna try sort that out so we'd get fast feedback
on any bugs introduced by version changes.

BTW keep up the great work updating dependencies to newer versions; it
frequently does lots of good! Our CI / CD system should have caught this
issue

On 25 August 2015 at 22:44, Andrea Cosentino <notifications@github.com>
wrote:

> I'm sorry about the forge upgrade. I didn't know there was a bug on
> 2.18.0.Final
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4652#issuecomment-134750719>.
>



-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration
