### ISSUE TITLE
openshift client not working in gofabric8

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4679]
The error can be reproduced by running the validate command.  It is affecting any OpenShift resource not just templates.  The Kubernetes client is unaffected.

Running..
```sh
oc login https://cd.fabric8.io:8443 -u admin -p admin
curl -L https://github.com/fabric8io/gofabric8/releases/download/v0.2/gofabric8-0.2-darwin-amd64.tar.gz | tar -xvz
chmod +x gofabric8
./gofabric8 -s https://cd.fabric8.io:8443 validate
```

Gives this error..

```
Validating your OpenShift installation at https://cd.fabric8.io:8443 in namespace default

Service account.................✔
Console.........................✔
Templates.......................✘ the server could not find the requested resource
```

**Comment by jimmidyson** [comment]
`the server could not find the requested resource` indicates that the URL is wrong. Is the oapi path set correctly? I think you can try running with `--v=8` to increase logging levels which should include what URLs it's trying to hit. Maybe.

**Comment by rawlingsj** [comment]
Great - the `--v=8` worked nicely and yeah you're right @jimmidyson the URL is wrong, it's `api` rather than `oapi`.
```
https://cd.fabric8.io:8443/api/v1/namespaces/default/templates
```
should be 
```
https://cd.fabric8.io:8443/oapi/v1/namespaces/default/templates
```

**Comment by jimmidyson** [comment]
@rawlingsj - Fixed, pull latest gofabric8.

**Comment by rawlingsj** [comment]
Works great!  Thanks @jimmidyson
