### ISSUE TITLE
API error (404): Cannot start container 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4695]
From the mailing list and we have also just seen this https://groups.google.com/d/msg/fabric8/ys9c5pt0cbo/Z734PjIMAQAJ

```
elasticsearch-5asv9 : API error (404): Cannot start container 4abe4341120f1c4fec3d8cd5fe6cacc89a3e92969f2010bb3ae851a7285059ae: [8] System error: no such file or directory
jenkins-e0ubi : API error (404): Cannot start container f523a4490290e9590b71861461118af970395f0c9c0d7ee0ef9335d41386c5ac: [8] System error: no such file or directory
```

**Comment by hirunika3** [comment]
How long will it take to fix the issue or is there's any workaround until the issues are fixed?

**Comment by rawlingsj** [comment]
I think these were down to docker issues - not seen this in a while so closing
