### ISSUE TITLE
Change default API version by configuration?

### ISSUE THREAD

**Issue by Javierperezmartin** [fabric8io/fabric8#4725]
I'm trying to change 'v1' API to 'v1beta3' API, but it seems that there's no config parameter to do so. Is there any way to change the 'v1' default API, so the REST requests go to 'http://kubernetes.server:port/api/v1beta3/... ?

**Comment by davsclaus** [comment]
I doubt that, and v1beta3 is deprecated and removed from OS3 / kubernetes. So you better upgrade to v1

**Comment by Javierperezmartin** [comment]
You are right. It was because of using some docker images containing
Kubernetes, they still use beta versions, but just built one from the
scratch with v1. Anyway, such images have a high calification, so I thought
change version by configuration could be an open issue.

BR, Javier
