### ISSUE TITLE
allow fabric8-arquillian to be configured via an env var / system property to use a known canonical namespace to run the test case

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4737]
so that it recreates all the dependent templates (e.g. like `mvn fabric8:recreate` does) at the start of a test and then leaves the namespace around at the end of the test.

This will then let folks keep namespaces around so they can look inside.

Longer term we maybe wanna add more sophisticated GC of test namespaces; using annotations of a namespace that is in use (so that we can prevent 2 test runs running against the same namespace) and to be able to GC the last X test namespaces before creating a new test namespace etc

**Comment by iocanel** [comment]
After our talk this morning, I pretty much fixed that locally?
Do you mind if I re-assign the issue to me?

**Comment by jstrachan** [comment]
@iocanel awesome - go right ahead - it was gonna be the little thing I hacked on while on the train tomorrow - guess I'll have to find another issue ;)

**Comment by jstrachan** [comment]
BTW one nice side effect of allowing optionally pre-defined namespaces for fabric8-arquillian tests is we can let the [gofabric8 installer](https://github.com/fabric8io/gofabric8) pre-create any SCC's / secrets / persistent volumes for the namespace up front and folks could always add some extra custom apps in there too (that remain there before & after the test).
