### ISSUE TITLE
Best practise in use with Camel/Fuse projects

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [fabric8io/fabric8#4745]
Hello,

I am right now evaluating Fuse 6.2 and started to use the Fabric component but ran into many problems with the deploy and also the containers and profiles which didn't seem to mesh well together. Sometimes the container would end up in an alive state and nothing happend or sometimes the container would end up in alive and waiting and it was hard to know what exactly was wrong with it.

Do you know if there is documentation coming which will describe some benefits and best practise for using Fabric8 for Camel integration projects together with Fuse (6.2)? We specifically want to build say 50-100 camel based integrations and want to know how Fabric8 can help to provide high availability in our qa and production environment and for things like monitoring.

Thanks
Souciance

**Comment by jstrachan** [comment]
BTW for questions on JBoss Fuse you're best off using the forum
https://developer.jboss.org/en/products/fuse

or support
https://access.redhat.com/

or the JIRA for JBoss Fuse is
https://issues.jboss.org/projects/ENTESB

**Comment by jstrachan** [comment]
FWIW there's a link to the new FAQ here: http://fabric8.io/guide/faqFuse.html
