### ISSUE TITLE
the Create Project wizard should allow importing from an existing gogs repository

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4787]
once the project is in gogs, we've got the forge `devops-edit` project; so we just need a UI that folks can pick the project to import and it can then run the `devops edit` UI on it to create the project / jenkins build et al inside OpenShift

**Comment by davsclaus** [comment]
@jstrachan is this possible now? Didnt you mention something about this yesterday

**Comment by jstrachan** [comment]
yes - thanks, its sorted now
