### ISSUE TITLE
README documentation very out of date

### ISSUE THREAD

**Issue by hotmeatballsoup** [fabric8io/fabric8#4799]
The following snippet is from your kubernetes-api README:

    KubernetesFactory kubeFactory = new KubernetesFactory();
    Kubernetes kube = kubeFactory.createKubernetes();
    PodListSchema pods = kube.getPods();

But in reality, `KubernetesFactory` and those other classes are completely missing from the `kubernetes-api` JAR. Please update your README to contain proper/current uses of the client jar.

**Comment by davsclaus** [comment]
@hotmeatballsoup what readme do you refer to? Can you provide a link?

The readme here seems up to date?
https://github.com/fabric8io/kubernetes-client

**Comment by davsclaus** [comment]
Ah yeah that snippet is outdated, let me try to fix up that
