### ISSUE TITLE
add build ID, jenkins build URL, git URL, git commit, git branch annotations by default to the generated RC so that we can provide better navigation

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4800]

**Comment by jimmidyson** [comment]
You could possibly put all this under one annotation as a blob of JSON?

**Comment by jstrachan** [comment]
could do - its a tricky one - i figured since 2 of them are just URLs that folks might wanna easily grab and link to in tools; using separate annotations was maybe a little easier to use

**Comment by davsclaus** [comment]
@jstrachan this causes the fabric8:json goal to not work in offline mode, see ticket #4852

**Comment by jstrachan** [comment]
the goal still works - its just a noisy log right?

**Comment by davsclaus** [comment]
yes so maybe there is a nicer way of knowing if we have a kubernetes connection or not.

**Comment by jstrachan** [comment]
I guess offline mode in maven maybe?

On 2 October 2015 at 10:48, Claus Ibsen <notifications@github.com> wrote:

> yes so maybe there is a nicer way of knowing if we have a kubernetes
> connection or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4800#issuecomment-144977487>.
>



-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration

**Comment by jstrachan** [comment]
though you could be offline but still have a local kubernetes install really

On 2 October 2015 at 11:07, James Strachan <james.strachan@gmail.com> wrote:

> I guess offline mode in maven maybe?
>
> On 2 October 2015 at 10:48, Claus Ibsen <notifications@github.com> wrote:
>
>> yes so maybe there is a nicer way of knowing if we have a kubernetes
>> connection or not.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fabric8io/fabric8/issues/4800#issuecomment-144977487>
>> .
>>
>
>
>
> --
> James
> -------
> Red Hat
>
> Twitter: @jstrachan
> Email: james.strachan@gmail.com
> Medium: https://medium.com/@jstrachan/
> Blog: http://macstrac.blogspot.com/
>
> fabric8: http:/ <http://fusesource.com/>/fabric8.io/
> hawtio: http:/ <http://fusesource.com/>/hawt.io/
>
> Open Source DevOps and Integration
>



-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration

**Comment by jstrachan** [comment]
FWIW now we silently ignore the warnings if JENKINS_HOME is not defined. (you can override the env var used to detect a CI / CD build along with enabling/disabling warnings too
