### ISSUE TITLE
Link to quickstarts is not longer correct

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4809]
This `https://github.com/fabric8io/fabric8/blob/master/docs/quickstarts.md` page refers to wrong link for the quickstarts

Example for karaf -> https://github.com/fabric8io/fabric8/tree/master/quickstarts/karaf

**Comment by davsclaus** [comment]
I think @rhuss fixed up the quickstarts today, but there may be some links in the doc somewhere.

@cmoulliard do you remember where you found that broken link?

**Comment by cmoulliard** [comment]
@davsclaus Updated issue with the correct link of the md page
