### ISSUE TITLE
Origin 1.0.6: cannnot login to fabric8 console

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4811]
Try here:

http://fabric8.fabric8.osecloud.com, will leave it up for a bit

Seems to authenticate and then redirect to authentication page

**Comment by davsclaus** [comment]
Yeah the vagrant is still using 1.0.5, i wonder if @jimmidyson or @rawlingsj are aware of any problems ahead of OS3 upgrade?

**Comment by jimmidyson** [comment]
I think @ceposta & I worked out that it was related to #4810 wasn't it?

**Comment by jimmidyson** [comment]
@davsclaus Would you be able to update the openshift version in the vagrantfile & verify it works for you locally?

**Comment by davsclaus** [comment]
ok checking now, its installing with 1.0.6

**Comment by davsclaus** [comment]
seems okay from my camel ipaas testing with 1.0.6. @rawlingsj will give the CI/CD story a test too

**Comment by davsclaus** [comment]
we have upgraded and haven't seen problems with this since.
