### ISSUE TITLE
create the gerrit repo & sync if the code review is enabled in ProjectConfig (fabric8.yaml)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4825]
e.g. this code...
https://github.com/jstrachan/fabric8/blob/cdelivery/components/fabric8-devops-connector/src/main/java/io/fabric8/devops/connector/DevOpsConnector.java#L301-301

**Comment by cmoulliard** [comment]
Code to be integrated is : https://github.com/jstrachan/fabric8/blob/cdelivery/fabric8-maven-plugin/src/main/java/io/fabric8/maven/CreateGerritRepoMojo.java#L92-92

**Comment by jstrachan** [comment]
@cmoulliard does this work now?

**Comment by jstrachan** [comment]
@cmoulliard I'm guessing we can close this for now - let me know if not and we can always reopen
