### ISSUE TITLE
Move "Create Project" button from default workspace to home page

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4856]
The "create project" button is available under the screen of the default workspace 

![screenshot 2015-10-02 13 06 43](https://cloud.githubusercontent.com/assets/463790/10245335/cebb7144-6906-11e5-87f2-15316b32ee7f.png)
As this button is mainly used to create `DevOps Project` with 2 workspaces (staging, prod), we should move it to this screen (= home screen) and rename it to "Create DevOps" Project. 

![screenshot 2015-10-02 13 06 31](https://cloud.githubusercontent.com/assets/463790/10245317/af09f38e-6906-11e5-8165-439b43839821.png)

**Comment by jstrachan** [comment]
don't really grok this. Workspaces (OpenShift namespace) != Project (git repo + source code).

Depending on the choices in the New Project wizard there may or may not be workspaces created. I don't see that as a reason to add a Create Project to the workspaces page - afterall you must be inside  workspace first anyway
