### ISSUE TITLE
oauth fails with fabric8 on openshift enterprise v3 - need to allow CORS in master, helpful advice for others

### ISSUE THREAD

**Issue by eformat** [fabric8io/fabric8#4866]
useful tips if you try to run fabric8 on openshift enterprise v3 and cannot login (you get redirected back to the login console @ OAUTH_AUTHORIZE_URI)

(1) make sure your admin has a login via web console e.g. if using HTPasswdPasswordIdentityProvider in OSEv3

htpasswd -b /etc/openshift-passwd admin admin

(2) make sure you install fabric8 with the right domain for you:

gofabric8 deploy -d example.com -y

(3) if you try to login to the fabric8 console take a look at the chrome debug console. if you see CORS warnings/errors:

XMLHttpRequest cannot load https://example.com:8443/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fabric8.example.com' is therefore not allowed access.

(4) you need to set CORS on ose-master,  add domain - or be more permissive for all domains set it to:

-- vi  /etc/openshift/master/master-config.yaml
corsAllowedOrigins:
  - ".*"

-- restart master
systemctl restart openshift-master

you should now be able to login to http://fabric8.example.com

**Comment by hodrigohamalho** [comment]
up

**Comment by jstrachan** [comment]
I've just added a troubleshooting section to the getting started docs with all this information https://github.com/jstrachan/fabric8/blob/fixes/docs/getStarted/openshift.md#troubleshooting it should show up in the website very soon. Many thanks for all this!

**Comment by sbadakhc** [comment]
Also if your using /etc/hosts file for name resolution make sure you have the domain in the list of hosts...e.g:
```
192.168.122.100 **example.com** master.example.com fabric8.example.com fabric8-master.example.com docker-registry.example.com gogs.example.com nexus.example.com jenkins.example.com
```
