### ISSUE TITLE
Blocking issue : letschat web server is not working anymore - 2.2.40

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4869]
I don't see errors within the log of the pod of letschat but we can access's the web server `letschat.vagrant.f8` since 2.2.40

```
[vagrant@vagrant ~]$ docker ps | grep fabric8/lets-chat
186a3507a303        fabric8/lets-chat                           "npm start"              18 minutes ago      Up 18 minutes                           k8s_letschat.bdbd0aba_letschat-hudg0_default_208655fc-69ff-11e5-8b5c-080027a295a0_75993d1f
[vagrant@vagrant ~]$ docker logs 186a3507a303

> lets-chat@0.4.0 prestart /usr/src/app
> migroose

using default username: fabric8
Lets create a default user for id fabric8 and email: fabric8-admin@googlegroups.com
Count not find user: fabric8 so cannot create any default rooms
Created user fabric8

> lets-chat@0.4.0 start /usr/src/app
> node app.js

using default username: fabric8
Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm install node-stringprep`

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.0

Found user for username: fabric8 already so not creating a default user
Lets create a room id fabric8_default
Created room fabric8_default
```

**Comment by rawlingsj** [comment]
I've just tested Lets Chat with 2.2.40 successfully with no issues.  

On one of the mailing list emails you sent @cmoulliard  you mentioned you did a vagrant reload, this may have confused things with openshift if you were connecting to a different wifi (just a guess as we have little else to go on).

If you are still having issues a bit more info is needed including what http error code you get if any, logs from the router, check the service is running and if you can curl the lets chat endpoint from within the vagrant image using the service ip.  These things will help narrow the issue down but like I say it all seems to work fine after my test this evening.

**Comment by cmoulliard** [comment]
Letschat is back after recreating this morning a new Vagrant Machine
