### ISSUE TITLE
[console] Unable to resize RC's 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4870]
No pop up is shown after trying to resize RC

![bhfqyi](https://cloud.githubusercontent.com/assets/1457180/10269983/7872fc9e-6adc-11e5-9ce7-98bff8a11da4.gif)

**Comment by davsclaus** [comment]
Oh I could resize last week with my camel quickstarts.

**Comment by davsclaus** [comment]
Yep got the same problem now with lates 2.2.40 release. It worked last week. I guess there has been an update to the web console causing this problem.

**Comment by davsclaus** [comment]
I dont see anything in the javascript log

**Comment by jstrachan** [comment]
this has been fixed in the new fabric8-console image - it was a boostrap issue

**Comment by davsclaus** [comment]
thanks james
