### ISSUE TITLE
Hawt/Jolokia of a pod created for camel-cdi example is not accessible 

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4875]
Version used : 2.2.240

There is still an issue when I try to access the hawt/jolokia console of a container

<img width="1407" alt="screenshot 2015-10-05 15 29 55" src="https://cloud.githubusercontent.com/assets/463790/10281926/16fff7f4-6b78-11e5-9855-1be6a876493b.png">

```
[15:33:27] <ro14nd>	A 503 indicates more an error of the API proxy then on the Jolokia side. Maybe the pod is down ?
[15:33:50] <ch007m>	There is a forbidden access --> https://www.dropbox.com/s/qe8779juk1zpk0v/Screenshot%202015-10-05%2015.33.36.png?dl=0

[15:36:55] <jdyson>	gashcrumb, jstrachan, that second screenshot (https://www.dropbox.com/s/wmslk3un08jl3ek/Screenshot%202015-10-05%2015.29.55.png?dl=0) shows a 404 with a typo in persistentvolumes
[15:37:45] <+gashcrumb>	jdyson: good catch :-)
```

**Comment by gashcrumb** [comment]
Regardless of the typo that 404 error has nothing to do with the jolokia connection.  If you're getting a 503 from the proxy when trying to connect to jolokia the first thing I'd suggest checking is that the app actually started up successfully with `oc logs <pod ID>`

**Comment by cmoulliard** [comment]
There is nothing within the log of the pod. The log is empty. Interesting.

**Comment by jimmidyson** [comment]
So looks like the pod hasn't started properly? `oc describe pod <podid>` show anything?

**Comment by cmoulliard** [comment]
Forget my previous comment. I found error

```oc project gogsadmin-dummy-prod
Now using project "gogsadmin-dummy-prod" on server "https://localhost:8443".

[vagrant@vagrant ~]$ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
dummy-kmhvs   1/1       Running   12         22m

[vagrant@vagrant ~]$ oc logs dummy-kmhvs
Error: Invalid or corrupt jarfile /maven/
```

**Comment by rhuss** [comment]
Well '/maven' is obviously not  a jar file. The example you are using is this --> https://github.com/fabric8io/ipaas-quickstarts/tree/master/quickstart/cdi/camel ?

**Comment by cmoulliard** [comment]
Yes. I tried to use the camel cdi quickstart example ('io.fabric8.archetypes:cdi-camel-archetype:2.2.40')

**Comment by rhuss** [comment]
Have you checked in the project somewhere ? Or could gist the pom ?

**Comment by cmoulliard** [comment]
This problem is not specific to camel cdi as I have also the same issue for cdi-cxf quickstart example --> "Error: Invalid or corrupt jarfile /maven/"

**Comment by rhuss** [comment]
Did you create it via 'mvn archetyp:generate' or via the UI ?

**Comment by rhuss** [comment]
Using it on the command line works for me 'mvn clean install docker:build docker:start' I guess, that when creating it from the UI, there are different environment variables set (and hence confuses the startup script ?) // @jstrachan

**Comment by cmoulliard** [comment]
Project has been created from a "Create Project" - "Cd Pipeline" & build
with jenkins job based on the Groovy script

On Mon, Oct 5, 2015 at 4:41 PM, Roland Huß <notifications@github.com> wrote:

> Using it on the command line works for me 'mvn clean install docker:build
> docker:start' I guess, that when creating it from the UI, there are
> different environment variables set (and hence confuses the startup script
> ?) // @jstrachan <https://github.com/jstrachan>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/4875#issuecomment-145550518>.
>



-- 
Charles Moulliard
Apache Committer / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by davsclaus** [comment]
it worked today for the camel-servlet quickstart.

**Comment by cmoulliard** [comment]
Do we have an idea about this problem and how to fix it ?

**Comment by cmoulliard** [comment]
I confirm. camel war servlet is working.

**Comment by davsclaus** [comment]
We are still waiting for a new OS3 release. 1.0.7 should have a fix for this, and it requires using jolokia 1.3.2 also.

**Comment by davsclaus** [comment]
1.0.7 is out
