### ISSUE TITLE
hawt-app plugin readme is outdated

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4949]
See
https://github.com/fabric8io/fabric8/tree/master/hawt-app-maven-plugin#usage

it refers to jboss name. It should be updated to fabric8 naming.

@rhuss wonder if there is other changes needed? Maybe you wanna take a look and fix this

**Comment by rhuss** [comment]
@davsclaus Yeah, I overseen that. The properties has been already adapted, but I will check again.
