### ISSUE TITLE
Develop Create Project Fails due to logon failure

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#5027]
Just installed the latest distribution using vagrant. All appeared ok, saw the new console entry point with the 2 perspectives. Selected Develop then openshift then +Create Project. The gogsadmin user is defaulted but the default password 'RedHat$1' as per documentation isn't accepted: http://fabric8.io/guide/cdelivery.html

**Comment by stevef1uk** [comment]
Ok. Just realised that none of the cdelivery pods are running by default so the result above is expected.

**Comment by jstrachan** [comment]
Yeah - this is similar to #5028 - I should be able to fix it to make it more clear that the fabric8-forge pod is not running/started yet etc

**Comment by stevef1uk** [comment]
I started the c-delivery services and still was unable to login though

**Comment by oscerd** [comment]
@stevef1uk It seems there are some problems with the gogs docker image.

I have to pull the image directly

```
docker pull fabric8/gogs:0.6.1
```

If you get the following error

```
Repository docker.io/fabric8/gogs already being pulled by another client. Waiting.
```

then do

```
vagrant ssh
```

and kill the docker daemon. It will restart automatically.

After these operations and after waiting for the Docker images pull I see all the cd-pipeline pods running

```
$ oc get pods 
NAME                                 READY     STATUS    RESTARTS   AGE
docker-registry-1-tvl4q              1/1       Running   2          1d
fabric8-forge-06gjq                  1/1       Running   0          13m
fabric8-yt4hk                        1/1       Running   2          1d
fluentd-elasticsearch-172.28.128.4   1/1       Running   2          1d
gerrit-hjnt8                         1/1       Running   0          13m
gogs-jwbmv                           1/1       Running   0          13m
jenkins-mwofh                        1/1       Running   0          13m
jenkins-swarm-client-yljyq           1/1       Running   0          13m
nexus-4rmjr                          1/1       Running   0          13m
router-1-yqnue                       1/1       Running   2          1d
sonarqube-nyor1                      2/2       Running   0          13m
```

Hope this help.

Andrea

**Comment by jstrachan** [comment]
@stevef1uk as per #5028 the next release will list the required dependencies of `cd-pipeline` before showing the login page; we've also got a readiness check in fabric8-forge so we only let the UI show the login page when we know gogs, jenkins and farbic8-forge pods are all started and in the ready state.

Thats not to say that your environment will work though I'm afraid. A few folks have reported issues that even if everything really is started (it takes fabric8-forge about a minute to be properly ready) then the login fails if DNS isn't working such that the fabric8-forge pod can communicate with the public host name of the gogs service.

I suspect looking at the logs of the `fabric8-forge` pod should show the reason for the login failure; either that or the JavaScript console of the browser.

At least with the next release; it should alert users to not even try to login until everything has properly started up correctly

**Comment by stevef1uk** [comment]
James, for the first time ever I have deleted my vagrant container , issued vagrant up and then run the c-delivery services. They have all started and the CPU utilisation of my MBA is ok and I even have about 0.5GB of RAM free! I have been able to run the Create Project wizard but I am not sure what to enter in the fields so defaulted most. I can see the repository has been created and even access the Jenkins console too. The only remaining fly in the ointment is that within my environments there are no apps visible and no Jenkins jobs have been created. It would be good to document suitable defaults.

**Comment by jstrachan** [comment]
@stevef1uk glad you got so far!!! :) 

I just raised and fixed this issue btw #5048 in case you were hitting it; a few folks have struggled logging in and fabric8-forge not being able to access gogs - though it looks like you got past that one!

Also the UI now asks you to run the CD Pipeline & lets you know what pods its waiting for to start before it can use the Create Project wizard etc; so its a little easier to use now I think.

I've just added a default Pipeline flow so you don't have to worry about that bit either. (Its on my list to make a much nicer UI to help you browse through the available flows and see their docs etc).

So when the new release is out in a few hours time you'll just have to:

* Pick a name of the project

* Choose the Type of project; I tend to choose the Type of `From Archetype Catalog` and then the archetype ``cdi-camel-archetype` but feel free to just use a Type of `Java Web Application (WAR)'  a WAR if you like.

Other than that you should be able to use the default values now in the next release and it should generate a CD Pipeline etc.

Note that currently no jenkins job is created if you don't pick a Jenkins workflow script (called 'flow' in the current release - I've renamed it to `pipeline` to be more clear) which is on the last page of the wizard. So maybe thats the reason for the lack of jenkins job?

**Comment by jstrachan** [comment]
hopefully the new release that just went out helps on this. I did find a bit of a bug in the logic for showing the "Run CD Pipeline" versus "Waiting for it to start" mind you ;) so the next release is gonna be better! :)

**Comment by jstrachan** [comment]
I'm hoping this one is now fixed - let us know if not and we can reopen

**Comment by stevef1uk** [comment]
James. Yes, it is working for me now. You are a star! Also, it seems 8GB is enough to run this on my MBA. I was thinking that I needed to upgrade to 16GB but that isn't necessary. Great stuff!
I think the awesome phrase you use on the video demo of this capability is well deserved.

**Comment by jstrachan** [comment]
who-hooo!!!! Thanks for letting us know. Now to add more awesome....

**Comment by stevef1uk** [comment]
I wasn't able to see it complete. It was still at the Canary stage when I needed to suspend the vagrant VM so as to have enough memory to run my work VM ;-)
Out of curiosity, if I wanted to refresh my set-up is there a less network intensive way than vagrant destroy, git pull, vagrant up? Only at home do I have access to high speed broadband.

**Comment by jstrachan** [comment]
st
