### ISSUE TITLE
shouldn't have "Create project" if cd-app or fabric8-forge is not installed

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#5028]
get's weird when seeing the errors not knowing (even if knowing) that fabric8-forge and the cd app should be installed and i get "cannot login" errors when trying to create a new project

**Comment by jstrachan** [comment]
agreed!

I want to add a readiness check to fabric8-forge so we know when its really started up.

Plus the Create Project page shouldn't allow you to click the `Create Java Project with Forge` button if its not started.

BTW we need an `Import Project` page too which doesn't need Fabric8 Forge which can go on that top level page; we might also have some other options (e.g. creating an OpenShift app thingy, or maybe a Yeoman wizard for node apps or something).

**Comment by jimmidyson** [comment]
How about an option in the console to deploy forge if it's not already deployed?

**Comment by jstrachan** [comment]
Yeah! Lemme try add something like that...

**Comment by jstrachan** [comment]
BTW fabric8-forge has a readiness check now too; so the Create Page only shows the button to create a project if gogs + jenkins + fabric8-forge all have ready pods. If the RCs are not even created it adds a `Run cd pipeline` button
