### ISSUE TITLE
fabric8.yml file structure

### ISSUE THREAD

**Issue by moix** [fabric8io/fabric8#5040]
Hi,

I'm adding some of the fabric8 functionality via the maven plugin to a project and I need to create the fabric8.yml file but I'm not able to find documentation about its structure. Sorry if it is out there but I dont fint it; the only reference about it is in the documentation: http://fabric8.io/guide/fabric8YmlFile.html:
* the fabric8.yml file directly using a text editor in source control

but what's the structure of the file and where should it be located in my project?

Thanks!

**Comment by jstrachan** [comment]
Sorry for the lack of docs. If you want to programatically generate the file, there's a little library load/save it...
https://github.com/fabric8io/fabric8/tree/master/components/fabric8-devops
```
ProjectConfig config = ProjectConfigs.loadFromFolder(someFolder)
```

Or to generate

```
ProjectConfig config = new ProjectConfig();
config.setXXX(yyy);
ProjectConfigs.saveToFolder(someDir, config, true);
```

The other option is to use the `devops-edit` CLI command in JBoss Forge or update a project's settings in the web console. (The Settings button is a little bit hidden right now ;) - its on the Detail tab of a project).

If you've an existing project that you'd like to edit the fabric8.yml file for; we should have an import project UI soon so you can just import an existing project via git and then use the `devops-edit` CLI / Forge command / web console to view/edit its contents

**Comment by moix** [comment]
Alright thanks, I'm checking it.
