### ISSUE TITLE
Can't connect to a container - terminal -insufficient privilege

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#5043]
The new pod screen proposes a button to open a terminal for a fod. But when we click on it, we get within the terminal this message "Could not connect to the container. Do you have sufficient privilege". Is there a workaround ?

![screenshot 2015-10-20 09 15 58](https://cloud.githubusercontent.com/assets/463790/10600462/3899f20e-770b-11e5-9003-bb1a4dd3c2ff.png)

**Comment by jstrachan** [comment]
FWIW we're waiting for the next release of OpenShift - e.g. 1.0.7 for this to be enabled in the back end

**Comment by davsclaus** [comment]
1.0.7 is now out
