### ISSUE TITLE
fabric8-forge should use the internal address for communicating with gogs by default to avoid possible DNS errors 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5048]
some folks have experienced DNS issues of the fabric8-forge pod not being able to communicate using the external host name of the gogs pod.

Lets try reuse the internal address where possible in the fabric8-forge pod instead!

**Comment by jimmidyson** [comment]
It should use the internal address anyway to remain in-cluster comms rather than potentially using external networks which may incur costs on public cloud.

**Comment by jstrachan** [comment]
agreed
