### ISSUE TITLE
pushing to private docker registry when running in the cluster

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5070]
I'm trying to push images to a private docker registry that is hosted in the same namespace as the jenkins workflow job.  The image needs to be available to be pulled from this regsitry but from other namespaces (like a prod environment).

Pushing from outside the cluster works via an openshift route..
__WORKS__
```
mvn docker:push -Ddocker.registryPrefix=fabric8-docker-registry.vagrant.f8:80/
```

Using the service env vars in the workflow script work but this is not available between namespaces..
__WORKS__
```
mvn docker:push -Ddocker.registryPrefix=${env.FABRIC8_DOCKER_REGISTRY_SERVICE_HOST}:${env.FABRIC8_DOCKER_REGISTRY_SERVICE_PORT}/
```

Pushing using the service DNS fails.. if I add the port in the docker registry prefix as the examples above I get this...
__ERROR__
```
mvn docker:push -Ddocker.registryPrefix=fabric8-docker-registry:80/fabric8/jr-test/

[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ jr-test ---
[INFO] DOCKER> ... The push refers to a repository [fabric8-docker-registry:80/fabric8/jr-test] (len: 1)
[ERROR] DOCKER> unable to ping registry endpoint https://fabric8-docker-registry:80/v0/
v2 ping attempt failed with error: Get https://fabric8-docker-registry:80/v2/: dial tcp: lookup fabric8-docker-registry: no such host
 v1 ping attempt failed with error: Get https://fabric8-docker-registry:80/v1/_ping: dial tcp: lookup fabric8-docker-registry: no such host 
```

If I don't set the port in the docker registry prefix I get a 301
__ERROR__
```
mvn docker:push -Ddocker.registryPrefix=fabric8-docker-registry/fabric8/jr-test/
 
[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ jr-test ---
[ERROR] DOCKER>  (Moved Permanently: 301)
```

Anyone got any ideas of how I can push / pull from a private docker registry between namespaces (environments)?

**Comment by rawlingsj** [comment]
Ah I think the problem is that its the docker daemon that is mounted into the swarm pod that cant resolve the DNS service.

So in the third option above and also repeated below that's what there's `no such host `
```
mvn docker:push -Ddocker.registryPrefix=fabric8-docker-registry:80/fabric8/jr-test/

[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ jr-test ---
[INFO] DOCKER> ... The push refers to a repository [fabric8-docker-registry:80/fabric8/jr-test] (len: 1)
[ERROR] DOCKER> unable to ping registry endpoint https://fabric8-docker-registry:80/v0/
v2 ping attempt failed with error: Get https://fabric8-docker-registry:80/v2/: dial tcp: lookup fabric8-docker-registry: no such host
 v1 ping attempt failed with error: Get https://fabric8-docker-registry:80/v1/_ping: dial tcp: lookup fabric8-docker-registry: no such host 
```

**Comment by rawlingsj** [comment]
So I should try the openshift route instead

**Comment by rawlingsj** [comment]
Yay it works!

So the issue was I was trying to use the kubernetes service DNS to push images to the provate registry, but because the docker daemon is mounted into the swarm pod it is actually run on the host, therefore it cant resolve the kubernetes service using dns and instead has to use the ha proxy.

I think that's all correct ;)

**Comment by rhuss** [comment]
Sorry, being late. Good to know that you found it :)
