### ISSUE TITLE
kubernetes vagrant image documentation issue (says landrush but code snippet is hostmanager)

### ISSUE THREAD

**Issue by petenorth** [fabric8io/fabric8#5079]
On 

https://github.com/fabric8io/fabric8-installer/blob/master/vagrant/kubernetes/ReadMe.md

It has

Linux

* Install the Vagrant plugin landrush

    vagrant plugin install vagrant-hostmanager

Should it not be vagrant-landrush?

**Comment by davsclaus** [comment]
I think @rawlingsj have fixed this now

**Comment by rawlingsj** [comment]
Ah I didn't realise there were the same steps on the kubernetes guide, I updated the openshift https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/openshift#linux

I'll sort it now though.

**Comment by rawlingsj** [comment]
thanks for pointing out @petenorth, readme is now updated https://github.com/fabric8io/fabric8-installer/blob/master/vagrant/kubernetes/ReadMe.md#linux
