### ISSUE TITLE
gerrit pod continually restarts, error '/root/.ssh/id_rsa' are the same file

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5098]
On a clustered openshift using a new namespace I've just deployed the latest release and see the issue that a couple have people reported on IRC recently..

```
➜  fabric8-devops git:(master) ✗ oc get pods
NAME                            READY     REASON    RESTARTS   AGE
fabric8-docker-registry-dxfd8   1/1       Running   0          4m
fabric8-forge-lw9lo             1/1       Running   0          4m
fabric8-hf9nz                   1/1       Running   0          5m
gerrit-zosgg                    0/1       Running   11         4m
gogs-pfdhm                      1/1       Running   0          4m
jenkins-swarm-client-2v2mc      1/1       Running   0          4m
jenkins-zahxh                   1/1       Running   0          4m
nexus-a8nk2                     1/1       Running   0          4m
➜  fabric8-devops git:(master) ✗ oc logs gerrit-zosgg
/root/.ssh/id_rsa
mv: '/root/.ssh/id_rsa' and '/root/.ssh/id_rsa' are the same file
```

@cmoulliard @christian-posta does this mean anything to you guys?

**Comment by tdcox** [comment]
Yup, confirmed here.

**Comment by cmoulliard** [comment]
I will have a look. Question : Is the process to create a docker container different when we use a cluster and/or new namespace ?

**Comment by sbadakhc** [comment]
Can you point me to the process you're using to create these images?  I can help investigate or test fixes.

**Comment by jstrachan** [comment]
@sbadakhc thanks for the offer! Here's the project that creates the docker image for gerrit:
https://github.com/fabric8io/docker-gerrit

I guess the bit thats failing is: 
https://github.com/fabric8io/docker-gerrit/blob/master/bin/conf-and-run-gerrit.sh#L13

maybe we just need to check that we don't  run that `mv` command if `$file` and `$new` are the same?

**Comment by sbadakhc** [comment]
@jstrachan you're welcome and thanks.  I will investigate and get back to you.

**Comment by sbadakhc** [comment]
I added a test to see if the file exists and to replace it if it does.  I think this is simpler than to test to see if they are the same.  I'm also working on the assumption that new file is the safe bet in this circumstance which I'm not sure about!  Pull request made.

**Comment by jstrachan** [comment]
it looks like the latest PR on gerrit doesn't quite work:
```
/home/gerrit/bin/conf-and-run-gerrit.sh: line 14: [: missing `]'
id files identical
/root/.ssh/id_rsa
cp: cannot stat '/root/.ssh/id_rsa': No such file or directory
```

**Comment by jstrachan** [comment]
have tried to fix it; will see if the new image is any better...
https://github.com/fabric8io/docker-gerrit/commit/1c0653e395592225bcf4fb4761082fc04dd68fe9

**Comment by jstrachan** [comment]
the latest image now startups fine for me on vagrant. lets see if the next release works on OpenStack too

**Comment by rawlingsj** [comment]
this is fixed now
