### ISSUE TITLE
Unable to connect to Kubernetes cluster over http

### ISSUE THREAD

**Issue by shruti-palshikar** [fabric8io/fabric8#5113]
I am using the fabric8 java API to connect to a remote kubernetes cluster from java. However it fails with the following exception

    DEBUG [2015-10-26 17:11:11,270] io.fabric8.kubernetes.api.KubernetesHelper: Address does not appear to be SSL-enabled - falling back to http
    ! javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

How do I make sure that java connects to http and not https? I am using Dropwizard as the http server. Is this a property taht can be set for this server? Or this is something that needs to be configured on the kubernetes master?

This is how I create the connection object

		

`KubernetesClient kubernetes = new KubernetesClient (new KubernetesFactory(MASTER))`;

    where MASTER = "http://myMaster:8080";

**Comment by davsclaus** [comment]
Can you tell more about your kubernetes cluster? I dont understand how dropwizard comes into the picture?

You need a kubernetes platform such as Google Cloud Platform, OpenShift3 etc.

**Comment by jimmidyson** [comment]
If you're just interested in the fabric8 kubernetes client then you shutoff use the one at https://github.com/fabric8io/kubernetes-client. The one I think you're using is the old one that we rewrote.
