### ISSUE TITLE
enabling fabric8.combineDependencies only include dependencies

### ISSUE THREAD

**Issue by moix** [fabric8io/fabric8#5119]
I'm trying to configure fabric8-maven-plugin so json goal generates the kubernetes.json.
Apart from the replication controller and the service auto-generated, I need to include additional kubernetes rc and services this project depends on, so I was checking the _fabric8.combineDependencies_ option documented at http://fabric8.io/guide/mavenFabric8Json.html#combining-json-files.

If I understand, this option merge all dependencies with classifier=kubernetes and type=json with the generated json, but when I enable it, only dependencies appear, not the generated json

Is that behaviour correct? Am I doing something wrong?

**Comment by moix** [comment]
Actually now I started trying with _fabric8.extra.json_ and behaviour is weird as well, log says it does:

```
[INFO] Combining generated json /home/moix/dev/project/target/classes/kubernetes.json with extra json /home/moix/dev/project/src/main/fabric8/kubernetes-extra.json
[INFO] Saved as :/home/moix/dev/project/target/classes/kubernetes.json
```

but when I check combined json it only contains the generated, not the extra, any idea?

**Comment by davsclaus** [comment]
For services you can add those in the `<properties>` section.

Btw what is that extra RC you need?

And yeah there could be a bug in the maven plugin. We are hardly using those extra json files anymore, as you can also describe the kube json in java code with a nice dsl.

For example
https://github.com/fabric8io/fabric8-devops/blob/master/jenkins/src/main/java/io/fabric8/apps/jenkins/JenkinsModelProcessor.java

**Comment by moix** [comment]
Thanks @davsclaus, yes yesterday I did lot of tests and think there must be a bug probably around _KubernetesHelper.combineJson_

I saw the DSL way but thought was easier to try first extra json.

The project I'm working need a database so the extra replication controller and service is for it.

**Comment by davsclaus** [comment]
You are sure welcome to help fix the bug, we love contributions.

**Comment by davsclaus** [comment]
Thanks for the PR that fixed this
https://github.com/fabric8io/fabric8/commit/4111f93554879c03b0ba11e40af164f8c5660417

**Comment by moix** [comment]
no problem, thanks for the project :)

By the way, still pending to fix _fabric8.combineDependencies_, I though the same fix will apply but I tested and still doesn't include the generated json. Will try to take a look.
