### ISSUE TITLE
OAuth issue under OpenShift 1.0.7

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8#5181]
Fabric8 console appears to be inaccessible under 1.0.7. I see the following error when redirected by oauth:

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://fabric8.fuse.kill-9.co.uk/"}

The route appears to exist.

**Comment by tdcox** [comment]
It actually looks like it flashes up the console menu bar for a second, before being redirected to an error page.

**Comment by jstrachan** [comment]
just been chatting on IRC about this one - think its a bad OAuthClient configuration

**Comment by jstrachan** [comment]
looks like using -domain rather than --domain was the issue

**Comment by tdcox** [comment]
Yeah, thanks Evernote! They are now replacing double quotes with right and left speechmarks and double -- with a single long dash that reverts to a single - when copied and pasted out.
