### ISSUE TITLE
fabric8 deploy assumptions

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5204]
Now that we've had a few openshift and kubernetes installations setup we are getting feedback that the fabric8 deploy makes a few assumptions that dont reflect typical setups.

Lets try to capture these assumptions here.

1. We could have a master domain setup for our api server but a different domain record used when running apps.

For example when running the fabric8 console the oauth config should point to the openshift api server on demo.master.fabric8.io but when creating the route for the console it should be fabric8.apps.fabric8.io.

@christian-posta @tdcox is that correct and do you have any more?

**Comment by tdcox** [comment]
Ansible scripting examples for installing OpenShift have defaults that presuppose a master with domain starting master.<my domain name> and a default subdomain of apps.<my domain name> which can cause some issues with OAuth for apps in fabric8.

https://github.com/christian-posta/openshift-terraform-ansible/blob/master/example-inventory

**Comment by jstrachan** [comment]
we can now specify apiserver being different to domain now. Also we replace the domain in all the templates on `gofabric8 deploy` so I think these issues are fixed? Maybe lets raise new issues if there's anything missing
