### ISSUE TITLE
parameterize gofabric8 for installation on OpenShift w/out assumptions about where the master/apps/ports live

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#5219]
When we deploy openshift3, i've always seen master and apps domain live at different places, i.e.:

master.osecloud.com for the master node, and *.apps.osecloud.com for the apps.

So this means a `gofabric8 deploy --domain=apps.osecloud.com` will install correctly, but when you try to login to the fabric8 console, the oauth redirect will take you to https://apps.osecloud.com which is not where the master is. We can work around this by creating the deployment with `gofabric8 deploy --domain=master.osecloud.com` and then delete the actual routes and create them again with the right apps sub domain `gofabric8 routes --domain=apps.osecloud.com'

On the other hand, if you have your oauth/master/kube api living at port 443, then even with above workaround, the oauth client will redirect you to a master with port 8443, which would be wrong in that setup. would be nice to be able to configure exactly where the master/app subdomain is and where the master port is from `gofabric8 deploy`

**Comment by christian-posta** [comment]
At least need to parameterize the port here:

https://github.com/jstrachan/fabric8-devops/blob/e31cb4d93fc2e5dcf4e2ea67bf9567542d3d8b73/console/src/main/fabric8/env.properties#L5-L5

**Comment by jstrachan** [comment]
the port is now parameterizable
https://github.com/fabric8io/fabric8-console/blob/master/app-console/src/main/fabric8/templateParameters.properties#L11

as is the APISERVER too
https://github.com/fabric8io/fabric8-console/blob/master/app-console/src/main/fabric8/env.properties#L6
https://github.com/fabric8io/fabric8-console/blob/master/app-console/src/main/fabric8/templateParameters.properties#L8

I guess this is now fixed?

**Comment by jstrachan** [comment]
@christian-posta gonna close this as I think its all fixed now; lemme know if not and we can reopen
