### ISSUE TITLE
Upgrade Kubernetes-model to 1.0.35

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#5239]
Hi,

I see Kubernetes-model 1.0.35 has been released. In Fabric8 dependency we're still using 1.0.34. 

Can we upgrade or there are problems? I see Kubernetes-model uses Openshift 1.0.8 too..

**Comment by oscerd** [comment]
I think we can, anyway I'll wait a confirm :-)

**Comment by davsclaus** [comment]
yeah I think upgrade is fine. @iocanel do you see any problem not updating fabric8 to latest versions of model/client etc.

**Comment by iocanel** [comment]
No, but please upgrade kubernetes-client first so that all three are aligned.

**Comment by jimmidyson** [comment]
Is anything using the model directly rather than as a transitive dep of client?

**Comment by oscerd** [comment]
Actually the client is on the latest version. I'll check if there are components using the model directly.

**Comment by oscerd** [comment]
kubernetes-model.version is only in pom.xml file.

**Comment by oscerd** [comment]
As @jimmidyson is suggesting here #5293 , I'll remove the kubernetes-model depedency
