### ISSUE TITLE
fabric8 getting started issues on GKE

### ISSUE THREAD

**Issue by loshkovskyi** [fabric8io/fabric8#5325]
Hello,

I'm using your guide http://fabric8.io/guide/getStarted/gke.html to get started with fabric8 on a self-managed Kubernetes cluster.  
There are a few issues in the guide. For example, this command produces error 404:

```
kc create -f http://central.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.28/console-kubernetes-2.2.28-kubernetes.json
```

And link to the console documentation in the guide http://fabric8.io/guide/getStarted/console.html gives the error 404 as well.

I'm unsure which correct latest version to use. From the sources, it looks to be `2.2.65` but I suppose it's for Kubernetes `v1.1` or higher (I'm using `v1.0`).

The latest JSON that I have found is the following:

```
kubectl create -f http://central.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.23.1/console-kubernetes-2.2.23.1-kubernetes.json
```

Which results in these errors:

```
kubectl get po
NAME              READY     STATUS    RESTARTS   AGE
fabric8-fgn06     0/1       API error (500): Cannot start container 764da99dd09795114eb4e2efbd14b997f9f0f00d51773a0e133c761afa0c445d: [8] System error: Unable to find user nobody
                  15        8m
templates-om9j5   0/1       API error (404): Cannot start container 8dd55af96142d3978f45e2edbe8960c5741ef583ab10dddacc442640a988bd08: [8] System error: no such file or directory
                  15        8m
```

I have not resolved these issues yet. But using correct version might help in this case. Just to confirm, my Kubernetes cluster is fully functional and I'm able to run various examples from the Kubernetes repository.

Thank you.

**Comment by davsclaus** [comment]
@rawlingsj was there some problems with the latest version of our console not working on GKE? I recall something about an older version was last known working a while back?

**Comment by rawlingsj** [comment]
Ah yeah there was but I think @gashcrumb took a look and the latest version was working.  The console has had a redesign so there was a bit of attention needed to make sure it ran as expected on vanilla kubernetes as well as openshift.

There's actually a new release happening at the moment and should be finished in the next couple of hours so we should try with that.  I'll update the issue and docs once the release is ready.

FWIW we should be able to use helm pretty soon to install the console so we can have a consistent way to install and upgrade on top of kubernetes.

**Comment by davsclaus** [comment]
yeah the helm is gonna rock

**Comment by loshkovskyi** [comment]
I don't use GKE, my setup is done with https://github.com/CiscoCloud/kubernetes-ansible
I thought fabric8 should work on a standalone Kubernetes cluster as well. Looking forward to test your latest release both on Kubernetes and OpenShift.
