### ISSUE TITLE
Security Contexts Missing on DevOps

### ISSUE THREAD

**Issue by sbadakhc** [fabric8io/fabric8#5334]
Hi I'm seeing the following error when deploying Fabric8 into new project "devops".   Browsing via the console I can see all of the pods have deployed except for gerrit, gerrit-ssh and nexus which are currently in a pulling state.  I was wondering what the implications of the error is?

I have attached my osev3 post installation routine which details the configuration steps I take as part of the deployment.  I could really use a second opinion with respect to best practice.

Thanks,
Sal.

[osev3-post-install.txt](https://github.com/fabric8io/fabric8/files/44516/osev3-post-install.txt)

```
Validating your OpenShift installation at https://master01.example.com:8443 in namespace devops

Service account...............................................................✔ 
Console.......................................................................✔ 
Router........................................................................✘ 
Templates.....................................................................✔ 
Failed to get SecurityContextConstraints, securitycontextconstraints "fabric8" not found in namespace devops
```

**Comment by sbadakhc** [comment]
So after leaving it overnight it seems that only the gerrit and gerrit-ssh pods are still in the "pending state"

Looking at the container log I see the only the following entry:
```
[root@node02 ~]# docker logs ca7486336941
/root/.ssh/id_rsa
```

**Comment by rawlingsj** [comment]
I've just run a test and things seemed to be ok.  A couple of things to check, do you have the output of the `gofabric8 deploy` step?  We can see if there were any problems there.  The gerrit pod in non vagrant setups does seem to be an [issue](https://github.com/fabric8io/fabric8/issues/5098) but we're not relaiant on it so shouldn't cause you issues (until  this error is fixed I delete the gerrit RC).

I also wonder if you've got issues with docker pulling the images.  We've seen this a fair amount in the past, we've added a gofabric8 pull command so we can pull all the images for a template, i.e. `gofabric8 pull cd-pipeline`.  

It might be worth recreating that devops project to be on the safe side.  I've attached the steps used on an existing openshift install if that helps.  I noticed that you were running the templates from the CLI, there's also a `Run` button on the fabric8 console that allows you to select the templates that the gofabric8 deploy installed which means if you wanted to you can avoid the wget step you did to get the templates and process them.

**Comment by rawlingsj** [comment]
Figured I'd post the reply anyway as it looks like you just beat me :)  yeah that gerrit issue is tracked here https://github.com/fabric8io/fabric8/issues/5098

**Comment by rawlingsj** [comment]
FWIW I know they're not needed but if others run into similar issues here's the steps I ran https://gist.github.com/rawlingsj/8e16408e5605000a8417#file-gistfile1-txt-L58-L96

**Comment by sbadakhc** [comment]
I will check the gerrit issue and get back to you.  I'm also having problems with the registry and router on the default project but I don't know how that might the devops project.  I can rebuild and rerun the deployments easily enough so hopefully I can come back with some more info.

**Comment by jstrachan** [comment]
@sbadakhc did you run `gofabric8 deploy` on this `devops ` namespace? Currently thats the only time we do the installation of the SCC.

We could create a `gofabric8 setup` command that doesn't install any templates but just sets up the SCCs

**Comment by sbadakhc** [comment]
@jstrachan 

Here is how I'm provisioning the project and deploying Fabric8.  I'm a complete noob here so please advise!
```
################################################################################
#
# Project setup 

echo -e "# Create htpasswd file"
mkdir /etc/openshift
touch /etc/openshift/htpasswd
echo -e "# Add users"
oadm policy add-cluster-role-to-user cluster-admin admin
oadm policy add-role-to-user system:registry reguser
htpasswd -b /etc/openshift/htpasswd admin admin
htpasswd -b /etc/openshift/htpasswd reguser reguser

echo -e "# Create devops project"
oadm new-project devops --admin=devops
oc project devops


################################################################################
#
# Fabic8 setup

echo -e "# Download Fabric8 components"
cd /opt
mkdir gofabric8
cd gofabric8
wget https://github.com/fabric8io/gofabric8/releases/download/v0.3.18/gofabric8-0.3.18-linux-amd64.tar.gz
tar zxfv *.tar.gz
./gofabric8 deploy -y -d devops.cloudapps.example.com
./gofabric8 secrets -y
oc get oauthclient fabric8
./gofabric8 validate
cd /opt
mkdir fabric8
cd fabric8
curl -o fabric8.zip http://repo1.maven.org/maven2/io/fabric8/devops/distro/distro/2.2.65/distro-2.2.65-templates.zip
unzip fabric8.zip
cd main
export KUBERNETES_DOMAIN=example.com
mvn io.fabric8:fabric8-maven-plugin:2.2.65:create-routes -Dfabric8.domain=example.com
oc process -v DOMAIN=$KUBERNETES_DOMAIN -f cd-pipeline-2.2.65.json | oc create -f -
cd ~

################################################################################
```

**Comment by jstrachan** [comment]
ah, I've not tried `gofabric8 deploy` yet in another namespace other than `default`.

I just had a look at the code, I think it generates an SCC for fabric8_devops:
https://github.com/fabric8io/gofabric8/blob/336cc495ad0a3cdf75d64538fb71c807b369cfe5/cmds/deploy.go#L317-L317

so it could just be a mistake in the validation logic; not correctly using the right SCC name if running in a namespace other than default? e.g. I wonder if your installation actually works ok?

I've tried to fix the validation logic:
https://github.com/fabric8io/gofabric8/commit/7fe1b89a50590484e7167895f1fd715e79aa073d

you should be able to see the SCC in your devops namespace via
```
oc get scc
```

So hopefully its all working, its just a bad validation step.

I've just cut a new gofabric8 release with an attempted fix for this validation bug; I wonder if that helps?
https://github.com/fabric8io/gofabric8/releases/tag/v0.3.19

**Comment by sbadakhc** [comment]
Thanks James...confirmed and closing.

**Comment by sbadakhc** [comment]
Thanks James,

Is the reason for using the default project because all other subsequent
namespaces will have access to those components for was it just arbitrary?

Thanks,
Sal

On Mon, Nov 30, 2015 at 4:47 PM, James Strachan <notifications@github.com>
wrote:

> ah, I've not tried gofabric8 deploy yet in another namespace other than
> default.
>
> I just had a look at the code, I think it generates an SCC for
> fabric8_devops:
>
> https://github.com/fabric8io/gofabric8/blob/336cc495ad0a3cdf75d64538fb71c807b369cfe5/cmds/deploy.go#L317-L317
>
> so it could just be a mistake in the validation logic; not correctly using
> the right SCC name if running in a namespace other than default? e.g. I
> wonder if your installation actually works ok?
>
> I've tried to fix the validation logic:
> fabric8io/gofabric8@7fe1b89
> <https://github.com/fabric8io/gofabric8/commit/7fe1b89a50590484e7167895f1fd715e79aa073d>
>
> you should be able to see the SCC in your devops namespace via
>
> oc get scc
>
> So hopefully its all working, its just a bad validation step.
>
> I've just cut a new gofabric8 release with an attempted fix for this
> validation bug; I wonder if that helps?
> https://github.com/fabric8io/gofabric8/releases/tag/v0.3.19
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/5334#issuecomment-160667265>.
>



-- 
Senior Consultant
Nordics GPS Platform
Red Hat - Malmö

M: +46(0)705900431
E: sal@redhat.com
L: www.linkedin.com/in/sbadakhchani
G: https://github.com/sbadakhc

**Comment by jstrachan** [comment]
Just arbitrary - there's nothing special about the default namespace. We
should support folks using any namespace really

On Tuesday, 1 December 2015, Salim Badakhchani <notifications@github.com>
wrote:

> Thanks James,
>
> Is the reason for using the default project because all other subsequent
> namespaces will have access to those components for was it just arbitrary?
>
> Thanks,
> Sal
>
> On Mon, Nov 30, 2015 at 4:47 PM, James Strachan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > ah, I've not tried gofabric8 deploy yet in another namespace other than
> > default.
> >
> > I just had a look at the code, I think it generates an SCC for
> > fabric8_devops:
> >
> >
> https://github.com/fabric8io/gofabric8/blob/336cc495ad0a3cdf75d64538fb71c807b369cfe5/cmds/deploy.go#L317-L317
> >
> > so it could just be a mistake in the validation logic; not correctly
> using
> > the right SCC name if running in a namespace other than default? e.g. I
> > wonder if your installation actually works ok?
> >
> > I've tried to fix the validation logic:
> > fabric8io/gofabric8@7fe1b89
> > <
> https://github.com/fabric8io/gofabric8/commit/7fe1b89a50590484e7167895f1fd715e79aa073d
> >
> >
> > you should be able to see the SCC in your devops namespace via
> >
> > oc get scc
> >
> > So hopefully its all working, its just a bad validation step.
> >
> > I've just cut a new gofabric8 release with an attempted fix for this
> > validation bug; I wonder if that helps?
> > https://github.com/fabric8io/gofabric8/releases/tag/v0.3.19
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/fabric8io/fabric8/issues/5334#issuecomment-160667265
> >.
> >
>
>
>
> --
> Senior Consultant
> Nordics GPS Platform
> Red Hat - Malmö
>
> M: +46(0)705900431
> E: sal@redhat.com <javascript:_e(%7B%7D,'cvml','sal@redhat.com');>
> L: www.linkedin.com/in/sbadakhchani
> G: https://github.com/sbadakhc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/5334#issuecomment-160944645>.
>


-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration
