### ISSUE TITLE
Getting started issues on OpenShift

### ISSUE THREAD

**Issue by loshkovskyi** [fabric8io/fabric8#5336]
I have setup fabric8 on OpenShift Origin. When I click `Create Project` in the fabric8 console, I see `Import Project from Git` and `Setup Source Secret`, whereas I expect to see `Create Project using Wizard` according to your getting started guide: https://vimeo.com/142857726
Is it by design and I should indeed import project from Git?

Also, it takes about 1 minute to list all projects. Not sure how to address this issue. When I hit http://fabric8.vagrant.f8/workspaces?q=, I see:
>There are no namespaces currently available

wait for 1-2 minutes and they all appear.

**Comment by rawlingsj** [comment]
Yeah we've added the ability to add a username / password (for when using github, also soon to switch to a github api key instead) or ssh keys (for using gogs).

Once you have created a secret you will see the create project wizard.  This is a new feature so we've not recorded a screencast of it yet.  Will try and do one by the end of the week or beginning of next week by the latest.

As for the the delay you're seeing, yeah I've seen that a lot recently too.  Needs to be looked at for sure.

**Comment by rawlingsj** [comment]
@loshkovskyi I've raised a separate issue which is more directly focused on the listing namespaces problem you mentioned. https://github.com/fabric8io/fabric8/issues/5344

I'll close this issue in favour of the new specific issue.
