### ISSUE TITLE
console seems slow getting namespaces

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5344]
There seems to be something up with watchers.  The first time the console loads after logging in it takes about 10 secs to get the namespaces, in the logs I saw a websocket timeout just before the namespaces appeared.  Refreshed the page twice and now no namespaces are found at all.

I also tried on vanilla kubernetes, the namespaces disn't appear at all.

**Comment by rawlingsj** [comment]
@gashcrumb I don't suppose this means anything to you?

**Comment by davsclaus** [comment]
Yes I noticed that too, in recent versions, that it may take seconds or what feel like 5 seconds before the UI shows those 3-4 namespaces.

**Comment by gashcrumb** [comment]
I've not seen this yet, but best place to start looking is in the 'network' tab in the chrome developer tools, you can filter it down to just the websockets, I'd expect to see at least 'namespaces' connected, guess there may not be any available frames to take a look at, but would be interested to hear if there are...

On vanilla kubernetes we may still have issues getting at the 'template' service, which is required to show the initial page that lists projects, I mentioned this at the tail of [this issue](https://github.com/fabric8io/fabric8/issues/4646).

**Comment by gashcrumb** [comment]
Checking it now and there's definitely a 3-4 second gap in the network tab.  I have a suspicion that this could actually be due to downloading the angry pods background music, this could be happening during bootstrap which is causing other code to block.  Let me re-work how those sound files are downloaded and see if that helps, as they don't really need to be grabbed when the console first boots up.

**Comment by gashcrumb** [comment]
K, made a couple updates, in hawtio-kube3d we no longer initialize it's sound objects when the script loads, which helps the app's initial bootup time a bit.  I also added a tweak to hawtio-kubernetes-api so that it uses polling by default for 'projects' so we don't have to wait for the websocket upgrade to fail, seems to have helped a bit.

Since 'projects' is used for that initial page we could probably benefit by fetching those at bootstrap much like we do namespaces, will take a minute and see if that makes a real difference or not.

**Comment by rawlingsj** [comment]
Sounds great!

**Comment by gashcrumb** [comment]
K, that last commit there seemed to really do the trick, so should eventually bubble it's way into the console :-)

**Comment by rawlingsj** [comment]
Thats fantastic!  FWIW there's a release going on... the :latest tag of the console docker image is likely to be tagged with the new release in about the next 30 mins incase you fancy a challenge ;)

**Comment by rawlingsj** [comment]
If not we can easily trigger another whenever you're ready.

**Comment by gashcrumb** [comment]
just pushed a new release of hawtio-kubernetes, so if fabric8-console gets rebuilt we should be in business.

**Comment by rawlingsj** [comment]
ok so is that just a case of kicking off the circleci fabric8-console job?

**Comment by gashcrumb** [comment]
Just checking, I may have actually done that for you...

**Comment by gashcrumb** [comment]
Guess not, triggered it anyways...

**Comment by rawlingsj** [comment]
Ah I should have done that, thanks though!

Great - thats finished so I'll kickoff a fabric8-devops release.  I was planning on pulling the console app from fabric8-devops so we could release it on its own but I've not got round to it yet.  Will try and do that soon though so it will be much quicker and less noise when doing console releases.

**Comment by rawlingsj** [comment]
@gashcrumb latest release looks great!

**Comment by mynameismevin** [comment]
I am trying to run fabric8 behind a firewall on vanilla k8s, and I'm running into this issue. I'm running `fabric8/fabric8-console:latest` with `fabric8/templates:2.2.98`. When I go to view the fabric8 console, this is the only page I can see outside of the user page. When I looked at the logs via `kubectl`, it shows no errors. My dev console in Chrome shows either 101 or 200 status codes as well.

![image](https://cloud.githubusercontent.com/assets/7537841/12022852/168e1bbe-ad51-11e5-8544-86aced8a2172.png)

Is it possible to run fabric8 behind a firewall or are there external dependencies that are needed? Is there anywhere I can look for more logging?

**Comment by mikefaille** [comment]
@mynameismevin I have the same problem with same version.

**Comment by theobolo** [comment]
@mynameismevin I got exactly the same problem. 
I'm on Azure with CoreOS and Weave, when i launch the fabric8 there is no errors.
 
But still, the namespaces are not discovered...

**Comment by Smana** [comment]
+1
