### ISSUE TITLE
Camel forge - Updating java source code should not reformat the code

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5355]
For example when editing camel endpoints in the java route builder classes.

Its using the eclipse formatter style, which is not the same as in IDEA or what the user uses. And it does a full reformat of the entire source file, even if you just edit a single method.

Also the save seems to prevent undo operation in IDEA.

**Comment by davsclaus** [comment]
@gastaldi do you remember if there was a way in forge to not do code reformatting when saving a java source resource?

What the goal is with the camel-edit-endpoint command is to edit an existing `string` in the source code, and keep the code as-is. Currently it would on save, do a full reformat of the entire java class.

**Comment by gastaldi** [comment]
There is `org.jboss.forge.roaster.model.JavaType.toUnformattedString()` that returns the unformatted version of the generated source code

**Comment by davsclaus** [comment]
Okay so this is the save in that else block that will find the old string and replace it in the method source code.
https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/ConfigureEndpointPropertiesStep.java#L446

I wonder if there is another way of updating the resource? Maybe work on it as plain text, and do the replace and be able to save it back, so its not saved as a java source, that may trigger this reformatting?

**Comment by gastaldi** [comment]
Try this: 

`facet.getJavaResource(clazz.getQualifiedName()).setContents(clazz.toUnformattedString());`

**Comment by gastaldi** [comment]
or better: 

`existing.setContents(clazz.toUnformattedString());`

**Comment by davsclaus** [comment]
If I do
```
                existing.setContents(clazz.toUnformattedString());

                // TODO: avoid formatting source code

                //facet.saveJavaSource(clazz);
```
the code is still reformatted.

**Comment by gastaldi** [comment]
Looks like the underlying impl delegates to the setContents(InputStream, Properties) method, it should work with: 

`existing.setContents(new ByteArrayInputStream(source.toUnformattedString().getBytes()),null);`

**Comment by davsclaus** [comment]
Last code I tried

```
                existing.setContents(new ByteArrayInputStream(clazz.toUnformattedString().getBytes()), null);
                //existing.setContents(clazz.toUnformattedString());

                // TODO: avoid formatting source code

                //facet.saveJavaSource(clazz);
```

As you can run the commands from cli, its easier to run run forge cli in debug mode, and then load the camel project, and run the edit command. Then you can set breakpoints and remote debug.

**Comment by davsclaus** [comment]
Ah its the 
```
                String body = method.getBody();
```
that returns the message body as a single string, instead of formatted as-is.

I think I will try avoiding this, and do the code manipulation on the unformatted class body, and save it as-is.

**Comment by davsclaus** [comment]
Got it working now, thanks @gastaldi for the help

**Comment by davsclaus** [comment]
btw the old way would also loose your code comments, as getBody is the java source only. I guess that api works best for adding new code etc. But for updating you need to be more careful.

And btw would love the pom.xml to be as-is as well. When you update it, it removes all empty lines and reformat it too etc.

**Comment by gastaldi** [comment]
Yes, there is already a JIRA about the pom.xml formatting. I blame the official maven model api for that
