### ISSUE TITLE
duplicate dashboards appear after CD job retriggered

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5368]
If a project / pipeline is re-triggered then duplicate environments, pipelines, commits and logs appear on the overview page..

<img width="1372" alt="screen shot 2015-11-30 at 23 18 16" src="https://cloud.githubusercontent.com/assets/1457180/11487731/32133b88-97b9-11e5-9845-a37e8f908889.png">

**Comment by rawlingsj** [comment]
<img width="491" alt="screen shot 2015-11-30 at 23 23 11" src="https://cloud.githubusercontent.com/assets/1457180/11487752/6e3586ca-97b9-11e5-939f-ae5d461aa942.png">

**Comment by gashcrumb** [comment]
Yeah, knew about this one, hadn't had a chance to address it yet, can you
assign this to me?

**Comment by rawlingsj** [comment]
ok cool - btw I dont want this issue to distract the fact that the dashboards are looking GREAT!  Nice work @gashcrumb!!

**Comment by rawlingsj** [comment]
fwiw here's a link to a screenshot of the latest dashboards https://github.com/fabric8io/fabric8/issues/5310#issuecomment-159312431

**Comment by rawlingsj** [comment]
Not sure if its related but I edited the source so a second job was triggered, after going back to the overview page and refreshing after seeing the duplicate dashboards it took 4 mins for the environments to update.  They updated straight after this error in the console `WebSocket opening handshake timed out`...

```
Preserve log
.
3
libs.js:39253 [Developer] entity has changed!
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-testing/replicationco…ollers?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-testing/pods?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-staging/replicationco…ollers?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-staging/pods?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-prod/pods?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
libs.js:149047 WebSocket connection to 'wss://demo.fabric8.io:8443/api/v1/namespaces/demo-prj-prod/replicationcontrollers?watch=true&access_token=U5XAcE2qwZVw_PPkpif129uLVXqR-glksI_ycXvsOH8' failed: WebSocket opening handshake timed out
4
libs.js:39253 [Developer] project versions has changed!
4
libs.js:39253 [Developer] project versions has changed!
2
libs.js:39253 [Developer] project versions has changed!
.

```

**Comment by rawlingsj** [comment]
dashboards aren't on the overview page anymore so not an issue!
