### ISSUE TITLE
Load balancing from apiman-gateway pod to kubernetes service ip is sticky.

### ISSUE THREAD

**Issue by stevemuk** [fabric8io/fabric8#5375]
I've noticed that if I create an apiman proxy that targets the service ip directly, load balancing is sticky to a single pod behind that service rather than round-robin. Under load the target pod may switch but again traffic is directed to just that one pod.

```sessionAffinity: None``` is set on both the apiman-gateway and app service config.

Running multiple gateway pods allows load balancing of the application but with the overhead of running more gateway pods than is really needed.

**Comment by jimmidyson** [comment]
Hey @KurtStam - any ideas on this?

**Comment by KurtStam** [comment]
@jimmidyson no idea.. I will take a look to see if the gateway has its own sessionAffinity setting. 
@stevemuk  Does 'Under load the target pod may switch'? mean there is /some/ load balancing going on?

**Comment by stevemuk** [comment]
I noticed this when I created an apiman proxy to the same application via an exposed route and also via the internal Kube-proxy. The exposed route round-robins each execution, where as the kube-proxy sends my request to the same pod.

The chosen pod changes every 10 secs or so under load. If I wait between invocations it also changes the pod.

**Comment by KurtStam** [comment]
@stevemuk, so - summarizing to make sure I fully understand:

1. the kube-proxy is the component not load balancing, and this only happens when using the apiman-gateway sitting in front of it? Or also when using the kube-proxy directly?
2. things work as expected using the apiman-gateway + ha-proxy

**Comment by KurtStam** [comment]
@jimmidyson there are no session affinity settings in the apiman-gateway. The gateway connects to one service endpoint address and it does nothing to influence session affinity as (atm) it is outside of its domain. So I'm thinking @stevemuk will find that the sticky behavior is experienced when using the kube-proxy directly, as I'm suspecting this behavior is built into the kube-proxy.

**Comment by jimmidyson** [comment]
@KurtStam so apiman doesn't do anything with keep-alives to backend servers? If apiman keeps connections alive then this will be respected by the kube proxy.

**Comment by stevemuk** [comment]
Ok just ran a test without apiman, the kube-proxy is sticky. Should I raise this with the open shift team?

**Comment by KurtStam** [comment]
@stevemuk yes - please do, and can you post a reference to the issue here, so that we can track it?

**Comment by jimmidyson** [comment]
@stevemuk As we discussed earlier it should be sticky if connections are kept open. If a new connection is created each time then it should load balance properly.

**Comment by stevemuk** [comment]
So should apiman-gateway keep connections open? As it stands no load balancing is done if you have a single apiman-gateway pod.

**Comment by KurtStam** [comment]
@stevemuk Debatable I guess. The apiman-gateway itself does not concern itself with load balancing one way or the other. At the moment it is using the OKHTTP (http://square.github.io/okhttp/) client. It maybe keeping connections open with its connection pooling for performance. I guess it's easy to swap it out for a different HTTP client since it has matching API's with other clients. 

I would think if you build 10 connections it should be distributed equally over all backend pods though. Isn't that good enough?

**Comment by jimmidyson** [comment]
Can you try setting the system property `http.keepAlive` to `false` & see if that helps? That should disable keep-alives which is normal for reverse proxy type software.

**Comment by stevemuk** [comment]
Ok tried a version of apiman-gateway with a ```-Dhttp.keepAlive=false``` and that seems to fix it.

**Comment by KurtStam** [comment]
@stevemuk @jimmidyson. I added this to the documentation (https://github.com/fabric8io/fabric8/pull/5679) and I'm going to close this. Please reopen if the '-Dhttp.keepAlive=false' default should be the default but I think it will be bad for performance. In a high performance environment you probably want to run a gateway pod on each node, and by default it will try to make all local calls by default.
