### ISSUE TITLE
there seems to be a new cd-pipeline RC created now which fails; also 'gofabric8 pull cd-pipeline` now barfs too

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5377]

**Comment by davsclaus** [comment]
wonder if this PR could be the trouble?
https://github.com/fabric8io/fabric8/commit/ff5300868d0b8d0b8f9adb4ffece0879a72f2bbd

**Comment by rawlingsj** [comment]
yeah it is that one.. just tested a fix.  I think its this line.. https://github.com/fabric8io/fabric8/commit/ff5300868d0b8d0b8f9adb4ffece0879a72f2bbd#diff-999e31ca5344efdde42e9d759bdc7f6cR583

**Comment by rawlingsj** [comment]
confirmed this is fixed with the latest release
