### ISSUE TITLE
Issue when installing using Vagrant on Windows

### ISSUE THREAD

**Issue by mriccia** [fabric8io/fabric8#5400]
I was following the getStarted/vagrant guide and stumbled upon this issue when running
`vagrant plugin install vagrant-hostmanager-fabric8`

```
Installing the 'vagrant-hostmanager-fabric8' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'vagrant-hostmanager-fabric8 (>= 0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.
```

I can see that the Gemfile has been taken down on [rubygems.org](https://rubygems.org/gems/vagrant-hostmanager-fabric8/versions/1.6.0) so is this not needed anymore?

**Comment by gashcrumb** [comment]
Think you can just use the regular vagrant-hostmanager plugin now, so we just need to update those docs.

**Comment by mriccia** [comment]
Cool, I'll do that and send a PR

**Comment by davsclaus** [comment]
yeah I think @rhuss fixed this so we use the regular one now

**Comment by davsclaus** [comment]
thanks for reporting

**Comment by rhuss** [comment]
Yeah, @jimmidyson cleaned it up since the sole purpose of this 'fork' that we needed a release early from trunk because of a fix for the Windows limitation allowing only 8 host entries per line in `/etc/hosts`.

**Comment by mriccia** [comment]
No problems, glad I could be of help.
Thank you for the clarification, I'll give it another try this evening
