### ISSUE TITLE
camel forge - Add endpoint - if no RouteBuilder

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5409]
then add the add route builder command as first step so the user can create it at the same time

**Comment by gastaldi** [comment]
https://github.com/forge/core/tree/master/ui#use-prerequisitecommandsprovider-when-you-need-some-commands-to-be-executed-prior-to-your-comand

**Comment by davsclaus** [comment]
Ah thanks, yeah that seems lovely way.

**Comment by davsclaus** [comment]
We have changed this a bit so you add/edit endpoints from the current cursor position. This feels more naturral when using a java editor.
