### ISSUE TITLE
cd pipeline doesn't seem to automatically trigger after project creation

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5452]
I think I noticed this on the last release and it happened again on the latest.  I had to manually trigger the workflow job in jenkins

**Comment by rawlingsj** [comment]
odd - latest release fabric8-devops 2.2.89 triggered automatically.  Will keep issue open for a short while just in case.

**Comment by jmlambert78** [comment]
ON 88 I TOUCHED A JAVA FILE AND THE TRIGGER WAS INITIATED FOR THE BUILD.

**Comment by rawlingsj** [comment]
Ok great - well sounds like the webhooks are still setup ok, its more just the initial job trigger.

**Comment by rawlingsj** [comment]
Latest release works fine.
