### ISSUE TITLE
Vagrant Provisioning Script Error

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#5454]
Just tried to pull down the latest stuff. Got the following error on 'vagrant up':
<snip>

==> default: Running provisioner: shell...
    default: Running: inline script
==> default: ==========================================================================
==> default: Using VM Memory of 12000 MB
==> default: ==========================================================================
==> default: Archive:  helm.zip
==> default:   inflating: helm                    
==> default: gofabric8
==> default: README.md
==> default: LICENSE
==> default: Downloading OpenShift binaries...
==> default: 
==> default: gzip: stdin: not in gzip format
==> default: tar: Child returned status 1
==> default: tar: Error is not recoverable: exiting now
==> default: mv: cannot stat ‘/tmp/openshift/*’: No such file or directory
==> default: A new version of Helm is available. You have v0.1.0+825f5ef. The latest is 0.2.0
==> default: [WARN] 
==> default: ---> Download version 0.2.0 here: https://github.com/helm/helm/releases/tag/0.2.0
==> default: [ERROR] Could not find 'kubectl' on $PATH: exec: "kubectl": executable file not found in $PATH
==> default: [ERROR] Could not load /root/.helm/config.yaml: open /root/.helm/config.yaml: no such file or directory
==> default: /var/lib/openshift /home/vagrant
==> default: /tmp/vagrant-shell: line 46: /usr/bin/openshift: No such file or directory
==> default: /tmp/vagrant-shell: line 47: /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml: No such file or directory
==> default: sed: can't read /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml: No such file or directory

**Comment by jimmidyson** [comment]
Sorry about that - they changed the way OpenShift is tarred up in a patch release...

**Comment by stevef1uk** [comment]
Thanks for a fast response. Looking good now.
