### ISSUE TITLE
Gitective project adoption

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8#5459]
Looking at Gitective, I notice is no longer mantained.

Since we are using it in fabric8 and hawtio too, can we adopt the project? What do you think about?

Jgit is released on regular basis and gitective is based on it and it's very powerful.

Maybe it's a stupid idea. Let me know what do you think about it.

**Comment by jstrachan** [comment]
yeah, there's some really handy JGit code in gitective. It'd be good to fork it and build, test and release it against the same JGit versions we're using in fabric8!

**Comment by jstrachan** [comment]
I've a vague memory of having to go back in JGit versions due to an issue with gitective using older versions of JGit; so being able to reuse the latest greatest JGit would be great

**Comment by oscerd** [comment]
Yes, actually there are some problems by switching to Jgit 4 and on 3.x too.

Do you want to fork gitective inside fabric8 repositories?

**Comment by oscerd** [comment]
Just tell me how do you want to proceed and I'll take care of the project :-)

**Comment by oscerd** [comment]
Ping

**Comment by oscerd** [comment]
Done
