### ISSUE TITLE
camel commands (like add component, add endpoint) should use a DTO for the Component name

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5478]
then we can return as much metadata as we can about a component (name, description, category, description, icon etc) then we can show a table or grid or something a little nicer to choose between

If you want to crib code we do this now for Pipeline choosing:

* PipelineDTO: https://github.com/jstrachan/fabric8/blob/41ed8c09438eb3f45a2bdc17b7b58ab77b4b8b96/forge/addons/devops/src/main/java/io/fabric8/forge/devops/dto/PipelineDTO.java#L25-L25
* selecting it in the forge command: https://github.com/jstrachan/fabric8/blob/982004020d2e95c61004db5bf7573514738ba5cd/forge/addons/devops/src/main/java/io/fabric8/forge/devops/DevOpsEditStep.java#L87-L87
* then you need to add a converter from String name -> DTO (for when we send/validate input): https://github.com/jstrachan/fabric8/blob/982004020d2e95c61004db5bf7573514738ba5cd/forge/addons/devops/src/main/java/io/fabric8/forge/devops/DevOpsEditStep.java#L132

**Comment by davsclaus** [comment]
Got it working but then discovered that in IDEA the component dto causes the wizard to be sluggish. It may be that there is too much for loops iterating

**Comment by jstrachan** [comment]
@davsclaus damn! wonder if there's too much data in the DTOs? Maybe there's just too many components?

**Comment by davsclaus** [comment]
yeah let me delete 150 camel components, then we can have em in one page also ;)

**Comment by jstrachan** [comment]
wonder if it'd make things less sluggish if we forced a category to be chosen first (using DTOs) then once there's a category, the next page shows the list of those components for that category; then there's only about 1/8th of the components returned?

**Comment by davsclaus** [comment]
yeah if we add more steps then its like

category -> select component -> what name / rb to use -> options 1 -> options 2 -> options N

where as today its (so I guess to much refresh happens depending on what you select in other fields, and so on)

one screen with all -> options 1 -> options 2 -> options N

**Comment by jstrachan** [comment]
@davsclaus LOL :)

given the large number of components these days I don't think its unreasonable to make users pick a catagory first; they can always go back and change it via the wizard interface etc. Plus showing 200 components in a pick list isn't great anyway - so forcing a category selection sounds good to me. 

The 2 fields on one form doesn't work too great on the web UI either btw; so having 2 pages might be easier

**Comment by davsclaus** [comment]
We should have DTO for language, data format as well.

**Comment by jstrachan** [comment]
agreed!

**Comment by davsclaus** [comment]
there is now 3 kind of dtos

- components
- data formats
- languages

which are the ones these commands can select among. The dtos include all the details we have from the camel catalog.

**Comment by jstrachan** [comment]
Awesome, many thanks!

**Comment by davsclaus** [comment]
the speedup is still needed and the extra steps for add component. But a good simple command is the add data format which is just one combobox. btw I use UISelectOne is that okay for the web?

**Comment by davsclaus** [comment]
darn it seems those dto classes makes the commands sluggish. Running 2.2.80 in IDEA works fine and runs at normal speed.

**Comment by davsclaus** [comment]
With the dto then after a few command runs then the IDEA is sluggish and unresponsive and you need to kill it.

**Comment by jstrachan** [comment]
Damn - wonder if we have to roll this back? Wonder if we could have a 'fabric8 only' command maybe that does use the DTOs?

**Comment by jstrachan** [comment]
I wonder if George has any idea on this BTW? He might have seen this kinda thing before. 

Another approach could be, we could have a command to find all the components - returning all the DTOs - which we could then use in the web console and leave the add component as it is for IDEA; then we can have a custom page in the web UI to find a component to add then default the component name and delegate to the real forge `camel-add-component` command.

**Comment by davsclaus** [comment]
yeah i ponder to rollback this so we have the gui commands as before. We can then add some code for getting data as dto's. I could probably add the dtos to camel-catalog so its there out of the box, and we can then easier reuse when needed.

**Comment by davsclaus** [comment]
It seems to run better having equals/hash on the dto objects
https://github.com/fabric8io/fabric8/pull/5489

IDEA is a bit slow when you in the UISelectOne dropdown box press page down / up for jumping in the list. Its faster if you use scroll mouse. That is also the case before the dto's.

**Comment by davsclaus** [comment]
The dto's are there - lets assume the speed is okay as-is.
