### ISSUE TITLE
camel add component / endpoint command - Add step for preselect

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5482]
yeah if we add more steps then its like

category -> select component -> what name / rb to use -> options 1 -> options 2 -> options N

where as today its (so I guess to much refresh happens depending on what you select in other fields, and so on)

one screen with all -> options 1 -> options 2 -> options N

**Comment by jstrachan** [comment]
adding a component doesn't seem to neeed another step; I'm forwarding to page 2 now  in the web based Camel perspective. Though I can't yet get the camel-add-endpoint to work yet, as I can't forward to page 2 of that wizard. It'd be nice if we split that command into a page of 'select camel component' then once a camel component is chosen, page 2 setups the route builder / XML file / endpoint name and so forth

**Comment by davsclaus** [comment]
yeah I started splitting them up but it wasn't super easy in forge as "you need to keep state" what is selected in those steps in that map, and depending on what happens execute login in next / execute - this is where forge is a bit bad IMHO.

Is there any hint in the web console why camel-add-endpoint do not allow next. 

But sure we can break it up, but it may take half a day to get the code with correctly.

**Comment by davsclaus** [comment]
We now separate this, so you add a component to the project. And add endpoint where you can select among the endpoints that are in the project.
