### ISSUE TITLE
trouble selecting a secret in the UI

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5503]
When selecting a secret in the UI the Save button appears for a moment and then sometimes disables shortly after but before being able to click it.

**Comment by jstrachan** [comment]
BTW I just improved the UI for selecting secrets:
https://github.com/fabric8io/fabric8-console/issues/61

hopefully things are better now. Though I've not been able to reproduce this particular issue; hopefully the new warnings make things a bit more clear?

**Comment by jstrachan** [comment]
Aha - managed to reproduce it on the beast; it was a bug when the kubernetes model changes causing the selection to be lost. Fixed!
