### ISSUE TITLE
Forge error installing fabric8 addons

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#5513]
Boss Forge, version [ 3.0.0.Alpha3 ] - JBoss, by Red Hat, Inc. [ http://forge.jboss.org ]

[core]$ addon-install --coordinate io.fabric8.forge:kubernetes
-***ERROR*** Project '/Users/stevef/Dev/github/forge/core' has errors
***ERROR*** Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.forge:forge-bom:pom:3.0.0-SNAPSHOT @ line 184, column 22

***SUCCESS*** Addon io.fabric8.forge:kubernetes,2.2.82 was installed successfully.
[core]$ exit
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/stevef/forge/forge-distribution-3.0.0.Alpha3/addons/org-jboss-forge-addon-maven-3-0-0-Alpha3/slf4j-jdk14-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/stevef/forge/forge-distribution-3.0.0.Alpha3/addons/org-jboss-forge-addon-database-tools-3-0-0-Alpha3/slf4j-jdk14-1.5.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
Exception when parsing/running: exit, null

At this point forge is unusable and won't even respond to <ctl>C or <ctl>|

**Comment by stevef1uk** [comment]
Seen this, but so 'fresh' I am not sure of the way forwards: https://issues.jboss.org/browse/FORGE-2531

**Comment by davsclaus** [comment]
Yeah there has been a couple of fixes in forge that should help with this command.

**Comment by davsclaus** [comment]
These tickets should help this:

https://issues.jboss.org/browse/FORGE-2531
https://issues.jboss.org/browse/FORGE-2566

**Comment by stevef1uk** [comment]
Thanks but I need to have a new release made available for me as building from the Forge source repo doesn't seem obvious and didn't work.

**Comment by davsclaus** [comment]
there is a new forge release

**Comment by davsclaus** [comment]
This PR should fix it. I can install the kubernetes addon now in forge3 beta2
https://github.com/fabric8io/fabric8-forge/pull/60
