### ISSUE TITLE
Camel forge - Gather source code line for java endpoints

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5524]
See if we can figure out the source code line the jdt parser has detected the uris, so we can shown that in the various tooling. We can gather that for xml files.

**Comment by davsclaus** [comment]
I dont see any information how do get this from roaster in its api. Maybe we would have to dig into the lower level jdt api.

Or we should ask the roaster guys to provide such details.

**Comment by davsclaus** [comment]
I logged a forge ticket
https://issues.jboss.org/browse/FORGE-2571

**Comment by davsclaus** [comment]
We have added our own line number parser until its out of the box from forge

**Comment by gastaldi** [comment]
Added in Roaster: http://github.com/forge/roaster/commit/47ed24a6c
