### ISSUE TITLE
extra camel endpoints appear on the Camel perspective

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5555]
see the attached screen shot. The last 2 have no name and use the reference  `#foo` URI syntax.

Here's the RouteBuilder source if its any help:
```
@ContextName("myCamel")
public class MyRoutes extends RouteBuilder {

	@Inject
	@Uri("timer:foo?period=5000")
	private Endpoint inputEndpoint;

	@Inject
	@Uri("log:output")
	private Endpoint resultEndpoint;

	@Inject
	@Uri("dataformat:blah:marshal")
	private Endpoint foo;

	@Override
	public void configure() throws Exception {
		// you can configure the route rule with Java DSL here

		from(inputEndpoint).beanRef("counterBean").to(resultEndpoint);
	}

}
```

<img width="1218" alt="camel-perspective" src="https://cloud.githubusercontent.com/assets/30140/12120920/b9694ce4-b3ca-11e5-9763-9fcc31527188.png">

**Comment by davsclaus** [comment]
Ah let me try to reproduce as its the java parser have changed heavily recently

**Comment by jstrachan** [comment]
yeah, it seems a recent change. FWIW I was using the cdi-camel java quickstart in the above

**Comment by davsclaus** [comment]
A fix for this is in forge, do you see this anymore?

**Comment by jstrachan** [comment]
Thanks! Those previous endpoints with the `#foo` have gone now. 

Though I seem to get a duplicate of the timer endpoint in the camel-cdi quickstart as shown below. Maybe we just need to filter out duplicate endpoint DTOs if the URI is the same?
<img width="1301" alt="fabric8-console" src="https://cloud.githubusercontent.com/assets/30140/12165456/ff8392ba-b515-11e5-9650-f611befbd24c.png">

**Comment by davsclaus** [comment]
Ah yeah must be the command doing some extra versus what the maven plugin / parser does. I will take a 2nd look. Also that log should be kind = producer.

**Comment by davsclaus** [comment]
Yeah I see the 2nd in the CLI too
```
[bar]$ camel-edit-endpoint
***INFO*** Required inputs not satisfied, entering interactive mode

[0] ( ) <select>
[1] ( ) timer:foo?period=5000
[2] ( ) log:output
[3] ( ) timer:foo?period=5000
[4] ( ) bean:counterBean
```

**Comment by davsclaus** [comment]
And we are back at the expected, and fixed also setting the line number for the fields, so we know where in the .java file the field is positioned

```
[bar]$ camel-edit-endpoint
***INFO*** Required inputs not satisfied, entering interactive mode

[0] ( ) <select>
[1] ( ) timer:foo?period=5000
[2] ( ) log:output
[3] ( ) bean:counterBean
```

**Comment by jstrachan** [comment]
@davsclaus oh line numbers rock! Was hoping we could add those in! Now I need to figure out how to create a link into the wiki source page ;)

**Comment by davsclaus** [comment]
yeah a link would rock ;)

**Comment by davsclaus** [comment]
assume it works now
