### ISSUE TITLE
Support generation of multiple services in JsonMojo

### ISSUE THREAD

**Issue by purplefox** [fabric8io/fabric8#5574]
The current JsonMojo only supports the generation of a single service in kubernetes.json.

This is a limitation for projects that require two or more services as they wouldn't be able to benefit from the nice Maven based automatic generation approach that f8 offers.

An example of an application that requires two services is a typical Vert.x clustered web application.

A vert.x web application will often consist of a Java process which acts both as a web server - serving web content to clients and also as a node in a Hazelcast (or other clustering provider) cluster. This would map to a single pod.

We require one service to load balance web traffic to the pods, and another (headless) service that maintains a list of the pod ip addresses so each hazelcast node can discover each other using DNS lookups on the headless service.

**Comment by christian-posta** [comment]
Can we do this with the annotation processors?

https://github.com/christian-posta/fabric8-devops/blob/master/gerrit/src/main/java/io/fabric8/app/gerrit/GerritModelProcessor.java#L10-10

http://fabric8.io/guide/annotationProcessors.html

**Comment by jimmidyson** [comment]
We've already done this tbh! Documented too ;) See http://fabric8.io/guide/mavenFabric8Json.html#maven-properties

Syntax is `fabric8.service.<name>.*` for all configurable service options.
