### ISSUE TITLE
Create forge command: camel-add-node-pattern-xml / add-node-endpoint-xml

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5578]
Like #5577 but for adding other nodes; from/to/filter etc

It would be good for this command to have a 'parent' parameter; to add at the end of a known route/node (eg inside a filter/when/otherwise)

An optional 'after' parameter would be handy in case want to add in the middle of the children. Eg from a > b > d - you may want to add a 'to c' after 'b' and before 'd'

The endpoint version of the command would then use the usual add endpoint wizard & then create a 'from' or 'to' node at the right point in the xml.

The pattern version should provide a choice of PatternDto objects (with categories to help filter them?) then provide wizard steps to configure the pattern & any expressions etc

**Comment by jstrachan** [comment]
I've got the endpoint nodes being created & edited so far; just need the patterns

**Comment by davsclaus** [comment]
Thanks @jstrachan got the endpoint polished a bit more so it do not re-layout the entire xml file.

I should be able to stand on your work and then make a wizard for the eips instead of the endpoints as we have today. But then most of the other works is similar. 

And then the xml to insert is the pattern xml but we should be able to dump that as xml snippet.

**Comment by davsclaus** [comment]
The edit-node-xml command did reformat the xml code, so I fixed that also.

**Comment by davsclaus** [comment]
and also the delete-node-xml has been improved with the same kind of fix to not re-layout the entire xml file.

**Comment by davsclaus** [comment]
First cut of add-node-xml on the way
https://github.com/fabric8io/fabric8-forge/pull/74

Currently it adds `<todo/>` in the xml as the eip model is not yet marshalled, but the overall principle is almost there. The EIP list is big with 163 nodes, so we should maybe add a filter like in the components, and also let it be more intelligent and filter unwanted / not useable in the list. For example not show rest when you add to a route etc. 

And for complex EIPs like a choice, should we then do that bit by bit, so you add a choice. then you need to add the when's you may need, and so on.

Well lets get some code in first, and see how it goes.

**Comment by jstrachan** [comment]
sounds awesome! That all sounds good to me; we can experiment with different web UIs to help filter/show patterns etc

We could always create a custom UI for CBR to make it easier to add new When nodes etc maybe or something

**Comment by davsclaus** [comment]
The early first cut is on the way:
https://github.com/fabric8io/fabric8-forge/pull/75

It adds the xml model of the eip you have chosen. Though the more complex ones that has an expression isn't yet working. We need an improved UIInput to allow to chose the expression language and what options it may have etc.

Though for a bunch of the simpler ones like log etc it works.

I will try to fix it so when there is a single node, the xml is just using one tag, eg ```<log xxx/>```

**Comment by davsclaus** [comment]
Also I need to sort out the ordering of the fields in the wizard, today the mandatory is not in the top etc, and we could maybe also sort them A..Z as we do for endpoints.

**Comment by davsclaus** [comment]
So a first cut of edit-node-xml is on the way. You can now edit simpler eips. 

Though I wonder if it makes sense to edit a 'to' node and make it able to edit it as both node + endpoint also. As maybe that is what you want. But then we have commands for each kind.

**Comment by jstrachan** [comment]
yeah - I figure for editing a from + to we'd just have 1 command and it'd show all the endpoints stuff; but also let folks edit the id/description etc?

**Comment by davsclaus** [comment]
The description is very seldom used. I think we should consider not include it at first. People tend to use code comment in the XML which we with the forge tools do not delete, they stay as-is.

**Comment by davsclaus** [comment]
There is a few other EIPs where you specify and endpoint uri, such as enrich and pollEnrich, wireTap and a few others.

So I wonder if we down the road can get the forge commands to have some nice way to "Do you want to edit the endpoint uri also?" YES   NO. or something. Or maybe even better a special button in the UI wizard, that allows you to edit the endpoint and when you click its "finish" it takes you back to the current wizard - or something.

But there is still a bit to get all the EIP options in the wizard. Especially the language expressions. I logged a forge ticket
https://issues.jboss.org/browse/FORGE-2587

**Comment by jstrachan** [comment]
yeah - I guess if we knew that a Node had an endpoint URI we could expose an "edit endpoint" option as a pull down menu option?

BTW we expose the "uri" property on from/to right now when returning the blob of JSON for the tree model; so we could just extend that to other patterns which have an endpoint URI too?

**Comment by davsclaus** [comment]
the edit-node-xml command should now preserve children and also indent properly. It uses 2 spaces currently, but I plan to try to detect if the xml file is using a different indent such as 4 and use that.

**Comment by davsclaus** [comment]
edit-node-xml should use same indent as the xml file does.

**Comment by davsclaus** [comment]
We have these kind of commands now
