### ISSUE TITLE
fabric8 release failing on ipaas-quickstarts

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5605]
looks like a recent dependency update is causing an error with ipaas-quickstarts..

from the ipaas-quickstart CI build..

```
17:35:46 ERROR MavenCli                       - Failed to execute goal io.fabric8:fabric8-cxf-plugins:2.2.86:java2swagger (process-classes) on project karaf-cxf-rest-archetype: Execution process-classes of goal io.fabric8:fabric8-cxf-plugins:2.2.86:java2swagger failed: An API incompatibility was encountered while executing io.fabric8:fabric8-cxf-plugins:2.2.86:java2swagger: java.lang.NoSuchMethodError: 
```

**Comment by oscerd** [comment]
Sorry about this. It was looking good on fabric8 only.

Sorry once again.
Il 15/gen/2016 23:41, "James Rawlings" <notifications@github.com> ha
scritto:

**Comment by rawlingsj** [comment]
not to worry! its hard to catch these as we have quite a lot of repos now.  I'm reverting it for now to get the release out.
