### ISSUE TITLE
Camel forge - Add support for add/edit at cursor position

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5625]
Wonder if we can get forge to tell us what the active window is, and what the cursor position is at, so we can detect if its in a xml or java file where you have camel endpoints etc.

It would be cool to be able to edit or add endpoints from cursor position.

**Comment by davsclaus** [comment]
@gastaldi any hints, in case you kinda can understand this ticket?

**Comment by gastaldi** [comment]
@davsclaus yeah, that would be great, I remember thinking of that a long time ago but apparently I forgot to create a JIRA about it. Could you do that? I think it would be great as a starting point to discussion

**Comment by davsclaus** [comment]
@gastaldi thanks I logged
https://issues.jboss.org/browse/FORGE-2585

**Comment by davsclaus** [comment]
Got this working for knowing what was the active java or xml file etc.

Now I will try dive down and get to know what the active element is at the cursor position, so we can try to have a command that "adapts" and edits an endpoint / eip if the cursor is position at either of them.

**Comment by davsclaus** [comment]
Pushed a PR to the f8 forge with a first cut prototype.

**Comment by davsclaus** [comment]
A few gremlins to iron out, such as when the cursor is not on an endpoint the list of endpoints from the file is shown, but the next navigator seems broken.

Also for endpoints annotated on fields with '@Uri' etc is detected on the wrong line, eg the line of the field, but we need the line where the uri is in the annotation.

**Comment by gastaldi** [comment]
That's weird. Do you see any stacktraces?

**Comment by gastaldi** [comment]
Also, do you have an example of this wrong line issue?

**Comment by davsclaus** [comment]
@gastaldi I dont have a stacktrace handy but it was in some forge core code. However I have fixed it in my camel addon code. There was some code I missed from an old existing working command to be ported to the new command.

The wrong line issue, it may be in our code as we have some parser logic. I need to take a look first. But it may be a challenge for us to find the exact line number in case the annotation is split in multi lines eg

```
123     @EndpointInject(context = "myCamel",
124                                uri = "log:foo")
125      private Endpoint myLogger;
```

**Comment by davsclaus** [comment]
Got the line number fixed with
https://github.com/fabric8io/fabric8-forge/pull/135
