### ISSUE TITLE
generation of kubernetes list using @KubernetesProvider does not work as is

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#5626]
so according to this doco page http://fabric8.io/guide/annotationProcessors.html we should be able to generate new Kubernetes json using the type-safe builder (which is awesome).

So the doc is outdated (i.e., refers to KubernetesBuilder when it should be KubernetesListBuilder).. but that's of secondary concern. I can submit a PR for that.

But the issue is that when we use KubernetesListBuilder (to build KubernetesList objects) it doesn't work. I get a blank output

>{
  "apiVersion" : "v1",
  "items" : [ ],
  "kind" : "List"
}

The problem is with this line 

https://github.com/christian-posta/fabric8/blob/master/components/kubernetes-generator/src/main/java/io/fabric8/kubernetes/generator/processor/KubernetesProviderProcessor.java#L95-95

At the moment I'm not seeing a clean way to make KubernetesList implement the HasMetadata interface.

**Comment by iocanel** [comment]
@christian-posta: you are right! It needs clean up!

Since we now delegate to combineJson() for creating the list, we don't need to worry about HasMetadata since combineJson() works with objects. 

I am on it.

**Comment by christian-posta** [comment]
Thanks @iocanel 

I just tried the latest masters and it works great.
Thanks!
