### ISSUE TITLE
Would be awesome for the @KubernetesProvider annotation to be able to generate new kubernetes.json files

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#5627]
So right now all @KubernetseProvider methods will generate manifest entries for a default "kubernetes.json" file 

https://github.com/christian-posta/fabric8/blob/master/components/kubernetes-generator/src/main/java/io/fabric8/kubernetes/generator/processor/AbstractKubernetesAnnotationProcessor.java#L61-61

and

https://github.com/christian-posta/fabric8/blob/master/components/kubernetes-generator/src/main/java/io/fabric8/kubernetes/generator/processor/AbstractKubernetesAnnotationProcessor.java#L38-38

would be awesome if we could say @KubernetesProvier("new-filename.json") and have it create a new, non-default kubernetes.json...

thoughts?

can work on this PR...

**Comment by iocanel** [comment]
It makes total sense! Go for it :-)

**Comment by iocanel** [comment]
I am wondering if we should also have property for specifying the input json too.

**Comment by christian-posta** [comment]
@iocanel ah.. yah.. for the @KubernetesModelProcessor for existing kube json files... yah that's a good idea... let me take a look at that too

**Comment by christian-posta** [comment]
Has been merged to master, should be available in 2.2.89 release
