### ISSUE TITLE
Oauth issue with gofabric8 deployment

### ISSUE THREAD

**Issue by lypht** [fabric8io/fabric8#5630]
I've been able to successfully deploy fabric8, but I'm getting the following error when trying to authenticate with openshift.  Here are some facts:
```OAUTH_CLIENT_ID:			fabric8
   OAUTH_PROVIDER:			openshift
   OAUTH_AUTHORIZE_URI:		https://master1.dev.obfuscatedFQDN.com:8443/oauth/authorize```

When attempting to resolve https://fabric8-master1.dev.obfuscatedFQDN.com, the fabric8 masthead flashes briefly, and then the redirect fails with the following:
`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"https://fabric8-master1.dev.obfuscatedFQDN.com/"}`

Do I need to generate a fabric8 secret or pass an environment variable?  Although I can't imagine it is overly relevant, we are using LDAP as the *openshift_master_identity_provider*.

Thanks in advance!

**Comment by christian-posta** [comment]
try adding your FQDN to the fabric8 oauthclient?

oc get oauthclient fabric8 -o yaml > fabric8-oauthclient.yaml

add it to the last entry

then update the oauthclient

oc update -f fabric8-oauthclient.yaml

**Comment by lypht** [comment]
Thanks, Christian.  The FQDN entry is already present in the oauthclient, both for http and https.

**Comment by jmlambert78** [comment]
As we try to use f8 in multiple domains on Openshift, we separate the spaces by having multiple routes
eg: jml.myopenshift.... and toto.myopenshift
We install f8 inside each of the spaces to be independant
To solve the oauthclient issue of fabric8 account, we need to add more lines in the oauthclient by the manip given above.
Question is, how to automate this ?

**Comment by rawlingsj** [comment]
@jmlambert78 I think there might be an issue with gofabric8 updating the oauthclients when deploying fabric8 in multiple namespaces so we can definitely look at that to see if it's the automated step you need.

@lypht I'm wondering if the issue you're seeing is related to dns wildcards, I'm not an expert in this area but the routes and master urls that I have set up are separated by dots rather than the hyphen as you have in yours.  Just a guess but I wonder if you can try deploying with a domain without the hyphen?

i.e. 

```
gofabric8 deploy -y -d master1.dev.obfuscatedFQDN.com
```
and then access fabric8 console at 
```
http://fabric8.master1.dev.obfuscatedFQDN.com
```
__or__ if installing in multiple namespaces..
```
gofabric8 deploy -y -d mydifferentnamespace.master1.dev.obfuscatedFQDN.com
```
access fabric8 console at 
```
http://fabric8.mydifferentnamespace.master1.dev.obfuscatedFQDN.com
```

**Comment by lypht** [comment]
@rawlingsj Unfortunately, browsers only consider wildcards valid for subdomains one level deep. So in this example, the certificate would be valid for master1.dev.obfuscatedFQDN.com but not for fabric8.master1.dev.obfuscatedFQDN.com, thus the dash.  This is the same methodology used in openshift to expose routes: `{{ app }}-{{ namespace }}.{{ env }}.{{ FQDN }}.com`.  I'll continue to research...

**Comment by lypht** [comment]
I've altered the route, truncating the namespace entirely: `fabric8.dev.FQDN.com`.
I've been able to do a bit more testing with this issue, but with similar results.  When using an edge terminated route in openshift, I receive the error mentioned above.  When changing tls termination to passthrough, I no longer receive the error, and the site resolves with the fabric8 masthead, but I am not authenticated and the remainder of the console is blank.  This screengrab doesn't show much, but validates that oauth is not choking on the request:
![screenshot from 2016-02-01 10-45-13](https://cloud.githubusercontent.com/assets/11807059/12723861/f4a6aa02-c8d0-11e5-9ef7-904ad2bcac6d.png)

And here's the edge termination screenshot, in all its glory:
![screenshot from 2016-02-01 10-48-13](https://cloud.githubusercontent.com/assets/11807059/12723965/557e00f0-c8d1-11e5-8343-b6c4bf7525a4.png)

I have tested iterating the oauthclient redirect-uri path with the following values:
*https://master1.dev.FQDN.com:8443/oauth/authorize/*
*https://master1.dev.FQDN.com:8443/oauth/token/display/*
*https://master1.dev.FQDN.com:8443/oauth/token/implicit/*
*https://master1.dev.FQDN.com:8443/console/*
*https://master1.dev.FQDN.com:8443*

All of which throw the same invalid_request error if edge and not passthrough.  Is there additional information I can provide?  Can I enable openshift log oauth requests?

**Comment by lypht** [comment]
Hello, everyone.

I'm adding my resolution to this issue for posterity, in the event someone else runs into the same errors.  I had poorly assumed from the responses that the *only* uri I was to add was the authenticating body, but in truth, *https://master1.dev.FQDN.com* **and** the client redirect uri must be in the whitelist for oauth to process correctly.  Once I added *https://fabric8.dev.FQDN.com* to this whitelist, I was able to reach the fabric8 console.  [This article](https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/README.md) inadvertently led me to resolve my issue.

**Comment by lypht** [comment]
Update - @jimmidyson helped me on #5659.  Only the fabric8 redirect is needed.  Do not include the master FQDN.

**Comment by lsirigudi** [comment]
i am facing the oauth issue described above with fabric8 deployment on ocp3.6 .
corsAllowedOrigin is present in master-config.yaml
Included redirect urls in oauthclient and updated it.
Is there something else that needs to be configured in oauth?
