### ISSUE TITLE
formatting error in docs

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/fabric8#5637]
There is a formating (markdown) error in the docs under: http://fabric8.io/guide/getStarted/apps.html#console

the command is not in a separate box

**Comment by davsclaus** [comment]
You are welcome to submit a PR with the fix

**Comment by MarWestermann** [comment]
Hi Claus. I already did.. 5 minutes after I created the issue.

**Comment by davsclaus** [comment]
Ah sorry I didnt spot the PR - must be before I had my 2nd cup of coffee.
