### ISSUE TITLE
NodeJS workflow create a pod that does not disappear at the end of the job

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5643]
While using the nodejs sample application I have remarked tthat a build-pod-xxxxxxx is created and kept long run. It is the result of the kubernetes.pod() command in the groovy workflow.
Maybe one should add a delete pod action at the end, but I does not have the syntax to test.

**Comment by jmlambert78** [comment]
Is this normal ?

**Comment by rawlingsj** [comment]
The build pod should be cleaned up now.  There was a new release over the weekend which I've been using and seems to remove the pod used to build the image.

**Comment by jmlambert78** [comment]
This has been fixed since few days. OK
