### ISSUE TITLE
create top level project types for `Integration microservice`, `Go`, `Swift`, `Node.js` et al

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5656]
rather than folks exploring lists of archetypes, it be nice to have a curated list of top level project kinds that can just be picked from the console easily

**Comment by jimmidyson** [comment]
Use `Go` (preferred) or `Golang` (never `Go Lang` :-b).

& `Node.js` probably.

**Comment by jstrachan** [comment]
@jimmidyson thx :) Phew, I'd used "Go" in the Java code :)
https://github.com/jstrachan/fabric8-forge/blob/a44b9761e44dd61c5db9f6e8bf58761ea9545b30/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/projecttypes/GoProjectType.java#L26

**Comment by jimmidyson** [comment]
Yay!

**Comment by davsclaus** [comment]
I think we have them now, is there more to come ?

**Comment by jstrachan** [comment]
there's all the ones I think we need for now at least - lets close
