### ISSUE TITLE
kubernetes-api: default values not supported

### ISSUE THREAD

**Issue by WinstonSureChill** [fabric8io/fabric8#5657]
# Overview

I'm having some troubles creating a kubernetes service from a json file, using the kubernetes api.

When I write a json file to describe a kubernetes object, I don't fill all the fields, because Kubernetes has default values for some fields. For example, if you don't specify any namespace, kubernetes will assume you want to use namespace "default". However fabric8's api doesn't seem to take default values into account.

# Example

I'm trying to run a minimal test, where I load a json file, before creating a service object with `KubernetesHelper.loadJson()`. I then try to register the service in kubernetes using `KubernetesClient.services().create()`.

```
import java.io.File;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;

import io.fabric8.kubernetes.api.KubernetesHelper;
import io.fabric8.kubernetes.api.model.Service;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;


public class TestFabric8 {

    public static void main(String[] args) {

        KubernetesClient kube = new DefaultKubernetesClient();

        // Load service file into a string
        String svcContent = null;
        try {
            byte[] encoded = Files.readAllBytes(Paths.get("/root/svc.json"));
            svcContent = new String(encoded, Charset.forName("UTF-8"));
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Create service object
        Service svc = null;
        try {
            svc = (Service) KubernetesHelper.loadJson(svcContent);
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Print service object
        System.out.println();
        System.out.println("Service object:");
        System.out.println();
        System.out.println(svc);
        System.out.println();

        // Create service
        kube.services().create(svc);
    }

}
```

and the minimal json file (/root/svc.json):

```
{
	"kind": "Service",
	"apiVersion": "v1",
	"metadata": {
		"name": "svc",
		"labels": {
			"name": "svc"
		}
	},
	"spec": {
		"ports": [
			{
				"name": "port",
				"port": 8080,
				"targetPort": 8080
			}
		],
		"selector": {
			"name": "pod"
		}
	}
}
```

# Output

When running it, I get this output:

```
Service object:

Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, generateName=null, generation=null, labels={name=svc}, name=svc, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ServiceSpec(clusterIP=null, deprecatedPublicIPs=[], externalIPs=[], loadBalancerIP=null, portalIP=null, ports=[ServicePort(name=port, nodePort=null, port=8080, protocol=null, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={name=pod}, sessionAffinity=null, type=null, additionalProperties={}), status=null, additionalProperties={})

io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:145)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:184)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:475)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:206)
        at testfabric8.TestFabric8.main(TestFabric8.java:43)

```

It appears to crash because no namespace is specified for my service. Indeed we can see when printing the service object that its namespace value is set to `null` (instead of `"default"`).

So when creating the service object from the json content, all the missing fields are created, but instead of being set to the kubernetes default value, they are set to `null`. `null` values don't seem to be handled when later registering the service in kubernetes.

I also tested using Controller.apply() directly on the json file, but I get the same behavior.

However, using kubectl works perfectly:

```
# kubectl create -f /root/svc.json
service "svc" created
# kubectl describe service svc
Name:                   svc
Namespace:              default
Labels:                 name=svc
Selector:               name=pod
Type:                   ClusterIP
IP:                     10.10.10.229
Port:                   port    8080/TCP
Endpoints:              <none>
Session Affinity:       None
No events.
```

# Expected behavior

I was expecting that default values would be supported either:
* on creation of the Service object (`KubernetesHelper.loadJson()`);
* on registration of the service into kubernetes (`KubernetesClient.services().create()`).

**Comment by WinstonSureChill** [comment]
In fact my problem was during the registration of the service, I forgot to specify a namespace.

So line
`kube.services().create(svc);`
has to be replaced by
`kube.services().inNamespace("default").create(svc);`

Nothing to do with the handling of default values, my bad!

**Comment by jimmidyson** [comment]
I was thinking if we should handle default namespaces as you described above in a similar way to `kubectl`. Right now I think explicitly specifying the namespace is probably the best way, but we might want to default it from the kube config file if one is present.
