### ISSUE TITLE
[Vanilla Kubernetes] Last Fabric8 console doesn't show the "Run..." button : 2.2.107

### ISSUE THREAD

**Issue by theobolo** [fabric8io/fabric8#5677]
Hello everyone,

I've big problems to run fabric8 on azure with a kubernetes vanilla cluster.

I have an Azure cluster with Kubernetes, CoreOs, Docker and Weave on it.
3 ETCD  ; 1 Kubernetes Master ; 4 Kubernetes Workers
My cluster is behind a DNS cloud ; "cluster".cloudapp.net

I followed the "getting-started" guide on the Kubernetes repo.

I reach the Fabric8 console like that  > 

http://"my-cluster":8080/api/v1/proxy/namespaces/default/services/fabric8/

Since the last version, the namespaces are correctly discovered by the console.
I use the fabric8 kubernetes console 2.2.105.

My main problem is the installation of the CD pipeline;
In that console version, the "RUN" button is not display.

How can i fix that ?

Thanks
![issues](https://cloud.githubusercontent.com/assets/7281773/12679377/209248d0-c6a4-11e5-88fa-48f0af27e28f.jpg)

**Comment by theobolo** [comment]
I've noticed something strange, 

the proxy Kubernetes URL of the template pod is not correct : 

http://kube-4923a0cbf413ea.cloudapp.net:8080/proxy/namespaces/default/services/templates/

instead of 

http://kube-4923a0cbf413ea.cloudapp.net:8080**/api/v1/**proxy/namespaces/default/services/templates/

![issue2](https://cloud.githubusercontent.com/assets/7281773/12679613/62c6b622-c6a5-11e5-924e-f239f1a6a59f.jpg)

**Comment by jimmidyson** [comment]
@theobolo What version of Kubernetes are you running?

**Comment by reddog** [comment]
Hi @theobolo and others,

Don't know if my issue's related...?

Built Azure / CoreOS / Kubernetes cluster from these instructions:  [kubernetes.io/v1.1/docs/getting-started-guides/coreos/azure/README.html](http://kubernetes.io/v1.1/docs/getting-started-guides/coreos/azure/README.html)

Then installed Fabric8 from these instructions:  [fabric8.io/guide/getStarted/gke.html](http://fabric8.io/guide/getStarted/gke.html)

I had to manually create an endpoint with the Azure Node CLI as follows:

on `kube-00` to get the port Fabric8's running on:

`/opt/bin/kubectl get -o template --template='{{(index .spec.ports 0).nodePort}}' services fabric8 -L name=fabric8`

on local development machine (happens to be a Windows box), ran from `c:\kubernetes\docs\getting-started-guides\coreos\azure`:

`node_modules/.bin/azure vm endpoint create kube-00 8081 <port>`

Web interface loads at [xx.xx.xx.xx:8081/api/v1/proxy/namespaces/default/services/fabric8/](http://xx.xx.xx.xx:8081/api/v1/proxy/namespaces/default/services/fabric8/) but just displays 

> There are no namespaces currently available.

Chrome console shows messages like:

> WebSocket connection to 'ws://xx.xx.xx.xx:8081/api/v1/namespaces?watch=true&access_token' failed: Error during WebSocket handshake: Unexpected response code: 200

![image](https://cloud.githubusercontent.com/assets/151362/12681133/f71f1770-c6a4-11e5-8749-f6f30bdc4cff.png)

Any ideas?!

**Comment by theobolo** [comment]
@jimmidyson I run the last stable 1.1.7 kubernetes version.

@reddog

Did you expose the 8081 to the Fabric8 NodePort ? 

The Kubernetes API, that the websocket try to reach, is not on the 8081 but on the 8080.

If you use azure and kubernetes with fabric8, you just need to expose the 8080 on Kube-00; that is the API kube server.

After that you can reach the console at : 

http://yourdomain.cloudapp.net:8080/api/v1/proxy/namespaces/default/services/fabric8 and the console will reach the api without any errors.

When you map the console directly to the node port, the console thinks that you are running it on a openshift environnement.

**Comment by theobolo** [comment]
@reddog  I did the same, i took the nodeport and exposed it to the outside world (my nodeport was 36657 exposed to 36657)
: and i've got the same problem the console try to find the API on the wrong port.

If you do what i've described you will be able to reach the console.

**Comment by reddog** [comment]
Thanks for the tip @theobolo.  I've removed the `8081 `endpoint.  I already have 8080 exposed which is mapped to 8080 (internal) since I have already installed KubeUI.

So, trying the following URL:  [xx.xx.xx.xx:8080/api/v1/proxy/namespaces/default/services/fabric8/workspaces?q=](http://xx.xx.xx.xx:8080/api/v1/proxy/namespaces/default/services/fabric8/workspaces?q=)

When browsing Fabric8 on `8080 ` I get the same 

> There are no namespaces currently available.

error, but Chrome's console now shows some 404 errors, not websocket errors:

> GET http://xx.xx.xx.xx:8080/oapi 404 (Not Found)

> GET http://xx.xx.xx.xx:8080/jolokia 404 (Not Found)

> GET http://xx.xx.xx.xx:8080/hawtio/jolokia 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/151362/12682073/9b26b662-c6a9-11e5-8596-be299d982d70.png)

Any ideas from here?
Thanks!

**Comment by theobolo** [comment]
Yep that's better now.

Some of the Fabric8 versions are not fully fonctionnal you need to install the last version the 2.2.105.

You can do that : 

`kubectl delete all -l provider=fabric8
 kubectl delete serviceaccount fabric8
 kubectl create -f http://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.105/console-kubernetes-2.2.105-kubernetes.json`

After that you will be able to see the namespaces.

**Comment by reddog** [comment]
Thanks for that @theobolo.

Just to make future reader's copying & pasting easier, here's the commands to uninstall and re-install Fabric8:

```
kubectl delete all -l provider=fabric8
kubectl delete serviceaccount fabric8
kubectl create -f http://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.105/console-kubernetes-2.2.105-kubernetes.json --validate=false
```

(Validation turned off due to this bug [github.com/kubernetes/kubernetes/issues/18555](https://github.com/kubernetes/kubernetes/issues/18555) )

Here's my output:

```
core@kube-00 ~ $ kubectl delete all -l provider=fabric8
replicationcontroller "fabric8" deleted
replicationcontroller "templates" deleted
service "fabric8" deleted
service "templates" deleted
pod "templates-s36jp" deleted

core@kube-00 ~ $ kubectl delete serviceaccount fabric8
serviceaccount "fabric8" deleted

core@kube-00 ~ $ kubectl create -f http://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.105/console-kubernetes-2.2.105-kubernetes.json --validate=false
serviceaccount "fabric8" created
service "fabric8" created
service "templates" created
replicationcontroller "fabric8" created
replicationcontroller "templates" created
```

Close, but something's missing - now I get a HTTP `503` saying there's no endpoint...!

> no endpoints available for service \"fabric8\"

![image](https://cloud.githubusercontent.com/assets/151362/12682357/ea122cec-c6aa-11e5-85a6-d71d43d4dbe3.png)

There is still an endpoint for port `8080 ` listed in the Azure portal.

**Comment by theobolo** [comment]
Open a new private tab CTRL + SHIFT + N 
Reload the page in it.
Just wait 1min it's a commom issues when you run theses commands.

**Comment by reddog** [comment]
@theobolo that works - thanks!!

Out of interest, why the delay setting up the new service and hence the 503?

So the issue is that Fabric8 is trying to get to the Kubernetes API on the same port (and IP I guess) that Fabric8 has been accessed from, as opposed to being able to be told that Fabric8 is on one port, and the Kubernetes API is on another (which potentially could be changed by the user, I guess)?

Thanks very much for your help!

**Comment by theobolo** [comment]
I think that the 503 error is due of the cache and dns refreshing (cloud service) and the delay of the new pod deploiement. 

You'r welcome, 

By the way it's possible to tell to fabric8 where is the URI of the kube-api.
You need to edit the .json or the .yml of the fabric8 controller and add an ENV variable.

yml format :

- name: KUBERNETES_MASTER_URI = 
   value: "http://"yourdomain":8080"

And deploy again the fabric8 pod.
But i'vnt tried it yet.

You will be confronted to my actual problem now.

You can't run the Fabric8 CD pipeline to handle a fully fonctionnal pipeline for you applications.
That's the more interessting. :)

So i still need help on the main issues, 
Thanks :)

**Comment by theobolo** [comment]
So today i've tried the new 2.2.107 version of the Fabric8 console, i kept the same Kubernetes version : 1.1.7.

But still, i can't see the "RUN" button and there is no errors in the web-browser console,
Except the Jokolia and hawtio errors.

**Comment by theobolo** [comment]
Still not displayed on the 2.2.111 version of Fabric8.

**Comment by rawlingsj** [comment]
@gashcrumb  should the `Run` button be available so that the processed templates in the `Template` pod can be launched when deployed on vanilla kubernetes?

**Comment by gashcrumb** [comment]
@rawlingsj should be yeah thanks to the 'template' service, unless there's an issue with it or the console isn't using the right URL to get to it, let me have a look

**Comment by theobolo** [comment]
Yep i think that the console just try the wrong URL.

On that config with Vanilla Kubernetes there's a lot of bad URL.
Fabric8 sometime forget the Kubernetes API based URL, for example when i click on "Create a new APP"

It's redirect me to : 

`http://"my-cluster":8080/workspaces/default/forge/createProject`

Instead of : 

`http://"my-cluster":8080/api/v1/namespaces/default/services/farbic8/workspaces/default/forge/createProject
`

So i think that the "Run" button is just looking for the wrong URL and try to reach : 

`http://"my-cluster":8080/templates/`

Instead of :

`http://"my-cluster":8080/api/v1/namespaces/default/services/templates/`

I'm pretty sure that's just a wrong URL.

**Comment by gashcrumb** [comment]
K, think I have it working better, actually took quite a bit more work than just fixing the URLs, also fixed that link to the create project page.  If you want to try it now you can update your fabric8 RC to pull in the 'latest' tag of the console, set the image pull policy to 'Always' and then kill off the running pod, otherwise this'll all be in the next release.

**Comment by ankitforcode** [comment]
@gashcrumb can u please explain what you did to have the create app working as I am running into exact same problem. The fabric8 console is installed however is not able to connect to template pod.

**Comment by ankitforcode** [comment]
The "Run CD pipeline" button does nothing and takes to the console where it says to drag and drop the templates and none were found. Seems the URL referred are "oapi" for the api calls, also fabric8-forge seems to be missing in the installation which seems to be breaking the process.

**Comment by theobolo** [comment]
@ankitforcode For the moment Fabric8 is not Vanilla Kubernetes proof ;)
The Forge is not working correctly you right.

By the way @gashcrumb the last build 2.2.112 display the "Run..." and after 2 page refresh it able to display the templates. 

![templates](https://cloud.githubusercontent.com/assets/7281773/13033759/edfdc31e-d322-11e5-9bd9-b4d78e5da851.png)

And the webconsole 

![webconsole](https://cloud.githubusercontent.com/assets/7281773/13033761/f7fbbcfe-d322-11e5-8f52-2be5af70165e.png)

@ankitforcode Still not working for you ?

**Comment by geoHeil** [comment]
Which templates are impacted by "only works on openshift" does the CI-CD pipeline + chaosmonkey + codereview + git hosting work on plain kubernetes?

**Comment by theobolo** [comment]
I deploy a fresh new cluster today on Azure with the last Alpha release of Kubernetes and CoreOS.
I will try it out.

**Comment by theobolo** [comment]
Fixed !
