### ISSUE TITLE
[Vanilla Kubernetes] How to fix the /jokolia | /hawtio | /oapi 404 (not found) ?

### ISSUE THREAD

**Issue by theobolo** [fabric8io/fabric8#5684]
Hello everyone,

Kubernetes version : 1.1.7
Fabric8 version : 2.2.107

When i open the Fabric8 console i've some errors about Jokolia, Oapi and Hawtio.

![ussiues](https://cloud.githubusercontent.com/assets/7281773/12718771/0bb76a72-c8f1-11e5-9068-01f3fadcaa6a.png)

Any ideas ?

**Comment by gashcrumb** [comment]
Shouldn't be anything to worry about, those are just trying to discover what backend stuff is available so irrelevant pages/functions can be disabled.

**Comment by theobolo** [comment]
@gashcrumb Thx for the answer :)
