### ISSUE TITLE
Forge - project-new - Reorder the list

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5685]
```
? Project location [/Users/davsclaus/Documents/workspace]:

[0] (x) war
[1] ( ) jar
[2] ( ) parent
[3] ( ) addon
[4] ( ) resource-jar
[5] ( ) ear
[6] ( ) from-archetype
[7] ( ) swift
[8] ( ) django
[9] ( ) vert.x
[10] ( ) nodejs
[11] ( ) integration
[12] ( ) go
[13] ( ) from-archetype-catalog
[14] ( ) generic

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Project type: [0-14]
```

We should make those non java stuff come last, eg after 13 and 14 in that list.

**Comment by davsclaus** [comment]
@gastaldi just wonder if you guys would know if there is any way we can sort that list shown in the project-new wizard?

As you can see above the list is mixed with the out of the box from forge itself with new ones from fabric8.

**Comment by gastaldi** [comment]
Hi @davsclaus,

ProjectType has a priority() method. Make sure it is set to a higher value. 

I believe it is fine for generic to be last (since it is not bound to any specific technology and because its priority() method returns Integer.MAX_VALUE) :)

**Comment by davsclaus** [comment]
Thanks just what I need

**Comment by davsclaus** [comment]
Yay looks better now
```
? Project location [/opt/forge-distribution-3.0.0.Beta4/bar]:

[0] (x) war
[1] ( ) jar
[2] ( ) parent
[3] ( ) addon
[4] ( ) resource-jar
[5] ( ) ear
[6] ( ) from-archetype
[7] ( ) from-archetype-catalog
[8] ( ) integration
[9] ( ) django
[10] ( ) go
[11] ( ) nodejs
[12] ( ) rails
[13] ( ) swift
[14] ( ) vert.x
[15] ( ) generic
```

**Comment by gastaldi** [comment]
Many people asked for nodejs and vert.x support, so I wonder if we can make these project types part of core?

**Comment by davsclaus** [comment]
Fixed by PR
https://github.com/fabric8io/fabric8-forge/pull/119

**Comment by davsclaus** [comment]
Yeah I would make it optional though, so the project-new is minimal out of the box.

And then people can install addons for forge-node or forge-vertx if they wanna use those. There may be need for some forge commands to work with these project kinds.

Also I would consider rename `addon` to `forge addon`. Also what is a `resource jar` ?

**Comment by gastaldi** [comment]
Resource jar is a JAR without java classes (without src/main/java).
I think it makes sense to rename addon to forge-addon. Can you JIRA that?

Thanks
