### ISSUE TITLE
The kibana and ES logging fails

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5686]
I installed the management app on fabric8 from vanilla vagrant this morning. The kibana and ES pods keep crashing, but the grafana and promethesus is working fine.

I wonder if @jimmidyson is aware of any issues. Or anyone else have trouble with this?

**Comment by theobolo** [comment]
@davsclaus Yep same problem here again ;)

On my config, neither grafana or kibana are working. The services are looking for a bad URI if you access it by the api URL 

ex :  http://"your-domain":8080/api/v1/proxy/namespaces/default/services/grafana 

Grafana is looking for **http://"your-domain":8080/api/dashboards/home ** and not 

**http://"your-domain":8080/api/v1/proxy/namespaces/default/services/grafana/api/dashboards/home**
witch is working.

![fabric8](https://cloud.githubusercontent.com/assets/7281773/12719403/1f06db04-c8f5-11e5-98f1-a88623255b2c.png)

Ad If i map the container port to the outside by exposing it with and Azure endpoint 

![grafana](https://cloud.githubusercontent.com/assets/7281773/12719500/9906a5d8-c8f5-11e5-9c9b-6eb9e88ddc90.png)

Grafana is looking for 
http://"your-domain":35642/api/datasources/**proxy/1/api/v1/**query_range?query=etc........

**Comment by jimmidyson** [comment]
These are 2 separate issues: one is starting the ES pod, one is accessing grafana via Azure endpoint. @theobolo Could you open a separate issue for that?

**Comment by jimmidyson** [comment]
@davsclaus For some reason the permissions on one of the Docker containers' start scripts is wrong - trying to figure out why.

**Comment by jimmidyson** [comment]
But this seems to build with correct permissions locally...

**Comment by jimmidyson** [comment]
@rawlingsj @rhuss Any idea how a script with 755 permissions on filesystem ends up with 644 in image via d-m-p? Builds locally fine for me with correct permissions in image, just seems last release messed up permissions somehow.

**Comment by rhuss** [comment]
@jimmidyson could be an issue from which OS the image is build. There are known issue when done from Windows when using build-mode "dir" (the default). It is recommended to use mode "tar" --> https://github.com/rhuss/docker-maven-plugin/issues/127

**Comment by rhuss** [comment]
@jimmidyson do you have a pointer how the ES image is built with d-m-p ?

**Comment by rawlingsj** [comment]
Odd.  Do you think the CD env affected it when building the images?

**Comment by rawlingsj** [comment]
I've noticed a couple of unrelated issues with the CD environment lately and am struggling to get a release out right now, I think I'm going to recreate the jenkins job, once done I can kick off a fabric8-devops release and we can take a look at the file permissions in the workspace if that helps?

**Comment by jimmidyson** [comment]
@rawlingsj Sure - I'm just going to try to force the fileMode to be on the safe side too so please wait for that.

**Comment by rawlingsj** [comment]
@jimmidyson sounds good

**Comment by rhuss** [comment]
could be. if no 'fileMode' is set in the assembly descriptor, then the actual permission permission is used (as created by the git checkout).

**Comment by jimmidyson** [comment]
@rhuss See https://github.com/fabric8io/fabric8-devops/blob/master/elasticsearch/pom.xml#L81-L114. This is actually an ES config sidecar container with just a single script in to run...
