### ISSUE TITLE
provide a way to manage non-docker and non-linux processes elegantly within Kubernetes so that Kubernetes acts as a global view and toolchain for the system

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5691]
Its important to many folks to be able to run and manage processes on non-linux and/or non-docker runtimes. e.g. folks running Java apps on Windows, AIX, Solaris, HP-UX. It would be great to have a simple way to manage things; so that it looks and feel like everything is really running on Kubernetes; but have external machines running stuff using simple shells scripts and tools like Ansible. Quite a few folks have asked for a unified kubernetes-like view and experience over their Linux + non-Linux hosts.

So Jenkins Pipeline can easily support [Ansible and running playbooks](https://github.com/jenkinsci/ansible-plugin#workflow-support) so how's this for a simple idea of how to bridge the non-Linux and non-Docker worlds to Kubernetes with minimal development and support effort while providing a unified kubernetes experience:

* folks create a zip/tarball of their app with start/stop scripts to run on a non-docker/linux platform along with an Ansible playbook to install and run the tarball (along with check its running and to restart if failed etc)
* we define an Ansible Inventory in a text file in a git repo to list the machines to run the app on for a given namespace
* on git push of the Ansible Inventory git repo we trigger a Jenkins build which does the following:
  * generates a Replication Controller for each playbook / tarball and set of hosts; with the size of replicas being the number of processes/hosts listed in the Inventory and the docker image being the `ansible supervisor` and adding a git volume for the playbook / inventory metadata mounted at a canonical folder for the docker image to use
  * generates a Service (with an external LoadBalancer) if it doesn't exist already for the app (if you wish to expose it) along with generating an Endpoint for all host names in the inventory: inserting/updating/deleting Endpoints as required. Then the app itself can use Kubernetes style service discovery; e.g. http://foo/ for a service named foo; provided we also ensure there's a DNS resolver or /etc/hosts that points to the external kubernetes load balancer.
* now if your inventory says to run 5 tomcat tarballs/zips, kubernetes will start 5 supervisor pods for your tomcat RC using the usual RC semantics
* each supervisor pod now loads the inventory from its git volume and finds the list of hosts to run the playbook on; so it grabs one of the host names; by querying the RC's annotations to find what hosts are already owned by what pods; it removes the hosts that are owned and picks a random remaining host name. It tries to do an optimistic update of the RC (using the resourceVersion number in kubernetes) to add an annotation of `ansible.fabric8.io/$POD_NAME=hostname` to define the ownership of one of the host names from the inventory.  If the update works, the pod won and owns that host name and the RC reflects that to all other pods and the outside world; otherwise it sleeps a random amount of time and tries again. If there are no more available host names it terminates. Eventually each pod should grab a unique hostname.
* now each pod will own a host from the inventory and the RC will be annotated with the mapping of pod name -> host name in case anyone wants to look at a specific host from the inventory
* each pod then runs the ansible playbook for the host to install and run the tarball if its not already running; then it tails the log to stdout so that we get centralised logging of all the remote apps in the usual centralised logging way on kubernetes / openshift
* it would be extra awesome to also add an annotation to expose Prometheus metrics on the pod from the remote process; maybe we need a little proxy in the pod from the pod's IP and a port to the remote port inside the the remote process? Or maybe we add the prometheus annotation using the actual remote host name and port so that no proxy is required? Either way, centralised metrics and alerts is awesome!
* the pod should act as a supervisor - in the systemd kind of sense - so that it monitors the liveness of the remote process and restarts it if necessary. This helps run stuff on remote operating system without having to deal too much with the difference of supervisors on different operating systems (e.g. windows versus AIX versus solaris etc)
* if the pod finds it can no longer communicate with the remote machine it should just terminate

The Jenkins build should also check when its updating the RC; are any of the current pods for the playbook (using labels and/or annotations) associated with old hosts that no longer exist in the inventory and if so they should be deleted. e.g. the inventory may say run the app on hosts `A, B, C`; after some time there's pods for those 3 hosts, then C is removed from the inventory. So the Jenkins build should check if any pods need to be deleted (i.e. it should delete the pod for C)

We need to ensure that the supervisor pod is small and lightweight; e.g. a small golang process in a small alpinelinux image.

What is awesome about all of the above is that:

* kubernetes does the load balancing and service discovery of all the things your app needs; by getting non-Linux and/or non-Docker processes to use external load balancers inside Kubernetes to access services. This does require some config on the host to ensure DNS points to the right service in the right namespace though. Worst case maybe we use environment variables? That might be simpler than DNS? Particularly if multiple apps get provisioned on the same host which talk to different services in different namespaces? But everything's meant to be a DNS problem right? :)
* the App Dashboard console in fabric8 now views all environments, via kubernetes with RCs and pods - whether the software is really running on kubernetes/docker/linux or not. i.e. a consistent real time view for any operating system. Also there's a consistent way to view and supervise the system and its logs. e.g. `kubectl get pods` or `kubectl log` etc. The command line tools `oc` and `kubectl` just work - apart from scaling of the RC - it looks and feels like a regular RC / pods / services. Even that, one day we could maybe do something along those lines; e.g. human workflow to update the inventory to add a new box to install the software on ;)
* we have a single user experience for managing all containers and processes; letting folks work as if all workloads are in docker on kubernetes; letting folks migrate from Windows / AIX / Solaris / HP UX as and when they can; while having a consolidated tool chain during the migration. Another way of saying that is all the crusty old stuff suddenly gets all hipster and developers and operations folks can just pretend the world turned into the coolness of docker and kubernetes overnight; while still working with the old and/or legacy operating systems! We then all get closer to kubernetes awesome faster, irrespective of legacy
* folks using non-docker can now get lots of the benefit of fabric8, kubernetes & OpenShift; while using legacy operating systems - such as CI / CD, service discovery, a unified dashboard and console along with centralised logging, metrics and alerts. The main missing feature is auto scaling and the extra cost of the supervisor processes; which is fairly minimal and hopefully acts as a nice motivator for folks to incrementally move microservices, one at a time, to docker and linux where things get even more awesomer ;)

### Extra beer tokens for more awesome

* it would be pretty cool when the fabric8 console opens a terminal for a pod or when using `oc exec` / `docker exec` on a pod that the execution of `bash` or `sh` really ran an ssh command to open a shell (depending on the OS) on the actual remote process. i.e. you get a shell on the box in the same way as using docker; the supervisor pod just acts as a proxy, forwarding shell input/output. Running bash on the pod really runs a ssh shell on the real remote pod!
* the supervisor implements kubernetes style liveness checks on the remote process, restarting where possible
* port the ansible supervisor to Chef / Puppet / Salt too along with similar Jenkins builds to spin up RCs etc; its just the actual docker image name of the pod template in the RC would differ based on the kind of tool used to install and manage the tarball/zip

### Remaining questions

* What if a supervisor cannot start the playbook properly? Should it keep retying forever or have some kind of back off and fail? Maybe it needs to annotate the RC when it decides it cannot use a host?

### Summary of development work

* a Jenkins pipeline/build that triggers on commit to the inventory / playbook repo that does the above (generates and applies the RC, Service and Endpoints - doing a create/update/delete as required)
* a docker image for the ansible supervisor; that grabs a host name, runs the playbook on a single host, tails the log and does liveness / restart checks
* have a few beers; we just made non-linux and non-docker feel almost as awesome as real kubernetes ;)

**Comment by jimmidyson** [comment]
Now that Docker supports Windows why wouldn't we try to extend Kubernetes to run on Windows?

**Comment by jstrachan** [comment]
@jimmidyson absolutely; if Kubernetes/OpenShift and Docker works on any other platforms we should try use that first - providing the customers operating system is new enough. 

Though I suspect some windows folks are stuck on old versions; and its probably gonna be a while until Docker + OpenShift is GA on Windows. Even then, there's still lots of folks using AIX, Solaris and HP-UX to think of too.

**Comment by rhuss** [comment]
Sounds like a plan ;-) (albeit probably a complex one ;-)

If I understand right, the goals are

1. having a uniform view from within Kubernetes to the legacy systems
2. having a way to deploy and lifecycle manage legacy systems (via automatic triggering Jenkins workflows which communicate with legacy via Ansible playbooks)
3. providing a way for apps on legacy platforms to consume Kubernetes managed services (from the 'new world')

This would be awesome. I'm a bit afraid thought that it will be quite hard to achieve the aimed overall uniformity in managing legacy systems and Kubernetes objects. 

IMO there should be a clear separation (or at least indication) of this kind of legacy support in any UI so that people are aware that these are different with different facilities (except, of course, I we can achieve complete equivalence)

fwiw I will be off till thursday now (skiing ;-), but really interested on how this evolves :)

**Comment by jstrachan** [comment]
@rhuss am snow boarding from tuesday next week too ;) hope we get good snow!

Your understanding sounds about right to me. Its really about using CI / CD to provision things via tools like Ansible but also trying to reuse the fabric8 console so folks get the same kind of visualisation of environments and using the supervisor pods to act as a kind of proxy and to perform keep alive checks and expose logs and metrics. 

A big motivation for this idea is to help Fuse customers who are currently using fabric8 v1 so that they can easily move to fabric8 v2 without having to make widespread changes of all their machines and operating systems to a modern linux + docker; some folks may be stuck for a while on old operating systems or non linux; so the idea was to use this approach as a migration tool; any new app folks write can be on native linux + docker; while over time folks can migrate stuff that only works on Windows / AIX / Solaris / HP-UX across to docker when possible. Ideally folks would eventually get to a pure docker + kubernetes approach.

I'm sure with annotations and labels we can make it clear that the pods are supervisors (rather than the 'real thing') and can be annotated with the actual real host and pid of the underlying process so that we can create some custom tools or visualisation for the external processes,

**Comment by chirino** [comment]
+1. One big feature that Fabric v1 customers loved was provisioning the Karaf container and also managing the container start/stop lifecycle.  With this approach it sounds like were completely covering that use case.

I would even be willing to live without all the K8 service discovery stuff if I have to.  Just providing app deployment and lifecycle management is awesome enough for these external platforms.  So Id' say sorting the DNS bits is optional.

@rhuss re: "clear separation (or at least indication)" if the supervisor image that is being used is not clear enough we could add some additional label to help clarify.  Perhaps add labels to indicate which remote host is being used? 

We should probably require the remote processes to follow the same docker convention of outputting logging to the console and to run in the foreground.  That should allow the supervisor pod uses a remote ssh command to execute the process, and pass the logging back to the pod.  And if the SSH connection fails, the remote process should also get killed.  We then have to worry less about process still running after a pod is terminated.

RE: "What if a supervisor cannot start the playbook properly?"  We should do that same thing as running an image who's run command fails.

**Comment by jstrachan** [comment]
@chirino agreed with all that. On the service discovery; its so trivial to generate a Service and Endpoints; worst case we could just pass in an environment variable in the Ansible playbook so that the remote app in the tarball just talks to the public URL directly of the external service.

**Comment by dhirajsb** [comment]
It would be nice to have a way of discovering what's on an Ansible machine, both for reconnect after a pod can't reach an ansible host, and possibly auto-configuration of pods for existing Ansible deployments. Perhaps Ansible has something for that??

**Comment by jstrachan** [comment]
FWIW I've a little prototype using spring boot's systemd / init.d stuff here:
https://github.com/fabric8io/fabric8-ansible-spring-boot

I've not found a way to run an ansible playbook and return the output of a command yet. 

So it might be simplest to try a pure SSH version (which we can port to PowerShell later for Windows) to download & install a JVM then install a tarball, unpack it and run it etc - like we used to do in fabric8 v1 to install a karaf distro etc?

**Comment by jstrachan** [comment]
I'm hoping we can still use Ansible to provision and install a JVM and the tarball; unpacking as required and setting up whatever permissions and users and stuff. 

Then hopefully there's a way to run the command inside the supervisor pod and capture stdout and stderr. So far I've not figured out the Ansible magic to do the latter; we may have to just drop down to ssh / PowerShell for that bit ;) but it'd be great to be able to reuse the inventory for the actual IP address, ssh user, keys and stuff

**Comment by jstrachan** [comment]
Its increasingly looking like Ansible [doesn't have support for interactively grabbing the output of commands](https://github.com/ansible/ansible/issues/3887#issuecomment-54672569) other than when a command terminates. 

So we can either:

1. use services to run stuff as part of the playbook; then the supervisor pod can tail the canonical log (and periodically check if the service is still up and if not restart it)
2. use Ansible to install the app, then run it via direct ssh / powershell on the box tailing the output

It seems that 2 is simpler really; folks could always hack their playbooks to do (1) if they prefer - the command to run the app is then just to tail the output

**Comment by jstrachan** [comment]
BTW there's a prototype of the gosupervise here: https://github.com/fabric8io/gosupervise so far it seems to be working if ran manually outside of kubernetes; next step is to dockerize / kuberize and get the RC creation automated...

**Comment by valdar** [comment]
+1: this would be a great tool for migrating fabric8 v1 projects/installations to k8/fabric8 v2.

**Comment by jstrachan** [comment]
@valdar thanks! I'm hoping we should have a working prototype this week so folks can try it out

**Comment by jstrachan** [comment]
@dhirajsb BTW on your discovery question; right now the route we're taking is the Ansible playbook provisions whatever version of software is required to disk (in its own versioned area of the file system); then the supervisor pod runs the right version of the software - if the pod is terminated the old version stops. 

So when we apply a new version we can stop the pods running the old version and run a new version etc. I'm hoping we can even make use of Kubernetes's rolling upgrades to perform rolling upgrades of software ;) (as we create a new RC for the new version and roll pods over to the new version etc)

So there's no discovery per se, but you can run the playbook as many times as you like; it just ensures the right version is installed. A separate background playbook could garbage collect old installations I guess too. Or maybe the playbook could ensure there's only, say, 2 versions installed at any time, removing older versions etc

**Comment by jstrachan** [comment]
who-hoo! Its working!

Follow [these instructions](https://github.com/fabric8io/gosupervise#for-fabric8-ansible-spring-boot) and you should get 2 pods remotely running the spring boot example and tailing the logs. You can then scale the RC up and down as you like and view the logs of the remote processes inside kubernetes / Kibana etc

**Comment by jstrachan** [comment]
I'm pondering renaming the `gosupervise` project and binary to `kansible` for k8s + ansible as the term and command to type to get kubernetes and ansible rocking together. Has a nice catchy ring to it. Unless anyone has any better ideas?

**Comment by jstrachan** [comment]
I'm gonna mark this issue as resolved thanks to kansible: https://github.com/fabric8io/kansible then we can use the other [kansible issues](https://github.com/fabric8io/kansible/issues) to track more fine grained issues relating to kansible
