### ISSUE TITLE
Cannot deploy continuous delivery on native openshift

### ISSUE THREAD

**Issue by xelfe** [fabric8io/fabric8#5697]
I'm trying to make fabric8 working on the top of our openshift origin 3.1. The deploiyement with fabric8 installer look to be good except during the "./gofabric8 secrets" stage where I got some warning about "no such file" or "secrets already exists" ...

Whatever I can log in the fabric8 console but when I'm trying to deploy the pipeline, openshift give me this complaintfor jenkins;

`Error creating: Pod "jenkins-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.privileged: invalid value 'true', Details: Privileged containers are not allowed provider restricted: .spec.containers[0].securityContext.VolumeMounts: invalid value 'data', Details: Host Volumes are not allowed to be used] `

and this one for fabric8-forge;
`Error creating: Pod "fabric8-forge-" is forbidden: service account gotya/fabric8 was not found, retry after the service account is created `

Anyone know what's going wrong ? Every other things work great on our openshift installation.

**Comment by rawlingsj** [comment]
I dont think this is down to the `gofabric8 secrets` step, the warnings are there really just to highlight there were no secrets found on your filesystem to import so gofabric8 generates secrets instead.

The errors you added above seem more to do with the `gofabric8 deploy` step.

Can you check the console output if you run `gofabric8 deploy` again and make sure the SecurityContextConstraints are created correctly.  It also looks from the forge error that the fabric8 service account wasnt created so it would be good see the output of `oc get sa`

The start of my console output shows the SecurityContextConstraints being created...

```
Starting fabric8 console deployment using 2.2.111...

SecurityContextConstraints restricted is configured correctly
SecurityContextConstraints restricted.........................................✔
SecurityContextConstraints fabric8 is setup correctly
SecurityContextConstraints fabric8............................................✔
addClusterRoleToUser cluster-admin system:serviceaccount:default:fabric8......✔
addClusterRoleToUser cluster-admin system:serviceaccount:default:jenkins......✔
addClusterRoleToUser cluster-reader system:serviceaccount:default:metrics.....✔
```

**Comment by xelfe** [comment]
Thanks to your reply. This is what I got;

```
./gofabric8 deploy -d app.domain --api-server=master.domain;
SecurityContextConstraints restricted is configured correctly
SecurityContextConstraints restricted.........................................✔
SecurityContextConstraints fabric8 is setup correctly
SecurityContextConstraints fabric8............................................✔
addClusterRoleToUser cluster-admin system:serviceaccount:default:fabric8......✔
addClusterRoleToUser cluster-admin system:serviceaccount:default:jenkins......✔
addClusterRoleToUser cluster-reader system:serviceaccount:default:metrics.....✔
addServiceAccount metrics.....................................................✔
addServiceAccount router......................................................✔
fabric8 console...............................................................✔
```
oc get sa;
```
NAME  SECRETS  AGE
builder    4         35d
default    3         35d
deployer 2         35d
fabric8    2         4m
metrics   2         4m
registry   3         35d
router     4         35d

```

Every thing looks good until I run cdelivery. Fabric8-docker-registry, gogs, gogs-ssh and and nexus running but not jenkins and fabric8-forge with the errors I gave.

**Comment by xelfe** [comment]
I got it working, but I have to create project into default workspace.. it is what I was supposed to do from the begin ? I was thinking that only the deployement of fabric8 had to be on default and after any workspace can deploy the continuous delivery...

**Comment by rafaeltuelho** [comment]
Sorry by commenting in a close issue. But I got the same problem describe here. I tried to deploy the `cd-pipeline` in a new namespace I created (eg. `ci-cd`)
Can someone explain why we have to deploy the `cd-pipeline`  template on default namespace? This is not so clear on `fabric8` installation docs.
