### ISSUE TITLE
fabric8 1.x quickstarts demo README.md files has a few broken links and wrong instructions

### ISSUE THREAD

**Issue by jluo** [fabric8io/fabric8#5698]
For instance, this README.md file from karaf camel-amq demo:
https://github.com/fabric8io/fabric8/blob/1.x/quickstarts/karaf/camel-amq/README.md
has four broker links:
https://raw.githubusercontent.com/fabric8io/fabric8/master/docs/images/camel-amq-quickstart-diagram.jpg
https://raw.githubusercontent.com/fabric8io/fabric8/master/docs/images/mq-broker-groups.png
https://raw.githubusercontent.com/fabric8io/fabric8/master/docs/images/mq-client-create-wizard.jpg
https://raw.githubusercontent.com/fabric8io/fabric8/master/docs/images/camel-endpoint-choose.jpg

And the instruction:
Section: Using the web console
Sub-section:  Installing the quick start
Bulletin point #6 says:
6. In the Create New Container page, in the profiles filter field enter my and select the mq-client-mygroup from the list, as shown in the figure below. We do this so the client connects to correct A-MQ group; as you can have multiple broker groups in fabric8.

However,  there is no "profiles filter field" on that page when you following the instruction. In fact, you will need to go ahead and create the child container without the "mq-client-mygroup" profile. After the child container is created, you will need to go to the child container by clicking the child container you just created, then you will have the profiles filter field displayed. You can then follow the instruction and add the mq-client-mygroup profile to the container. After that, continue with the rest of instruction in order to test the demo.

And other demos also have broken links and we might need to clean them up. For instance, this one:
https://raw.githubusercontent.com/fabric8io/fabric8/1.x/quickstarts/karaf/beginner/camel-cbr/README.md
has a broken link:
https://raw.githubusercontent.com/fabric8io/fabric8/master/docs/images/camel-cbr-diagram.jpg

**Comment by davsclaus** [comment]
fabric8 v1 is maintained as part of jboss fuse, you can find it there
https://github.com/jboss-fuse/fabric8
