### ISSUE TITLE
elastic Search crashes in the nodejs pipeline.

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5699]
In the workflow for nodejs, I get some elasticsearch crash 
here is the log http://pastebin.com/JfzGpeWW
Not blocking, but data included

**Comment by rawlingsj** [comment]
Yeah this is really just a warning if elasticsearch isn't running.  We now send deployment events if it is.  The exception is tidied up and code to check if elasticsearch is running with this commit https://github.com/fabric8io/kubernetes-workflow/commit/a6f291501b9e3c3fc594b0cfb6fb8758ab6222f0

Will be in the next release.

**Comment by rawlingsj** [comment]
This is fixed and released now.
