### ISSUE TITLE
Scaling pods (fabric8 generated image on local registry) scaling does not support multi hosts

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5703]
I have a nodejs pipeline that deploy in staging & prod env 
I work on a 3nodes OO with all nodes scheduleable
When for example the app is on Node1 for its first instance, the scale to 2 is creating a new Pod on another machine and it is where the pb comes : 
- The pod is created and stays in pending mode, for a while, and the image is not pulled to the local machine.
- I pulled manually from the ssh console on that node the image, then I play to scale more and the next pod allocated to that machine is fine, but the 1 initialy launched is staying pending

I do not understand if this comes from the fact that the image is on a local registry

**Comment by rawlingsj** [comment]
I've tested this today on a multi node cluster and I had no issue.  Could you see if there are and events on the rc or pod?  i.e. `oc get events` or `oc describe rc yournoderc`

**Comment by jmlambert78** [comment]
After this issue opening, I got success scaling. Consider this as closed. Thx
