### ISSUE TITLE
fabric8-console - Add events page

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5704]
I would like to have a events page, like we have for pods, services and so on.

Then on that page we can show all the events for the namespace. And you can filter on kind (pods, rc, etc). and whatnot.

Today you can only find these events by click on each pod, rc etc.

But sometimes you want to see them all, eg like

oc get events

**Comment by jstrachan** [comment]
BTW I added an events page a few months back; if there's an event on a pod, you get the event count on the pods page which links to the events page - filtering on that pod id etc.

We're just missing an Events link on the nav bar. 

e.g. this link should work right now: http://fabric8.vagrant.f8/kubernetes/namespace/default/events
