### ISSUE TITLE
fabric8 release failing, sonartype "signature-staging" failures

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5737]
The quickstarts are now enabled which is causing an issue during the release as the license signing hasnt happened on the karaf quickstarts...

```
[ERROR] Rule failure while trying to close staging repository with ID "iofabric8-2165".
[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] Repository "iofabric8-2165" failures
[ERROR]   Rule "signature-staging" failures
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-amq/2.2.99/karaf-camel-amq-2.2.99.zip.asc' does not exist for 'karaf-camel-amq-2.2.99.zip'.
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-amq/2.2.99/karaf-camel-amq-2.2.99.tar.gz.asc' does not exist for 'karaf-camel-amq-2.2.99.tar.gz'.
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-log/2.2.99/karaf-camel-log-2.2.99.zip.asc' does not exist for 'karaf-camel-log-2.2.99.zip'.
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-log/2.2.99/karaf-camel-log-2.2.99.tar.gz.asc' does not exist for 'karaf-camel-log-2.2.99.tar.gz'.
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-rest-sql/2.2.99/karaf-camel-rest-sql-2.2.99.zip.asc' does not exist for 'karaf-camel-rest-sql-2.2.99.zip'.
[ERROR]     * Missing Signature: '/io/fabric8/quickstarts/karaf-camel-rest-sql/2.2.99/karaf-camel-rest-sql-2.2.99.tar.gz.asc' does not exist for 'karaf-camel-rest-sql-2.2.99.tar.gz'.
```

As far as I can tell this is because the karaf quickstarts build the zips and tar.gz in the package phase however the license signing needed by sonartype needs them to be created during install.
https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/karaf/camel-amq/pom.xml#L246

I'm not sure of the impact of changing this to install but certainly the tests fail.

@chirino @dhirajsb I'll disable the quickstarts so that we can get this release out but could one of you look at the karaf examples so that the tarballs are created in the `install` phase so that the license signing takes place during the release?  Then we can include the quickstarts again.

**Comment by dhirajsb** [comment]
@rawlingsj it sounds strange to me since maven convention is to create packages during `package` phase. I think I should be able to change it to `install`, I'll do it today. 
Do we have to do the same thing on the `redhat` branch, or is it unrelated to the license signing on the `master` branch?

**Comment by rawlingsj** [comment]
@dhirajsb sorry I got my package / install comments back to front, [it's currently at `install` ](https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/karaf/camel-amq/pom.xml#L246)which causes the problem above, it's my best guess that the signing issue is because the karaf assembly should be at `package` which it wasn't set at when added.  From your comment above that convention is to create it at package maybe this is not much of an issue and needs changing along with addressing the integration test failure after doing so.

**Comment by rawlingsj** [comment]
fixed thanks for sorting that @chirino
