### ISSUE TITLE
cannot interact with openshift

### ISSUE THREAD

**Issue by xelfe** [fabric8io/fabric8#5738]
I'm giving a try again on a new openshift fresh install using gofabrib8 installer  deploy. Everything looks ok, I can login to the fabric8 console with my admin user without any problem. The problem is when I'm trying to deploy the continuous delivery , or any action via the fabric8 console, nothing happen. I got only a refresh page and I cant see any errors messages. The datas going like into only one way, because I can see alls the info about my openshift install but cannot doing any action on it.

**Comment by rawlingsj** [comment]
hi @xelfe, are there any errors in the browser java script console?

**Comment by xelfe** [comment]
yeah like this Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)

**Comment by rawlingsj** [comment]
hmm not sure, is there anymore to the log message which might help us figure out what it's doing?

You could try and run the cd-pipeline from the CLI to see if that works, just replace the DOMAIN below with your value..

```
oc process cd-pipeline -v DOMAIN=yourdomain.io | oc create -f -
```

**Comment by xelfe** [comment]
@rawlingsj 

> hmm not sure, is there anymore to the log message which might help us figure out what it's doing?

Sure. This is a full part of my console;

```
Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)
libs-5ee70f0e.js:9 [Kubernetes] Failed to create namespace: user-secrets-source-admin: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json, application/yaml","reason":"UnsupportedMediaType","code":415}

Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)
libs-5ee70f0e.js:9 [Kubernetes] Failed to update Service name: fabric8-docker-registry ns: default error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json, application/yaml","reason":"UnsupportedMediaType","code":415}
```

> You could try and run the cd-pipeline from the CLI to see if that works, just replace the DOMAIN below with your value..

Doing "oc process cd-pipeline -v DOMAIN=app-prefix.mydomain | oc create -f -" Looks good. Every pods od cd is starting

**Comment by gashcrumb** [comment]
I actually just fixed this on Friday, might just need a new console release
to pick up the fix.

**Comment by rawlingsj** [comment]
Ah brilliant.  A new release is on it's way and should be finished in the next hour or two.

**Comment by xelfe** [comment]
@rawlingsj 

What's gonna be the better way to make an update ? Each time that I'm trying de re-install a lot of stuff stay on my openshift indeed I do "oc delete all -l provider=fabric8"

**Comment by rawlingsj** [comment]
yeah that;s normally what I do too, that and delete the templates..

```
oc delete all -l provider=fabric8 && oc delete templates --all
```

**Comment by xelfe** [comment]
Since the last commits, I can create project into fabric8 console but still cannot deploy the CD.
This is what I got into my javascript console when I try to deploy them;

```
Uncaught TypeError: (intermediate value)(...) is not a function(anonymous function) @ libs.js:276005
libs.js:39319 [hawtio-oauth] All oauth plugins have executed

POST https://master.my-domain:8443/api/v1/proxy/namespaces/default/services…mand/execute/devops-get-overview?secretNamespace=user-secrets-source-admin 

[Forge] Failed to load https://master.my-domain:8443/api/v1/proxy/namespaces/default/services…mand/execute/devops-get-overview?secretNamespace=user-secrets-source-admin [object Object] 404
```

The return of https://master.my-domain:8443/api/v1/proxy/namespaces/default/services…mand/execute/devops-get-overview?secretNamespace=user-secrets-source-admin is;

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"proxy\" \"services\" with name \"fabric8-forge\" in project \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "fabric8-forge",
    "kind": "services"
  },
  "code": 403
}
```

**Comment by gashcrumb** [comment]
Should be working now in 2.2.116, may need to clear your browser cache after updating to be on the safe side.

**Comment by xelfe** [comment]
Nice. Thank you !

**Comment by HananAwwad** [comment]
I have the following error only when i am using the jboss developer studio
"The body of the request was in an unknown format - accepted media types include: application/json, application/yaml
Could not create resource dsd in namespace '': {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json, application/yaml","reason":"UnsupportedMediaType","code":415}
" 

Please help
