### ISSUE TITLE
Issue to deploy a template in Fabric8 Console, since today. 

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5740]
I have a fresh start on the v115, and while pushing on the cd-pipeline button in the console UI i get this message : http://pastebin.com/b3xs4NdQ
I have tried to change the console to 113 to see 
While clikin on the manage default refresh I get this exception as well.
Uncaught TypeError: (intermediate value)(...) is not a function(anonymous function) @ libs.js:276005
libs.js:39319 [hawtio-oauth] All oauth plugins have executed
libs.js:39319 [kubernetes-watcher] Backend is an Openshift instance
libs.js:39319 [k8s-objects] Using polling for kind:  imagestreamtags
libs.js:39319 [k8s-objects] This:  t {restURL: "https://oshift.paaxxx.com:8443/oapi/v1/namespaces/default/imagestreamtags", handler: t, _lastFetch: Array[0], log: s, _connected: false…}
libs.js:39319 [k8s-objects] Using polling for kind:  projects
libs.js:39319 [k8s-objects] This:  t {restURL: "https://oshift.paasxx.com:8443/oapi/v1/projects", handler: t, _lastFetch: Array[0], log: s, _connected: false…}
libs.js:39319 [fabric8-console] started, version:  1.0.73
libs.js:39319 [fabric8-console] commit ID:  d8dcd57cc28596af2299bbe06011793365e5fee0

**Comment by xelfe** [comment]
same as me; https://github.com/fabric8io/fabric8/issues/5738

**Comment by gashcrumb** [comment]
Fixed [here](https://github.com/hawtio/hawtio-kubernetes/commit/f06965488e83999aae42c3ae5115c47dbdce5c62) just kicked off a fabric8-console build in case you want try the 'latest' tag of the image, build is [here](https://circleci.com/gh/fabric8io/fabric8-console/735)

**Comment by jmlambert78** [comment]
I saw also some issue on the secrets window, will check the release fixes that as wel

**Comment by jmlambert78** [comment]
I got the last version, but i cannot deploy even with the latesst verion of console.

**Comment by gashcrumb** [comment]
Should be working now in 2.2.116, may need to clear your browser cache after updating to be on the safe side.

**Comment by jmlambert78** [comment]
issue is fixed by the version 
fabric8/fabric8-console:2.2.114
fabric8/fabric8-forge:2.2.125
fabric8/jenkins-docker:2.2.113
