### ISSUE TITLE
Problem in the build process of node, go etc with an exception in jenkins

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5743]
I have got a problem since this weekend on nodejs & go building in f8
http://pastebin.com/mbYQfbk8 for go issue
http://pastebin.com/RaKZPb4m for nodejs issue
We are stuck in building new images. 
thx for help

**Comment by jmlambert78** [comment]
after test of the today's release, I find that the build works, but not the deploy steps
 I have got on the last release : ERROR: Error during kubernetes apply: Cannot find resource `environmentAnnotations.properties` on the classpath!  Finished: FAILURE
[20:39] <jmlambert78> it is building, pushing image, but not deploying
[20:40] <jmlambert78> you may reach the server here to see : http://fabric8.178.62.222.9.xip.io/workspaces/default/projects/golang-examplenew/environments

**Comment by rawlingsj** [comment]
@iocanel I think this is likely to be down to the recent refactoring of kubernetes-workflow, can we make sure a manual cd-pipeline test is incorporated into our local testing until its automated by ci/cd?

**Comment by rawlingsj** [comment]
I'll have a look at fixing this now and try to get another release out tonight.
