### ISSUE TITLE
The number of replicas in replication controller spec is set to zero after rolling update is done

### ISSUE THREAD

**Issue by xiaoming1999** [fabric8io/fabric8#5764]
I did a a rolling update as shown in the following code:
---
ReplicationController rc = kubeClient.replicationControllers().inNamespace("default")
	.withName("rollingUpdate").rolling().edit().editSpec().editTemplate().withNewSpec()
	.addToContainers(containers).addToVolumes(volumes).endSpec().endTemplate().endSpec().done();
System.out.println(" Spec replicas: " + rc.getSpec().getReplicas() + " status replicas: " + rc.getStatus().getReplicas());

---
The rc.getSpec().getReplicas() is shown to be zero and rc.getStatus.getReplicas() is shown to be the right number.

In the visit() function, the item's number of replicas is set to zero and the item seems to be overwrited by the createdRC as returned in function rollUpdate() of RollingUpdater.java. 
    public ReplicationController done() {
    ReplicationController item = builder.build();visitor.visit(item);return item;
}

**Comment by jimmidyson** [comment]
A rolling update is completely client side logic. This means that the client needs to increment the new RC replicas while decrementing the old RC replicas, waiting for both the new replica to start & the old one to stop (otherwise you could hit unreconcilable resource/quota problems).

So we are not correctly returning the created RC after the rolling update has been completed - thanks for the report, will fix soon.

**Comment by xiaoming1999** [comment]
I am not sure whether the statement that the rolling update is completely client side logic is correct. It seems to me that the logic is buried under rolling and visit. The old and new RC replicas are all handled in the rollingupdate() function. See the code in the end.

In the code, the new RC is scaled up first before the old RC is scaled down. Can this cause deadlock in resource limited environment such as port, memory? Would it be safer to scale old RC down first before scale up new RC?
---

  ReplicationController rollUpdate(ReplicationController oldRC, ReplicationController newRC) {
    try {
      // Get what namespace we're working in
      String namespace = oldRC.getMetadata().getNamespace();
      // And the old RC name
      String oldRCName = oldRC.getMetadata().getName();

      // Update the old RC to ensure there's no overlap between the new & old RCs' selectors
      String oldDeploymentHash = md5sum(oldRC);

      //Before we update the RC though we need to add the labels to the existing managed pods
      PodList oldRCPods = pods().inNamespace(namespace).withLabels(oldRC.getSpec().getSelector()).list();

      for (Pod pod : oldRCPods.getItems()) {
        pod.getMetadata().getLabels().put(DEPLOYMENT_KEY, oldDeploymentHash);
        pods().inNamespace(namespace).withName(pod.getMetadata().getName()).replace(pod);
      }

      // Now we can update the old RC with the new selector
      oldRC.getSpec().getSelector().put(DEPLOYMENT_KEY, oldDeploymentHash);
      oldRC.getSpec().getTemplate().getMetadata().getLabels().put(DEPLOYMENT_KEY, oldDeploymentHash);
      replicationControllers().inNamespace(namespace).withName(oldRCName).cascading(false).replace(oldRC);

      // Ensure it looks like a new RC
      newRC.getMetadata().setResourceVersion(null);

      int requestedNewReplicas = newRC.getSpec().getReplicas();

      // Set the new RC replicas to 0 before we do anything so we can scale up ourselves
      newRC.getSpec().setReplicas(0);

      // Set the selector for the new deployment
      String newDeploymentHash = md5sum(newRC);
      newRC.getSpec().getSelector().put(DEPLOYMENT_KEY, newDeploymentHash);
      newRC.getSpec().getTemplate().getMetadata().getLabels().put(DEPLOYMENT_KEY, newDeploymentHash);

      String newRCName = newRC.getMetadata().getName();

      if (newRCName == null || newRCName.equals(oldRC.getMetadata().getName())) {
        newRC.getMetadata().setName(oldRCName + "-" + newDeploymentHash);
      }

      ReplicationController createdRC = replicationControllers().inNamespace(namespace).create(newRC);

      // Now do the scale up/scale down dance
      int oldReplicas = oldRC.getSpec().getReplicas();
      while (createdRC.getSpec().getReplicas() < requestedNewReplicas) {
        int newReplicas = createdRC.getSpec().getReplicas() + 1;
        replicationControllers().inNamespace(namespace).withName(createdRC.getMetadata().getName()).scale(newReplicas, true);
        waitUntilPodsAreReady(createdRC, namespace, newReplicas);
        createdRC.getSpec().setReplicas(newReplicas);

        if (oldReplicas > 0) {
          replicationControllers().inNamespace(namespace).withName(oldRCName).scale(--oldReplicas, true);
          waitUntilPodsAreReady(oldRC, namespace, oldReplicas);
        }
      }

      // Now delete all existing remaining resources, ensure to cascade
      replicationControllers().inNamespace(namespace).withName(oldRCName).delete();

      // Check if we need to rename it back to the original RC name
      if (Objects.equals(oldRCName, newRCName)) {
        createdRC.getMetadata().setResourceVersion(null);
        createdRC.getMetadata().setName(oldRCName);

        createdRC = replicationControllers().inNamespace(namespace).create(createdRC);

        replicationControllers().inNamespace(namespace).withName(oldRCName + "-" + newDeploymentHash).cascading(false).delete();

        Map<String, String> createdRCSelector = createdRC.getSpec().getSelector();
        createdRCSelector.remove(DEPLOYMENT_KEY);
        createdRC.getSpec().getTemplate().getMetadata().getLabels().remove(DEPLOYMENT_KEY);
        createdRC = replicationControllers().inNamespace(namespace).withName(createdRC.getMetadata().getName()).cascading(false).replace(createdRC);
      }

**Comment by xiaoming1999** [comment]
In the following function, the new RC is scaled down first before the old RC is scaled down. Will this cause deadlock in resource limited environment such as same ports, limited memory or cpu etc? Would it be safer to scale old RC down first before scale up new RC?
---
 ReplicationController rollUpdate(ReplicationController oldRC, ReplicationController newRC) {
    try {
      // Get what namespace we're working in
      String namespace = oldRC.getMetadata().getNamespace();
      // And the old RC name
      String oldRCName = oldRC.getMetadata().getName();

      // Update the old RC to ensure there's no overlap between the new & old RCs' selectors
      String oldDeploymentHash = md5sum(oldRC);

      //Before we update the RC though we need to add the labels to the existing managed pods
      PodList oldRCPods = pods().inNamespace(namespace).withLabels(oldRC.getSpec().getSelector()).list();

      for (Pod pod : oldRCPods.getItems()) {
        pod.getMetadata().getLabels().put(DEPLOYMENT_KEY, oldDeploymentHash);
        pods().inNamespace(namespace).withName(pod.getMetadata().getName()).replace(pod);
      }

      // Now we can update the old RC with the new selector
      oldRC.getSpec().getSelector().put(DEPLOYMENT_KEY, oldDeploymentHash);
      oldRC.getSpec().getTemplate().getMetadata().getLabels().put(DEPLOYMENT_KEY, oldDeploymentHash);
      replicationControllers().inNamespace(namespace).withName(oldRCName).cascading(false).replace(oldRC);

      // Ensure it looks like a new RC
      newRC.getMetadata().setResourceVersion(null);

      int requestedNewReplicas = newRC.getSpec().getReplicas();

      // Set the new RC replicas to 0 before we do anything so we can scale up ourselves
      newRC.getSpec().setReplicas(0);

      // Set the selector for the new deployment
      String newDeploymentHash = md5sum(newRC);
      newRC.getSpec().getSelector().put(DEPLOYMENT_KEY, newDeploymentHash);
      newRC.getSpec().getTemplate().getMetadata().getLabels().put(DEPLOYMENT_KEY, newDeploymentHash);

      String newRCName = newRC.getMetadata().getName();

      if (newRCName == null || newRCName.equals(oldRC.getMetadata().getName())) {
        newRC.getMetadata().setName(oldRCName + "-" + newDeploymentHash);
      }

      ReplicationController createdRC = replicationControllers().inNamespace(namespace).create(newRC);

      // Now do the scale up/scale down dance
      int oldReplicas = oldRC.getSpec().getReplicas();
      while (createdRC.getSpec().getReplicas() < requestedNewReplicas) {
        int newReplicas = createdRC.getSpec().getReplicas() + 1;
        replicationControllers().inNamespace(namespace).withName(createdRC.getMetadata().getName()).scale(newReplicas, true);
        waitUntilPodsAreReady(createdRC, namespace, newReplicas);
        createdRC.getSpec().setReplicas(newReplicas);

        if (oldReplicas > 0) {
          replicationControllers().inNamespace(namespace).withName(oldRCName).scale(--oldReplicas, true);
          waitUntilPodsAreReady(oldRC, namespace, oldReplicas);
        }
      }

      // Now delete all existing remaining resources, ensure to cascade
      replicationControllers().inNamespace(namespace).withName(oldRCName).delete();

      // Check if we need to rename it back to the original RC name
      if (Objects.equals(oldRCName, newRCName)) {
        createdRC.getMetadata().setResourceVersion(null);
        createdRC.getMetadata().setName(oldRCName);

        createdRC = replicationControllers().inNamespace(namespace).create(createdRC);

        replicationControllers().inNamespace(namespace).withName(oldRCName + "-" + newDeploymentHash).cascading(false).delete();

        Map<String, String> createdRCSelector = createdRC.getSpec().getSelector();
        createdRCSelector.remove(DEPLOYMENT_KEY);
        createdRC.getSpec().getTemplate().getMetadata().getLabels().remove(DEPLOYMENT_KEY);
        createdRC = replicationControllers().inNamespace(namespace).withName(createdRC.getMetadata().getName()).cascading(false).replace(createdRC);
      }

**Comment by jimmidyson** [comment]
All rolling update logic is performed by the Java client, not in the API server - that's what I mean by it's all client side logic.

Each pod gets its own network namespace so port conflicts aren't a problem.

Scaling up before scaling down is the correct way round to ensure that there is always least the same resource available to process incoming requests. If you scale the old RC down first then you could be reducing the availability of your service, which is exactly what you are trying to avoid by doing a rolling upgrade.

If you're in a resource constrained environment then rolling upgrades may not be the correct way for you to perform upgrades. They are meant to be used to avoid downtime & during the rolling upgrade period will use more resource, but this should be limited to one pod's worth of resource more than the old RC was using - in a Kubernetes environment there is normally at least that amount available. If you want to strictly cap resource usage than you might be better off using `replace` without rolling upgrade, but be aware that will incur service downtime as your old pods are deleted before your new pods are created.

**Comment by xiaoming1999** [comment]
Thanks. This really clarify some of my understandings. 

Is the rolling update fault tolerant? Say in case the machine crashes or network is down in the middle of the update, will the rolling update be able to handle cases like these?

**Comment by jimmidyson** [comment]
At the moment no it doesn't handle resuming rolling updates. However that should be easy enough to add in as we add a hash of the updated RC config to the new RC labels in order to identify the RC for exactly the purpose you describe - we just haven't got around to implementing resume yet. Contributions welcome :)

**Comment by xiaoming1999** [comment]
Thanks a lot.
