### ISSUE TITLE
linux host virtual box 503 error

### ISSUE THREAD

**Issue by geoHeil** [fabric8io/fabric8#5776]
Hi after a vagrant up on a Linux host somewhat successfully I cannot connect to the cluster and only get a 503 error:

```
curl https://vagrant.f8 -k
<html>
  <body>
    <h1>503 Service Unavailable</h1>
    No server available to handle the request.
  </body>
</html>
```
Executing `rhc setup` to set the open shift command line tools and entering `vagrant.f8` or the `172.28.128.4` ip results in the following error after accepting insecure certificate YES:
The server did not respond correctly. This may be an issue with the server configuration or with your connection to
the server (such as a Web proxy or firewall). Please verify that you can access the OpenShift server
https://vagrant.f8/broker/rest/api

But a ping of the ip like `ping 172.28.128.4` works.

I already (repeatedly) tried to execute
```
sudo apt-get install -y resolvconf dnsmasq
sudo sh -c 'echo "server=/vagrant.f8/127.0.0.1#10053" > /etc/dnsmasq.d/vagrant-landrush'
sudo service dnsmasq restart
```

which did not help either.

**Comment by oscerd** [comment]
What Linux version are you using?

**Comment by geoHeil** [comment]
I use the 15.10 version

**Comment by oscerd** [comment]
I meant the distribution sorry.

**Comment by geoHeil** [comment]
ubnuntu 15.10

**Comment by oscerd** [comment]
But I guess is Ubuntu then

**Comment by geoHeil** [comment]
correct.

**Comment by oscerd** [comment]
I had similar error when I was passing from Ubuntu to Fedora/Centos linux distribution. In that case the dnsmasq didn't work correctly and I had to edit the etc/hosts file manually.

Never see this problem on Ubuntu.

**Comment by geoHeil** [comment]
correct. it is not setup there. 
I will manually like as:
`172.28.128.4    vagrant.f8`


now a curl to:
` http://fabric8.vagrant.f8/` returns some content. However the `rhc setup` with `vagrant.f8` still fails

**Comment by jimmidyson** [comment]
rhc is the openshift v2 client. You'll need to get the v3 client from https://github.com/openshift/origin/releases. The address for the api server is https://172.28.128.4:8443.

Please read http://fabric8.io/guide/getStarted/local.html fit more details of setting up the client locally.

**Comment by oscerd** [comment]
I didn't notice you were using rhc command. Sorry @geoHeil

**Comment by geoHeil** [comment]
Thank you very much. I googled a lot but unfortunately the regular openshift gets better search results.

**Comment by jimmidyson** [comment]
@geoHeil No worries - that's proving a problem for a number of users tbh.
