### ISSUE TITLE
fabric8-maven-plugin - Readiness probe with HTTP

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5783]
Wonder if anyone have tried the HTTP readiness probe?

For example on a container where you run a standard Apache Camel on port 8080 you could specify
```
    <fabric8.readinessProbe.httpGet.host>127.0.0.1</fabric8.readinessProbe.httpGet.host>
    <fabric8.readinessProbe.httpGet.port>8080</fabric8.readinessProbe.httpGet.port>
    <fabric8.readinessProbe.httpGet.path>/</fabric8.readinessProbe.httpGet.path>
```

But it seems not working. And all the quickstarts and whatnot are using the exec with curl as readiness check
```
./quickstart/war/wildfly/quickstart-template.json-                "name": "${APP_NAME}",
./quickstart/war/wildfly/quickstart-template.json-                "image": "library/${APP_NAME}:latest",
./quickstart/war/wildfly/quickstart-template.json:                "readinessProbe": {
./quickstart/war/wildfly/quickstart-template.json-                  "exec": {
./quickstart/war/wildfly/quickstart-template.json-                    "command": [
./quickstart/war/wildfly/quickstart-template.json-                      "/bin/bash",
./quickstart/war/wildfly/quickstart-template.json-                      "-c",
./quickstart/war/wildfly/quickstart-template.json-                      "(curl -f 127.0.0.1:8080) >/dev/null 2>&1; test $? != 7"
./quickstart/war/wildfly/quickstart-template.json-                    ]
./quickstart/war/wildfly/quickstart-template.json-                  },
./quickstart/war/wildfly/quickstart-template.json-                  "initialDelaySeconds": 30,
./quickstart/war/wildfly/quickstart-template.json-                  "timeoutSeconds": 5
./quickstart/war/wildfly/quickstart-template.json-                },
```

**Comment by davsclaus** [comment]
I found an example from forge
https://github.com/fabric8io/fabric8-forge/blob/master/fabric8-forge/pom.xml#L27

It does not use the host, so it seems setting port and path is all it requires. I wonder if we could not auto imply to the container port if you do not set a port, then you do not have to duplicate that. Then just set the path, and then port and host is implied.

Also wonder if there is any default timeout values? I could not find it in the fabric8-maven-plugin. But is there some timeout in kubernetes? @jimmidyson wonder if you know more?

**Comment by davsclaus** [comment]
Also all our quickstarts uses 
```
davsclaus:~/workspace/quickstarts (master)/$ git grep "initialDelaySeconds"
quickstart/cdi/camel-http/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/cdi/camel-jetty/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/cdi/camel-mq/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/cdi/camel/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/cdi/cxf/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/java/fatjar/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/java/mainclass/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/karaf/camel-amq/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/karaf/camel-log/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/karaf/camel-rest-sql/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/karaf/cxf-rest/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/spring-boot/camel/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/spring-boot/webmvc/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/spring/camel/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/war/camel-servlet/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/war/cxf-cdi-servlet/quickstart-template.json:                  "initialDelaySeconds": 30,
quickstart/war/wildfly/quickstart-template.json:                  "initialDelaySeconds": 30,
```

Isn't that a high initial delay? The quickstarts start fast, so I wonder what it really does that delay?

**Comment by jimmidyson** [comment]
That generated readiness probe is weird. It should be a http readiness probe, not a command. Will take a look.

30 seconds must be a default but as you say is too high - what do you think a sane default would be for our java apps? 1 / 5 / 10 seconds?

**Comment by davsclaus** [comment]
Some Java app servers like Tomcat etc can be a bit slow to start.

```
01-Mar-2016 10:01:36.903 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 12883 ms
```

For example to start locally tomcat with a camel war.

**Comment by davsclaus** [comment]
So should it not be something like

timeout = 30
initial = 1

How does the http probe work?

- container is starting
- it wait 1 sec before first poll
- if it fails, then try again after X delay
- and it keep trying until it gets a HTTP STATUS 2xx, 
- .. or until the total time is > 30 sec and timeout

**Comment by jimmidyson** [comment]
Ah is this stuff generated by forge? Sorry I was looking at the quickstarts. This is built from a template? Can you point me to the source please?

**Comment by davsclaus** [comment]
generate by forge? 

The quickstarts are ready to run projects, and then we use those to build maven archetypes, that when you run those archetypes, create the same quickstart source code (but you can change the name of the project etc) but the pom.xml should be 99% identical.

jboss forge do not generate anything in that situation.

However there is a fabric8-setup command in forge, you can use to run on an **existing maven project** that are not docker or kubernetes ready. The idea is that the forge command look at your maven project and then accordingly add those changes to the pom.xml to setup the d-m-p plugin, and whatnot. That command is currently a "bit behind" because there are too many changes in the quickstarts, and the are too different. 

The source code for the quickstarts are here
https://github.com/fabric8io/ipaas-quickstarts/tree/master/quickstart

**Comment by davsclaus** [comment]
About the readinessProbe, was the idea we add those to all our quickstarts, or in the longer run try to have some general readiness probe for jolokia / JVM so end users do not have to add them explict?

But still would be nice to have them in the quickstarts, as when scaling up/down and killing pods, it may happen a service is accessed to soon, before the JVM with Camel is ready.

**Comment by jimmidyson** [comment]
Readiness probes should be in all quickstarts. Would be a good idea to have good defaults so don't have to be explicitly added.

**Comment by davsclaus** [comment]
I got this one working for my camel and tomcat example
https://github.com/fabric8io/ipaas-quickstarts/commit/426bd4145b3971c5f197807037cb32c0c721777e

**Comment by davsclaus** [comment]
Working on adding the readiness to the other quickstarts

**Comment by davsclaus** [comment]
In this PR
https://github.com/fabric8io/ipaas-quickstarts/pull/1163
