### ISSUE TITLE
Cant use pipeline with jenkins security

### ISSUE THREAD

**Issue by xelfe** [fabric8io/fabric8#5788]
I cant use the pipeline when security on jenkins is enable. I'm hosting fabric8 on public servers so I have to prevent registering in almost services. There's a way to do it already ? Any plans of doing this ?

**Comment by xelfe** [comment]
Still no comment ?

**Comment by rawlingsj** [comment]
I expect the fabric8-forge pod is unable to create and trigger jobs in Jenkins without passing a bearer token. 
We'll try to add this in the next couple of weeks.

**Comment by dotw** [comment]
was this feature implemented? how to pass the token to forge?
