### ISSUE TITLE
hawtapp-maven-plugin has issues with deps of type "test-jar"

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8#5791]
It seems that if two deps are included, one with scope `compile` and one with scope `test` **and** type `test-jar` (which causes the tests to be deployed, too), then the plugin gets confused and included one of both deps randomly.

The issue has been analysed in https://github.com/fabric8io/ipaas-quickstarts/issues/1157 and is probably due to this [map lookup](https://github.com/fabric8io/fabric8/blob/2382f31799020401639a531b8505c13f20c8e77d/hawt-app-maven-plugin/src/main/java/io/fabric8/maven/hawt/app/BuildMojo.java#L160-L160) which doesn't honor the type.

would be good to add a unit test for this scenario, too (even if this would be the first test).

**Comment by jimmidyson** [comment]
The problem is actually in Maven's core `ArtifactUtils` - it doesn't take type into account with it's `versionlessKey` which it uses in building a map of artifacts for a project...:

```java
public static String versionlessKey(Artifact artifact) {
  return versionlessKey(artifact.getGroupId(), artifact.getArtifactId());
}
```

Will have to build our own map which does take type into account. Working on it now.

**Comment by rhuss** [comment]
thx, @jimmidyson 

sorry would have tried to fix it myself but my panic is growing slowly now when I think to my next week's presentation slides :)
