### ISSUE TITLE
create Integration project fails

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5841]
we get this error:
```
Could not find artifact io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.100 in central (http://repo1.maven.org/maven2)
```

**Comment by rawlingsj** [comment]
That looks similar to this issue https://github.com/fabric8io/fabric8/issues/5834

**Comment by jstrachan** [comment]
Yeah, this one is the ProjectType in the Forge new project wizard is using the wrong archetype id - have a fix - testing & pushing shortly...

**Comment by rawlingsj** [comment]
ah ok

**Comment by davsclaus** [comment]
I think this is fixed now?

**Comment by jstrachan** [comment]
yeah - think it is in master. @davsclaus I was gonna change the ProjectType to use "spring-camel-archetype" but it looks like we have a "java-camel-spring-archetype" released now?

**Comment by davsclaus** [comment]
Its using the new archetype, and with the 101 it should work

```
davsclaus:~/workspace/fabric8-forge (master)/$ git grep "java-camel-spring-archetype"
addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/projecttypes/CamelProjectArchetypeStep.java:        setArchetypeArtifactId("java-camel-spring-archetype");
```

**Comment by davsclaus** [comment]
Should be fixed now
