### ISSUE TITLE
can't clone from gogs in the latest greatest release

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5849]
I cut a release of fabric8-devops + fabric8-forge with the fixes for Elasticsearch + Gogs. I can spin up new projects and see the source inside gogs.

Though if I try to clone a git project it fails:
```
$ git clone http://gogs.vagrant.f8/gogsadmin/mymsthing.git
Cloning into 'mymsthing'...
error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly
```

**Comment by jimmidyson** [comment]
Any logs in gogs? gogs logs?

**Comment by jstrachan** [comment]
I don't see anything in particular in the gogs logs:
```
[Macaron] Started GET /gogsadmin/mymsthing.git/info/refs?service=git-upload-pack for 172.28.128.1
[Macaron] Completed /gogsadmin/mymsthing.git/info/refs?service=git-upload-pack 200 OK in 8.929579ms
```

I wonder if its related to the router? Lemme have a look around...

**Comment by jstrachan** [comment]
Hmm, don't see any error logs in the router or `journalctl -fu openshift` or in gogs. More than happy to try stuff if you like. Its certainly a bit odd!

**Comment by jstrachan** [comment]
So its definitely related to the service and/or router.

I can `docker exec` into the Jenkins container and clone git directly using the pod IP address
```
git clone http://172.17.0.6:3000/gogsadmin/mymsthing.git
Cloning into 'mymsthing'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
root@jenkins-gmofg:/tmp# cd mymsthing/
```

**Comment by jstrachan** [comment]
so I can't clone via the service portalIP / clusterIP though for gogs. I wonder if its related to nodePort?
https://gist.github.com/jstrachan/2b1e5977442fadba64a2#file-gogs-service-yml-L22

**Comment by jstrachan** [comment]
though I can clone inside the Jenkins pod using the `gogs` DNS name:
```
git clone http://gogs/gogsadmin/mymsthing.git
```

**Comment by jstrachan** [comment]
does seem intermittent:
```
root@jenkins-gmofg:/tmp/zz# git clone http://gogs/gogsadmin/mymsthing.git
Cloning into 'mymsthing'...
fatal: repository 'http://gogs/gogsadmin/mymsthing.git/' not found
root@jenkins-gmofg:/tmp/zz# git clone http://gogs/gogsadmin/mymsthing.git
Cloning into 'mymsthing'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
```

**Comment by jstrachan** [comment]
schoolboy error! I'd got a stale broken gogs pod that was confusing me - DOH!
