### ISSUE TITLE
duplicate templates displayed in console when templates exist in multiple namespaces

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5850]
I've run gofabric8 deploy in two namespaces, not sure yet if that's a likely scenario but even so when I do the console shows the templates from both namespaces, I'm thinking it should only display the templates from the namespace that the console is running in?

**Comment by gashcrumb** [comment]
Yeah, as I recall it should only show templates in the current namespace, will take a look...

**Comment by gashcrumb** [comment]
Hmm, no currently it's looking at /oapi/v1/templates, so will show all templates.  We should probably change this to use the namespaced one instead.

**Comment by gashcrumb** [comment]
K, it's fixed, just want to tidy up the alignment on the templates page and maybe actually add a preview/updates/error reporting too before putting out another console release.

**Comment by rawlingsj** [comment]
ooh nice!  sounds great.

**Comment by gashcrumb** [comment]
This should be all set now
