### ISSUE TITLE
New to Fabric8, a Question 

### ISSUE THREAD

**Issue by websemantics** [fabric8io/fabric8#5863]
Hi Everyone, .. 

This might be too obvious, so I apology if so,

What's the take of Fabric8 when it comes to Openshift 3, Source to Image (s2I), .. Does Fabric8 have Custom Builders for creating Docker Images from source or use built in Docker Image builder?

Many thanks,

**Comment by rawlingsj** [comment]
Hi @websemantics sorry for the delay, I think your question was missed.  So we currently use docker [onbuild images](https://github.com/fabric8io/jenkins-workflow-library/blob/master/workflows/node/CanaryReleaseStage/Jenkinsfile#L9-L13) and [custom Builder images](https://github.com/fabric8io?utf8=%E2%9C%93&query=builder) in our Jenkinfiles for all non java builds, i.e. node, swift, golang etc and the [docker-maven-plugin](http://fabric8io.github.io/docker-maven-plugin/) for java apps.  
Having said that we're in the process of moving over to using the [openshift binary source](https://docs.openshift.com/enterprise/3.0/dev_guide/builds.html#binary-source) builder, so a jenkinsfile or user can create their binaries using the build tools they're used to and pass the aftifacts to openshift to build the image.  

This has a number of advantages
- openshift does the heavy lifting of building docker images
- binaries are built in the same way that people are used to, using build tools and scripts native to the language they're developed in and should fit it better with existing CI processes
- from a Jenkinsfile PoV we wont have to run privileged pods or mount the docker socket to perform docker operations - this is a much safer approach

**Comment by websemantics** [comment]
Thanks @rawlingsj ever so much .. that's great news as greater integration with openshift builders will standardize the practice of source to image for the community .. btw, awesome, awesome work on Fabric8 ..

**Comment by rawlingsj** [comment]
Yeah we should be switched over to using the openshift binary source soon.  

Great to hear you like it :)

**Comment by websemantics** [comment]
I've downloaded the project source code and trying to make sense of it's large array of components, hopefully understand it well enough to make contributions .. reading the docs currently .. thanks again ..

**Comment by rawlingsj** [comment]
Sounds great.. we love contributions!  If you need any realtime help we hang out on irc.freenode.net #fabric8.
