### ISSUE TITLE
Jenkins Project is not created when importing Git Repository

### ISSUE THREAD

**Issue by honratha** [fabric8io/fabric8#5866]
When I created a project using the Fabric8 Console, I saw that a jenkins project is not created when clicking "Import from Git".
The main issue I see is in the GitCommandCompletePostProcessor.java class (Line 113). 
It seems that the BuildConfig is only created if the "project-new" Command is triggered. 
For the Import Project, this not the the case, since there only a new BuildConfig is generated in a first request and in a second one the "devops-get-overview" command is executed.

**Comment by rawlingsj** [comment]
I've just forked the [node example](https://github.com/fabric8-quickstarts/node-example) added my github username + password as a new secret in the fabric8 console, imported my forked project using https://github.com/rawlingsj/node-example.git, selected a pipeline and the jenkins job created and was triggered.

The only issue I saw was the pods arent showed in the environments on the dashboard which we'll get a fix for asap. https://github.com/fabric8io/fabric8/issues/5867

Could you let me know if there's anything different from your approach which might explain why your jenkins job isn't being created.  Can you check the fabric8-forge pod logs for any errors?

**Comment by honratha** [comment]
Thanks, I verified and indeed, after adding a pipeline the job was created.
I think the issue occurs when there is already a fabric8.yml and Jenkinsfile in the project.
