### ISSUE TITLE
The readinessProbe should support setting the scheme

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/fabric8#5909]
That way it can probe SSL services.

**Comment by rhuss** [comment]
Funny, its exactly  the current spot where I am in  my refactoring journey :). In the new plugin you will be able to set a full URL (including protocol).

**Comment by KurtStam** [comment]
With this change, it now supports httpGet.scheme. Testing showed that it is successfully ignoring the validity of the certificate, so you can use a self signed cert (https://github.com/kubernetes/kubernetes/issues/9866).

**Comment by KurtStam** [comment]
@rhuss that sure is funny!
