### ISSUE TITLE
[CI/CD] Build failure due to "No POM"

### ISSUE THREAD

**Issue by saknopper** [fabric8io/fabric8#5916]
I'm trying to get a very simple HelloWorld WildFly example to build in fabric8 using the CI/CD pipeline. My environment is a local Vagrant installation on OS X.

When I'm doing this manually using the following command:
`mvn install docker:build fabric8:json fabric8:apply`
everything works perfectly.

However when trying to import my git repo as an app in fabric8 and triggering a build I get the following error (snippet):

> 
> mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -DnewVersion=1.0.5
> [INFO] Building Maven Stub Project (No POM) 1
> [ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:set (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/workspace/fabric8-wildfly-helloworld). Please verify you invoked Maven from the correct directory.

(full log: [build_log_no_pom.txt](https://github.com/fabric8io/fabric8/files/210446/build_log_no_pom.txt))

Obviously, my project has a pom.xml but it doesn't seem to be able to find it.

What am I doing wrong?

**Comment by rawlingsj** [comment]
Ah I saw this yesterday on one of our environments.  At a guess until I can have a proper look, I wonder if you selected the option to copy the pipeline to the project workspace? There's a checkbox under the pipeline selection options. 

If you're able to give that a try it might be the problem, if it is we'll put a proper fix together. 

James.

**Comment by saknopper** [comment]
I tried both with and without the option to copy the pipeline to the project workspace. It doesn't make a difference though.

Thanks for looking into it, hope you can find something.

Sander

**Comment by rawlingsj** [comment]
I've recreated the error, still not sure what's going on yet but I can see the URL in the jenkins job configuration is the global function library (https://github.com/fabric8io/jenkins-workflow-library.git) and not the project repo.  So when [`checkout scm`](https://github.com/fabric8io/jenkins-workflow-library/blob/master/workflows/maven/CanaryReleaseAndStage/Jenkinsfile#L29) runs it clones the wrong repo.

Will continue to look at what's going on..

**Comment by rawlingsj** [comment]
Fixed with the commit above and I've just kicked off a release - should  be ready in an hour or so.

@christian-posta this should fix the error you saw too.
