### ISSUE TITLE
looks like cd-pipeline builds without elasticsearch fails

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5930]
I just tried a clean VM with `cd-pipeline` only and the build failed due to ES errors:
```
[Pipeline] kubernetesApply
Not adding annotation `fabric8.io/git-branch` to ReplicationController myms with value `myms-1.0.1` as there is already an annotation value of `myms-1.0.1`
Not adding annotation `fabric8.io/git-commit` to ReplicationController myms with value `5e9349f06be3444417ac9c4a1a24dcf79d8826c1` as there is already an annotation value of `5e9349f06be3444417ac9c4a1a24dcf79d8826c1`
Not adding annotation `fabric8.io/build-url` to ReplicationController myms with value `http://172.30.21.207:80/job/myms/1` as there is already an annotation value of `http://172.30.21.207:80/job/myms/1`
Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
[Pipeline] stage (Approve)
Entering stage Approve
Proceeding
[Pipeline] hubotApprove
Hubot sending to room fabric8_default => Version 1.0.1 has now been deployed to the Staging environment at:
/kubern
etes/pods?environment=Staging

Would you like to promote version 1.0.1 to the Production namespace?

    to Proceed reply:  fabric8 jenkins proceed job myms build 1
    to Abort reply:    fabric8 jenkins abort job myms build 1

No service hubot  is running!!!
No service found!
[Pipeline] approveRequestedEvent
Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
[Pipeline] } //withPod
[Pipeline] Run build steps in a Pod : End
[Pipeline] } //node
[Pipeline] Allocate node : End
[Pipeline] End of Pipeline
Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
ERROR: Error creating Approve event in elasticsearch
Finished: FAILURE
```

**Comment by geostant** [comment]
Is there a solution ?

**Comment by rawlingsj** [comment]
@geostant this has been working for a while.  Are you seeing the exact same error?  If you're seeing a slightly different error could you open a new issue and add the Jenkins console logs please?

Note that we will only send events to elasticsearch during the pipeline if elasticsearch is running.  Elasticsearch is bundled with the Logging app which is runnable from the fabric8 console Run menu.

**Comment by geostant** [comment]
@rawlingsj I'm working with fabric8 UI and having that same error:

> Started by user anonymous
> Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
> ERROR: No flow definition, cannot run
> Finished: FAILURE

I've created another pod with elasticsearch but that didn't solved the issue

**Comment by rawlingsj** [comment]
@geostant ok that looks like a slightly different error.  `ERROR: No flow definition, cannot run`.
This suggests there was no jenkinsfile found.  

During the project creation did you select a pipeline in the new project wizard?

**Comment by geostant** [comment]
@rawlingsj couldn't get to that screen, after setting secret and clicked save, nothing really happens.
switching to the pipeline screen give me an endless loading symbol.

**Comment by rawlingsj** [comment]
Ok - would you mind raising a new issue with the details please?  With as much information as possible so that we can fully understand the problem.  Including info about your environment,  minikube / minishift / vagrant / openshift or kubernetes cluster.  Also details about what you are doing; importing a project or creating a new one using the project wizard.

Could you also include and logs from the fabric8-forge pod also check the browser Javascript console for and errors and include those too please.

**Comment by geostant** [comment]
@rawlingsj roger that, will do so now.
Thanks !

**Comment by rawlingsj** [comment]
@geostant great - thanks
