### ISSUE TITLE
quickstarts/walkthrough.html simple-fatjar is now fatjar

### ISSUE THREAD

**Issue by starksm64** [fabric8io/fabric8#5936]
The current http://fabric8.io/guide/quickstarts/walkthrough.html refers to a ipaas-quickstarts/quickstart/java/simple-fatjar project that is now called fatjar. The section that says:

And then change directory to

cd quickstart
cd java
cd simple-fatjar

should be:
...
cd quickstart
cd java
cd fatjar

**Comment by davsclaus** [comment]
Thanks for reporting. If you fancy you are welcome to do a PR with a doc fix. The doc is here
https://github.com/fabric8io/fabric8/blob/master/docs/quickstarts/walkthrough.md

**Comment by starksm64** [comment]
The PR is #5941

**Comment by davsclaus** [comment]
Thanks for the PR that has been merged
