### ISSUE TITLE
Annoying errors reported with importing secrets

### ISSUE THREAD

**Issue by sbadakhc** [fabric8io/fabric8#5947]
These are not show stopping but annoying.
![screenshot from 2016-04-19 07-06-26](https://cloud.githubusercontent.com/assets/2914400/14628370/9e0d6cca-05fd-11e6-8be8-1ce1960cbb41.png)

**Comment by sbadakhc** [comment]
Still seeing these errors.  Any ideas?

**Comment by rawlingsj** [comment]
TBH I don't think we need the secrets step now, we've moved the secrets into the jenkins app itself so I think we can avoid running `gofabric8 secrets` unless you want to delete and override the defaults that are created.

**Comment by sbadakhc** [comment]
Great...I will try it give it a spin.

**Comment by sbadakhc** [comment]
Looks good.  Closing...thanks.

**Comment by rawlingsj** [comment]
Great!
