### ISSUE TITLE
app from staging and prod appearing in the console's default namespace

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5970]
the `my-nodeapp2` app was built using the new project + cd pipelines and has been staged and deployed to production using the correct namespaces however, the app also appears in the default namespace in the console but not the CLI..

<img width="1412" alt="screenshot 2016-04-25 20 57 29" src="https://cloud.githubusercontent.com/assets/1457180/14797148/0919ebf8-0b29-11e6-8b89-fbfc58177e04.png">

```
kc get pods
NAME                            READY     STATUS    RESTARTS   AGE
elasticsearch-3q64c             2/2       Running   0          1h
fabric8-docker-registry-ljyun   1/1       Running   2          1d
fabric8-forge-no7lu             1/1       Running   2          2h
fabric8-pndcp                   2/2       Running   4          1d
gogs-hy21l                      1/1       Running   4          1d
java-developer-13x5h            1/1       Running   4          3h
jenkins-5vhjw                   1/1       Running   4          1d
kibana-l7900                    2/2       Running   0          1h
nexus-bozmj                     1/1       Running   3          1d
```

**Comment by jstrachan** [comment]
yeah - this is wacky - am pretty sure they are not in the namespaces; but that they just appear on the overview page

**Comment by gashcrumb** [comment]
Looked into it, turns out the `api` is actually returning those along with objects of the right namespace.  So I guess it's an upstream k8s change?  For now I've added this commit to hawtio-kubernetes-api to strip out those additions -> https://github.com/hawtio/hawtio-kubernetes-api/commit/854480686bcad756c81c52c3a5165fad1bf8b381

**Comment by jstrachan** [comment]
looks fixed to me!

**Comment by rawlingsj** [comment]
brilliant!
