### ISSUE TITLE
Fabric8 Deployment Loads Top "Fabric8" Banner, but then has a DNS error.

### ISSUE THREAD

**Issue by jameslabocki** [fabric8io/fabric8#5998]
James,

I'm trying to get hands on with Fabric8 to better understand it, but I'm hitting an issue.

1. I deployed Fabric8 on OpenShift Enterprise in my lab.

[root@jj-float155 ~]# gofabric8 -s https://10.19.139.155:8443 --domain=apps.jlabocki.syseng.us deploy

Deploying fabric8 to your OpenShift installation at https://10.19.139.155:8443 in namespace myproject

Loading fabric8 releases from maven repository: https://repo1.maven.org/maven2/Continue? [Y/n] y

Starting fabric8 console deployment using 2.2.130...

SecurityContextConstraints restricted is updated to enable fabric8
SecurityContextConstraints restricted.........................................✔ 
SecurityContextConstraints fabric8-myproject is setup correctly
SecurityContextConstraints fabric8............................................✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:myproject:fabric8....✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:myproject:jenkins....✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:myproject:metrics...✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:myproject:fluentd...✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount router......................................................✔ 
Creating fabric8 console resources
fabric8 console...............................................................✔ 
Created fabric8 console
Installing templates!
Downloading templates for version 2.2.171
Loading template main/metrics-2.2.167.json
Loading template main/chat-letschat-2.2.167.json
Loading template microservices/git-collector-2.2.167.json
Loading template main/chat-irc-2.2.167.json
Loading template microservices/fabric8-docker-registry-2.2.167.json
Loading template microservices/gogs-2.2.167.json
Loading template microservices/letschat-2.2.167.json
Loading template microservices/fabric8-forge-2.2.171.json
Loading template main/chat-slack-2.2.167.json
Loading template microservices/gitlab-2.2.167.json
Loading template main/cd-pipeline-2.2.171.json
Loading template microservices/chaos-monkey-2.2.167.json
Loading template main/social-2.2.167.json
Loading template microservices/gerrit-2.2.167.json
Loading template main/management-2.2.167.json
Loading template microservices/artifactory-2.2.167.json
Loading template main/logging-2.2.167.json
Loading template microservices/kiwiirc-2.2.167.json
Loading template microservices/jenkins-2.2.167.json
Loading template microservices/nexus-2.2.167.json
Install DevOps templates......................................................✔ 
Downloading templates for version 2.2.117
Loading template microservices/message-broker-2.2.117.json
Loading template microservices/example-message-consumer-2.2.117.json
Loading template microservices/example-message-producer-2.2.117.json
Loading template main/messaging-2.2.117.json
Loading template microservices/kafka-2.2.117.json
Loading template main/apiman-2.2.117.json
Loading template microservices/zookeeper-2.2.117.json
Loading template microservices/message-gateway-2.2.117.json
Install iPaaS templates.......................................................✔ 
Downloading templates for version 1.0.16
Loading template main/kubeflix-1.0.16.json
Loading template microservices/hystrix-dashboard-1.0.16.json
Loading template microservices/turbine-server-1.0.16.json
Install Kubeflix templates....................................................✔ 
Create routes.................................................................✔ 

2. I then browse to my fabric8 deployment at http://fabric8.apps.jlabocki.syseng.us/

I see the bar for fabric8 renders on the page, but then I get forwarded to this URL:

https://apps.jlabocki.syseng.us:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F&redirect_uri=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F

and that ends up with a "This site can't be reached" because "apps.jlabocki.syseng.us’s server DNS address could not be found".

My openshift deployment consists of a master (172.16.66.65) and node (172.16.66.66) that have floating IP addresses provided by OpenStack.

Does anyone have any idea or any thoughts around what I might be missing? Why is fabric8 forwarding me to apps.jlabocki.syseng.us instead of fabric8.apps.jlabocki.syseng.us?

**Comment by jameslabocki** [comment]
Also, I have set corsAllowedOrigins to - .* in vi /etc/origin/master/master-config.yaml and still receive the error.

corsAllowedOrigins:
  - .*

**Comment by rawlingsj** [comment]
I wonder if you need to pass the api-server flag to point to the floating ip?
```
gofabric8 deploy -y -s https://10.19.139.155:8443 --domain apps.jlabocki.syseng.us --api-server 10.19.139.155
```

**Comment by jameslabocki** [comment]
I created a new project (to start fresh) and tried that. I still get forwarded to the following address which fails.

https://apps.jlabocki.syseng.us:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F&redirect_uri=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F

What is causing the redirect for oauth to take place? My oauthclient looks like this:

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#

apiVersion: v1
items:
- apiVersion: v1
  kind: OAuthClient
  metadata:
    creationTimestamp: 2016-05-10T14:15:07Z
    name: fabric8
    resourceVersion: "60181"
    selfLink: /oapi/v1/oauthclients/fabric8
    uid: 99051e08-16b9-11e6-8f76-fa163eb73436
  redirectURIs:
  - http://localhost:9090
  - http://localhost:2772
  - http://localhost:9000
  - http://fabric8.apps.jlabocki.syseng.us
  - https://fabric8.apps.jlabocki.syseng.us
- apiVersion: v1
  kind: OAuthClient
  metadata:
    creationTimestamp: 2016-05-04T13:41:42Z
    name: openshift-browser-client
    resourceVersion: "60396"
    selfLink: /oapi/v1/oauthclients/openshift-browser-client
    uid: efc77a85-11fd-11e6-89a8-fa163eb73436
  redirectURIs:
  - https://jj-float155.cloud.lab.eng.bos.redhat.com:8443/oauth/token/display
  secret: d10ae884-be86-454b-b107-62aae863115d
- apiVersion: v1
  kind: OAuthClient
  metadata:
    creationTimestamp: 2016-05-04T13:41:42Z
    name: openshift-challenging-client
    resourceVersion: "60397"
    selfLink: /oapi/v1/oauthclients/openshift-challenging-client
    uid: efd3a515-11fd-11e6-89a8-fa163eb73436
  redirectURIs:
  - https://jj-float155.cloud.lab.eng.bos.redhat.com:8443/oauth/token/implicit
  respondWithChallenges: true
  secret: 7e3f95f5-a14d-483b-9396-bd666d865e5a
- apiVersion: v1
  kind: OAuthClient
  metadata:
    creationTimestamp: 2016-05-04T13:41:42Z
    name: openshift-web-console
    resourceVersion: "60395"
    selfLink: /oapi/v1/oauthclients/openshift-web-console
    uid: efc36a3e-11fd-11e6-89a8-fa163eb73436
  redirectURIs:
  - https://jj-float155.cloud.lab.eng.bos.redhat.com:8443/console/
  - http://localhost:9000
  - https://localhost:9000
  secret: 5b255d20-9f05-4994-8725-624fa939b36e
kind: List
metadata: {}

**Comment by jameslabocki** [comment]
Also, the pod itself seems to have the correct URI set for OAUTH authorization.

```
[root@jj-float155 ~]# oc env pod fabric8-vx77l --list |grep -i authorize
OAUTH_AUTHORIZE_PORT=8443
OAUTH_AUTHORIZE_URI=https://10.19.139.155:8443/oauth/authorize
```

**Comment by jameslabocki** [comment]
Also, If I manually change the URL to the following

`https://10.19.139.155:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F&redirect_uri=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F`

Then I receive this error:

`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://fabric8.apps.jlabocki.syseng.us/"}`

**Comment by rawlingsj** [comment]
I think creating a new project and running gofabric8 deploy wouldn't have updated the existing fabric8 oauthclient.  Sounds like a bug but to get you past it you could try deleting the fabric8 oauthclient and re run the gofabric8 deploy?

**Comment by jameslabocki** [comment]
Still no luck. I delete and rerun `gofabric8 deploy`

```
[root@jj-float155 ~]# oc delete oauthclient fabric8
oauthclient "fabric8" deleted
[root@jj-float155 ~]# gofabric8 deploy -y -s https://10.19.139.155:8443 --domain apps.jlabocki.syseng.us --api-server 10.19.139.155
Deploying fabric8 to your OpenShift installation at https://10.19.139.155:8443 in namespace lab2

Loading fabric8 releases from maven repository: https://repo1.maven.org/maven2/
Starting fabric8 console deployment using 2.2.130...

SecurityContextConstraints restricted is configured correctly
SecurityContextConstraints restricted.........................................✔ 
SecurityContextConstraints fabric8-lab2 is setup correctly
SecurityContextConstraints fabric8............................................✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:lab2:fabric8.........✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:lab2:jenkins.........✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:lab2:metrics........✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:lab2:fluentd........✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount router......................................................✔ 
Creating fabric8 console resources
fabric8 console...............................................................✘ replicationControllers "fabric8" already exists
Created fabric8 console
Installing templates!
Downloading templates for version 2.2.171
Loading template main/metrics-2.2.167.json
Loading template main/chat-letschat-2.2.167.json
Loading template microservices/git-collector-2.2.167.json
Loading template main/chat-irc-2.2.167.json
Loading template microservices/fabric8-docker-registry-2.2.167.json
Loading template microservices/gogs-2.2.167.json
Loading template microservices/letschat-2.2.167.json
Loading template microservices/fabric8-forge-2.2.171.json
Loading template main/chat-slack-2.2.167.json
Loading template microservices/gitlab-2.2.167.json
Loading template main/cd-pipeline-2.2.171.json
Loading template microservices/chaos-monkey-2.2.167.json
Loading template main/social-2.2.167.json
Loading template microservices/gerrit-2.2.167.json
Loading template main/management-2.2.167.json
Loading template microservices/artifactory-2.2.167.json
Loading template main/logging-2.2.167.json
Loading template microservices/kiwiirc-2.2.167.json
Loading template microservices/jenkins-2.2.167.json
Loading template microservices/nexus-2.2.167.json
Install DevOps templates......................................................✔ 
Downloading templates for version 2.2.117
Loading template microservices/message-broker-2.2.117.json
Loading template microservices/example-message-consumer-2.2.117.json
Loading template microservices/example-message-producer-2.2.117.json
Loading template main/messaging-2.2.117.json
Loading template microservices/kafka-2.2.117.json
Loading template main/apiman-2.2.117.json
Loading template microservices/zookeeper-2.2.117.json
Loading template microservices/message-gateway-2.2.117.json
Install iPaaS templates.......................................................✔ 
Downloading templates for version 1.0.16
Loading template main/kubeflix-1.0.16.json
Loading template microservices/hystrix-dashboard-1.0.16.json
Loading template microservices/turbine-server-1.0.16.json
Install Kubeflix templates....................................................✔ 
Create routes.................................................................✔ ```

The oauthclient shows up as so:

```
[root@jj-float155 ~]# oc get oauthclient fabric8
NAME      SECRET    WWW-CHALLENGE   REDIRECT URIS
fabric8             FALSE           http://localhost:9090,http://localhost:2772,http://localhost:9000,http://fabric8.apps.jlabocki.syseng.us,https://fabric8.apps.jlabocki.syseng.us
```

When I browse to http://fabric8.apps.jlabocki.syseng.us/ , I am redirected to:

`https://apps.jlabocki.syseng.us:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F&redirect_uri=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F
`

However, this time if I s/10.19.139.155/apps.jlabocki.syseng.us` I arrive at the openshift console to authenticate. Upon successful authentication, however I am redirected back to:

`https://apps.jlabocki.syseng.us:8443/oauth/authorize?client_id=fabric8&response_type=token&state=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F%3Fstate%3Dhttp%253A%252F%252Ffabric8.apps.jlabocki.syseng.us%252F&redirect_uri=http%3A%2F%2Ffabric8.apps.jlabocki.syseng.us%2F%3Fstate%3Dhttp%253A%252F%252Ffabric8.apps.jlabocki.syseng.us%252F`

**Comment by jameslabocki** [comment]
Maybe I will try removing all the routes, services, rc, oauthclient, and removing the containers+images to see if there is something that is being passed in as an environment variable or stored in the image?

**Comment by jameslabocki** [comment]
No luck, even after completing removing images, services, routes, oauthclient, etc. I'm not sure what is causing the redirect to apps.jabocki.syseng.us (which points to the openshift node at 10.19.139.161) instead of redirecting to 10.19.139.151 (the openshift master). 

# gofabric8 deploy -y -s https://10.19.139.155:8443 --domain apps.jlabocki.syseng.us --api-server 10.19.139.155

# oc get oauthclient fabric8
NAME      SECRET    WWW-CHALLENGE   REDIRECT URIS
fabric8             FALSE           http://localhost:9090,http://localhost:2772,http://localhost:9000,http://fabric8.apps.jlabocki.syseng.us,https://fabric8.apps.jlabocki.syseng.us

**Comment by jameslabocki** [comment]
Fixed, I followed this post: https://groups.google.com/forum/#!topic/fabric8/nblbeAVkMeM

and changed all oauthclient entries to point to fabric8.apps.jlabocki.syseng.us and then `systemctl restart atomic-openshift-master`

-James
