### ISSUE TITLE
Unable to Deploy CD Pipeline application

### ISSUE THREAD

**Issue by jameslabocki** [fabric8io/fabric8#5999]
I'm a fabric8 newbie, so I apologize if I'm missing something obvious. I have deployed fabric8 on openshift and am now trying to deploy an application. I am told in the UI that I need to "Run the CD Pipeline". When I deploy it, it gets past the service account creation for "gogs" and "jenkins". The rest of the deployment just spins including "Kind: Secret gogs-https-admin" and all the rest of the pieces. 

Here is a screencast:
https://allthingsopendotcom.files.wordpress.com/2016/05/fabric8problem.mov

I have no idea how to troubelshoot this. Is there some log I should be watching to see what is failing or where it is hung?

**Comment by rawlingsj** [comment]
You'll need to run 'gofabric8 secrets' to generate the default secrets needed for the pods to start. We need to remove this step and include everything in the single gofabric8 deploy.

**Comment by jameslabocki** [comment]
Thanks, that seems to have worked (although I hit a weird UI bug where no templates shows up, but if I click the green arrow fast enough I can deploy the template before it disappears). 

Just so I get smarter about fabric8, how would I have debugged that? Is there a log I could have looked at to see why the deployment was failing? thanks!

**Comment by jstrachan** [comment]
There may be errors in the JavaScript console. Hitting reload in your browser can help if things get wonky
