### ISSUE TITLE
Java.lang.IllegalStateException: : No adapter available for type:class io.fabric8.kubernetes.client.ExtensionsAPIGroupClient

### ISSUE THREAD

**Issue by pmganachari** [fabric8io/fabric8#6004]
Hello,

I am trying to create Kubernetes Job using following code.
**client.extensions().jobs().inNamespace("aa-system").create(job);**
with all necessary data filled in job.

Getting following exception.
FAILED: **java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.ExtensionsAPIGroupClient**
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.ExtensionsAPIGroupClient
        at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:135)
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.extensions(DefaultKubernetesClient.java:214)

any suggestions would be appreciated.

Regards,
Pradeep

**Comment by jimmidyson** [comment]
What version of kubernetes-client are you using? I can't seem to reproduce it.

**Comment by pmganachari** [comment]
libraryDependencies += "io.fabric8" % "kubernetes-client" % "1.3.90"
libraryDependencies += "io.fabric8" % "kubernetes-model" % "1.0.45"
 %  "provided"
libraryDependencies += "io.fabric8" % "kubernetes-api" % "2.2.115"
%  "provided"


and rest are compile dependencies..

we want to run an algorithm (which is a jar file) as Kubernetes Job.

An application (replication controller), which creates kubernetes Job
(algorithm to calculate threshold value).
Hence, *client.extensions().jobs().inNamespace("aa-system").create(job); *code
runs in application which is replication controller.

As in, We will create replication controller first with ./kubectl create -f
coommand, which in turn tries to create kubernetes Job.

**Comment by jstrachan** [comment]
Does removing the 2 "provided" clauses help?

**Comment by jstrachan** [comment]
I think I saw on another thread that this was fixed via sbt changes right? Gonna close for now - will reopen if there's still an issue

**Comment by ngtuna** [comment]
@jstrachan Not sure how it worked to you but I got this same issue when creating deployment. I am on k8s 1.8.7 - probably k8s version causes the problem I guess.
