### ISSUE TITLE
authentication not supported when copying flow to project

### ISSUE THREAD

**Issue by jameslabocki** [fabric8io/fabric8#6017]
I am creating a new application. I get to the "Edit the DevOps configuration for this project" screen, I select "Copy flow to project". Here is a screenshot.

![screenshot from 2016-05-17 09-17-53](https://cloud.githubusercontent.com/assets/238043/15323591/bf977bdc-1c10-11e6-9c22-a484618390bb.png)

I get the following error. It seems to point to an authentication error with the gogs service. I'm not sure if there is a step I missed when deploying the CD-pipeline or App that is causing this. Any ideas on what I should do to debug this? How is fabric8 attempting to authenticating to the gogs service? Where is it set?

> The last operation resulted in the following error:
> Error 500 Server Error
> HTTP ERROR 500
> Problem accessing /api/forge/command/execute/devops-edit. Reason:
> 
>     Server Error
> Caused by:
> 
> org.apache.cxf.interceptor.Fault: http://gogs.apps.jlabocki.syseng.us/gogsadmin/next-big-thing2.git: authentication not supported
> org.apache.cxf.interceptor.Fault: http://gogs.apps.jlabocki.syseng.us/gogsadmin/next-big-thing2.git: authentication not supported
> 	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
> 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
> 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:517)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.eclipse.jgit.api.errors.TransportException: http://gogs.apps.jlabocki.syseng.us/gogsadmin/next-big-thing2.git: authentication not supported
> 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:164)
> 	at io.fabric8.forge.rest.main.GitHelpers.doCommitAndPush(GitHelpers.java:156)
> 	at io.fabric8.forge.rest.main.GitHelpers.doAddCommitAndPushFiles(GitHelpers.java:168)
> 	at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:806)
> 	at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
> 	at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:753)
> 	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteoperation(RepositoryResource.java:749)
> 	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:743)
> 	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:591)
> 	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:559)
> 	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:273)
> 	at sun.reflect.GeneratedMethodAccessor970.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
> 	... 39 more
> Caused by: org.eclipse.jgit.errors.TransportException: http://gogs.apps.jlabocki.syseng.us/gogsadmin/next-big-thing2.git: authentication not supported
> 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:480)
> 	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:379)
> 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:155)
> 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1250)
> 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:157)
> 	... 54 more

**Comment by rawlingsj** [comment]
There's a secrets tab next to the pipeline one you're on, from there you should be able to select the pre installed `gogs-https-admin` secret, this should allow forge to create the project.

**Comment by jameslabocki** [comment]
Thanks!

**Comment by rawlingsj** [comment]
phew :)
