### ISSUE TITLE
app support for persistent volumes

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6021]
After the great work @paoloantinori has done on our internal Kubernetes cluster we now have GlusterFS PV available.  

Initially to start with, for fabric8's own purposes it would be good for PV to be supported by templates ..

- elasticsearch - store events and charts we want to demonstrate continuous improvement of fabric8 itself
- jenkins - save pipeline state so pipelines can withstand failure
- gogs - store project source code

OpenShift create multiple templates so one for persistece and a second for non persistent apps, @jimmidyson @rhuss and I were talking on IRC about possible ways we could support PV in our existing apps.  Currently we came up with these options..

1. Duplicate java projects used to generate kuberneres.json and add in PV related properties - (seems a bit rubbish)
2. If PV is specified in the POM f-m-p generates persistent and non persistent versions of JSON
3. Console provides an option at deploy-time asking if persistence is required and sets up the PVC and PV

Option 3 sounds best, but I guess might involve a bit of work.  Any other options we can think of?  

@jstrachan @gashcrumb what do you guy's think?

**Comment by jstrachan** [comment]
I wonder if we should add PVCs everywhere we think they should be; then folks can bind those to any implementation they wish. Then have a tool to generate an `emptyDir` equivalent that gives a tiny bit of local persistence until the pods move (which is OK for single node folks)?

Not sure if we have to generate 2 templates for each project; or if we let tools like the fabric8-console or gofabric8 do the transformation for folks running things on 1 node?

e.g. gofabric8 can install the emptyDir or PVC version of the templates?

**Comment by jstrachan** [comment]
PVCs seem like the right thing we should be doing everywhere; seems the `emptyDir` is a hack transform we do on installation of single nodes (or use in the console on a single node system?)

**Comment by jstrachan** [comment]
I wonder if we could make a PV implementation for folks using 1 node that just uses the host file system? :)

**Comment by jstrachan** [comment]
DOH - there's HostPath already for single nodes!
http://kubernetes.io/docs/user-guide/persistent-volumes/

so we should just use that for single nodes and always use PVs?

**Comment by rawlingsj** [comment]
:) I was just typing that about using hostpath - yeah great idea about the single node thing

**Comment by jstrachan** [comment]
it should be easy, hopefully, to automate setting up the PV HostPath stuff in gofabric8...

**Comment by jstrachan** [comment]
gonna close this one as its almost fixed and being tracked now by this issue: https://github.com/fabric8io/fabric8/issues/4413
