### ISSUE TITLE
Fabric8/Vagrant - Tearing Down VM

### ISSUE THREAD

**Issue by mbooco** [fabric8io/fabric8#6079]
When I tear down my VM using vagrant halt and then start it with vagrant up. I notice all my gogs and Jenkins repositories are there. I have tried vagrant suspend/up but it gets stuck coming back up with: default: Warning: Remote connection disconnect. Retrying...then ssh does not get started.

Vagrant halt/up works fine but I lose my work when it come back up.

Any suggestion how to tear down a VM without losing data files?

**Comment by rawlingsj** [comment]
@mbooco I think there was a slight typo above, did you mean __aren't there__

>  I notice all my gogs and Jenkins repositories are there

We have an open issue about adding persistence into our apps, unfortunately we've not got to it yet but it is needed, totally agree it's a pain loosing data.  FWIW the issue where we're discussing options is..

https://github.com/fabric8io/fabric8/issues/6021

**Comment by mbooco** [comment]
Sorry, yes it is a typo..

Corrected...I did noticed all my Gogs and Jenkins repositories are NOT
persisted after performing vagrant halt/up on my laptop.

After reading #6021 <https://github.com/fabric8io/fabric8/issues/6021>, and
your comment I agree this feature should be an important priority.

Any timetable mentioned yet?

Thanks

**Comment by rawlingsj** [comment]
The next two weeks are really busy with conferences for a bunch of the main fabric8 committers.  Once back, one of the priorities is to migrate our apps to the new fabric8-maven-plugin so I think that's going to be the best time to add in support for persistence volumes.  I'd say the work should start around then.

**Comment by jstrachan** [comment]
gonna close this one as its almost fixed and is being tracked by this issue: https://github.com/fabric8io/fabric8/issues/4413

**Comment by mbooco** [comment]
Thanks for the update.

Mark

**Comment by jstrachan** [comment]
BTW it's fixed now - if you grab the latest 'gofabric8' and run the deploy command
