### ISSUE TITLE
the injected KubernetesClient should be pre-configured to use the integration test namespace from Arquillian's Session

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#6101]
right now the KubernetesClient and kubernetes-assertions are not usable in the `fabric8-arquillian` namespace by default. Really this should be done by default so that you can do `assertThat(client).pods()` etc without worrying about the namespace.

I've a patch (using reflection :) on its way; @iocanel ideally a MutableKubernetesClient that has a setNamespace() method might be cleaner :)

**Comment by jstrachan** [comment]
@iocanel see this code - I'm sorry, I'm a bad man! :) 
https://github.com/jstrachan/fabric8/blob/9184b6859b5100baac51af4778a41028cd774f6d/components/fabric8-arquillian/src/main/java/io/fabric8/arquillian/kubernetes/SessionListener.java#L129-L141

The main issue is we only know/create the namespace name after the KubernetesClient is created; so we need a way to mutate it. So wondered about a mutable version of DefaultKubernetesClient?

Not sure why we can't just call setNamespace() on a KubernetesClient; I mean we switch namespaces on the CLI and console all the time?

**Comment by jimmidyson** [comment]
You already have `inNamespace` in the DSL for all types - why isn't that enough?

**Comment by jstrachan** [comment]
it returns a new modified object which is different to the one that Arquillian has injected everywhere

**Comment by jstrachan** [comment]
if we could figure out how to have the ARQ Session when we create the KubernetesClient - and we had the Session initialised so that its chosen the namespace - we could avoid this - but I've zero clue how to even go about doing that
