### ISSUE TITLE
Docker container creation needs at least one command to run after container is started

### ISSUE THREAD

**Issue by pires** [fabric8io/fabric8#613]
When trying to create a Docker container (after #599 is merged) with *Cmd* undefined (as by default), Docker daemon will return HTTP Status 500:

```
2014/01/29 15:05:00 POST /containers/create
[/var/lib/docker|a100a26b] +job create()
No command specified[/var/lib/docker|a100a26b] -job create() = ERR (1)
[error] api.go:1064 Error: create: No command specified
[error] api.go:87 HTTP Error: statusCode=500 create: No command specified
```

Given this, and accordingly to @jstrachan, one should update the Docker profile to include a default *Cmd* value.

**Comment by davsclaus** [comment]
v1 is only maintained about the osgi/karaf stuff. So closing this as for docker you should use fabric8 v2
