### ISSUE TITLE
gogs and jenkins data is lost after VM restart

### ISSUE THREAD

**Issue by n-k** [fabric8io/fabric8#6142]
When using the openshift vagrant install, if VM is restarted all projects in gogs and all builds in jenkins are lost.

**Comment by jmlambert78** [comment]
normal, as no PV are defined per default

**Comment by jmlambert78** [comment]
I mean Persistent Volumes...

**Comment by AaoGITKarein** [comment]
@jmlambert78 Yes, Fabric8io team is already working on that, For your reference  https://github.com/fabric8io/fabric8/issues/6021

**Comment by n-k** [comment]
@AaoGITKarein that's great to know! This is clearly a duplicate so I will close this.
