### ISSUE TITLE
Starting fabric8 using vagrant openshift do not create routes

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#6182]
so you cannot open the web console anymore.

![screen shot 2016-07-21 at 9 00 25 am](https://cloud.githubusercontent.com/assets/477100/17023486/986a700c-4f21-11e6-96fd-7fbc7161cee2.png)

```
davsclaus:/workspace/fabric8-installer/vagrant/openshift (master)/$ oc get pods
NAME                            READY     STATUS    RESTARTS   AGE
docker-registry-1-85ei4         1/1       Running   0          36m
fabric8-docker-registry-tq75r   1/1       Running   0          41m
fabric8-forge-z89bt             1/1       Running   0          41m
fabric8-hl12k                   1/1       Running   0          42m
gogs-auq5f                      1/1       Running   0          41m
jenkins-026wg                   1/1       Running   0          41m
nexus-9f5lg                     1/1       Running   0          41m
router-1-m89p1                  2/2       Running   0          36m
davsclaus:/workspace/fabric8-installer/vagrant/openshift (master)/$ oc get routes
davsclaus:/workspace/fabric8-installer/vagrant/openshift (master)/$
```

Using the latest 
    Image:		fabric8/fabric8-console:2.2.163

**Comment by davsclaus** [comment]
I cannot see any errors in `oc get events`

**Comment by jstrachan** [comment]
Ah - we've tried to make things work nicer on minishift without needing to run the router. Think in the Vagrantfile we need to move the router creation up first before gofabric8 - or run 'gofabric8 routes' after we start the router?

**Comment by christian-posta** [comment]
i've merged https://github.com/fabric8io/fabric8-installer/pull/99 to sort this btw

**Comment by davsclaus** [comment]
Fixed by @christian-posta in gofabric8 - thanks
