### ISSUE TITLE
allow selecting version of spring-boot from fabric8 create-project wizard

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#6201]
love that fabric8 uses the spring initializr stuff from start.spring.io.
Would love to be able to specify what version of spring-boot to use like start.spring.io does

https://www.evernote.com/shard/s180/sh/1bb9bec8-e456-4612-92cc-d112326c09c9/3c5d54a4f12aa7673a0daab85f6b0db2

**Comment by davsclaus** [comment]
```
* Build system: [0]

[0] (x) 1.3.7
[1] ( ) 1.4.0

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Spring Boot Version (Spring Boot Version to use): [0-1]
```

**Comment by davsclaus** [comment]
Will be fixed by https://github.com/fabric8io/fabric8-forge/pull/435
