### ISSUE TITLE
Archetype catalog is not generated

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#6237]
For some reason, I'm not seeing the archetype catalog here: (versions before 2.2.105 had the proper xml catalog built)

http://central.maven.org/maven2/io/fabric8/archetypes/archetypes-catalog/2.2.105/
http://central.maven.org/maven2/io/fabric8/archetypes/archetypes-catalog/2.2.159/
http://central.maven.org/maven2/io/fabric8/archetypes/archetypes-catalog/2.2.161/

I do see the xml here, but it returns 404 when i click on it:

http://central.maven.org/maven2/io/fabric8/archetypes/archetypes-catalog/2.2.104/

**Comment by jstrachan** [comment]
Yeah the attach of the archetype-catalog does look a tad broken. Note though that we tend to use the jar which has the archetype catalog inside it.

**Comment by christian-posta** [comment]
@jstrachan true, but tooling like JBDS/Eclipse/IntelliJ need the XML catalog file i think.. seems like it's created properly (target/classes/archetype-catalog.xml) and the pom.xml says to put it into the release. When I try locally to do a deploy it does attach properly. Can point me to the build where this is done so I can take a look why it's not working?
