### ISSUE TITLE
Validation of REST service proxy API : Cannot query the API Server REST Proxy Service API at 

### ISSUE THREAD

**Issue by arubalac** [fabric8io/fabric8#6250]
Hi,

I just installed minikube in my Mac and deployed gofabric8 as per the "Getting Started" documentation. 

When I executed the `gofabric8 validate` command , I am getting the following response:

<img width="1247" alt="screen shot 2016-08-13 at 10 41 19 pm" src="https://cloud.githubusercontent.com/assets/10407640/17647482/33556738-61a7-11e6-9e93-bbfe2b0e071f.png">

Could you please let me know , what might be the cause of this issue. I verified that the kubernetes (minikube) is running fine .
Is it a show stopper in going forward with working on fabric8. Please help in resolving the same. Thank you.

Regards
Arun

**Comment by rajdavies** [comment]
As a work around, type  minikube service fabric8 --url - and connect to the console using the result - e.g.

$ minikube service fabric8 --url
http://192.167.64.8:30064
