### ISSUE TITLE
The pipeline screen doesn't show up

### ISSUE THREAD

**Issue by samiaben88** [fabric8io/fabric8#6277]
Hi,
I'm deploying a nodejs app using an openshift cluster (one master and one node) 
when i want to deploy my nodejs project that is in bitbucket, after i put the adress of my git repository and the secret , the pipeline screen doesn't show up, i got juste the wait icon, any idea?
this are the logs in fabric8-forge pod:
[fabric8-forge logs.txt](https://github.com/fabric8io/fabric8/files/434217/fabric8-forge.logs.txt)

**Comment by rawlingsj** [comment]
It looks like you have a dns issue in you cluster.  The stacktrace in the log you attached has a line 

```
java.net.UnknownHostException: kubernetes.default.svc
```

To check could you try this test please? 
https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#how-do-i-test-if-it-is-working

**Comment by samiaben88** [comment]
i try this and i got that:

# kubectl exec busybox -- nslookup kubernetes.default
Server:    178.33.25.174
Address 1: 178.33.25.174 ip174.ip-178-33-25.eu

Name:      kubernetes.default
Address 1: 172.30.0.1

**Comment by rawlingsj** [comment]
Yeah that looks fine, could you try and kill the fabric8 forge pod, letting the RC recreate it and try to create a new project again?  Not sure yet why the forge pod had that error when the test above worked.

**Comment by samiaben88** [comment]
i delete the fabric8-forge pod it got recreated, but I still have the same exeption:
Caused by: 
java.net.UnknownHostException: kubernetes.default.svc: unknown error
I dont understand why ?

**Comment by rawlingsj** [comment]
I just noticed the two hostnames are slightly different, forge is using `kubernetes.default.svc` rather than `kubernetes.default`, in your busybox test can you try to append `.svc` ?
```
kubectl exec busybox -- nslookup kubernetes.default.svc
```

**Comment by samiaben88** [comment]
This is what I get : 

[root@fabric8 ~]# kubectl exec busybox -- nslookup kubernetes.default.svc
Server:    178.33.25.174
Address 1: 178.33.25.174 ip174.ip-178-33-25.eu

Name:      kubernetes.default.svc
Address 1: 172.30.0.1

**Comment by rawlingsj** [comment]
Can you try to lookup the hostname from within the running forge pod?  It doesn't have nslookup so maybe try this, if you can connect to the API server you should get an unauthorized error..

```
oc exec  $(oc  get pods | grep fabric8-forge | cut -f 1 -d ' ') -- curl --insecure  https://kubernetes.default.svc
```

@jimmidyson any ideas what might be going on?

**Comment by jimmidyson** [comment]
What forge image is this using? Are they both running on the same node? Are /etc/resolv.conf the same in the busybox pod & the forge pod?

**Comment by samiaben88** [comment]
This is the forge image : 
Image: fabric8/fabric8-forge:2.3.17

My fabric8 pod and fabric8-forge are running in the same master node.

this is the /etc/resolv.conf from the busybox pod:
/etc # cat resolv.conf                                                          
search default.svc.cluster.local svc.cluster.local cluster.local otrux.com      
nameserver 178.33.25.174                                                        
nameserver 178.33.25.174                                                        
options ndots:5   

this is the /etc/resolv.conf from the forge pod:
sh-4.2$ cat resolv.conf                                                         
search sunseed.svc.cluster.local svc.cluster.local cluster.local otrux.com      
nameserver 178.33.25.173                                                        
nameserver 213.186.33.99                                                        
options ndots:5

**Comment by jimmidyson** [comment]
> My fabric8 pod and fabric8-forge are running in the same master node.

So they're both running on the same host? On 178.33.25.173 (the master as you specified above) or 178.33.25.174 (the node as you specified above)?

**Comment by jimmidyson** [comment]
This might be easier if you jump on freenode IRC #fabric8 channel plus gist.github.com for any long info we need.

**Comment by samiaben88** [comment]
The busybox is runing on the slave node : 178.33.25.174
 fabric8-forge is running on the master node: 178.33.25.173

**Comment by jimmidyson** [comment]
OK that makes a bit more sense. Can you check on the master what is listening on port 53 - is it openshift? Something like `sudo netstat -tulpn | grep :53` on the master should show up the process listening in the last column. If it is openshift, can you try on the host `dig @localhost kubernetes.default.svc.cluster.local` to see if it resolves that properly?

**Comment by samiaben88** [comment]
whet i do the netstate I dont get anything in the master, but in the slave i get this : 
*tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1065/dnsmasq
tcp6       0      0 :::53                   :::*                    LISTEN      1065/dnsmasq
udp        0      0 0.0.0.0:53              0.0.0.0:*                           1065/dnsmasq
udp6       0      0 :::53                   :::*                                1065/dnsmasq

in the slave : 
dig @localhost kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @localhost kubernetes.default.svc.
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54607
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A   172.30.0.1

;; Query time: 12 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Aug 24 05:12:32 EDT 2016
;; MSG SIZE  rcvd: 70

in the master : 
 dig @localhost kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @localhost kubernetes.default.svc.cluster.local
; (2 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by jimmidyson** [comment]
What version of OpenShift are you running? This looks like a problem with the master config. Can you check the logs as that should start DNS server automatically unless you've explicitly disabled that in the master config AFAIK?

**Comment by jimmidyson** [comment]
Ah seeing https://github.com/openshift/origin/pull/7807 it seems this has changed. Need to look at this more. This is more of an OpenShift question than a fabric8 one though but let's see what we can find out.

**Comment by jimmidyson** [comment]
I assume you're using OpenShift >= 1.3.0-alpha.2?

**Comment by samiaben88** [comment]
I install openshift with ansible script
deployment_type=origin
openshift_release=v1.2
 
and this is my master config in /etc/origine/master/master-config.yaml: 

admissionConfig:
apiLevels:
- v1
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://fabric11.otrux.com:8443
  publicURL: https://fabric11.otrux.com:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
controllers: '*'
corsAllowedOrigins:
  - 127.0.0.1
  - localhost
  - 178.33.25.173
  - kubernetes.default
  - kubernetes.default.svc.cluster.local
  - kubernetes
  - openshift.default
  - openshift.default.svc
  - fabric11.otrux.com
  - 172.30.0.1
  - openshift.default.svc.cluster.local
  - kubernetes.default.svc
  - openshift
dnsConfig:
  bindAddress: 0.0.0.0:8053
  bindNetwork: tcp4
etcdClientInfo:
  ca: ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
    - https://fabric11.otrux.com:4001
etcdConfig:
  address: fabric11.otrux.com:4001
  peerAddress: fabric11.otrux.com:7001
  peerServingInfo:
    bindAddress: 0.0.0.0:7001
    certFile: etcd.server.crt
    clientCA: ca.crt
  keyFile: etcd.server.key
  servingInfo:
    bindAddress: 0.0.0.0:4001
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
  storageDirectory: /var/lib/origin/openshift.local.etcd
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
     {}
  apiServerArguments:
  controllerArguments:
  masterCount: 1
  masterIP: 178.33.25.173
  podEvictionTimeout:
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerConfigFile: /etc/origin/master/scheduler.json
  servicesNodePortRange: ""
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
masterClients:
  externalKubernetesKubeConfig: ""
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: https://fabric11.otrux.com:8443
networkConfig:
  clusterNetworkCIDR: 10.1.0.0/16
  hostSubnetLength: 8
  networkPluginName: redhat/openshift-ovs-subnet
# serviceNetworkCIDR must match kubernetesMasterConfig.servicesSubnet
  serviceNetworkCIDR: 172.30.0.0/16
oauthConfig:
 assetPublicURL: https://fabric11.otrux.com:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: htpasswd_auth
    provider:
      apiVersion: v1
      file: /etc/origin/master/htpasswd
      kind: HTPasswdPasswordIdentityProvider
  masterCA: ca.crt
  masterPublicURL: https://fabric11.otrux.com:8443
  masterURL: https://fabric11.otrux.com:8443
  sessionConfig:
    sessionMaxAgeSeconds: 3600
    sessionName: ssn
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 500
pauseControllers: false
policyConfig:

  bootstrapPolicyFile: /etc/origin/master/policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: "s0:/2"
    mcsLabelsPerProject: 5
    uidAllocatorRange: "1000000000-1999999999/10000"
routingConfig:
  subdomain:  "fabric11.otrux.com"
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
 bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: True

**Comment by samiaben88** [comment]
oc version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5

**Comment by jimmidyson** [comment]
I'm personally unfamiliar with the ansible scripts but the master needs dnsmasq running too as it's a scheduleable node in your setup.

**Comment by jimmidyson** [comment]
On the master can you share the output of `systemctl status dnsmasq` please?

**Comment by jimmidyson** [comment]
Wonder if this is openshift/openshift-ansible#2115 ?

**Comment by samiaben88** [comment]
When i got the instalation of my openshift done, i could run the pipline and i got my  project in jenkins, but after that i faced i problem : i didend have had enought memory RAM , when now i fix the problem, i got this one

**Comment by jimmidyson** [comment]
So this is after a reboot? Wonder if dnsmasq on the master wasn't started properly, perhaps not enabled on boot? `systemctl status dnsmasq` should help with that hopefully.

**Comment by samiaben88** [comment]
yes indeed:

systemctl status dnsmasq
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

**Comment by jimmidyson** [comment]
So can you try starting that with `systemctl enable dnsmasq; systemctl start dnsmasq`. Also can you share `ls -l /etc/dnsmasq*` please to check it's configured properly?

**Comment by samiaben88** [comment]
yeaaay it works, thanks a looot ^_^

**Comment by jimmidyson** [comment]
Yay! Glad to be of help.
