### ISSUE TITLE
how to specify a image version for  exposecontroller during install 

### ISSUE THREAD

**Issue by Fei-Guang** [fabric8io/fabric8#6287]
i deploy it with 

`    gofabric8 deploy -y`

`$kubectl get pod

    exposecontroller-3595537957-xa1ci          0/1       ImagePullBackOff   0          1d
    fabric8-docker-registry-3325330425-kw513   1/1       Running            0          1d
    fabric8-forge-1940540613-hluak             1/1       Running            0          1d
    fabric8-pipqr                              2/2       Running            0          1d
    gogs-2269793706-in1iu                      1/1       Running            0          1d
    ingress-nginx-2962199599-4n4wa             1/1       Running            0          1d
    nexus-324233599-o8re9                      1/1       Running            0          1d`

exposecontroller always  need to pull and there is an error , how to specify a version like fabric8/exposecontroller:2.2.242

**Comment by rawlingsj** [comment]
Hi @Fei-Guang - you can edit the deployment (kubernetes) / deploymentconfig (openshift) and append the version tag to the image name using

```
kubectl edit deployment exposecontroller
```
then with the vi editor append the version to the line  `image: fabric8/exposecontroller`

For now I left off the version being automatically added but I can add it back in.  What I dont understand tough is why the image isn't found?  I.e. the :latest tag should be found and pulled by default if no tag appears at the end of the image name.

for example, this works..
```
docker pull fabric8/exposecontroller
```
Can you get the logs of `kubectl describe pod exposecontroller-3595537957-xa1ci` please?

**Comment by Fei-Guang** [comment]
only the master is connected with internet, but the the minion node is not . i want to the minion doesn't pull the image. i'll try to edit the deployment (kubernetes).

**Comment by jstrachan** [comment]
All kubernetes nodes need Internet access so that the docker daemons can each pull docker images

**Comment by Fei-Guang** [comment]
i edit the deployment to change imagePullPolicy: IfNotPresent and the pod  is running .
