### ISSUE TITLE
How to add a PVC to my default Gogs pod

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6296]
I have a kubernetes cluster running on Ubuntu 16.04. I installed fabric8 with:
 `gofabric8 deploy --app=cd-pipeline`.
I noticed that Gogs is not having persistent storage by default. I have created a PV using kubectl and I also created a PVC. Now, how do I add this PVC to the gogs pod?

**Comment by rawlingsj** [comment]
Hi @chbe8475, right now I'm afraid we don't have support for persistent volumes yet however this is being addressed at the moment.  We're working on a feature to be able to automatically persist gogs + jenkins + elasticsearch etc using a PV controller, whether you're running a single VM locally and use hostpath or are on a public cloud and want to use a hosted PV implementation.  For more info you might want to track this issue https://github.com/fabric8io/fabric8/issues/6253 for which development is underway.

**Comment by chbe8475** [comment]
Ok thanks.
