### ISSUE TITLE
make it easier to find out what the default gogs admin user and pw is

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6303]
Right now it's very hard to find out what the default username and password is for gogs.  Perhaps we should output this at the end of `gofabric8 deploy` and display it in the the UI when running the cd-pipeline app?

**Comment by Mahaswami** [comment]
Also it would be great if we can fix the Dockerfile documentation for gogs. it says password is admin123.

If you can just guide me to where to fix that I can get you a PR right away.

**Comment by rawlingsj** [comment]
Good point thanks @Mahaswami, the gogs dockerfile is https://github.com/fabric8io/docker-gogs/blob/master/Dockerfile#L8

Having said that we're in the process of updating the gogs image and I think there may be a different way to set the admin user so this change may not be needed. 

@jimmidyson do we set the admin user differently with your updates to the gogs image?

**Comment by jimmidyson** [comment]
No it's exactly the same, via env var that should really be generated on deployment.

**Comment by jimmidyson** [comment]
Fixes by #102

**Comment by rawlingsj** [comment]
Fixed with https://github.com/fabric8io/docker-gogs/commit/72a5adb4da0748acfa3a4f748e5c556c6de1277e
and we now print a summary at the end of `gofabric8 deploy`
