### ISSUE TITLE
Attempting to add 'microservice' app on Fabric8 freshly deployed on Kubernetest 1.3.5 returns 504 at pipeline selection step

### ISSUE THREAD

**Issue by kb1ca** [fabric8io/fabric8#6307]
(opening issue at the direction of ceposta after conversation on IRC)

I have deployed a brand new Kubernetes 1.3.5 cluster, using their vSphere quickstart script. The configuration was altered to deploy 8 nodes to avoid a low disk space issue on the nodes, and 2 CPUs with 8Gb of ram were allocated to each node.

I then deployed fabric8 on top using gofabric8 v0.4.45 thusly:

`./gofabric8 deploy -y --domain=f8.scrd.ad --app=cd-pipeline`
`./gofabric8 secrets -y`

No problems were reported, and all the pods eventually entered running status. I verified the deployment with `./gofabric8 validate` and no errors were reported.

I proceeded to configure a wildcard dns record for *.f8.scrd.ad pointing to the ingress controller and brought up the fabric8 console. All looked fine.

I navigated to the 'default' team dashboard, selected 'create new app', and got as far as the 'pipelines' tab. At that point I got a '504 The previous operation timed out' message at the top of the frame, above the tiles for the different pipelines, but below the tabs. The Chrome debug console logs output similar to:

`libs.js:120926[Forge] About to post to k8s/api/v1/proxy/namespaces/default/services/fabric8-forge:80/api/forge/command/execute/project-new?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin payload: {"namespace":"default","resource":"","inputList":[{"type":"Microservice","topLevelPackage":"org.example","version":"1.0.0-SNAPSHOT","targetLocation":"/opt/jboss","stack":"None","overwrite":false,"named":"test10"}]}
libs.js:120926[Kubernetes] Navigating to the relative path: workspaces/default/projects/test10/forge/command/devops-edit`
` `
`libs.js:120926[Forge] About to post to k8s/api/v1/proxy/namespaces/default/services/fabric8-forge:80/api/forge/command/execute/devops-get-overview?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin payload: {"namespace":"default","projectName":"test10","resource":"","inputList":[{"format":"JSON"}]}
http://fabric8.default.f8.scrd.ad/k8s/api/v1/proxy/namespaces/default/servi…s-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
libs.js:120926[Forge] Failed to load k8s/api/v1/proxy/namespaces/default/services/fabric8-forge:80/api/forge/command/execute/devops-get-overview?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.11.1</center>
</body>
</html>`

A pipeline tile can still be selected and the 'next' button is available, but clicking it just loops navigation back to the pipeline page and logs another 504 in the browser console. Returning to the team dashboard seems to show the app as configured, but the build never commences (even for other types of apps).

A copy of the complete log file from the fabric8-forge pod is available at https://gist.github.com/kb1ca/864fd189e68d910be487c41c590aa9ed

**Comment by rawlingsj** [comment]
Looking at the logs I can't see anything that's gone wrong, it reports that all the webhooks were set up correctly.

Do you have any insight to the resources being used?  The 504 issue may be related and I've seen that on openshift clusters when HA proxy is struggling.  I wonder just to test - can you try having the ingress controller on a node by itself using node selectors.  There maybe an easier way but one way to do this is make the node that we've assigned the nginx-controller to unschedulable..
```
kubectl patch nodes $NODENAME -p '{"spec": {"unschedulable": true}}'
```
then delete any other pods that are running on that node, these will then be scheduled to other nodes.

I wonder if memory is creeping up in some of our java apps like fabric8-forge / nexus / jenkins.  We are currently adding resource limits to our core apps and that should be released soon, we need to do a bit more testing though.

**Comment by kb1ca** [comment]
It looks like ingress-nginx already had a node all to itself:

`NAME                                       READY     STATUS    RESTARTS   AGE       IP           NODE`
`ingress-nginx-1158990307-rxgnw             1/1       Running   0          23h       10.244.3.3   172.16.6.124`
`gogs-733908790-7uynp                       1/1       Running   0          23h       10.244.7.2   172.16.6.141`
`fabric8-bmspe                              2/2       Running   0          17h       10.244.4.4   172.16.6.156`
`exposecontroller-4293711093-dzbdh          1/1       Running   0          23h       10.244.1.3   172.16.6.194`
`fabric8-docker-registry-3152672539-raubd   1/1       Running   0          23h       10.244.1.2   172.16.6.194`
`fabric8-forge-3208716130-dabjd             1/1       Running   0          17h       10.244.1.5   172.16.6.194`
`nexus-208730651-5du19                      1/1       Running   0          17h       10.244.5.2   172.16.6.195`
`jenkins-2744995563-w3sme                   1/1       Running   0          17h       10.244.6.2   172.16.6.198`

I'll try tearing down the k8s cluster and bringing it up fresh with 12Gb per node and see if that makes a difference.

**Comment by rawlingsj** [comment]
Ok, I think we should also apply some kubernetes resource limits to the ingress-nginx deployment.yml, not sure what other folks use. I'll have a look about and also take a look at our running ingress controller pods to see memory + CPU usage.

**Comment by kb1ca** [comment]
I saw no change in behavior with 12Gb per node so I went up to 16Gb and 4 CPUs per node. Still no success... Peeking inside all the pods none showed memory exhaustion or low disk space. Seems like it's not a resource limit?

Changing tactics I tore down the k8s cluster, built all the nodes out fresh again, and ran gofabric8 without including the cd-pipeline, thus:

`./gofabric8 deploy -y --domain=f8.scrd.ad`
`./gofabric8 secrets -y`

When I went into the default team dashboard and attempted to deploy a new app it didn't complain that cd-pipeline wasn't installed (?). Assuming that's just a ui glitch I went to the runtime overview and explicitly deployed the cd-pipeline. I was then able to select a pipeline for the microservice app without the 504 messages, complete the configuration, and eventually it started the canary build as expected.

**Comment by blindpirate** [comment]
I met this problem today, and it's exactly what you describe, @kb1ca , how do you resolve it?

**Comment by jstrachan** [comment]
any chance you could attach the log of the fabric8-forge pod? Not sure what request is causing the 504

**Comment by blindpirate** [comment]
I think I found why this occurs. Creating app is very, very slow (up to 2 min), thus gateway in network (e.g nginx) will respond prematurely.  In minikube of my local machines, everything is ok, which I think it's because of absence of gateways.

**Comment by jstrachan** [comment]
@blindpirate aha great catch! Certainly the first time you create a project its really slow as the fabric8-forge pod tends to download the maven internet right now unfortunately. Will see if we can try to improve the pre-caching.

I wonder if we can just increase the ingress timeout to something quite large?

**Comment by rawlingsj** [comment]
I think you can increase the timeout setting in the nginx configmap https://github.com/fabric8io/fabric8-devops/blob/master/ingress-nginx/src/main/fabric8/configmap.yml#L9
 and bounce the nginx-ingress pod

**Comment by rawlingsj** [comment]
You can edit the configmap using:
```
kubectl edit configmap nginx-config -n fabric8-system
```

**Comment by blindpirate** [comment]
@jstrachan @rawlingsj 
Thanks a lot!

**Comment by rawlingsj** [comment]
@blindpirate fingers crossed that helps.  If it does would you mind letting us know along with what value you used, then we can increase the default in the configmap for the next release.

**Comment by blindpirate** [comment]
@rawlingsj

Here is my configuration right now:

```
  client-max-body-size: 2000m
  proxy-connect-timeout: 10s
  proxy-read-timeout: 10s
  server-names-hash-bucket-size: "256"
  server-names-hash-max-size: "1024"
```

**Comment by blindpirate** [comment]
And I think this issue can be closed. :)

**Comment by jstrachan** [comment]
thanks @blindpirate for the update!

**Comment by rawlingsj** [comment]
@blindpirate just to check did you increase the `proxy-connect-timeout`?  The values you pasted above 

> Here is my configuration right now:
  client-max-body-size: 2000m
  proxy-connect-timeout: 10s
  proxy-read-timeout: 10s
  server-names-hash-bucket-size: "256"
  server-names-hash-max-size: "1024"

are the same as the existing config.  I wonder if there's a copy/paste accident there?
