### ISSUE TITLE
running apps in another namespace, have to hit run twice

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6318]
when selecting an app and choosing another namespace to deploy the app into I have to click `Run` twice for it do work

**Comment by rawlingsj** [comment]
One other thing I noticed which may be related is if you select a different namespace on the second page before clicking `Done` it's ignored and the app is deployed in the default namespace

**Comment by gashcrumb** [comment]
Think I've got this one all set, both issues you mentioned.  Just pushed a hawtio-kubernetes release so should be available in the console next time it gets built...

**Comment by gashcrumb** [comment]
@rawlingsj have you had a chance to verify this btw?

**Comment by rawlingsj** [comment]
all sorted!  thanks @gashcrumb
