### ISSUE TITLE
Delete replicaSet error

### ISSUE THREAD

**Issue by zhaorendong** [fabric8io/fabric8#6346]
Now I use the kubernetes-client 1.4.7.When I delete the replicaSet,it is error.the error message is:

<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The requested URL could not be retrieved</TITLE>
<STYLE type="text/css"></STYLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The requested URL could not be retrieved</H2>
<HR noshade size="1px">
<P>
While trying to process the request:
<PRE>
PATCH http://10.255.242.213:1180/apis/extensions/v1beta1/namespaces/default/replicasets/deploymenttest10-2977087190 HTTP/1.1
Content-Type: application/json-patch+json; charset=utf-8
Content-Length: 355
Host: 10.255.242.213:1180
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.4.1

[{&quot;op&quot;:&quot;replace&quot;,&quot;path&quot;:&quot;/spec/replicas&quot;,&quot;value&quot;:0},{&quot;op&quot;:&quot;add&quot;,&quot;path&quot;:&quot;/spec/template/metadata/annotations&quot;,&quot;value&quot;:{}},{&quot;op&quot;:&quot;add&quot;,&quot;path&quot;:&quot;/spec/template/spec/containers/0/resources/limits&quot;,&quot;value&quot;:{}},{&quot;op&quot;:&quot;add&quot;,&quot;path&quot;:&quot;/spec/template/spec/containers/0/resources/requests&quot;,&quot;value&quot;:{}},{&quot;op&quot;:&quot;add&quot;,&quot;path&quot;:&quot;/spec/template/spec/nodeSelector&quot;,&quot;value&quot;:{}}]
</PRE>
<P>
The following error was encountered:
<UL>
<LI>
<STRONG>
Invalid Request
</STRONG>
</UL>

<P>
Some aspect of the HTTP Request is invalid.  Possible problems:
<UL>
<LI>Missing or unknown request method
<LI>Missing URL
<LI>Missing HTTP Identifier (HTTP/1.0)
<LI>Request is too large
<LI>Content-Length missing for POST or PUT requests
<LI>Illegal character in hostname; underscores are not allowed
</UL>
<P>Your cache administrator is <A HREF="mailto:fcui@hp.com">fcui@hp.com</A>. 

<BR clear="all">
<HR noshade size="1px">
<ADDRESS>
Generated Wed, 14 Sep 2016 08:36:13 GMT by cmcscbks (squid/2.7.STABLE9)
</ADDRESS>
</BODY></HTML>

**Comment by jimmidyson** [comment]
That's very odd - what version of Kubernetes are you using?

**Comment by zhaorendong** [comment]
Tht version of Kubernetes is v1.3.3.

**Comment by jimmidyson** [comment]
You're going through a squid proxy by the look of things. Are you sure the proxy is configured properly to proxy patch requests?

**Comment by jimmidyson** [comment]
Looks like you need to upgrade squid - see http://squid-web-proxy-cache.1019090.n4.nabble.com/Minimum-Squid-Version-for-HTTP-PATCH-method-support-td4676661.html for discussion.

Closing as this looks like a proxy issue rather than a fabric8 one.

**Comment by zhaorendong** [comment]
Dear Jimmi,

I'm afraid there's some misunderstanding about the issue.
In my environment, there's no squid web proxy installed, we use bare-metal kubernetes.

It's quite odd that when deleting ReplicaSet, fabric8 returns "Invalid Request" back to java.
By using earlier releases v1.3.99, same error "Invalid Request" occurs while deleting ReplicationController.

Would you please help verify if this is some issue or not?
Thanks!

**Comment by jimmidyson** [comment]
Sorry if I've misunderstood but the original report shows an output page from a squid proxy.

`Generated Wed, 14 Sep 2016 08:36:13 GMT by cmcscbks (squid/2.7.STABLE9)`

There link I sent shows exact behaviour that you're experiencing with squid 2.7 as noted in the original issue.

Could you please double check that there is no squid proxy set up in your environment? If not, I'm totally confused how you managed to get that error message which is returned from squid.

**Comment by zhaorendong** [comment]
Dear Jimmi,
   I had found the question that is the eclipse error,Thanks!
