### ISSUE TITLE
Kubernetes vs. Openshift

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6366]
I have now played around a bit with fabric8 and it is really awesome. Now I want to do a more proper installation on a kubernetes cluster.

Should I install fabric8 on Kubernetes or Openshift?
What is the recommendation?

If I choose Openshift do I get features which I do not get if choose kubernetes?

**Comment by christian-posta** [comment]
IMHO openshift is probably the way to go. It takes care of installing the SDN layer for you (OVS), has things like security, role based access control, oauth, ldap connectivity, etc out of the box. It has an ansible installer that you can use to install it on a real cluster.

**Comment by cmoulliard** [comment]
Such discussion should be done through the Mailing list, IRC channel

**Comment by christian-posta** [comment]
@cmoulliard sure. though we've been using the issue tracker more broadly, including questions. happy to take this discussion to mailing list if we see it's more valuable for broader discussion.

**Comment by chbe8475** [comment]
Thanks for the input @christian-posta. I will continue on other channels if I feel the need.
