### ISSUE TITLE
gofabric8 deploy hanging Loading template

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#6382]
I accepted the update prompt to the latest version (0.4.71) I am seeing the deploy process freeze at different places. One mac gets to Loading the kiwiirc.yml file and the other the example-message-consumer.yml

Left both for quite some time on a fast internet connection.

I tried the same thing with the disable persistent volumes flag and it completes as expected.

I have had this working with PVs before and used the gofabric8 cleanup command to clean everything up.

Just out of curiosity, where are the physical files on the host stored?

**Comment by stevef1uk** [comment]
After a lot of attempts I sort of managed to get fabric8 deployed but still have a problem. The pods for Gogs, Nexus and Jenskins won't start. Even though I have deleted the minikube cluster something isn't right. I am seeing the following errors for all these Pods:

Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "nexus-3238985641-ceyci"/"default". list of unattached/unmounted volumes=[nexus-storage]

Unable to mount volumes for pod "nexus-3238985641-ceyci_default(2a29fa12-8261-11e6-b69d-aebc3cd88295)": timeout expired waiting for volumes to attach/mount for pod "nexus-3238985641-ceyci"/"default". list of unattached/unmounted volumes=[nexus-storage]

How do I recover things?

**Comment by rawlingsj** [comment]
I've just seen the halting install of templates too.  I don't know if it's a coincidence but I upgraded my mac to Sierra this morning and I've run in to a few problems running golang binaries.  I don't have any time today unfortunately but will be able to look at this tomorrow.

Out of interest can you see the PV bound?
`kubectl get pv; kubectl get pv`

**Comment by stevef1uk** [comment]
James, well it is the weekend ;-)

I also have upgraded both macs to Sierra this week. I did try to build gofabric8 to investigate but the make command seemed to hang, so perhaps there is a Go issue. 

I tried minikube and minishift and both show the same problem, 

A quick google seems to say that you need Go 1.7 for Sierra so I did that and gofabric8 deploy runs through first time. A documentation update required I guess.

Thanks for your response I wouldn't have thought to look for a Go issue :-)

**Comment by stevef1uk** [comment]
I was a bit premature. The above works on my old  MacBook air, but it doesn't work on my new iMac. Firstly on the iMac I have trouble creating the qinikube cluster. Quite often it hangs. Then when it did complete fabric8 deploy still hangs.

**Comment by jimmidyson** [comment]
Everyone should upgrade to 1.7.1 if they're building golang apps. Make sure to also update any ci builds too.

**Comment by rawlingsj** [comment]
@stevef1uk gofabric8 0.4.72 has been released which was compiled with go 1.7.1, tested here and things seem to be working although I have had a couple of intermittent issues with minikube.  I'm hoping that's down to the current version being compiled with 1.6.3 however that's addressed in the next release https://github.com/kubernetes/minikube/commit/567778307e783410e8300283a6925cf5b42eaf51

I've also started up minishift successfully so that looks good.

@jimmidyson I'm thinking this is a bit of an issue for kubernetes and openshift as the client binaries running on OSX Sierra are likely to be hit by this.  I'll do a bit of testing and look to raise issues in the right places but I've already seen a panic trying to do an `oc edit`.

**Comment by jimmidyson** [comment]
> I'm thinking this is a bit of an issue for kubernetes and openshift

@rawlingsj Good point! I assume there are already issues for that so have a look first - link to issues here please if you find them so we can track.

**Comment by jimmidyson** [comment]
https://github.com/kubernetes/kubernetes/issues/32999

**Comment by jimmidyson** [comment]
https://github.com/kubernetes/kubernetes/pull/28742

**Comment by rawlingsj** [comment]
https://github.com/openshift/origin/issues/11085

**Comment by rawlingsj** [comment]
This one seems to be the main issue that's suggesting the 1.7.1 upgrade https://github.com/golang/go/issues/16570

**Comment by stevef1uk** [comment]
Since building minikube with Go 1.7.1 and using the latest gofabric8 I haven't had a recurrence of this so closing.
