### ISSUE TITLE
........................................Could not find finalized endpoint being pointed to by fabric8: 

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6395]
........................................Could not find finalized endpoint being pointed to by fabric8:

**Comment by rawlingsj** [comment]
can you check if the fabric8 pod is running?  
```
kubectl get pods
```

and also check the logs and events
```
kubectl describe rs fabric8
kubectl logs fabric8-xxxx
```

**Comment by SMEmp** [comment]
On macOS 10.11.6, using `minikube` and the `xhyve` driver:

`kubectl get pods` shows a series of pods, and over time they transition from `ContainerCreating`->`Running`

* exosecontroller
* fabric8 x 2
* fabric8-docker-registry
* fabric8-forge
* gogs
* jenkins
* nexus

So far all have started successfully except Jenkins, with 0 restarts and an age of 15 min

**Comment by talisunep** [comment]
I get the same error when trying to install fabric8 on my google cloud cluster authenticated by kubectl

........................................Could not find finalized endpoint being pointed to by fabric8: 

similarly gofabric8 validates also returns all checks

$kubectl get pods --watch gives the following, i do not see `fabtic8-8deqm`

NAME                                       READY     STATUS              RESTARTS   AGE
exposecontroller-1259906887-2p7fr          0/1       ContainerCreating   0          26m
fabric8-docker-registry-4208065930-8kyim   1/1       Running             0          25m
fabric8-forge-4086519617-tspdk             1/1       Running             0          25m
fabric8-mrivp                              2/2       Running             0          26m
gogs-132257305-snxpn                       0/1       CrashLoopBackOff    9          25m
jenkins-1432297598-uzmit                   0/1       CrashLoopBackOff    9          25m
nexus-896083465-5omck                      0/1       CrashLoopBackOff    9          25m

Also the fabric console via browser loads but i only see top icons and no content
https://$KUBERNETES_SERVER/api/v1/proxy/namespaces/default/services/fabric8/workspaces

Is there any configuration in the gofabric installation i may have missed ?

**Comment by eggie5** [comment]
Same issue on Google Container Engine

```
$ kubectl get pods
NAME                                       READY     STATUS             RESTARTS   AGE
configmapcontroller-2543188956-kolpd       1/1       Running            0          7m
exposecontroller-2623795922-1ulcl          0/1       CrashLoopBackOff   6          7m
fabric8-313113940-wllie                    2/2       Running            0          7m
fabric8-docker-registry-3156868298-w6icb   1/1       Running            0          7m
fabric8-forge-359487485-vbb2y              1/1       Running            0          7m
gogs-2729425529-nedth                      1/1       Running            0          7m
jenkins-887048200-gd5q7                    1/1       Running            0          7m
nexus-2932090418-gg2dz                     1/1       Running            0          7m
```

**Comment by RobinsChens** [comment]
@rawlingsj  that's a big problem to pull these docker image from hub.docker for chinese user

**Comment by RobinsChens** [comment]
@rawlingsj can you make the image from cd-pipeline.yml be replaced registry

**Comment by jessyZu** [comment]
+1

**Comment by rawlingsj** [comment]
@jessyZu can you provide more details about your +1 please?  As far as I can tell there are three different issues that folks have experienced on this issue.

**Comment by rawlingsj** [comment]
@RobinsChens 
> @rawlingsj can you make the image from cd-pipeline.yml be replaced registry

Can you explain what you mean by this please?  Also if it's not related to this issue can you raise a new one with all the details please?

**Comment by jessyZu** [comment]
@rawlingsj  when I install fabric8 on my mac, everything  before installing "PVC... Nexus ..." is OK,but when the console diplays "PVC... Nexus ..." ，this error occurs: "Could not find finalized endpoint being pointed to by fabric8."

type gofabric8 validate 

```
Service account...............................................................✔
Console.......................................................................✘ replicationcontrollers "fabric8" not found
Jenkinshift Service...........................................................✔
PersistentVolumeClaims........................................................✔
ConfigMaps....................................................................✔

```
AND
```

kubectl get pods
NAME                                       READY     STATUS    RESTARTS   AGE
configmapcontroller-3181247428-10jc0       1/1       Running   2          22h
exposecontroller-1086916571-3j45x          1/1       Running   1          22h
fabric8-1449330595-xzxyh                   2/2       Running   2          22h
fabric8-docker-registry-2499738801-csqcj   1/1       Running   2          22h
fabric8-forge-3808647267-hwrzz             1/1       Running   1          22h
gogs-2742318956-lghi3                      1/1       Running   1          21h
jenkins-2726635756-wbuy5                   1/1       Running   1          22h
nexus-2180198382-cwcum                     1/1       Running   1          22h

```

```
gofabric8 version                 
gofabric8, version 0.4.101 (branch: 'master', revision: '248db1b')
  build date:       '20161026-04:35:21'
  go version:       '1.7.1


```

**Comment by dalu** [comment]
I'll post here, not sure if I should create a new issue.

fedora server 25
installed "a bunch of stuff" and docker rkt kubernetes.

first time install with gofabric8 deploy failes so I do gf8 volumes

```
[root@stack ~]# kubectl describe rs fabric8
Name:		fabric8-3141829270
Namespace:	default
Image(s):	fabric8/fabric8-console:2.2.199,fabric8/jenkinshift:2.2.199
Selector:	expose=true,group=io.fabric8.platform.console,pod-template-hash=3141829270,project=fabric8-console,provider=fabric8
Labels:		expose=true
		group=io.fabric8.platform.console
		pod-template-hash=3141829270
		project=fabric8-console
		provider=fabric8
		version=2.2.199
Replicas:	0 current / 1 desired
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  1h		18s		153	{replicaset-controller }			Warning		FailedCreate	Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account

Name:		fabric8-docker-registry-1981087684
Namespace:	default
Image(s):	registry:2
Selector:	group=io.fabric8.devops.apps,pod-template-hash=1981087684,project=fabric8-docker-registry,provider=fabric8
Labels:		group=io.fabric8.devops.apps
		pod-template-hash=1981087684
		project=fabric8-docker-registry
		provider=fabric8
		version=2.2.298
Replicas:	0 current / 1 desired
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  1h		18s		153	{replicaset-controller }			Warning		FailedCreate	Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account

Name:		fabric8-forge-3730694965
Namespace:	default
Image(s):	fabric8/fabric8-forge:2.3.80
Selector:	group=io.fabric8.forge.apps,pod-template-hash=3730694965,project=fabric8-forge,provider=fabric8
Labels:		group=io.fabric8.forge.apps
		pod-template-hash=3730694965
		project=fabric8-forge
		provider=fabric8
		version=2.3.80
Replicas:	0 current / 1 desired
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  1h		18s		153	{replicaset-controller }			Warning		FailedCreate	Error creating: No API token found for service account "fabric8", retry after the token is automatically created and added to the service account
```

kubectl get pods

empty

kubectl version 
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-11-18T13:25:24Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-11-18T13:25:24Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}


gofabric8 version
gofabric8, version 0.4.112 (branch: 'master', revision: '50d5d75')
  build date:       '20161129-10:39:49'
  go version:       '1.7.1'

**Comment by jstrachan** [comment]
@jessyZu this is your issue - its not really an issue; just a bad warning message - its just taking a while to download the docker images. Type `kubectl get pod -w` and you can watch them all download and startup etc

**Comment by jstrachan** [comment]
@dalu sounds like a bad kubernetes installation if no pods are being started - sounds like you've no nodes with any capacity? 'kubectl get node`.

**Comment by dalu** [comment]
```
kubectl get node
NAME        STATUS    AGE
127.0.0.1   Ready     18h
```

**Comment by jstrachan** [comment]
@dalu can you run any pods at all of any kind on your kubernetes cluster?

**Comment by dalu** [comment]
To be honest, I'm not sure. Kubernetes is quite new to me.
I wanted to give it a try and I neede a manifest for run pods (using fc25 cockpit).
So I went and searched for manifests and your site came up, and I went to / and saw what you built there, which is really interesting, especially the staging and then production concept.
I had built something along those lines but way more primitive.
And I decided to give it a go and ended up here.

I noticed etcd thrashing my hard disks every 500ms and decided to not use kubernetes.
And now I've removed docker, kubernetes and etcd from that installation.

Thanks for you help. I'll keep an eye on your project, looks promising.
And you've given me some inspiration on how to design and improve my little project,
which aims to be a shared hosting solution with isolated customer environments.
I believe the rkt approach is sound. Customers would push updates via git, a builder would build and test, a staging environment would be set up and if approved it would go live.
What etcd does can be done with a small database cluster.
Best of luck :)

**Comment by jstrachan** [comment]
@dalu sounds like you don't have a valid kubernetes installation - its fairly challenging installing it correctly on linux TBH. 

You might wanna just try [minikube](https://github.com/kubernetes/minikube) which is easy to install and use and use that to get familiar with kubernetes and/or fabric8

**Comment by lamplis** [comment]
I solved it by simply doing a "gofabric8 deploy" with my windows 10 with virtualbox and not hyper-v

**Comment by fabriziocucci** [comment]
Same issue here on iOS El Capitan!

I've installed gofabric8 with:
`curl -sS https://get.fabric8.io/download.txt | bash`

I've started the cluster with:
`gofabric8 start`

I've validated the cluster with:
`gofabric8 validate`

```
Validating your Kubernetes installation at https://192.168.64.2:8443 in namespace default

Service account...............................................................✔ 
Console.......................................................................✔ 
Jenkinshift Service...........................................................✔ 
PersistentVolumeClaims........................................................✔ 
ConfigMaps....................................................................✔ 
```

I've tried to open the Fabric8 Developer Console with:
`gofabric8 console`

but the following error came out:
`........................................Could not find finalized endpoint being pointed to by fabric8: Endpoint for service is not ready yet`

Running the following:
`$ kubectl get pods`

gives me:
```
NAME                                       READY     STATUS              RESTARTS   AGE
configmapcontroller-3703242456-x3h1w       1/1       Running             1          4h
exposecontroller-116335569-7rtb0           1/1       Running             1          4h
fabric8-3192130638-4kr05                   0/2       ContainerCreating   0          4h
fabric8-docker-registry-1981087684-5n9rr   1/1       Running             1          4h
fabric8-forge-3730694965-15kcv             0/1       ContainerCreating   0          4h
```

Any suggestions?

**Comment by fabriziocucci** [comment]
I've tried [this](https://github.com/fabric8io/fabric8/issues/6658#issuecomment-269101738) and it solved the problem.

Now I'm in this status:
```
NAME                                       READY     STATUS             RESTARTS   AGE
configmapcontroller-3703242456-f9ctf       1/1       Running            1          1h
exposecontroller-2934573704-pp18d          1/1       Running            1          1h
fabric8-3192130638-a4gq5                   2/2       Running            2          1h
fabric8-docker-registry-1981087684-yyxee   1/1       Running            1          1h
fabric8-forge-3730694965-h7w6b             0/1       ImagePullBackOff   0          1h
gogs-3384048149-qru2j                      0/1       ImagePullBackOff   0          1h
jenkins-1661962136-mgdsr                   0/1       ImagePullBackOff   0          1h
nexus-3628846063-fi18n                     1/1       Running            1          1h
```
but it may be because of my slow internet connection (e.g. fabric8-forge is 2GB)!

**Comment by magick93** [comment]
I'm also experiencing the same issue.

I'm running Fabric8 on:
OpenShift Master: v1.3.2
Kubernetes Master: v1.3.0+52492b4

Running `gofabric8 validate `gives thumbs up to all.
