### ISSUE TITLE
'Create New Application' is stucked

### ISSUE THREAD

**Issue by blindpirate** [fabric8io/fabric8#6398]
Hello guys,

I deployed fabric8 in `default` namespace and then create a team with existing `default` namespace, but it is stucked at 'Waiting for the CD Pipeline application to startup'.

![image](https://cloud.githubusercontent.com/assets/12689835/18913757/34871ca8-85bc-11e6-953b-9e67829b21b2.png)

What can I do? Am I wrong at somewhere?

What's more, my fabric8 index page looks strange without left nav bar. I noticed several http request related to `ingress` has failed, I read the documentation but cannot figure out why. 

Thank you very much.

![image](https://cloud.githubusercontent.com/assets/12689835/18913834/b93a07e4-85bc-11e6-9b04-c3c67f2f0e15.png)

**Comment by rawlingsj** [comment]
Hi @blindpirate hmm not too sure about that yet.  Could you try a page refresh and also check the browser javascript console?  

The side nav bar looks correct and only shows more options when you're in a team or runtime view.

Could you also check that all the pods are running please?  From the picture above the core apps are all green so not sure why your not taken to the create project page.
```
oc get pods
```

**Comment by blindpirate** [comment]
@rawlingsj Thank you for your reply.
I tried refresh many times in the past few hours, but it didn't work. Errors in console are same with index page.

![image](https://cloud.githubusercontent.com/assets/12689835/18935010/c4bf1b24-860f-11e6-9ea4-243b6be2ca8b.png)

I create a team in an existing namespace `default` where fabric8 apps was installed, so all the pods are running before I click 'Create A New Application'.

```
zhbs-MacBook-Pro:~ zhb$ kc get pods
NAME                                       READY     STATUS    RESTARTS   AGE
exposecontroller-4181097659-9yhwi          1/1       Running   0          11h
fabric8-docker-registry-4101503268-6axzt   1/1       Running   0          11h
fabric8-forge-2174045090-5icet             1/1       Running   0          11h
fabric8-m2wnb                              2/2       Running   0          11h
gogs-1761864434-8wjek                      1/1       Running   0          11h
grafana-146106356-d23or                    1/1       Running   0          1d
grafana-146106356-ngs6e                    1/1       Running   0          8d
jenkins-3751445750-tnudp                   1/1       Running   0          11h
nexus-2108881151-35ugb                     1/1       Running   0          11h
nginx-test-3327434295-r5vwi                1/1       Running   0          8d
prometheus-4250976560-ilbux                1/1       Running   0          1d
web-kubectl-3328477630-u9gpg               1/1       Running   0          9d
```

**Comment by rawlingsj** [comment]
Ok thanks for the update @blindpirate, I'm drawling a blank but it's a little late here so I'm wondering if you're about tomorrow if you could join `irc.freenode.net` channel `#fabric8` tomorrow and hopefully we can figure this out?  My nick is `jrawlings`

If not, we can carry on investigating through this issue.

**Comment by blindpirate** [comment]
No problem, I'm in China(UTC+8) and it' morning here. Please comment here or send me emails when you're ready. My email is zhangbodut#gmail.com and I will pay attention to it.

I have to say, fabric8 is really cool.

**Comment by rawlingsj** [comment]
@blindpirate one way or another we'll figure out what's going on and it'll be even cooler then ;)

**Comment by jstrachan** [comment]
any chance you could attach your javascript logs in your browser?

**Comment by malagant** [comment]
Did you solve this anyhow? I have the exact same situation.

**Comment by malagant** [comment]
This should be solved by https://github.com/fabric8io/fabric8-console/pull/260

**Comment by mycheng** [comment]
@malagant  now  this is the problem in  release 2.2.199? ,  may i use  gofabric8 deploy to k8s cluster use the new release
