### ISSUE TITLE
App Builds failing from fabric8 console

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#6454]
On mac Sierra 10.12 (16A323)
gofabric8, version 0.4.82 (branch: 'master', revision: '49da7d1')
  build date:       '20161014-12:39:38'
  go version:       '1.7.1'
minikube version: v0.10.0

I have just recreated my local environment and deployed fabric8:
minikube  start  --memory=6000  --v=999 --logtostderr  --show-libmachine-logs --cpus=2
gofabric8 deploy -s

Built the Go app ok, but when trying funcktion (Java) saw:

 BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.796 s
[INFO] Finished at: 2016-10-15T19:32:43+00:00
sh-4.2# exit
[INFO] Final Memory: 68M/578M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project myfunc1: Failed to deploy artifacts: Could not find artifact org.example:myfunc1:jar:1.0.2 in local-nexus (http://nexus/content/repositories/staging/) -> [Help 1]

When trying the MicroService similar error:

 BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:37 min
[INFO] Finished at: 2016-10-15T19:43:23+00:00
sh-4.2# exit
exit
[INFO] Final Memory: 56M/556M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project myms1: Failed to deploy artifacts: Could not find artifact org.example:myms1:jar:1.0.1 in local-nexus (http://nexus/content/repositories/staging/) -> [Help 1]

The common issue is that artefacts are not able to be deployed to Nexus

**Comment by rawlingsj** [comment]
@KurtStam I'm going to revert the `mvn deploy` https://github.com/fabric8io/jenkins-pipeline-library/commit/6efaadf8302de8c2686d8cf69bc1314c74a1482e fix until we catch up on Monday and figure out the best way to add persistence for nexus storage + configuration and mvn deploy.

@stevef1uk thanks for raising, we'll make a release tonight so that java project pipelines work again but a heads up until we work out a better solution we're not deploying java artifacts to nexus.  We'll get that sorted this week,

**Comment by stevef1uk** [comment]
Thanks for such a fast response. I am making some movies to show fabric8 internally at our forthcoming internal European conference. I will start again tomorrow.

**Comment by rawlingsj** [comment]
Sounds great @stevef1uk!  We've been working hard around the stability side of things so anything you hit keep letting us know and we'll address asap.

Tonights release has finished and I've just tested a new project wizard with the microservice quickstart on minikube with the canary release, stage, approve and promote pipeline - it completed successfully.  See below screenshot...

<img width="1420" alt="screenshot 2016-10-15 23 33 40" src="https://cloud.githubusercontent.com/assets/1457180/19413815/7d5a73da-9331-11e6-8258-ba04b0753437.png">

As mentioned before we'll get the artifacts deploying to nexus again after a bit more investigation.

**Comment by stevef1uk** [comment]
Working now.
