### ISSUE TITLE
Plugin io.fabric8:fabric8-maven-plugin:3.1.74 or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6456]
Jenkins just stopped building my applications with this output:

```
mvn package -U io.fabric8:fabric8-maven-plugin:3.1.74:build
[INFO] Scanning for projects...
[INFO] Downloading: http://nexus/content/groups/public/io/fabric8/fabric8-maven-plugin/3.1.74/fabric8-maven-plugin-3.1.74.pom
[WARNING] The POM for io.fabric8:fabric8-maven-plugin:jar:3.1.74 is missing, no dependency information available
[INFO] Downloading: http://nexus/content/groups/public/io/fabric8/fabric8-maven-plugin/3.1.74/fabric8-maven-plugin-3.1.74.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.856 s
[INFO] Finished at: 2016-10-17T08:09:23+00:00
[INFO] Final Memory: 14M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.fabric8:fabric8-maven-plugin:3.1.74 or one of its dependencies could not be resolved: Could not find artifact io.fabric8:fabric8-maven-plugin:jar:3.1.74 in nexus (http://nexus/content/groups/public) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
sh-4.2# exit
exit
```

When I go to for example https://mvnrepository.com/artifact/io.fabric8/fabric8-maven-plugin the latest release is 3.1.73.
Could you please either publish 3.1.74 or change back to 3.1.73?

**Comment by jimmidyson** [comment]
3.1.74 has been deployed to maven central: http://repo1.maven.org/maven2/io/fabric8/fabric8-maven-plugin/3.1.74/

Looks like a config issue in the nexus instance?

**Comment by rawlingsj** [comment]
I've seen this before and yeah I think it might be related to a nexus caching problem.

We should be able to avoid this altogether by using the fabric8-maven-plugin that comes with the java project that's being built.

**Comment by chbe8475** [comment]
Thanks guys, I really appreciate your fast response to this issue and the attention you give issues in general.

It was a nexus caching problem as @rawlingsj suggested. I logged in as admin in nexus and right-clicked on the Central repository and clicked 'Expire Cache'. The next build in jenkins went ok.

I do agree that it would be good if the fabric8-maven-plugin from the project was used. I like the idea that jenkins is using the same plugins as I am using in my local environment.

Thanks.
