### ISSUE TITLE
`Unsupported value: "tcp": supported values: TCP, UDP` When Testing

### ISSUE THREAD

**Issue by blindpirate** [fabric8io/fabric8#6481]
I was trying fabric8 with gofabric8 v0.4.93 on minikube. I created a microservice app and everything looks fine. I didn't commit any code, but when going to Integration Testing, I got an error of `Service "awesome" is invalid: [spec.ports[0].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[0].protocol: Invalid value: "tcp": cannot create an external load balancer with non-TCP/UDP ports]`. It seems that fabric8 tried to deploy it to testing namespace of k8s but met an error that service type was mistaken with `tcp` instead of `TCP`. I thought it was easy to fix and tried to find where it was defined but failed.

![image](https://cloud.githubusercontent.com/assets/12689835/19639521/755f0048-9a0b-11e6-9c3a-ed830daf3ea1.png)

So how can I do with this error? Or any workaround?

Thank you very much.

Here is complete jenkins output [https://gist.github.com/blindpirate/6e763dcf24b10b01e7fc2df24fcb398b](https://gist.github.com/blindpirate/6e763dcf24b10b01e7fc2df24fcb398b)

**Comment by rhuss** [comment]
This is fixed with https://github.com/fabric8io/fabric8-maven-plugin/issues/596 and will be available later this day in a 3.1.80 release.

**Comment by blindpirate** [comment]
OK, thank you very much @rhuss .

**Comment by blindpirate** [comment]
For now, which version can I used without being affected? @rhuss

**Comment by rhuss** [comment]
I'm just building 3.1.80, should be available in ~ 30 minutes.
