### ISSUE TITLE
How to add a customized app type?

### ISSUE THREAD

**Issue by blindpirate** [fabric8io/fabric8#6489]
Hello guys, I'm using fabric8 and want to add a app type in `Create A New Project` page, but I don't know how. I was trying to watch the ajax in order to find the backend interface but failed.

So how can I define a customized app type to benefit my users? 

Thank you very much.

![image](https://cloud.githubusercontent.com/assets/12689835/19752066/fe4a58d0-9c2c-11e6-9975-f848f67e5798.png)

**Comment by jstrachan** [comment]
we have a pending issue to make it easy to add quickstart catalogs:
https://github.com/fabric8io/fabric8-forge/issues/509

which is probably going to be the easiest way to extend fabric8 with custom project kinds. The other option is to add a JBoss Forge addon that provides whatever project wizard you wish:
https://forge.jboss.org/document/develop-an-addon

though it does require some knowledge of the ProjectNew addon in Forge I'm afraid.

**Comment by blindpirate** [comment]
OK, thank you!
