### ISSUE TITLE
What url to access after deploying to kubernetes?

### ISSUE THREAD

**Issue by arasheedu** [fabric8io/fabric8#6504]
Hi there,

I was able to run the installer to deploy against my Kubernetes cluster.
Just not sure what url:port I should access?

Thanks,
Rasheed

**Comment by jstrachan** [comment]
the command:
```
gofabric8 console
```

should open the console. There's also `gofabric8 service jenkins` to view jenkins or whatever services. [More details here](https://fabric8.io/guide/getStarted/gofabric8.html#access-the-fabric8-developer-console)
