### ISSUE TITLE
Builds always fails after a succesful one

### ISSUE THREAD

**Issue by MarcSolde** [fabric8io/fabric8#6523]
So, as the title implies, all of my Jenkins builds fail after a succesful one, but they pass if I run them one more time, kind of following a Pass-Fail-Pass pattern. I found this happening at least on _node_ and _go_ based apps. The output is the following:
```
ERROR: Error during kubernetes apply: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/default-production/replicationcontrollers. Message: object is being deleted: replicationcontrollers "test" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=replicationcontrollers, name=test, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=object is being deleted: replicationcontrollers "test" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
Finished: FAILURE
```

Is there any way to fix this? Also I'm running fabric8 on a kubernetes enviroment deployed on AWS.

**Comment by rawlingsj** [comment]
Not sure if this is related but I think we need to move away from replicationcontroller's and use Deployments asap.

We're just trying to get a new release out at the moment but I'll work on moving to a Deployment straight after that.

If you wanted to try yourself then you can modify the internal jenkins pipeline library and change the resource returned [here](https://github.com/fabric8io/jenkins-pipeline-library/blob/master/vars/getKubernetesJson.groovy#L9) to be a Deployment.

To modify the shared library for now you can get the jenkins URL 

```
gofabric8 service jenkins -u
```

then with that URL clone the shared library from the internal jenkins git repo

e.g.
```
git clone http://<your jenkins url>/workflowLibs.git
```

modify `workflowLibs/vars/getKubernetesJson.groovy` and `git commit -a -m 'updates' && git push origin master`  

then retrigger the jenkins job.

If you prefer to wait however then we should hopefully have a fix in the next day or so.

**Comment by MarcSolde** [comment]
Thanks for the info, I'll try this fix and if I'm not lucky, I'll wait a couple of days.

**Comment by rawlingsj** [comment]
I've recreated the issue and working on a fix.  It's related to the version number not being worked out correctly but this is hidden in our current approach to building the docker image.  It's not related to the use of replication controllers so sorry if you've spent time looking at that but FWIW we should be using deployments and I'll sort that soon.

I'll get a fix for the subsequent builds asap and after work on a better solution as to why it wasn't clear what was missing.

**Comment by MarcSolde** [comment]
I have seen that you have referenced this issue in  [fabric8io/fabric8-pipeline-library#4](https://github.com/fabric8io/fabric8-pipeline-library/issues/4), implying that it is already solved. Sadly this isn't the case in my experience since I'm still getting the same error, but that may be just because I have some kind error during configuration, so let me explain exactly what I'm doing and let's see if I can get some orientation on how to fix it :smile: 

Right now I'm deploying directly into master without using auxiliar branches nor pull request, when I create the app through the fabric8 console I'm not activating _code review_ option and I'm doing all the git adds/commit/push/etc through a console. To just say things on top of my head, could it be some kind of port problem? I mean, right now my cluster only has inbound connections set up from _Anywhere_ to ports 80 and 22, could it be that I have to open some more ports?
