### ISSUE TITLE
why not release a stable version? I'm crazy

### ISSUE THREAD

**Issue by seanzhau** [fabric8io/fabric8#6547]
I'm running by the version:
```
fabric8/configmapcontroller:2.2.287
fabric8/exposecontroller:2.2.287
fabric8/fabric8-console:2.2.190
fabric8/fabric8-forge:2.3.72
fabric8/gogs:v0.9.97
fabric8/jenkins-docker:2.2.287
fabric8/nexus:2.2.287
```

One day,you changed the jenkinsfile library to https://github.com/fabric8io/fabric8-jenkinsfile-library.git,My project can't running.
OK, I get the error message,and I changed my profile...

But now....All of the old project and new project
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 2: unable to resolve class Library , unable to find class for annotation
@ line 2, column 1.
@Library('github.com/fabric8io/fabric8-pipeline-library@master')
^
WorkflowScript: 28: unable to resolve class io.fabric8.Utils
@ line 28, column 13.
def utils = new io.fabric8.Utils()
^
2 errors
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:861)
at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:550)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:499)
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
at groovy.lang.GroovyShell.parse(GroovyShell.java:743)
at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:106)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:376)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:343)
at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:212)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

The logic has been changed , I must upgradde my all fabric8 version?
I can used my local gogs registry to keep the version, but I don't know how much other logic changes I must use keep it in my local registry...

**Comment by RobinsChens** [comment]
it seems that you need to back to fabric8-platform-2.2.19-openshift.yml

**Comment by seanzhau** [comment]
@RobinsChens 2.2.19 it's a stable version?

**Comment by RobinsChens** [comment]
@seanzhau 好了，我知道你懂中文，我现在测试过的版本中，这个2.2.19可以使用

**Comment by seanzhau** [comment]
@RobinsChens 有没有QQ之类的联系方式，交流一下？

**Comment by rawlingsj** [comment]
@seanzhau it looks like your jenkins version is old, we use the new @Library annotation to import the shared library but the latest jenkins plugins are needed to support this.  

More details are in this mailing list post https://groups.google.com/forum/#!topic/fabric8/wpxekBWlY0k

The latest version is 2.2.28 which we recommend using http://central.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.2.28/fabric8-platform-2.2.28-openshift.yml

**Comment by akdj** [comment]
hello everyone！

I have the same problem as @seanzhau  , and I don't know how to check my version of fabric8.. can you tell me how to do this? 
I installed fabric8 in my openshift platform with gofabric8 installer, and with the command line "gofabric8 version", I can only check the version of the installer, and no fabric8

```
> gofabric8, version 0.4.121 (branch: 'master', revision: '835aa16')
>   build date:       '20170306-10:48:35'
>   go version:       '1.7.1'
```
And I am noy sure, for installing a specific version of fabric8, if it is this command line : 
"gofabric8 depoy --domain=xxx.xxxxx.com --version=vx.x.x.x.x " or this one  "gofabric8 deploy --domain=xxx.xxxx.com --version-xxxx"  ???


大家好  @RobinsChens  

我跟 @seanzhau   有一样的问题 

```
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> WorkflowScript: 2: unable to resolve class io.fabric8.Utils 
>  @ line 2, column 13.
>    def utils = new io.fabric8.Utils()
>                ^
```

   但是我不知道 我的fabric8的version， 能不能告诉我怎么查看？ 我是利用gofabric8安装在openshift origin上的。 
但用“gofabric8 version" 我只能查看gofabric8的version。。。

```
> gofabric8, version 0.4.121 (branch: 'master', revision: '835aa16')
>   build date:       '20170306-10:48:35'
>   go version:       '1.7.1'
```
 不知道有没有用
而且 我不清楚 是不是用这个命令句 可以安装指定的version ： 
"gofabric8 depoy --domain=xxx.xxxxx.com --version=vx.x.x.x.x " of "gofabric8 deploy --domain=xxx.xxxx.com --version-xxxx"

**Comment by seanzhau** [comment]
@akdj just like this
`/gofabric8-linux-amd64 deploy -y --namespace=fabric8 --domain=ipaas.seanzhau.com --version=2.4.1`

you can get the ipaas version from `https://repo1.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/`

if you install with the `latest` version,you will be a lot of problem.

**Comment by akdj** [comment]
Thank you very much!

**Comment by akdj** [comment]
@seanzhau 

Hi! it is me again... 
I try the installation with 

`

> /gofabric8-linux-amd64 deploy -y --namespace=myproject --domain=domain.name.com --version=2.2.4

`

and it doesn't want to terminate the installation... it is still displaying dot like ..... 

```

> Downloading images and waiting to open the fabric8 console...
> 
> -------------------------
> ..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

```

I don't know if it is because of I use the latest version of openshift or docker or kubernetes ? 
or it just I chose a bad version of fabric8...   I tried with v2.2.28, v2.2.4.

**Comment by akdj** [comment]
and now..... it is displaying in loop : "Waiting, endpoint for service is not ready yet.."  

before it also displayed this but just two or three times, and now there are more than 20 messages like "Waiting, endpoint for service is not ready yet.."
