### ISSUE TITLE
Invalid credentials for gogs

### ISSUE THREAD

**Issue by vbartoni** [fabric8io/fabric8#6578]
When creatinng new app (openshift), fabric8-forge gets error from gogs (invalid credentials).
When instaling fabric8, there might be some issue with secrets:
> gofabric8 secrets -y
> No secrets created as no fabric8 secrets annotations found in the Fabric8 Catalog

When then proceeding to create an app, UI asks me to provide a secret.
So I created one with credentials gogsadmin/RedHat$1 Then fabric8-forge fails.
Note that username is gogsadmin, password lenght 8.
I tried to create multiple secrets, so I probably haven't every time mistyped the credentials.
I managed to login manually to gogs, and there I can see that appliction repository is created.

Logs from fabric8-forge pod:
> Using UsernamePasswordCredentialsProvider{user: gogsadmin, password length: 8}
> Application {http://git.rest.forge.fabric8.io/}RepositoriesResource has thrown exception, unwinding 
> now: org.eclipse.jgit.api.errors.TransportException: http://gogs.teco3.vedranfabric8.tecdomain.net/gogsadmin/intefration9.git: cannot open git-upload-pack
> .
> .
> java.net.ConnectException: Connection refused gogs.teco3.vedranfabric8.tecdomain.net

From gogs pod logs:
> [Macaron] 2016-11-22 10:39:02: Completed /gogsadmin/intefration9.git/info/refs?service=git-receive-pack 401 Unauthorized in 17.602953ms

**Comment by vbartoni** [comment]
oc v3.3.1.5
kubernetes v1.3.0+52492b4

gofabric8, version 0.4.105 (branch: 'master', revision: '5274309')
  build date:       '20161109-10:37:34'
  go version:       '1.7.1'

**Comment by vbartoni** [comment]
Password in secret  looks good:
> [cloud-user@vedranfabric8-oshift-master-0 ~]$ oc get secret gogspasswordvedran -o yaml
apiVersion: v1
data:
  password: UmVkSGF0JDE=
  username: Z29nc2FkbWlu

Pasword is RedHat$1 when decoded:

> [cloud-user@vedranfabric8-oshift-master-0 ~]$ echo UmVkSGF0JDE=|base64 -d
> RedHat$1
>

**Comment by vbartoni** [comment]
jstrachan (IRC)
vedran[m] can you do a clone from the command line on your machine? can you login with that user/pwd to gogs?
e.g. git clone on http://gogs.teco3.vedranfabric8.tecdomain.net/gogsadmin/intefration9.git:
it might be worth checking its not a DNS issue; can you curl  http://gogs.teco3.vedranfabric8.tecdomain.net/gogsadmin/intefration9 from inside the fabric8-forge pod (kubectl exec -it fabric8-forge-xxxx bash)
am close to switching to using internal kubernetes service URLs for git to avoid these kinds of DNS issues btw; should have a release in the next day or so
V
vedran
jstrachan (IRC): yes, I can go to gogs - these are defult credentials, and I can see new app's repo created
sorry, I missed that "clone"  word :-)
it' snot DNS since I get connection refused from fabric8-forge, and invalid credentials error from gogs
JJ
jstrachan (IRC)
can you git clone from your machine? also curl from inside the fabric8-forge pod then we can be sure its not a firewall / dns issue
V
vedran
jstrachan (IRC): I'll check now if I can clone
jstrachan (IRC): sh-4.2$ curl -v http://gogs.teco3.vedranfabric8.tecdomain.net/gogsadmin/intefration9

About to connect() to gogs.teco3.vedranfabric8.tecdomain.net port 80 (#0)
Trying 10.175.16.62...
Connection refused
Failed connect to gogs.teco3.vedranfabric8.tecdomain.net:80; Connection refused
Closing connection 0
curl: (7) Failed connect to gogs.teco3.vedranfabric8.tecdomain.net:80; Connection refused

jstrachan (IRC): that was DNS check
13:38
jstrachan (IRC): clone worked

**Comment by jstrachan** [comment]
after discussing it further on IRC this looks like its DNS, ip4/ip6, firewall or some other networking related issue. 

This should be fixed by https://github.com/fabric8io/fabric8-platform/issues/81

**Comment by jstrachan** [comment]
fix now merged so will be included in the next release

**Comment by vbartoni** [comment]
#### Info

Same failure as in logs listing above. Is fabric8 deployment tested on openshift?
Fabric8-forge version includes a fix - urls suppose to be kubernetes internal.

Version of fabric8-pod:
Containers:
fabric8-forge:
Image: fabric8/fabric8-forge:2.3.73

When ssh to fabric8-forge pod environment variables for credentials appear to be fine.
Are credentials used from env variables below?
sh-4.2$ env|grep GOGS
JENKINS_GOGS_USER=gogsadmin
JENKINS_GOGS_PASSWORD=RedHat$1

#### Fabric8-forge logs

Performing a pull in git repository /tmp/fabric8-forge/namespace/user-secrets-source-bartpved/gogs-new/teco3/camel2/.git on remote URL: teco3/camel2
Using UsernamePasswordCredentialsProvider{user: gogsadmin, password length: 8}
Application {http://rest.forge.fabric8.io/}RootResource has thrown exception, unwinding now: org.eclipse.jgit.api.errors.TransportException: http://gogs.teco3.vedranfabric8.tecdomain.net/gog
sadmin/camel2.git: cannot open git-upload-pack
Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@1212a09
org.apache.cxf.interceptor.Fault: http://gogs.teco3.vedranfabric8.tecdomain.net/gogsadmin/camel2.git: cannot open git-upload-pack
.
.
java.net.ConnectException: Connection refused gogs.teco3.vedranfabric8.tecdomain.net

#### Gogs logs

Two bold lines might indicate some problems:

Macaron] 2016-11-28 10:17:52: Started POST /api/v1/user/repos for 10.1.2.1
[Macaron] 2016-11-28 10:17:52: Completed /api/v1/user/repos 201 Created in 70.718402ms
[Macaron] 2016-11-28 10:17:52: Started GET /gogsadmin/camel2.git/info/refs?service=git-receive-pack for 10.1.2.1
**[Macaron] 2016-11-28 10:17:52: Completed /gogsadmin/camel2.git/info/refs?service=git-receive-pack 401 Unauthorized in 1.327305ms**
[Macaron] 2016-11-28 10:17:52: Started GET /gogsadmin/camel2.git/info/refs?service=git-receive-pack for 10.1.2.1
[Macaron] 2016-11-28 10:17:53: Completed /gogsadmin/camel2.git/info/refs?service=git-receive-pack 200 OK in 66.504286ms
[Macaron] 2016-11-28 10:17:53: Started POST /gogsadmin/camel2.git/git-receive-pack for 10.1.2.1
**2016/11/28 10:17:53 [...ogs/models/update.go:167 PushUpdate()] [E] updateIssuesCommit: No issue number specified**
[Macaron] 2016-11-28 10:17:53: Completed /gogsadmin/camel2.git/git-receive-pack 200 OK in 161.024874ms

**Comment by jstrachan** [comment]
@vbartoni yes we test on openshift and kubernetes.

BTW we released 2.4.4 of the fabric8 platform late last night - want to try with the new release? (gofabric8 start)

**Comment by vbartoni** [comment]
Tnx! I can't test at the moment, we teared down the openshift, but I'll let you  once i have the environment again. We are having problems with OpenShift SDN, (raised a ticket at RedHat - CASE 01747742), looks like pod-to-pod communication is not always working. Might be that this is related to this issue too.
