### ISSUE TITLE
prometheus pod fails to start when using glusterfs

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6581]
On the new fabric8 CD infra (Kubernetes v1.4.5) the prometheus pod fails to start.  We have glusterfs and dynamic PV provisioning.  

kubectl logs prometheus-999244325-wduhb prometheus -n fabric8-system
```
time="2016-11-23T10:44:55Z" level=info msg="Starting prometheus (version=1.3.1, branch=master, revision=be476954e80349cb7ec3ba6a3247cd712189dfcb)" source="main.go:75"
time="2016-11-23T10:44:55Z" level=info msg="Build context (go=go1.7.3, user=root@37f0aa346b26, date=20161104-20:24:03)" source="main.go:76"
time="2016-11-23T10:44:55Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:247"
time="2016-11-23T10:44:56Z" level=error msg="Error opening memory series storage: could not detect storage version on disk, assuming version 0, need version 1 - please wipe storage or run a version of Prometheus compatible with storage version 0" source="main.go:181"
```

**Comment by rawlingsj** [comment]
I found a related issue https://github.com/coreos/prometheus-operator/issues/29 and updated our prometheus Deployment to use the suggested `subPath: prometheus-db` in the volumeMount and the pod now starts.

@jimmidyson does that sound like a fair fix?  If so I'll go ahead and update our prometheus deployment yaml.

**Comment by jimmidyson** [comment]
:+1:
