### ISSUE TITLE
pipeline app depricted

### ISSUE THREAD

**Issue by sbadakhc** [fabric8io/fabric8#6582]
Hi,
I see the message below when attempting to install the pipeline app.  I was wondering which package I need to use now?

```
Please note that the --app parameter is now deprecated.
Please use the --package argument to specify a package like `platform`, `console`, `ipaas` or to refer to a URL or file of the YAML package to install
```

Thanks,
Sal.

**Comment by rawlingsj** [comment]
hey @sbadakhc by default `fabric8-platform` is used so you shouldn't need to pass the flag.

**Comment by sbadakhc** [comment]
Great! Thanks.
