### ISSUE TITLE
Still waiting to schedule task

### ISSUE THREAD

**Issue by jessyZu** [fabric8io/fabric8#6588]
![2016-11-24 2 11 08](https://cloud.githubusercontent.com/assets/699533/20588427/ff7a1162-b24f-11e6-8f3e-425842812b8a.png)

I create a app,and choose a pipeline to run according to the manual,but it hangs there:

```

Still waiting to schedule task

kubernetes-db1d0fa9ca95428988c760ed98cf4c10-c4412bfc8d8 is offline


```

**Comment by davsclaus** [comment]
A new slave pod is created that jenkins will use to build your application. If you wait a while it should come up. 

If you look at the runtime view you can list the pods. Or use the kubectrl command line to get the pod lists. Mind about namespaces if your build is in another namespace.

**Comment by jessyZu** [comment]
I found my application's source url is error by default,it's http://192.168.99.102:30490/ .But the gogs repository is http://192.168.99.100:30490/, so it hangs when checking out the git repository.

**Comment by jessyZu** [comment]
I found my application's source url is error by default,it's http://192.168.99.102:30490/ .But the gogs repository is http://192.168.99.100:30490/, so it hangs when checking out the git repository.

**Comment by magick93** [comment]
Hi Jessy

Did you find a solution for this?

I also have the same problem. The Jenkins slave hangs during creation.

You mention the application url was incorrect. Where did you find this? Which application was this?

```
$ kubectl get pods -n default
NAME                                                       READY     STATUS              RESTARTS   AGE
configmapcontroller-1-397qh                                1/1       Running             3          5d
docker-registry-1-hlxdm                                    1/1       Running             3          8d
exposecontroller-2-67pjh                                   1/1       Running             0          46m
fabric8-3-q1lby                                            1/1       Running             0          46m
fabric8-docker-registry-1-an81b                            1/1       Running             3          5d
fabric8-forge-1-ivmfl                                      1/1       Running             3          5d
gogs-4-z9pgu                                               1/1       Running             0          46m
jenkins-1-1vsqx                                            1/1       Running             0          26m
kubernetes-d97cd045224140249733e9020db80775-a87302ee7d93   0/2       ContainerCreating   0          4m
nexus-1-8s9r2                                              1/1       Running             3          5d
router-1-t86jr                                             1/1       Running             3          8d
```

**Comment by DevOps-IT** [comment]
I am waiting for last 20 min, but it is still the same issue "Still waiting to schedule task
default-22c2961c55df3 is offline"
Can anyone suggest any possible solution.

kubectl get pods .. .command returned nothing
