### ISSUE TITLE
Installing fabric with devops goodies

### ISSUE THREAD

**Issue by sbadakhc** [fabric8io/fabric8#6589]
Hi I'm currently installing fabric8 with the commands below.  Once I login to the console however I don't see any teams or tooling I used to see when installing with the deprecated --app option.  Can you let me know what I'm missing here?

Thanks,
Sal.

```
gofabric8-linux-amd64 deploy --yes --namespace="default" --domain=${DOMAIN}
gofabric8-linux-amd64 secrets --yes
gofabric8-linux-amd64 volumes --yes
gofabric8-linux-amd64 routes --yes
oc get oauthclient fabric8
```

**Comment by rawlingsj** [comment]
Hi @sbadakhc FWIW you shouldn't need to run the secrets, volumes or routes anymore, this should be done automatically.  Are you running on minishift?

If you are `gofabric8 deploy` should be all you need.

**Comment by jstrachan** [comment]
I've just noticed a regression in `fabric8/fabric8-console:2.2.194` on openshift - but this version works!
* `fabric8/fabric8-console:2.2.192`
so as a work around you could type
```
oc edit dc fabric8
```
and update the fabric8-console image version. Hope I can figure out a fix ASAP though

**Comment by sbadakhc** [comment]
Thanks gents!

Much appreciated.
