### ISSUE TITLE
kotlin function archetype missing source files

### ISSUE THREAD

**Issue by amb-it-ion** [fabric8io/fabric8#6592]
Used Archetype: funktion-kotlin-example-archetype:2.2.185

Please find attached: [log.txt](https://github.com/fabric8io/fabric8/files/613012/log.txt)

**Comment by davsclaus** [comment]
Can you try with a newer version of fabric8 and the kotlin archetype.

**Comment by amb-it-ion** [comment]
the kotlin archetype was listed as the newest available version using the maven archetype search/filter. I installed fabric8 2 days ago with a fresh install from minikube+gofabric8. can you please point me in the right direction on how to update either?

**Comment by davsclaus** [comment]
You can find latest maven here which is more up to date
http://search.maven.org/

You can update fabric8-forge by changing its deployment to use a newer docker image tag

**Comment by amb-it-ion** [comment]
thanks for the quick response, will try to make some time tonight and come back with feedback. in any case, kudos to the fast response and a dearly needed, great product!

**Comment by davsclaus** [comment]
I just reproduced this with 2.2.191. I suspects its the archetype-builder that dont include src/main/kotlin. I will take a look

**Comment by davsclaus** [comment]
Okay found the bug and will be fixed in upcoming releases
https://github.com/fabric8io/ipaas-quickstarts/pull/1472
