### ISSUE TITLE
My builds in jenkins stopped

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6593]
My build in jenkins stopped due to a null value. The logs say:
`+ mvn clean -e -U deploy null`

I found a commit in vars/mavenCanaryRelease.groovy which changed something like this:
`sh "mvn clean -e -U deploy

 sh "mvn clean -e -U deploy ${config.profiles}`

made by @christian-posta 

Any idea how I can solve this?

**Comment by rawlingsj** [comment]
Ah I just merged that!  Sorry I'll revert now, we should be using versioned libraries to avoid folks getting changes before they've gone through QA.

**Comment by rawlingsj** [comment]
@chbe8475 can you trigger another build please?  I've reverted that change and we'll put a proper fix in place.

**Comment by chbe8475** [comment]
It seems to work now, thanks. I am very thankfull for the awesome reaction time from your side on this one.

**Comment by rawlingsj** [comment]
No problem!  glad it's sorted but we still need to make sure we used a fixed version of the library to avoid this kinda thing happening again.  

I've raised https://github.com/fabric8io/fabric8/issues/6594.
