### ISSUE TITLE
JavaExecGenerator in maven plugin 3.2: Problems with main class treatment in non-fat-jar deployments

### ISSUE THREAD

**Issue by oweise** [fabric8io/fabric8#6599]
First encountered with Fabric8 maven plugin version 3.2.4, does not happen in 3.1.x:

The JavaExecGenerator seems to have some problems correctly setting the JAVA_MAIN_CLASS environment var for the docker build when the deployment is not a fat jar. If the main class is set manually via generator configuration it is never set as this env var in the docker build.

Reproduce:

- Create a new project by the quickstart archtetype "cdi-cxf-archetype"
- Change the fabric8 maven plugin version to 3.2.4 in the pom.xml of the project
- Deploy the project to kubernetes
- The container crashes with the error message in log: ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 89 found in /deployments (1 expected)

The problems I think are located in the following methods:

- getEnv()
  - The line ret.put(JAVA_MAIN_CLASS...) is only run if the main class in the config was empty and the main class detector instead determined the main class. So setting the main class in config will never result in the env variable JAVA_MAIN_CLASS being set
  - As the main class from the config is already injected and conditionally used by the mainClassDetector I think this first check for the main class from the config is superfluous. The mainClassDetector instead should only be used
  - The return of the call to mainClassDetector.getMainClass() is not used, therefor this invocation does nothing
- hasMainClass()
  - This treats the contents of Config.mainClass like a boolean. It however is a class name that via Boolean.parseBoolean() will be interpreted as false, even if it is filled.

If you want I could try to resolve these issues in my fork and submit a pull request once ready.

I think the project could use some more testing coverage in that area. If nobody is already working on this I could see what I can do.

**Comment by rhuss** [comment]
Your analysis  is absolutely correct, also w.r.t test coverage :) tbh, unit test coverage is not good yet, but its on our very focus. The solution for the issue should probably be simple: Move [this line](https://github.com/rhuss/fabric8-maven-plugin/blob/c9037f6579ea3440636fd44594c1e2ea53619e0a/generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java#L151-L151) two lines down. 

A PR is highly appreciated, and if you could start some unit tests, that would be really awesome !

**Comment by davsclaus** [comment]
Did we get a PR with a fix for this? I think its worth fixing those 2 lines down quickly so this wont be forgotten.

**Comment by rhuss** [comment]
no, not yet.

**Comment by rhuss** [comment]
mean, we dont have a PR yet :) I could do this later but also wont cry if someone helps does it :)

**Comment by davsclaus** [comment]
Okay let me do a PR

**Comment by rhuss** [comment]
thanks !

**Comment by davsclaus** [comment]
I created a PR
https://github.com/fabric8io/fabric8-maven-plugin/pull/715

There were a few more changes than moving the lines 2, as there was that noop call as mentioned above, and also the early return seems flawed which didnt add those extra arguments that happens further below.

**Comment by rhuss** [comment]
yep, sorry, wondered how this could slipped through.

**Comment by oweise** [comment]
Sorry, I already did a pull request to fix this issue, including unit test. Have I missed out on notifying someone?

**Comment by davsclaus** [comment]
Ah its here
https://github.com/fabric8io/fabric8-maven-plugin/pull/685

It has merge conflicts now, I wonder if you mind updating it and merge it together with latest master which has some fixes.

The unit tests you did is really good to have included.

**Comment by oweise** [comment]
Ok, on it

**Comment by oweise** [comment]
Done. I used the already existing fix/enhancements for getEnv(), added my fix for hasMainClass() plus the test.

**Comment by davsclaus** [comment]
Thanks the PR is now merged
