### ISSUE TITLE
example Arquillian Fabric8 integration test link is not working.

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8io/fabric8#6602]
Steps to Reproduce
1.Click on [example Arquillian Fabric8 integration test](https://github.com/fabric8io/ipaas-quickstarts/blob/master/sandbox/apps/jadvisor/src/test/java/io/fabric8/apps/jadvisor/JadvisorKubernetesTest.java#L41) which is present in readme

**Comment by davsclaus** [comment]
This link is a 404. Wonder if you pasted the wrong link?

**Comment by dipak-pawar** [comment]
Hey @davsclaus ,

*Steps to Reproduce*
1.Go to here https://github.com/fabric8io/fabric8/tree/master/components/fabric8-arquillian.
2. Look for example section under it in readme.
3. Click on `Arquillian Fabric8 integration test` link.
