### ISSUE TITLE
No build logs in elasticsearch

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6603]
I just realized that I have no build logs in elasticsearch. Jenkins give me this log at the end of each build:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.116 s
[INFO] Finished at: 2016-11-29T12:26:08+00:00
[INFO] Final Memory: 20M/487M
[INFO] ------------------------------------------------------------------------
sh-4.2# exit
exit
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
Found Elasticsearch server, sending:{"timestamp":"2016-11-29T12:23:22.280+0000","build_number":19,"app":"stage-core","build_result":"SUCCESS","start_time":"2016-11-29T12:23:22.285+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#19","BUILD_ID":"19","BUILD_NUMBER":"19","BUILD_TAG":"jenkins-stage-core-19","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"dabe5faff8de0036","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"dabe5faff8de0036","JOB_BASE_NAME":"stage-core","JOB_NAME":"stage-core","library.github.com/fabric8io/fabric8-pipeline-library.version":"master","VERSION_PREFIX":"1.0"},"build_url":"job/stage-core/19/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}
ERROR: Elasticsearch response: Field name [library.github.com/fabric8io/fabric8-pipeline-library.version] cannot contain '.'
Finished: SUCCESS

I guess it is the 'cannot contain '.' which is the important thing.

**Comment by rawlingsj** [comment]
This should be fixed with the new release that was available this morning

This is the commit with the fix https://github.com/jenkinsci/kubernetes-pipeline-plugin/commit/492c727069d620e0a2927828bf988ae750b5d88a

Closing but we can reopen if you still see the problem with the latest version.
