### ISSUE TITLE
Donate forge camel parset to Apache Camel

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#6617]
Its stabilized and we can move the parser code to Apache Camel and the maven plugin as well.
Then the Camel community can benefit from this and maybe others build tooling on top of that.

The fabric-forge camel commands can then use the parser from Apache Camel instead of its own code.

This can be part of Camel 2.19 onwards.

**Comment by oscerd** [comment]
+1, great!

**Comment by davsclaus** [comment]
See ticket
https://issues.apache.org/jira/browse/CAMEL-10559

**Comment by davsclaus** [comment]
This has been ported to Apache Camel.
