### ISSUE TITLE
why not use mvn clean deploy -DskipTests

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6629]
although we have integration test step ,why not add -DskipTests ,it executed twice for test

**Comment by rawlingsj** [comment]
Hi @RobinsChens when raising issues can you give as much context as possible please, there are many different areas and aspects to fabric8.  Most of the time it's very hard to understand one line issues so they tend to not attract peoples attention.

For this issue my guess is you mean in the maven canary release? https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenCanaryRelease.groovy#L13

I'm not sure disabling the until tests when running a `mvn deploy` is a good idea, whilst there should never be failing unit tests in master I think it's still a valid check to perform.

The integration tests are different however and will deploy the new pod into a test environment, perform assertions like 'is the pod running for x secconds'.  

So I think both are valid, if this is not what you meant when raising the issue then please reopen but provide more information.  Thanks.
