### ISSUE TITLE
Can't run CD Pipeline after installation

### ISSUE THREAD

**Issue by christofhe** [fabric8io/fabric8#6658]
I have installed Fabric8 and want to create an new application. There I need run the CD pipeline before I can create any new application.
But running this always fails. Does somebody have a solution for this?

**Comment by jstrachan** [comment]
I don't quite follow what you mean. There's a new project wizard that creates new projects; or you can import projects from existing git repos. Then once a project is created/imported you get to pick the Jenkins pipeline for the project. Then the CD pipeline runs.

e.g. like in this demo: https://youtu.be/bERRJksRB1A?t=842

**Comment by christofhe** [comment]
![cdpipeline](https://cloud.githubusercontent.com/assets/24695451/21389779/a38911d4-c783-11e6-8347-4fffc3fda478.png)

I receive this message before I can create any application. So I run the CD pipeline but this never succeed.

**Comment by jstrachan** [comment]
how do you install fabric8? it looks like there's not the core features running (jenkins, forge, nexus, gogs)

**Comment by abstractpaper** [comment]
I have the same issue. Notice how the namespace changes from `f8` to `default` in the URL. This looks like a bug.

A quick workaround for this is to change the namespace in the URL to `f8` and reload. The applications will take a few seconds before they appear. Perhaps a loading spinner is helpful to indicate so.

**Comment by christofhe** [comment]
@jstrachan I install it via this command: "curl -sS https://get.fabric8.io/download.txt | bash" 
add this to export PATH=$PATH:$HOME/.fabric8/bin the PATH
and start via this command "gofabric8 start". Still the same problem.

@abstractpaper the solution that you suggest didn't work.

**Comment by abstractpaper** [comment]
@christofhe Changed this to `f8`?

![image](https://cloud.githubusercontent.com/assets/1040633/21391299/1732f308-c783-11e6-93c3-eed2b14a8518.png)

**Comment by christofhe** [comment]
yes the same problem

**Comment by jstrachan** [comment]
@christofhe can you show me the output of 
```
kubectl get pod
```

as it might just be its downloading docker images?

**Comment by jstrachan** [comment]
@abstractpaper so you installed fabric8 into namespace `f8` right? So if you go to the home page of the console and select the `f8` team can you create an app?

**Comment by christofhe** [comment]
@jstrachan 
`NAME                                       READY     STATUS    RESTARTS   AGE
configmapcontroller-3703242456-jk5vs       1/1       Running   0          1h
exposecontroller-116335569-m50cz           1/1       Running   0          1h
fabric8-3192130638-r75m9                   2/2       Running   0          1h
fabric8-docker-registry-1981087684-jmjjl   1/1       Running   0          1h
fabric8-forge-3730694965-07gvq             1/1       Running   0          1h
`

**Comment by abstractpaper** [comment]
@jstrachan that's another problem I'm facing at the moment. When trying to create an app it asks me to create a CD pipeline. When I try to create a CD pipeline in `f8` namespace it starts failing when creating services:

![screenshot from 2016-12-21 13-49-24](https://cloud.githubusercontent.com/assets/1040633/21391624/64d80408-c784-11e6-9851-dfcc87241c22.png)

I have tried to create the CD pipeline in a new separate namespace `jenkins` which progresses better but also fails at deployments:

![screenshot from 2016-12-21 13-55-55](https://cloud.githubusercontent.com/assets/1040633/21391843/3d747e40-c785-11e6-89f2-80f7b95e87f5.png)

**Comment by christofhe** [comment]
@abstractpaper yes that is also my problem

**Comment by jstrachan** [comment]
@christofhe odd - looks like you've no gogs, jenkins or nexus pods running. I wonder if your cluster is out of resources?

**Comment by jstrachan** [comment]
@abstractpaper if you install fabric8 with these instructions you should have the "CD Pipeline" apps all running in the default namespace - gogs, jenkins, nexus, fabric8-forge:
http://fabric8.io/guide/getStarted/gofabric8.html

then from the home page if you open the `default` team and then try create an app it should all work (assuming all the pods correctly started up)

**Comment by jstrachan** [comment]
@abstractpaper there's a current issue with auto-provisioning of Persistent Volumes if you try run the `CD Pipeline` app via the `Run...` button when using things like minishift / minikube - so its advisable to just install fabric8 on minishift / minikube using 'gofabric8 start' as per: http://fabric8.io/guide/getStarted/gofabric8.html

**Comment by abstractpaper** [comment]
@jstrachan I used stackpoint to setup fabric8 on AWS (so no minikubes involved). All I did is grant stackpoint access and it created the Kubernetes cluster and installed fabric8 for me, so it was basically a fresh installation.

When trying to create an app in the `default` namespace I get this:

![image](https://cloud.githubusercontent.com/assets/1040633/21392338/473a7fa4-c787-11e6-8c56-699f7e4dfd53.png)

**Comment by jstrachan** [comment]
@abstractpaper if you're using stackpoint then you need to use the `f8` team. So go to the home page of the console, select the `f8` team and you should be able to create apps there

**Comment by christofhe** [comment]
@jstrachan for me the same I did a local fresh installation and I receive the same message.
I suppose that the resources will be included when Fabric8 is installed.

**Comment by jstrachan** [comment]
@christofhe whats the output of
```
kubectl get pod -w
```

if you don't have started pods for jenkins, gogs and nexus then I would expect your issue is due to missing Persistent Volumes. See: https://fabric8.io/guide/getStarted/persistence.html

**Comment by christofhe** [comment]
@jstrachan 

NAME                     STATUS    VOLUME                           CAPACITY   ACCESSMODES   AGE
gogs-data                Bound     default-gogs-data                1Gi        RWO           6h
jenkins-jobs             Bound     default-jenkins-jobs             1Gi        RWO           6h
jenkins-mvn-local-repo   Bound     default-jenkins-mvn-local-repo   1Gi        RWO           6h
jenkins-workspace        Bound     default-jenkins-workspace        1Gi        RWO           6h
nexus-storage            Bound     default-nexus-storage            1Gi        RWO           6h

NAME                             CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                            REASON    AGE
default-gogs-data                1Gi        RWO           Recycle         Bound     default/gogs-data                          6h
default-jenkins-jobs             1Gi        RWO           Recycle         Bound     default/jenkins-jobs                       6h
default-jenkins-mvn-local-repo   1Gi        RWO           Recycle         Bound     default/jenkins-mvn-local-repo             6h
default-jenkins-workspace        1Gi        RWO           Recycle         Bound     default/jenkins-workspace                  6h
default-nexus-storage            1Gi        RWO           Recycle         Bound     default/nexus-storage                      6h

**Comment by jstrachan** [comment]
@christofhe whats the output of
```
kubectl get pod -w
```
do you have gogs, nexus, fabric8-forge, jenkins pods running and ready? If so that UI page should not appear

**Comment by christofhe** [comment]
@jstrachan 
configmapcontroller-3703242456-jk5vs       1/1       Running   0          2h
exposecontroller-116335569-m50cz           1/1       Running   0          2h
fabric8-3192130638-r75m9                   2/2       Running   0          2h
fabric8-docker-registry-1981087684-jmjjl   1/1       Running   0          2h
fabric8-forge-3730694965-07gvq             1/1       Running   0          2h

no gogs, nexus fabric8-forge, jenkins are not running

**Comment by jstrachan** [comment]
@christofhe so we need to find out why those deployments are not starting.

```
kubectl describe deploy gogs
kubectl describe deploy jenkins
kubectl describe deploy nexus
kubectl describe deploy fabric8-forge
kubectl get event
minikube logs
```

**Comment by christofhe** [comment]
@jstrachan 

Error from server (NotFound): deployments.extensions "gogs" not found
Error from server (NotFound): deployments.extensions "jenkins" not found
Error from server (NotFound): deployments.extensions "nexus" not found

**Comment by jstrachan** [comment]
it looks like it failed to even install those apps. Could you attach the output of your 'gofabric8 start' command you ran? Sounds like it failed pretty badly before actually installing 3 key Deployment resources

**Comment by christofhe** [comment]
xhyve driver already installed
Downloading https://storage.googleapis.com/minikube/releases/v0.14.0/minikube-darwin-amd64...
Downloaded /Users/cdb/.fabric8/bin/minikube
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/darwin/amd64/kubectl...
Downloaded /Users/cdb/.fabric8/bin/kubectl
using the executable /Users/cdb/.fabric8/bin/minikube
running: /Users/cdb/.fabric8/bin/minikube start --vm-driver=xhyve --memory=6144 --cpus=1 --disk-size=50g
Starting local Kubernetes cluster...
Downloading Minikube ISO
 36.00 MB / 36.00 MB [==============================================] 100.00% 0s
Kubectl is now configured to use the cluster.
waiting for all Deployments to start in namespace default


Deploying fabric8 to your Kubernetes installation at https://192.168.64.4:8443 for domain  in namespace default

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/
Creating new Namespace: default
Deploying package: platform version: 2.4.6

Now about to install package https://repo1.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.6/fabric8-platform-2.4.6-kubernetes.yml
Processing resource kind: Namespace in namespace default
Found namespace on kind Secret of user-secrets-source-adminProcessing resource kind: Secret in namespace user-secrets-source-admin
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: Secret in namespace default
Processing resource kind: ServiceAccount in namespace default
Processing resource kind: ServiceAccount in namespace default
Processing resource kind: ServiceAccount in namespace default
Processing resource kind: ServiceAccount in namespace default
Processing resource kind: ServiceAccount in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: Service in namespace default
Processing resource kind: PersistentVolumeClaim in namespace default
Processing resource kind: PersistentVolumeClaim in namespace default
Processing resource kind: PersistentVolumeClaim in namespace default
Processing resource kind: PersistentVolumeClaim in namespace default
Processing resource kind: PersistentVolumeClaim in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Found namespace on kind ConfigMap of user-secrets-source-adminProcessing resource kind: ConfigMap in namespace user-secrets-source-admin
Processing resource kind: ConfigMap in namespace default
Processing resource kind: ConfigMap in namespace default
Processing resource kind: Deployment in namespace default
Processing resource kind: Deployment in namespace default
Processing resource kind: Deployment in namespace default
Processing resource kind: Deployment in namespace default
Processing resource kind: Deployment in namespace default
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
platform......................................................................✔ 

Recreating configmap exposecontroller 
PersistentVolume name default-gogs-data will be created on host path /data/default/gogs-data
PersistentVolume name default-jenkins-jobs will be created on host path /data/default/jenkins-jobs
PersistentVolume name default-jenkins-mvn-local-repo will be created on host path /data/default/jenkins-mvn-local-repo
PersistentVolume name default-jenkins-workspace will be created on host path /data/default/jenkins-workspace
PersistentVolume name default-nexus-storage will be created on host path /data/default/nexus-storage
Recreating PVC gogs-data
Recreating PVC jenkins-jobs
Recreating PVC jenkins-mvn-local-repo
Recreating PVC jenkins-workspace
Recreating PVC nexus-storage

-------------------------

Default GOGS admin username/password = gogsadmin/RedHat$1

Checking if PersistentVolumeClaims bind to a PersistentVolume .....
Downloading images and waiting to open the fabric8 console...

-------------------------
........................................Could not find finalized endpoint being pointed to by fabric8: Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

Endpoint for service is not ready yet

**Comment by jstrachan** [comment]
@christofhe those errors you got:
```
Failed to create Deployment: Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```
are a known bug introduced into kubernetes 1.5.0. You may wanna use 1.4.x or see if they are resolved in 1.5.x - see https://github.com/fabric8io/gofabric8/issues/316#issuecomment-267322620 we're waiting on this fix https://github.com/kubernetes/kubernetes/pull/38574

**Comment by abstractpaper** [comment]
@jstrachan I have downgraded Kubernetes to 1.4.x and the problem disappeared. Thanks!

**Comment by christofhe** [comment]
stupid question maybe but how do you change the version?

**Comment by stawrul** [comment]
@christofhe First you have to remove the current version of Kubernetes bu running: 
`$ minikube delete`
Then you have to create a new instance specifying the desired version of Kubernetes (e.g. v1.4.5 which works for me): 
`$ minikube start --vm-driver=xhyve --memory=6144 --cpus=1 --disk-size=50g --kubernetes-version v1.4.5`
Finally you need to install fabric8 on top of new instance of Kubernetes by running:
`$ gofabric8 start`

**Comment by christofhe** [comment]
Thx now everything works
