### ISSUE TITLE
Fabric8 team 2.4.6 release does not work with kubectl 1.5.1 (osx)

### ISSUE THREAD

**Issue by oogmy** [fabric8io/fabric8#6660]
Error below:

Error from server (Invalid): ConfigMap "catalog-letschat" is invalid: metadata.annotations: Too long: must have at most 262144 characters
Error from server (Invalid): Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Error from server (Invalid): Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Error from server (Invalid): Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value

**Comment by ElMoselYEE** [comment]
I've run into this "imagePullPolicy: Required value" issue and found this issue (https://github.com/fabric8io/fabric8/issues/6658) which suggests it is an open issue with Kuberentes >= 1.5.0. In that issue thread, a workaround that worked for me is downgrading to Kubernetes < 1.5. See steps here (https://github.com/fabric8io/fabric8/issues/6658#issuecomment-269101738).

**Comment by rawlingsj** [comment]
Issues with running on kuberentes >= 1.5.0 should be fixed in the next release which is currently being staged before QA and promotion.  Hopefully this will be resolved by the morning.

**Comment by jstrachan** [comment]
now fixed in fabric8 platform 2.4.15
