### ISSUE TITLE
health-check deployment config parse error

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6667]
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.yml
              path: application.yml
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /moses/user/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 200
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /moses/user/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 200
          timeoutSeconds: 10

**Comment by RobinsChens** [comment]
![image](https://cloud.githubusercontent.com/assets/11987492/21576473/06dec1f8-cf6c-11e6-93e9-7daf7181c5ac.png)

**Comment by RobinsChens** [comment]
![image](https://cloud.githubusercontent.com/assets/11987492/21576478/17a11144-cf6c-11e6-90ea-24464f8fbc03.png)

**Comment by jstrachan** [comment]
Copy & pasting the actual YAML in a code block or gist would make it a bit easier to link to the issue.

It looks like the livenessCheck needs to align to the same indentation as the volumeMount so it's part of the same container resource.
