### ISSUE TITLE
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.71:build (default) on project moses-merchants-provider: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.71:build failed: An error has occurred. Stream Closed

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6734]
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.71:build (default) on project moses-merchants-provider: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.71:build failed: An error has occurred. Stream Closed

**Comment by rhuss** [comment]
Please upgrade fabric8-maven-plugin and give more information.

**Comment by rhuss** [comment]
Also would appreciate it when you open the issue at https://github.com/fabric8io/fabric8-maven-plugin
