### ISSUE TITLE
gofabric8 start spend too much time when download docker image

### ISSUE THREAD

**Issue by doracl** [fabric8io/fabric8#6767]
![image](https://cloud.githubusercontent.com/assets/11531880/23248579/f72d187e-f9da-11e6-9f47-c6767650402d.png)

Can I install docker images manually, or  behind the http proxy?

**Comment by rajdavies** [comment]
By default, gofabric8 will use minikube to initialize the Kubernetes cluster. You can start MiniKube locally and then do a gofabric8 deploy.

You could download the images separately and then upload them to the docker registry inside MiniKube if you wish.
