### ISSUE TITLE
Generating kubernetes yml at runtime through JAVA API

### ISSUE THREAD

**Issue by chakravarthyvp** [fabric8io/fabric8#6768]
Hi,

    We have a proprietary deployment model that are POJOs. This is an equivalent of what kubernetes specifies for deployment of an application.

    Basically, at runtime, we'd be supplied with this in-house deployment model as POJOs and we'd like to generate a kubernetes yml. I went through the fabric8 plugins. There are only build-time generators or with the kubernetes client API that requires a kubernetes master. Is there any API/library that could generate a yaml ?

Best Regards
CVP

**Comment by chakravarthyvp** [comment]
Is there any update on this? Can someone help here?

**Comment by jmlambert78** [comment]
Maybe you should look for json object generation of k8s object.

Le 27 févr. 2017 3:56 PM, "Chakravarthyvp" <notifications@github.com> a
écrit :

**Comment by chakravarthyvp** [comment]
Hi jmlambert78,
    I'm not quite sure of what you pointed out to look at? Do you have links that I could refer to?

    All that need is to programatically generate a pod/service YML without the client-apis / build time ..

Best Regards
CVP

**Comment by jimmidyson** [comment]
@chakravarthyvp You can use the kubernetes-client to generate and dump YAML like:

```java
String yaml = SerializationUtils.dumpAsYaml(
  new DeploymentBuilder().withNewSpec()...endSpec().build()
);
```

Then write that YAML out however you want, to file, stream, etc. This is effectively what fabric8 maven plugin does at build time, you can just do the same and do whatever you want with the output.

**Comment by jimmidyson** [comment]
I'm going to close this now - please feel free to reopen it if you still have an issue.
