### ISSUE TITLE
Unauthorized Error When Trying to Connect to fabric8 Console Running on Minikube Cluster that sits on a Bare Metal Ubuntu 14.04 Machine

### ISSUE THREAD

**Issue by ChadCorsentino** [fabric8io/fabric8#6854]
Hello,

I'm trying to connect to the fabric8 console I set up on top of a minikube VM that sits on a bare-metal Ubuntu 14.04 Machine.

The Minikube cluster is running with a working fabric8 console:

$ gofabric8 validate
Validating your Kubernetes installation at https://{IP} in namespace default

Service account...............................................................✔
Console.......................................................................✔
Jenkinshift Service...........................................................✔
PersistentVolumeClaims........................................................✔
ConfigMaps....................................................................✔

$ kubectl get nodes
NAME           STATUS           AGE          VERSION     
minikube      Ready             2h             v1.6.0

$kubectl get pods
NAME                                                                READY          STATUS          RESTARTS          AGE
configmapcontroller-4273343753-8l5jb           1/1               Running                0                  2h
exposecontroller-2448081478-806t5               1/1                Running                0                  2h
fabric8-3873669821-332t1                               2/2               Running                 0                 2h
fabric8-docker-registry-125311296-1vmtb      1/1               Running                 0                 2h
fabric8-forge-1088523184-8znm4                   1/1               Running                 0                 2h
gogs-1628424283-j4cwl                                   1/1               Running                 0                 2h
jenkins-56914896-6k955                                  1/1               Running                 0                 2h
nexus-2230784709-qxqw9                               1/1               Running                 0                  2h

I deployed fabric8 using (IP from the gofabric8 validate command above):
$ gofabric8 deploy -y --domain=<IP_of_Minikube_cluster> --open-console=false

(Note: I used --open-console=false because it would hang at the end of fabric8 deployment printing dots "." for a long time after the "Waiting to open fabric8 console..." line.)

Everything seems to be working, however no matter what I do, I can't connect to the console from a web browser.

I always get "Unauthorized" (internally on the Ubuntu box).

Externally, I would get an error that couldn't find the dns, so I proceeded to forward the port.

Now I get the same "Unauthorized" error when trying to connect externally from a web browser.

I'm not sure what is causing this.

Regards,
Chad C.

**Comment by ChadCorsentino** [comment]
I was able to get the console to work internally using:
$ minikube service fabric8

However, I am still unable to connect from an external source.

How would I go about exposing this properly so other members of my team can access the console externally?

I tried port forwarding the ip I got from:
$ minikube service fabric8 --url

However, it still is not letting me connect externally.  Do I need to set up some type of authentication with fabric8?

**Comment by chbe8475** [comment]
I have not tried installing fabric8 on kubernetes 1.6 yet. I see that kubernetes from version 1.6 has introduced RBAC. Could this have anything to do with your problem?

**Comment by ChadCorsentino** [comment]
That could be.  I was actually able to get it to work last night by opening an ssh tunnel into the minikube VM:
HostMachine ~$ **minikube service --url**
<IP:Port>

HostMachine ~$ **ssh -g -L<PORT>:localhost:<PORT> docker@<IP>**
password:

$

This allowed me to connect to the console externally, however It only works while I keep that tunnel open.
