### ISSUE TITLE
update the homepage to describe that the fabric8 platform is mothballed

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#7065]
while some repos have activity (fabric8-maven-plugin, kubernetes-client) the fabric8-platform hasn't had a release in a very long time (July 2017!) - so we should describe that its no longer being maintained on the home page
http://central.maven.org/maven2/io/fabric8/platform/distro/distro/

**Comment by jstrachan** [comment]
cc @maxandersen

**Comment by rawlingsj** [comment]
Any chance we can get something up soon please?  Folks are still trying to install fabric8 and it's not fair to them wasting their time.

**Comment by maxandersen** [comment]
I know - working on it.

**Comment by jstrachan** [comment]
@maxandersen why is it taking so long to write one sentence on the home page?

**Comment by rawlingsj** [comment]
@maxandersen any updates on this? https://github.com/fabric8io/gofabric8/issues/648

**Comment by maxandersen** [comment]
Done - sorry for the wait.
